"use client";
import { FormEvent, useMemo, useState } from "react";
import type { V2ModuleKey, V2TeacherKey } from "../../../lib/v2-platform";

type Sample = { id: number; examType: string; year: string; examName: string; subject: string; questionNumber: string; stem: string; options: Record<string, string>; correctAnswer: string | null; teacherAnswer: string; teacherCompleteExplanation: string; completeExplanation: string; rubricJson: string } | null;
type Teacher = { key: V2TeacherKey; name: string; subject: string; brandNote: string; bookCount: number; questionCount: number; sample: Sample };
export default function TeacherWorkspace({ teacher, zoneTitle, summary, modules, brand }: { teacher: Teacher; zoneTitle: string; summary: string; modules: V2ModuleKey[]; brand: "get" | "angle" }) {
  const [answer, setAnswer] = useState(""); const [graded, setGraded] = useState(false); const [shot, setShot] = useState<string | null>(null); const [courseQuestion, setCourseQuestion] = useState("");
  const sample = teacher.sample;
  const type = teacher.key === "pengli" ? "法律申論" : teacher.key === "kangqing" ? "醫檢選擇題" : "中會計算／分錄";
  const rubric = useMemo(() => { try { const r = JSON.parse(sample?.rubricJson || "[]"); return Array.isArray(r) ? r : []; } catch { return []; } }, [sample]);
  function submit(event: FormEvent) { event.preventDefault(); if (answer.trim()) setGraded(true); }
  function file(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => setShot(String(reader.result || "")); reader.readAsDataURL(file); }
  return <main className={`v2-workspace ${brand}`}>
    <header><a href={`/v2-preview`}>← 返回V2入口</a><div><small>{brand === "angle" ? "元照 AI 解題室" : "高點 AI 實戰學習平台"}</small><b>{teacher.name}老師・{teacher.subject}</b></div><span>{type}</span></header>
    <section className="workspace-summary"><div><span>正式模組專區</span><h1>{zoneTitle}</h1><p>{summary}</p><small>目前串接 {teacher.bookCount} 份已拆解書籍／文件、{teacher.questionCount.toLocaleString()} 道題目主檔；PDF閱讀暫不開啟。</small></div><div className="workspace-modules">{modules.map((module) => <span key={module}>{module}</span>)}</div></section>
    <nav className="workspace-tabs"><a href="#question">題目與作答</a><a href="#grading">AI批改</a><a href="#micro">微課補強</a></nav>
    <div className="workspace-grid"><section id="question" className="question-surface"><header><span>{sample ? `${sample.year}｜${sample.subject}｜第${sample.questionNumber}題` : "題目資料"}</span><b>{type}</b></header>{sample ? <><h2>{sample.stem}</h2>{Object.entries(sample.options).length > 0 && <div className="sample-options">{Object.entries(sample.options).map(([key, value]) => <label key={key}><input name="option" type="radio" value={key} onChange={() => setAnswer(key)} /><b>{key}</b><span>{value}</span></label>)}</div>}<form onSubmit={submit}>{Object.entries(sample.options).length === 0 && <textarea value={answer} onChange={(event) => setAnswer(event.target.value)} rows={10} placeholder={teacher.key === "zhenghong" ? "輸入計算過程、分錄與答案…" : "輸入完整作答內容…"} />}<button disabled={!answer.trim()}>送出AI批改</button></form></> : <div className="empty-question">目前尚未找到可顯示的題目主檔，請回後台確認題目來源。</div>}</section>
      <aside id="grading" className={`grading-surface ${graded ? "ready" : ""}`}><span>AI GRADING</span><h2>{graded ? "批改結果" : "等待學生作答"}</h2>{graded ? <><div className="grade-score"><b>{teacher.key === "kangqing" ? (answer === sample?.correctAnswer ? "正確" : "需複習") : "分項診斷"}</b><small>依本題老師答案與評分標準</small></div><ul>{gradingItems[teacher.key].map((item, index) => <li key={item}><b>{item}</b><span>{rubric[index]?.description || feedback[teacher.key][index]}</span></li>)}</ul>{sample?.teacherAnswer && <details><summary>查看老師答案依據</summary><p>{sample.teacherAnswer.slice(0, 1200)}</p></details>}</> : <p>送出後會顯示分項評分、漏寫內容、錯誤原因及修改方向；這裡不只核對最後答案。</p>}</aside></div>
    <section id="micro" className="micro-workspace"><div className="micro-player"><span>00:12:35</span><div><b>微課播放位置</b><small>SRT時間片段與摘要會顯示在這裡</small></div></div><div className="micro-context"><span>目前字幕摘要</span><h2>{teacher.key === "zhenghong" ? "先確認計算基礎，再處理分錄" : teacher.key === "kangqing" ? "用病毒特徵排除錯誤選項" : "先辨識爭點，再安排規範與涵攝"}</h2><p>系統會帶入播放時間前後字幕、片段摘要及對應題目，不需要學生重新描述整段課程。</p><label className="shot-upload">上傳／貼上課程截圖<input type="file" accept="image/*" onChange={(event) => file(event.target.files?.[0])} /></label>{shot && <img src={shot} alt="準備提問的微課截圖" />}<textarea value={courseQuestion} onChange={(event) => setCourseQuestion(event.target.value)} rows={3} placeholder="針對這個畫面或老師剛才的說明提問…" /><button disabled={!courseQuestion.trim()}>連同時間碼與字幕問AI</button></div></section>
  </main>;
}
const gradingItems: Record<V2TeacherKey, string[]> = { pengli: ["爭點辨識", "法條與規範", "架構與涵攝", "結論與表達"], kangqing: ["答案判定", "錯誤選項原因", "對應知識點", "下一題建議"], zhenghong: ["觀念與公式", "計算步驟", "科目與借貸", "連鎖錯誤"] };
const feedback: Record<V2TeacherKey, string[]> = { pengli: ["檢查是否完整辨識主要爭點", "比對教材與老師設定的規範", "逐段檢查事實是否真正涵攝", "提供可直接重寫的修改方向"], kangqing: ["依老師答案判斷正誤", "說明每個干擾選項錯在哪裡", "定位回臨床病毒學知識點", "推薦同概念錯題與微課"], zhenghong: ["檢查使用觀念與公式", "保留部分正確步驟的給分", "核對會計科目、方向與金額", "避免前一步錯誤被重複扣分"] };
