"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

function returnToFromLocation() { if (typeof window === "undefined") return "/"; const value = new URLSearchParams(window.location.search).get("return_to") ?? "/"; return value.startsWith("/") && !value.startsWith("//") && !value.includes("\\") ? value : "/"; }

export default function MemberRegisterPage() {
  const [displayName, setDisplayName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; setBusy(true); setError(""); const returnTo = returnToFromLocation(); try { const response = await fetch("/api/member/register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName, email, password, confirmPassword, returnTo }) }); const result = await response.json().catch(() => ({})) as { returnTo?: string; error?: string }; if (!response.ok) throw new Error(result.error ?? "會員註冊失敗。"); window.location.assign(result.returnTo?.startsWith("/") ? result.returnTo : returnTo); } catch (cause) { setError(cause instanceof Error ? cause.message : "會員註冊失敗。"); setBusy(false); } }
  return <main className="main-entry-gate"><section className="admin-login-card"><span>MEMBER ACCESS</span><div className="main-entry-logo" aria-hidden="true">智</div><h1>立即註冊</h1><p>建立帳號後，立即免費體驗 30 題；付款後解鎖完整題庫與 30 天不限次練習。</p><form className="admin-login-form" onSubmit={submit}><label htmlFor="member-register-name">姓名</label><input id="member-register-name" type="text" autoComplete="name" value={displayName} onChange={(event) => setDisplayName(event.target.value)} required autoFocus /><label htmlFor="member-register-email">會員帳號（Email）</label><input id="member-register-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /><label htmlFor="member-register-password">設定密碼（至少 8 碼）</label><input id="member-register-password" type="password" autoComplete="new-password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required /><label htmlFor="member-register-confirm">確認密碼</label><input id="member-register-confirm" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required />{error ? <p className="admin-login-error" role="alert">{error}</p> : null}<button type="submit" disabled={busy}>{busy ? "建立帳號中…" : "註冊並開始免費 30 題"}</button></form><p className="member-login-help">已有帳號？<Link href={`/member-login?return_to=${encodeURIComponent(returnToFromLocation())}`}>返回登入</Link></p><Link className="admin-login-back" href="/">回入口頁</Link></section></main>;
}
