import { and, desc, eq } from "drizzle-orm";
import type { getDb } from "../../../../db";
import { activationCodes, appSettings } from "../../../../db/schema";
import { AI_ACCESS_SETTINGS_KEY, DEFAULT_AI_PLAN, type AiPlan } from "../../../../lib/ai-access";
import { MEDTECH_DEFAULT_PRODUCT_KEY } from "../../../../lib/medtech-product-settings";
import { requireAdmin } from "../../../../lib/member-auth";

type Db=Awaited<ReturnType<typeof getDb>>;
const categories=["law","accounting","medtech","data-structure"] as const;
function randomPart(length=4){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",bytes=crypto.getRandomValues(new Uint8Array(length));return Array.from(bytes,b=>alphabet[b%alphabet.length]).join("")}
async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value.trim().toUpperCase())))).map(b=>b.toString(16).padStart(2,"0")).join("")}
function publicCode(code:typeof activationCodes.$inferSelect){return{id:code.id,last4:code.last4,label:code.label,status:code.status,benefitType:code.benefitType,categories:code.examCategory?[code.examCategory]:categories.slice(),productKey:code.productKey,quota:code.quota,durationDays:code.durationDays,redeemBy:code.redeemBy?.toISOString().slice(0,10)??null,createdAt:code.createdAt.toISOString(),redeemedAt:code.redeemedAt?.toISOString()??null,redeemedBy:code.redeemedByMemberId?`會員 #${code.redeemedByMemberId}`:null}}
async function readPolicy(db:Db){const[row]=await db.select().from(appSettings).where(eq(appSettings.key,AI_ACCESS_SETTINGS_KEY)).limit(1);try{return{...DEFAULT_AI_PLAN,...((JSON.parse(row?.value??"") as {policy?:Partial<AiPlan>}).policy??{}),autoRenew:false}as AiPlan}catch{return DEFAULT_AI_PLAN}}
async function savePolicy(db:Db,policy:AiPlan){const[row]=await db.select().from(appSettings).where(eq(appSettings.key,AI_ACCESS_SETTINGS_KEY)).limit(1);let stored:Record<string,unknown>={};try{stored=JSON.parse(row?.value??"{}")}catch{}const value=JSON.stringify({...stored,policy,updatedAt:new Date().toISOString()});await db.insert(appSettings).values({key:AI_ACCESS_SETTINGS_KEY,value,updatedAt:new Date()}).onConflictDoUpdate({target:appSettings.key,set:{value,updatedAt:new Date()}})}
async function payload(db:Db){const[codes,policy]=await Promise.all([db.select().from(activationCodes).orderBy(desc(activationCodes.createdAt)).limit(500),readPolicy(db)]);return{policy,codes:codes.map(publicCode),updatedAt:new Date().toISOString()}}

export async function GET(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;return Response.json(await payload(auth.db),{headers:{"cache-control":"no-store"}})}
export async function POST(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;const body=await request.json()as Record<string,unknown>;
 if(body.action==="save-policy"){const input=body.policy as Partial<AiPlan>|undefined;const selected=Array.isArray(input?.categories)?input.categories.filter(x=>categories.includes(x as typeof categories[number])):[];const policy:AiPlan={enabled:input?.enabled===true,name:String(input?.name??DEFAULT_AI_PLAN.name).trim().slice(0,80)||DEFAULT_AI_PLAN.name,price:Math.max(1,Math.min(10000,Number(input?.price)||30)),quota:Math.max(1,Math.min(1000,Number(input?.quota)||30)),durationDays:Math.max(1,Math.min(365,Number(input?.durationDays)||30)),coachRounds:Math.max(1,Math.min(20,Number(input?.coachRounds)||5)),autoRenew:false,categories:selected.length?selected:[...categories],notes:String(input?.notes??"").trim().slice(0,2000)};await savePolicy(auth.db,policy);return Response.json(await payload(auth.db))}
 if(body.action==="generate-codes"){const policy=await readPolicy(auth.db),count=Math.max(1,Math.min(100,Number(body.count)||1)),label=String(body.label??"贈送方案").trim().slice(0,80)||"贈送方案",benefitType=body.benefitType==="medtech_book"?"medtech_book":"ai_access",examCategory=benefitType==="medtech_book"?"medtech":"",productKey=benefitType==="medtech_book"?String(body.productKey??MEDTECH_DEFAULT_PRODUCT_KEY):"",durationDays=Math.max(1,Math.min(365,Number(body.durationDays)||policy.durationDays)),redeemBy=body.redeemBy?new Date(`${String(body.redeemBy).slice(0,10)}T23:59:59+08:00`):null,plaintext:string[]=[];for(let i=0;i<count;i++){const code=`IB-${benefitType==="medtech_book"?"MT":"AI"}-${randomPart()}-${randomPart()}`;plaintext.push(code);await auth.db.insert(activationCodes).values({id:crypto.randomUUID(),codeHash:await digest(code),last4:code.slice(-4),label,benefitType,examCategory,productKey,quota:benefitType==="ai_access"?policy.quota:0,durationDays,status:"unused",redeemBy,createdBy:auth.member.email})}return Response.json({...await payload(auth.db),generatedCodes:plaintext})}
 if(body.action==="disable-code"){const[updated]=await auth.db.update(activationCodes).set({status:"disabled",updatedAt:new Date()}).where(and(eq(activationCodes.id,String(body.id??"")),eq(activationCodes.status,"unused"))).returning();if(!updated)return Response.json({error:"找不到可停用的未兌換啟用碼"},{status:404});return Response.json(await payload(auth.db))}
 return Response.json({error:"不支援的操作"},{status:400})
}
