"use client";
import { useEffect,useState } from "react";
import "./document-question-library.css";

type Category="medtech"|"accounting";
type Doc={id:number;name:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;questionCount:number;draftQuestionCount?:number;pageCount?:number|null;error?:string|null};
const stage=(doc:Doc)=>doc.processingStage==="completed"?"可進入工作區":doc.status==="failed"?"處理失敗":"文件處理中";
const progress=(doc:Doc)=>doc.processingStage==="completed"?100:doc.status==="failed"?100:({queued:8,uploaded:15,extracting:32,indexing:64,analyzing:84} as Record<string,number>)[doc.processingStage]??8;

export default function DocumentQuestionLibrary({category="medtech"}:{category?:Category}){
 const accounting=category==="accounting",label=accounting?"中會":"醫檢",base=accounting?"/accounting":"/medtech",api=accounting?"/api/accounting":"/api/medtech";
 const [docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[busyId,setBusyId]=useState(0),[publishingId,setPublishingId]=useState(0);
 async function load(){const documentResponse=await fetch(api+"/documents",{cache:"no-store"});const documentData=await documentResponse.json() as {documents?:Doc[]};setDocs(documentData.documents??[]);setLoading(false)}
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>void load(),4000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[]);
 function open(doc:Doc){if(doc.processingStage!=="completed")return;window.location.assign(base+"/admin/document-workspace?id="+doc.id+"&autoImport="+(doc.questionCount?"0":"1"))}
 async function remove(doc:Doc){if(!confirm("確定刪除「"+doc.name+"」？該文件的原稿、索引與 "+doc.questionCount+" 題配對題目都會移除。"))return;setBusyId(doc.id);const response=await fetch(api+"/documents",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({ids:[doc.id]})});const data=await response.json() as {error?:string};if(response.ok){setDocs(list=>list.filter(item=>item.id!==doc.id));setNotice("已刪除「"+doc.name+"」及其配對題目。")}else setNotice(data.error||"刪除文件失敗");setBusyId(0)}
 async function replace(doc:Doc,file:File){if(!confirm("確定新增「"+file.name+"」作為「"+doc.name+"」的另一個原稿版本？現有題目、解析與順序會保留，不會重新拆題。"))return;setBusyId(doc.id);setNotice("正在新增原稿版本，現有題目不會重新拆解…");const form=new FormData();form.set("id",String(doc.id));form.set("file",file);const response=await fetch(api+"/documents",{method:"PUT",body:form});const data=await response.json() as {error?:string};if(response.ok){setNotice("已新增「"+file.name+"」原稿版本，既有題目已保留。");await load()}else setNotice(data.error||"新增原稿失敗");setBusyId(0)}
 async function publishDocument(doc:Doc){const draftCount=Number(doc.draftQuestionCount??0);if(!draftCount){setNotice(`「${doc.name}」目前沒有待發布草稿題目。`);return}if(!confirm(`確定只發布「${doc.name}」的 ${draftCount.toLocaleString()} 題草稿？其他文件不會受到影響。`))return;setPublishingId(doc.id);setNotice(`正在檢查並發布「${doc.name}」…`);try{const response=await fetch(api+"/admin/questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({publishAllDrafts:true,documentId:doc.id})});const data=await response.json() as {updated?:number;skippedUnanswered?:number;error?:string};if(!response.ok){setNotice(data.error||"發布失敗，請稍後再試。");return}const skipped=Number(data.skippedUnanswered??0);setNotice(skipped?`「${doc.name}」已發布 ${Number(data.updated??0).toLocaleString()} 題；另有 ${skipped.toLocaleString()} 題沒有有效老師答案，仍保留草稿。`:`「${doc.name}」已發布 ${Number(data.updated??0).toLocaleString()} 題，其他文件未變更。`);await load()}catch{setNotice("發布失敗，請稍後再試。")}finally{setPublishingId(0)}}
 return <><section className="medtech-admin-panel file-question-heading"><div><span>以文件為單位</span><h2>{label}文件題庫</h2><p>每份原稿對應自己的題目清單；PDF、Word 與 HTML 都保留，方便切換對照與校正。</p></div><div className="file-question-heading-actions"><a href={base+"/admin/questions"}>題庫總覽</a></div></section>{notice&&<section className="medtech-admin-panel library-notice">{notice}</section>}<section className="medtech-admin-panel"><div className="file-question-list">{loading?<p>正在讀取文件題庫…</p>:docs.map(doc=><article key={doc.id}><div className="file-icon">{doc.name.toLowerCase().endsWith(".pdf")?"PDF":/\.html?$/i.test(doc.name)?"HTML":"DOC"}</div><div className="file-info"><span>{doc.subject} · {doc.type}</span><h3>{doc.name}</h3><small>{(doc.sizeBytes/1048576).toFixed(2)} MB{doc.pageCount?" · "+doc.pageCount+" 頁":""}</small></div><div className={"file-stage "+doc.processingStage}><b>{stage(doc)} · {progress(doc)}%</b><span>{doc.error||doc.processingMessage}</span><i/></div><div className="file-question-count"><b>{doc.questionCount}</b><span>拆出題目</span></div><div className="file-actions"><button className="primary" disabled={busyId===doc.id||doc.processingStage!=="completed"} onClick={()=>open(doc)}>{doc.questionCount?"開啟對照工作區":"進入並開始拆題"}</button><button className="publish-document" disabled={busyId===doc.id||publishingId===doc.id||doc.processingStage!=="completed"||!Number(doc.draftQuestionCount??0)} onClick={()=>void publishDocument(doc)}>{publishingId===doc.id?"發布中…":Number(doc.draftQuestionCount??0)?`發布此文件（${Number(doc.draftQuestionCount).toLocaleString()} 題）`:"本文件已發布"}</button><label className="secondary">新增原稿版本<input hidden type="file" accept=".pdf,.html,.htm,.docx" disabled={busyId===doc.id||publishingId===doc.id} onChange={event=>{const file=event.target.files?.[0];event.currentTarget.value="";if(file)void replace(doc,file)}}/></label><button className="danger" disabled={busyId===doc.id||publishingId===doc.id} onClick={()=>void remove(doc)}>刪除</button></div></article>)}{!loading&&!docs.length&&<div className="file-empty"><b>尚無文件題庫</b><p>請先到「文件上傳」新增 PDF、HTML 或 Word 原稿。</p></div>}</div></section></>;
}
