"use client";
import { useEffect,useMemo,useState } from "react";
import "./document-question-library.css";
import "./document-library-controls.css";
type Category="medtech"|"accounting";
type Doc={id:number;name:string;bookTitle?:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;questionCount:number;draftQuestionCount?:number;pageCount?:number|null;error?:string|null};
const stage=(doc:Doc)=>doc.processingStage==="completed"?"可進入工作區":doc.status==="failed"?"處理失敗":"文件處理中";
const progress=(doc:Doc)=>doc.processingStage==="completed"?100:doc.status==="failed"?100:({queued:8,uploaded:15,extracting:32,indexing:64,analyzing:84} as Record<string,number>)[doc.processingStage]??8;
export default function DocumentQuestionLibrary({category="medtech",restricted=false}:{category?:Category;restricted?:boolean}){
 const accounting=category==="accounting",label=accounting?"中會":"醫檢",base=accounting?"/accounting":"/medtech",api=accounting?"/api/accounting":"/api/medtech";
 const[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[busyId,setBusyId]=useState(0),[publishingId,setPublishingId]=useState(0),[query,setQuery]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[selected,setSelected]=useState<Set<number>>(new Set()),[batchBusy,setBatchBusy]=useState(false);
 async function load(){const response=await fetch(api+"/documents?limit=500",{cache:"no-store"}),data=await response.json() as{documents?:Doc[]};const rows=data.documents??[];setDocs(rows);setSelected(old=>new Set([...old].filter(id=>rows.some(row=>row.id===id))));setLoading(false)}
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>void load(),4000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[]);
 const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("zh-TW");return needle?docs.filter(doc=>[doc.name,doc.bookTitle,doc.subject,doc.type].some(value=>String(value??"").toLocaleLowerCase("zh-TW").includes(needle))):docs},[docs,query]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize),visibleIds=visible.map(doc=>doc.id),allPageSelected=visibleIds.length>0&&visibleIds.every(id=>selected.has(id)),allFilteredSelected=filtered.length>0&&filtered.every(doc=>selected.has(doc.id));
 function changeQuery(value:string){setQuery(value);setPage(1)}
 function toggle(id:number){setSelected(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next})}
 function selectPage(){setSelected(old=>{const next=new Set(old);if(allPageSelected)visibleIds.forEach(id=>next.delete(id));else visibleIds.forEach(id=>next.add(id));return next})}
 function selectAllResults(){setSelected(old=>{const next=new Set(old);if(allFilteredSelected)filtered.forEach(doc=>next.delete(doc.id));else filtered.forEach(doc=>next.add(doc.id));return next})}
 function open(doc:Doc){if(doc.processingStage==="completed")window.location.assign(base+"/admin/document-workspace?id="+doc.id+"&autoImport="+(doc.questionCount?"0":"1")+(restricted?"&quality=1":""))}
 async function deleteIds(ids:number[]){let deleted=0;for(let start=0;start<ids.length;start+=100){const response=await fetch(api+"/documents",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({ids:ids.slice(start,start+100)})}),data=await response.json() as{deleted?:number;error?:string};if(!response.ok)throw new Error(data.error||"刪除文件失敗");deleted+=Number(data.deleted??0)}return deleted}
 async function remove(doc:Doc){if(!confirm(`確定刪除「${doc.name}」？該文件的原稿、索引與 ${doc.questionCount} 題配對題目都會移除。`))return;setBusyId(doc.id);try{await deleteIds([doc.id]);setDocs(list=>list.filter(item=>item.id!==doc.id));setSelected(old=>{const next=new Set(old);next.delete(doc.id);return next});setNotice(`已刪除「${doc.name}」及其配對題目。`)}catch(error){setNotice(error instanceof Error?error.message:"刪除文件失敗")}finally{setBusyId(0)}}
 async function removeSelected(){const ids=[...selected].filter(id=>docs.some(doc=>doc.id===id));if(!ids.length)return;const questions=docs.filter(doc=>ids.includes(doc.id)).reduce((sum,doc)=>sum+doc.questionCount,0);if(!confirm(`確定批次刪除已選取的 ${ids.length} 本文件？\n\n原稿、索引及約 ${questions.toLocaleString()} 題配對題目都會一併刪除，無法復原。`))return;setBatchBusy(true);setNotice(`正在刪除 ${ids.length} 本文件及相關資料…`);try{const deleted=await deleteIds(ids);setDocs(list=>list.filter(doc=>!ids.includes(doc.id)));setSelected(new Set());setNotice(`批次刪除完成：已移除 ${deleted} 本文件、原稿、索引及配對題目。`)}catch(error){setNotice(error instanceof Error?error.message:"批次刪除失敗，未完成部分仍保留") }finally{setBatchBusy(false);await load()}}
 async function replace(doc:Doc,file:File){if(!confirm(`確定新增「${file.name}」作為「${doc.name}」的另一個原稿版本？現有題目、解析與順序會保留，不會重新拆題。`))return;setBusyId(doc.id);setNotice("正在新增原稿版本，現有題目不會重新拆解…");const form=new FormData();form.set("id",String(doc.id));form.set("file",file);const response=await fetch(api+"/documents",{method:"PUT",body:form}),data=await response.json() as{error?:string};if(response.ok){setNotice(`已新增「${file.name}」原稿版本，既有題目已保留。`);await load()}else setNotice(data.error||"新增原稿失敗");setBusyId(0)}
 async function publishDocument(doc:Doc){const count=Number(doc.draftQuestionCount??0);if(!count){setNotice(`「${doc.name}」目前沒有待發布草稿題目。`);return}if(!confirm(`確定只發布「${doc.name}」的 ${count.toLocaleString()} 題草稿？其他文件不會受到影響。`))return;setPublishingId(doc.id);setNotice(`正在檢查並發布「${doc.name}」…`);try{const response=await fetch(api+"/admin/questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({publishAllDrafts:true,documentId:doc.id})}),data=await response.json() as{updated?:number;skippedUnanswered?:number;error?:string};if(!response.ok){setNotice(data.error||"發布失敗，請稍後再試。");return}const skipped=Number(data.skippedUnanswered??0);setNotice(skipped?`「${doc.name}」已發布 ${Number(data.updated??0).toLocaleString()} 題；另有 ${skipped.toLocaleString()} 題沒有有效老師答案，仍保留草稿。`:`「${doc.name}」已發布 ${Number(data.updated??0).toLocaleString()} 題。`);await load()}catch{setNotice("發布失敗，請稍後再試。")}finally{setPublishingId(0)}}
 return <><section className="medtech-admin-panel file-question-heading"><div><span>以文件為單位</span><h2>{label}文件題庫</h2><p>{restricted?"只會顯示管理員授權的書本；可開啟原稿對照並編修題目。":"每份原稿對應自己的題目清單；可搜尋、分頁、勾選並批次刪除。"}</p></div>{!restricted&&<div className="file-question-heading-actions"><a href={base+"/admin/questions"}>題庫總覽</a></div>}</section>
 {notice&&<section className="medtech-admin-panel library-notice">{notice}</section>}
 <section className="medtech-admin-panel"><div className="file-library-tools"><label className="file-search"><span>搜尋書本</span><input value={query} onChange={event=>changeQuery(event.target.value)} placeholder="輸入書名、檔名、科目或教材類型"/><b>{filtered.length} 本</b></label><label>每頁<select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(1)}}><option value="10">10 本</option><option value="20">20 本</option><option value="50">50 本</option></select></label>{!restricted&&<div className="file-batch-actions"><button type="button" onClick={selectPage}>{allPageSelected?"取消本頁":"本頁全選"}</button><button type="button" onClick={selectAllResults}>{allFilteredSelected?"取消搜尋結果":"全選搜尋結果"}</button><button type="button" className="danger" disabled={!selected.size||batchBusy} onClick={()=>void removeSelected()}>{batchBusy?"批次刪除中…":`批次刪除（${selected.size}）`}</button></div>}</div>
<div className="file-question-list">{loading?<p>正在讀取文件題庫…</p>:visible.map(doc=><article key={doc.id} className={selected.has(doc.id)?"selected":""}>{!restricted&&<label className="file-select"><input type="checkbox" checked={selected.has(doc.id)} onChange={()=>toggle(doc.id)} aria-label={`選取 ${doc.name}`}/></label>}<div className="file-icon">{doc.name.toLowerCase().endsWith(".pdf")?"PDF":/\.html?$/i.test(doc.name)?"HTML":"DOC"}</div><div className="file-info"><span>{doc.subject} · {doc.type}</span><h3 title={doc.name}>{doc.bookTitle||doc.name}</h3>{doc.bookTitle&&doc.bookTitle!==doc.name&&<small className="file-source-name">原稿：{doc.name}</small>}<small>{(doc.sizeBytes/1048576).toFixed(2)} MB{doc.pageCount?` · ${doc.pageCount} 頁`:""}</small></div><div className={`file-stage ${doc.processingStage}`}><b>{stage(doc)} · {progress(doc)}%</b><span>{doc.error||doc.processingMessage}</span><i/></div><div className="file-question-count"><b>{doc.questionCount}</b><span>拆出題目</span></div><div className="file-actions">{!restricted&&<button className="optimize-document" disabled={busyId===doc.id||publishingId===doc.id||batchBusy} onClick={()=>window.location.assign(base+"/admin/document-workspace?id="+doc.id+"&quality=1")}>題庫品質修復中心</button>}<button className="primary" disabled={busyId===doc.id||doc.processingStage!=="completed"} onClick={()=>open(doc)}>{doc.questionCount?"開啟對照工作區":"進入並開始拆題"}</button>{!restricted&&<button className="publish-document" disabled={busyId===doc.id||publishingId===doc.id||doc.processingStage!=="completed"||!Number(doc.draftQuestionCount??0)} onClick={()=>void publishDocument(doc)}>{publishingId===doc.id?"發布中…":Number(doc.draftQuestionCount??0)?`發布此文件（${Number(doc.draftQuestionCount).toLocaleString()} 題）`:"本文件已發布"}</button>}{!restricted&&<><label className="secondary">新增原稿版本<input hidden type="file" accept=".pdf,.html,.htm,.docx" disabled={busyId===doc.id||publishingId===doc.id||batchBusy} onChange={event=>{const file=event.target.files?.[0];event.currentTarget.value="";if(file)void replace(doc,file)}}/></label><button className="danger" disabled={busyId===doc.id||publishingId===doc.id||batchBusy} onClick={()=>void remove(doc)}>刪除</button></>}</div></article>)}{!loading&&!filtered.length&&<div className="file-empty"><b>{query?"找不到符合的書本":"尚無已授權書本"}</b><p>{query?"請改用書名、檔名、科目或教材類型搜尋。":restricted?"請由總管理員在會員管理中勾選可編輯書本。":"請先到「文件上傳」新增 PDF、HTML 或 Word 原稿。"}</p></div>}</div>
 {filtered.length>0&&<nav className="file-pagination" aria-label="文件題庫分頁"><button disabled={safePage<=1} onClick={()=>setPage(1)}>第一頁</button><button disabled={safePage<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>上一頁</button><span>第 {safePage}／{totalPages} 頁 · 共 {filtered.length} 本</span><button disabled={safePage>=totalPages} onClick={()=>setPage(value=>Math.min(totalPages,value+1))}>下一頁</button><button disabled={safePage>=totalPages} onClick={()=>setPage(totalPages)}>最後一頁</button></nav>}</section></>;
}
