"use client";
import { useEffect,useRef,useState } from "react";
import DocumentQuestionLibrary from "./DocumentQuestionLibrary";
import MedtechAudioImport from "./MedtechAudioImport";
import MedtechExplanationBatch from "./MedtechExplanationBatch";
import "./processing-progress.css";
import "./processing-note.css";
type Member={id:number;email:string;displayName:string;status:"active"|"disabled";canAdmin:boolean;className:string};
type Doc={id:number;name:string;bookTitle?:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;chapterCount:number;questionCount:number;error?:string|null};
const subjects=["臨床病毒學","臨床血液學","臨床生化學","臨床微生物學","血庫學","醫學分子檢驗學"];
export default function MedtechAdminPage(){
 const [tab,setTab]=useState<"members"|"documents"|"questions"|"audio"|"explanations">("members"),[members,setMembers]=useState<Member[]>([]),[docs,setDocs]=useState<Doc[]>([]),[notice,setNotice]=useState("");
 const [draft,setDraft]=useState({displayName:"",email:"",className:"",role:"student",status:"active",canAdmin:false});
 const [subject,setSubject]=useState(subjects[0]),[customSubject,setCustomSubject]=useState(""),[bookTitle,setBookTitle]=useState("醫檢師國考題詳解（Ⅲ）臨床病毒學（下）"),[documentType,setDocumentType]=useState("教材"),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 const processing=useRef(new Set<number>());
 async function loadMembers(){const r=await fetch("/api/medtech/members");const d=await r.json() as {members?:Member[]};setMembers(d.members??[])}
 async function loadDocs(){const r=await fetch("/api/medtech/documents",{cache:"no-store"});const d=await r.json() as {documents?:Doc[]};setDocs(d.documents??[])}
 useEffect(()=>{void loadMembers();void loadDocs();const timer=window.setInterval(()=>{void loadDocs()},4000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("tab");if(requested==="questions"||requested==="documents"||requested==="members"||requested==="audio"||requested==="explanations")setTab(requested)},[]);
 useEffect(()=>{for(const doc of docs){if(["extracting","indexing","analyzing"].includes(doc.processingStage)&&!processing.current.has(doc.id))void process(doc.id)}},[docs]);
 async function create(){const r=await fetch("/api/medtech/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});if(r.ok){setNotice("醫檢師會員已新增。");setDraft({displayName:"",email:"",className:"",role:"student",status:"active",canAdmin:false});await loadMembers()}else setNotice("新增失敗，請檢查資料。")}
 async function update(id:number,patch:Partial<Member>){const r=await fetch("/api/medtech/members",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(r.ok){setMembers(list=>list.map(x=>x.id===id?{...x,...patch}:x))}}
 async function process(id:number,retry=false,reanalyze=false){if(processing.current.has(id))return;processing.current.add(id);try{const r=await fetch("/api/medtech/documents/process",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,retry,reanalyze})});const d=await r.json() as {error?:string;message?:string};if(!r.ok)setNotice(d.error??"文件處理失敗，請稍後重試。");else if(d.message)setNotice(d.message)}finally{processing.current.delete(id);await loadDocs()}}
 async function upload(){if(!file){setNotice("請先選擇文件。");return}const finalSubject=subject==="__custom__"?customSubject.trim():subject;const finalBookTitle=bookTitle.replace(/\s+/gu," ").trim();if(!finalSubject){setNotice("請輸入自訂科目名稱。");return}if(!finalBookTitle){setNotice("請輸入書籍名稱。");return}setBusy(true);const form=new FormData();form.set("file",file);form.set("subject",finalSubject);form.set("bookTitle",finalBookTitle);form.set("documentType",documentType);const r=await fetch("/api/medtech/documents",{method:"POST",body:form});const d=await r.json() as {document?:{id:number};error?:string};if(r.ok&&d.document){setNotice("上傳完成，正在建立索引。");await process(d.document.id)}else setNotice(d.error??"上傳失敗");setBusy(false)}
 async function updateDocSubject(doc:Doc){const next=prompt("修改科目名稱",doc.subject)?.trim();if(!next||next===doc.subject)return;const r=await fetch("/api/medtech/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,subject:next})});const d=await r.json() as {error?:string};if(r.ok){setDocs(list=>list.map(item=>item.id===doc.id?{...item,subject:next}:item));setNotice(`已將文件與 ${doc.questionCount} 題更新為「${next}」。`)}else setNotice(d.error??"科目修改失敗")}
 async function updateDocBookTitle(doc:Doc){const next=prompt("修改書籍名稱",doc.bookTitle||"")?.replace(/\s+/gu," ").trim();if(!next||next===doc.bookTitle)return;const r=await fetch("/api/medtech/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,bookTitle:next})});const d=await r.json() as {error?:string};if(r.ok){setDocs(list=>list.map(item=>item.id===doc.id?{...item,bookTitle:next}:item));setNotice(`已將文件來源更新為「${next}」。`)}else setNotice(d.error??"書籍名稱更新失敗")}
 async function removeDoc(id:number){if(!confirm("確定刪除這份醫檢教材與索引？"))return;await fetch("/api/medtech/documents",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({ids:[id]})});await loadDocs()}
 const heading=tab==="members"?"會員與帳號管理":tab==="documents"?"文件上傳與自動處理":tab==="questions"?"醫檢文件題庫":tab==="audio"?"語音匯入與題庫配對":"解析狀態總覽";
 const heroCount=tab==="members"?members.length:tab==="audio"||tab==="explanations"?"—":docs.length;
 const heroLabel=tab==="members"?" 位會員":tab==="audio"||tab==="explanations"?"": " 份文件";
 return <main className="medtech-admin-page">
  <header><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師管理後台</b><small>MEDTECH ADMIN</small></div></a><nav><a href="/medtech">學生首頁</a><a href="/medtech/account">我的帳號</a></nav></header>
  <nav className="medtech-admin-tabs"><button className={tab==="members"?"active":""} onClick={()=>setTab("members")}>會員管理</button><button className={tab==="documents"?"active":""} onClick={()=>setTab("documents")}>文件上傳</button><button className={tab==="questions"?"active":""} onClick={()=>setTab("questions")}>文件題庫</button><button className={tab==="explanations"?"active":""} onClick={()=>setTab("explanations")}>完整解析</button><button className={tab==="audio"?"active":""} onClick={()=>setTab("audio")}>語音匯入</button></nav>
  <section className="medtech-admin-hero"><div><span>醫檢師 · 獨立資料管理</span><h1>{heading}</h1><p>{tab==="questions"?"以一份原始文件為單位，對照管理該文件拆出的全部題目。":tab==="explanations"?"AI、老師與語音解析腳本的生成與編輯都在文件題庫工作區內完成，本頁只查看狀態。":tab==="audio"?"錄音完成後，依 TXT 檔名自動驗證並綁定對應題庫。":"醫檢會員與教材均獨立管理。"}</p></div><b>{heroCount}<small>{heroLabel}</small></b></section>
  {tab==="members"&&<><section className="medtech-admin-panel"><h2>新增醫檢師會員</h2><div className="medtech-member-form"><label>姓名<input value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Email<input value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>班級<input value={draft.className} onChange={e=>setDraft({...draft,className:e.target.value})}/></label><label>身分<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="student">學員</option><option value="teacher">老師／導師</option></select></label><label className="check"><input type="checkbox" checked={draft.canAdmin} onChange={e=>setDraft({...draft,canAdmin:e.target.checked})}/>管理員</label><button onClick={()=>void create()}>新增會員</button></div>{notice&&<p className="medtech-admin-notice">{notice}</p>}</section><section className="medtech-admin-panel"><h2>醫檢會員名單</h2><div className="medtech-admin-list">{members.map(m=><article key={m.id}><div><b>{m.displayName}</b><span>{m.email}</span></div><label>班級<input value={m.className} onChange={e=>setMembers(list=>list.map(x=>x.id===m.id?{...x,className:e.target.value}:x))} onBlur={e=>void update(m.id,{className:e.target.value})}/></label><label>狀態<select value={m.status} onChange={e=>void update(m.id,{status:e.target.value as Member["status"]})}><option value="active">使用中</option><option value="disabled">已停用</option></select></label><label className="check"><input type="checkbox" checked={m.canAdmin} onChange={e=>void update(m.id,{canAdmin:e.target.checked})}/>管理員</label></article>)}</div></section></>}
  {tab==="documents"&&<><section className="medtech-admin-panel"><h2>上傳醫檢教材</h2><div className="medtech-upload-form"><label>書籍名稱<input value={bookTitle} onChange={e=>setBookTitle(e.target.value)} placeholder="例如：醫檢師國考題詳解（Ⅲ）臨床病毒學（下）"/></label><label>科目<select value={subject} onChange={e=>setSubject(e.target.value)}>{[...new Set([...subjects,...docs.map(item=>item.subject)])].map(x=><option key={x}>{x}</option>)}<option value="__custom__">＋ 自訂科目</option></select>{subject==="__custom__"&&<input autoFocus value={customSubject} onChange={e=>setCustomSubject(e.target.value)} placeholder="輸入自訂科目名稱"/>}</label><label>類型<select value={documentType} onChange={e=>setDocumentType(e.target.value)}><option>教材</option><option>題庫</option><option>講義</option><option>考古題</option></select></label><label className="file">文件<input type="file" accept=".pdf,.html,.htm,.docx,.txt,.md,.json,.jsonl,.zip" onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{file?.name??"尚未選擇文件"}</span></label><button disabled={busy} onClick={()=>void upload()}>{busy?"處理中…":"上傳並自動處理"}</button></div>{notice&&<p className="medtech-admin-notice">{notice}</p>}</section><section className="medtech-admin-panel"><h2>醫檢教材清單</h2><div className="medtech-document-list">{docs.map(d=><article key={d.id}><div className="doc-main"><span>{d.bookTitle||"尚未設定書籍名稱"}</span><h3>{d.name}</h3><small>{d.subject} · {d.type} · {(d.sizeBytes/1048576).toFixed(2)} MB</small></div><div className={`doc-status ${d.processingStage}`}><b>{d.processingStage==="completed"?"處理完成":d.status==="failed"?"處理失敗":"處理中"}</b><span>{d.error||d.processingMessage}</span></div><div className="doc-counts"><span>{d.chapterCount}<small> 章節</small></span><span>{d.questionCount}<small> 題目</small></span></div><div className="doc-actions"><button onClick={()=>void updateDocBookTitle(d)}>修改書籍名稱</button><button onClick={()=>void updateDocSubject(d)}>修改科目</button>{d.processingStage!=="completed"&&<button onClick={()=>void process(d.id,d.status==="failed")}>{d.status==="failed"?"重新處理":"立即繼續"}</button>}{d.processingStage==="completed"&&d.questionCount===0&&<button onClick={()=>void process(d.id,false,true)}>重新辨識題目</button>}<button className="danger" onClick={()=>void removeDoc(d.id)}>刪除</button></div></article>)}</div></section></>}
  {tab==="questions"&&<DocumentQuestionLibrary/>}
  {tab==="audio"&&<MedtechAudioImport/>}
  {tab==="explanations"&&<MedtechExplanationBatch/>}
 </main>
}
