"use client";
import { useEffect, useMemo, useState } from "react";

type Row={id:number;memberId:number;email:string;displayName:string;role:string;status:"active"|"disabled";canAdmin:boolean;className:string;lastSeenAt:string|null};
export default function MedtechAdminPage(){
  const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[query,setQuery]=useState("");
  const [draft,setDraft]=useState({displayName:"",email:"",className:"",role:"student",status:"active",canAdmin:false});
  async function load(){setLoading(true);const r=await fetch("/api/medtech/members");const d=await r.json() as {members?:Row[];error?:string};setRows(d.members??[]);setNotice(r.ok?"":d.error??"讀取失敗");setLoading(false)}
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(x=>[x.displayName,x.email,x.className].some(v=>v.toLowerCase().includes(q))):rows},[rows,query]);
  async function create(){setNotice("");const r=await fetch("/api/medtech/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error??"新增失敗");return}setDraft({displayName:"",email:"",className:"",role:"student",status:"active",canAdmin:false});setNotice("醫檢師會員已新增。");await load()}
  async function update(id:number,patch:Partial<Row>){const r=await fetch("/api/medtech/members",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(r.ok)setRows(list=>list.map(x=>x.id===id?{...x,...patch}:x));else setNotice("更新失敗，請稍後再試。")}
  return <main className="medtech-admin-page"><header><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師管理後台</b><small>MEMBER MANAGEMENT</small></div></a><nav><a href="/medtech">學生首頁</a><a href="/medtech/account">我的帳號</a></nav></header><section className="medtech-admin-hero"><div><span>醫檢師 · 獨立權限管理</span><h1>會員與帳號管理</h1><p>只顯示醫檢師會員；司律會員與學習資料不會混入。</p></div><b>{rows.length}<small> 位會員</small></b></section><section className="medtech-admin-panel"><h2>新增醫檢師會員</h2><div className="medtech-member-form"><label>姓名<input value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Email<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>班級<input value={draft.className} onChange={e=>setDraft({...draft,className:e.target.value})} placeholder="例如：醫檢 115"/></label><label>身分<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="student">學員</option><option value="teacher">老師／導師</option></select></label><label className="check"><input type="checkbox" checked={draft.canAdmin} onChange={e=>setDraft({...draft,canAdmin:e.target.checked})}/>醫檢管理員</label><button onClick={()=>void create()}>新增會員</button></div>{notice&&<p className="medtech-admin-notice">{notice}</p>}</section><section className="medtech-admin-panel"><div className="medtech-admin-heading"><h2>醫檢會員名單</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋姓名、Email 或班級"/></div>{loading?<p>讀取會員中…</p>:<div className="medtech-admin-list">{visible.map(row=><article key={row.id}><div><b>{row.displayName}</b><span>{row.email}</span></div><label>班級<input value={row.className} onChange={e=>setRows(list=>list.map(x=>x.id===row.id?{...x,className:e.target.value}:x))} onBlur={e=>void update(row.id,{className:e.target.value})}/></label><label>狀態<select value={row.status} onChange={e=>void update(row.id,{status:e.target.value as Row["status"]})}><option value="active">使用中</option><option value="disabled">已停用</option></select></label><label className="check"><input type="checkbox" checked={row.canAdmin} onChange={e=>void update(row.id,{canAdmin:e.target.checked})}/>管理員</label></article>)}{!visible.length&&<p>目前沒有符合條件的會員。</p>}</div>}</section></main>;
}
