"use client";
import { useEffect,useRef,useState } from "react";
import DocumentQuestionLibrary from "./DocumentQuestionLibrary";
import MedtechAudioImport from "./MedtechAudioImport";
import MedtechExplanationBatch from "./MedtechExplanationBatch";
import CommercialMemberControls from "./CommercialMemberControls";
import MedtechGuidedContentBatch from "./MedtechGuidedContentBatch";
import "./processing-progress.css";
import "./processing-note.css";
import { useMedtechAdminAccess } from "./MedtechAdminAccess";
type PaymentOrder={orderId:string;transactionId:string|null;packageName:string;amount:number;currency:string;status:string;environment:string;paidAt:string|null;activatedAt:string|null;createdAt:string};
type Member={id:number;memberId:number;email:string;displayName:string;status:"active"|"disabled";canAdmin:boolean;permissions:string[];className:string;lastSeenAt?:string|number|null;entitlement?:{status:string;expiresAt:string;source:string;note:string}|null;paymentOrders?:PaymentOrder[];practiceStats?:{sessions:number;completed:number;answered:number;durationMinutes:number;accuracy:number;lastStartedAt:string|null;topWrong:{year:string;questionNumber:string;subject:string;count:number}|null}};
type Product={title:string;listPrice:number;salePrice:number|null;saleLabel:string;saleStartsAt:string|null;saleEndsAt:string|null;accessDays:number;trialQuestions:number;status:string;effectivePrice:number;saleActive:boolean};
type Doc={id:number;name:string;bookTitle?:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;chapterCount:number;questionCount:number;error?:string|null};
type SecurityData={sessions:{id:number;userKey:string;displayName:string;deviceLabel:string;status:string;firstSeenAt:string|number;lastSeenAt:string|number;lastPath:string}[];events:{id:number;userKey:string;displayName:string;eventType:string;outcome:string;deviceLabel:string;metadata:Record<string,unknown>;createdAt:string|number}[];note:string};
const subjects=["臨床病毒學","臨床血液學","臨床生化學","臨床微生物學","血庫學","醫學分子檢驗學"];
function adminTime(value:string|number){const date=new Date(value);return Number.isNaN(date.getTime())?"時間未知":new Intl.DateTimeFormat("zh-TW",{dateStyle:"short",timeStyle:"short",hour12:false,timeZone:"Asia/Taipei"}).format(date)}
function securityEventLabel(type:string){return ({new_device:"新裝置登入",device_limit:"超過裝置上限",ip_anomaly:"異常風險提示",kick_device:"踢出裝置"}[type]??type)}
export default function MedtechAdminPage(){
 const {fullAdmin}=useMedtechAdminAccess();
 const [tab,setTab]=useState<"commercial"|"members"|"documents"|"questions"|"guided"|"audio"|"explanations"|"security">("members"),[members,setMembers]=useState<Member[]>([]),[docs,setDocs]=useState<Doc[]>([]),[security,setSecurity]=useState<SecurityData|null>(null),[notice,setNotice]=useState("");
 const [product,setProduct]=useState<Product|null>(null),[canManageCommercial,setCanManageCommercial]=useState(false),[savingProduct,setSavingProduct]=useState(false),[extendDays,setExtendDays]=useState<Record<number,string>>({});
 const [draft,setDraft]=useState({displayName:"",email:"",password:"",className:"",role:"student",status:"active",canAdmin:false});
 const [subject,setSubject]=useState(subjects[0]),[customSubject,setCustomSubject]=useState(""),[bookTitle,setBookTitle]=useState("醫檢師國考題詳解（Ⅲ）臨床病毒學（下）"),[documentType,setDocumentType]=useState("教材"),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[creatingMember,setCreatingMember]=useState(false);
 const processing=useRef(new Set<number>());
 async function loadMembers(){const r=await fetch("/api/medtech/members");const d=await r.json() as {members?:Member[];canManageCommercial?:boolean};setMembers(d.members??[]);setCanManageCommercial(d.canManageCommercial===true)}
 async function loadProduct(){try{const r=await fetch("/api/medtech/admin/product",{cache:"no-store"});const d=await r.json().catch(()=>({})) as {product?:Product;canManageCommercial?:boolean;error?:string};if(d.product)setProduct(d.product);setCanManageCommercial(d.canManageCommercial===true);if(!r.ok)setNotice(d.error??"商品設定讀取失敗，請重新整理後再試。")}catch{setNotice("商品設定讀取失敗，請檢查網路後再試。")}}
 async function loadDocs(){const r=await fetch("/api/medtech/documents",{cache:"no-store"});const d=await r.json() as {documents?:Doc[]};setDocs(d.documents??[])}
 async function loadSecurity(){const r=await fetch("/api/medtech/security",{cache:"no-store"});const d=await r.json() as SecurityData & {error?:string};if(r.ok)setSecurity(d);else setNotice(d.error??"登入狀態讀取失敗。")}
 useEffect(()=>{if(fullAdmin){void loadMembers();void loadProduct()}void loadDocs();const timer=window.setInterval(()=>{void loadDocs()},4000);return()=>window.clearInterval(timer)},[fullAdmin]);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("tab");if(requested==="commercial"||requested==="questions"||requested==="guided"||requested==="documents"||requested==="members"||requested==="audio"||requested==="explanations"||requested==="security")setTab(requested)},[]);
 useEffect(()=>{if(tab!=="security")return;void loadSecurity();const timer=window.setInterval(()=>void loadSecurity(),15000);return()=>window.clearInterval(timer)},[tab]);
 useEffect(()=>{for(const doc of docs){if(["extracting","indexing","analyzing"].includes(doc.processingStage)&&!processing.current.has(doc.id))void process(doc.id)}},[docs]);
 async function create(){if(creatingMember)return;const password=draft.password||window.prompt("請設定會員初始密碼（至少 8 碼）")||"";if(password.length<8){setNotice("會員初始密碼至少需要 8 碼。");return}setCreatingMember(true);setNotice("正在建立會員帳號…");try{const r=await fetch("/api/medtech/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...draft,password})});if(r.ok){setNotice("醫檢師會員已新增。");setDraft({displayName:"",email:"",password:"",className:"",role:"student",status:"active",canAdmin:false});await loadMembers()}else{const data=await r.json() as {error?:string};setNotice(data.error||"新增失敗，請檢查資料。")}}catch{setNotice("新增失敗，請稍後再試。")}finally{setCreatingMember(false)}}
 async function update(id:number,patch:Partial<Member>){const r=await fetch("/api/medtech/members",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(r.ok){setMembers(list=>list.map(x=>x.id===id?{...x,...patch}:x))}}
 async function saveProduct(){if(!product||!canManageCommercial)return;setSavingProduct(true);setNotice("");try{const r=await fetch("/api/medtech/admin/product",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(product)});const d=await r.json().catch(()=>({})) as {product?:Product;error?:string};if(r.ok&&d.product){setProduct(d.product);setNotice("商品價格、活動與開通天數已儲存。")}else setNotice(d.error??`方案儲存失敗（HTTP ${r.status}）。`)}catch{setNotice("方案儲存失敗，請檢查網路後再試。")}finally{setSavingProduct(false)}}
 async function extend(member:Member){const days=Math.max(1,Number(extendDays[member.id]||30));const r=await fetch("/api/medtech/admin/entitlements",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({memberId:member.memberId,days,note:`總管理者延長 ${days} 天`})});const d=await r.json() as {error?:string};if(r.ok){setNotice(`已為 ${member.displayName} 延長 ${days} 天。`);await loadMembers()}else setNotice(d.error??"期限延長失敗")}
 async function togglePermission(member:Member,permission:string,checked:boolean){const permissions=checked?[...new Set([...(member.permissions||[]),permission])]:(member.permissions||[]).filter(item=>item!==permission);await update(member.id,{permissions} as Partial<Member>)}
 async function process(id:number,retry=false,reanalyze=false){if(processing.current.has(id))return;processing.current.add(id);try{const r=await fetch("/api/medtech/documents/process",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,retry,reanalyze})});const d=await r.json() as {error?:string;message?:string};if(!r.ok)setNotice(d.error??"文件處理失敗，請稍後重試。");else if(d.message)setNotice(d.message)}finally{processing.current.delete(id);await loadDocs()}}
 async function upload(){if(!file){setNotice("請先選擇文件。");return}const finalSubject=subject==="__custom__"?customSubject.trim():subject;const finalBookTitle=bookTitle.replace(/\s+/gu," ").trim();if(!finalSubject){setNotice("請輸入自訂科目名稱。");return}if(!finalBookTitle){setNotice("請輸入書籍名稱。");return}setBusy(true);const form=new FormData();form.set("file",file);form.set("subject",finalSubject);form.set("bookTitle",finalBookTitle);form.set("documentType",documentType);const r=await fetch("/api/medtech/documents",{method:"POST",body:form});const d=await r.json() as {document?:{id:number};error?:string};if(r.ok&&d.document){setNotice("上傳完成，正在建立索引。");await process(d.document.id)}else setNotice(d.error??"上傳失敗");setBusy(false)}
 async function updateDocSubject(doc:Doc){const next=prompt("修改科目名稱",doc.subject)?.trim();if(!next||next===doc.subject)return;const r=await fetch("/api/medtech/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,subject:next})});const d=await r.json() as {error?:string};if(r.ok){setDocs(list=>list.map(item=>item.id===doc.id?{...item,subject:next}:item));setNotice(`已將文件與 ${doc.questionCount} 題更新為「${next}」。`)}else setNotice(d.error??"科目修改失敗")}
 async function updateDocBookTitle(doc:Doc){const next=prompt("修改書籍名稱",doc.bookTitle||"")?.replace(/\s+/gu," ").trim();if(!next||next===doc.bookTitle)return;const r=await fetch("/api/medtech/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,bookTitle:next})});const d=await r.json() as {error?:string};if(r.ok){setDocs(list=>list.map(item=>item.id===doc.id?{...item,bookTitle:next}:item));setNotice(`已將文件來源更新為「${next}」。`)}else setNotice(d.error??"書籍名稱更新失敗")}
 async function removeDoc(id:number){if(!confirm("確定刪除這份醫檢教材與索引？"))return;await fetch("/api/medtech/documents",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({ids:[id]})});await loadDocs()}
 const heading=tab==="commercial"?"商品價格與開通設定":tab==="members"?"會員與帳號管理":tab==="documents"?"文件上傳與自動處理":tab==="questions"?"醫檢文件題庫":tab==="guided"?"引導學習預先產生":tab==="audio"?"語音匯入與題庫配對":tab==="security"?"登入狀態與異常紀錄":"解析狀態總覽";
 const heroCount=tab==="members"?members.length:tab==="security"?(security?.sessions.filter((item)=>item.status==="active").length??0):tab==="audio"||tab==="explanations"?"—":docs.length;
 const heroLabel=tab==="members"?" 位會員":tab==="security"?" 台目前使用中的裝置":tab==="audio"||tab==="explanations"?"": " 份文件";
 if(!fullAdmin)return <main className="medtech-admin-page"><header><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師題庫編修</b><small>MEDTECH QUESTION EDITOR</small></div></a><nav><a href="/medtech">學生首頁</a><a href="/medtech/account">我的帳號</a></nav></header><nav className="medtech-admin-tabs"><button className="active">文件題庫</button></nav><section className="medtech-admin-hero"><div><span>醫檢師 · 文件題庫編修權限</span><h1>醫檢文件題庫</h1><p>此帳號只能開啟文件題庫、對照原稿並編修題目。</p></div><b>{docs.length}<small> 份文件</small></b></section><DocumentQuestionLibrary restricted/></main>;
 return <main className="medtech-admin-page">
  <header><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師管理後台</b><small>MEDTECH ADMIN</small></div></a><nav><a href="/medtech">學生首頁</a><a href="/medtech/account">我的帳號</a></nav></header>
  <nav className="medtech-admin-tabs">{canManageCommercial&&<button className={tab==="commercial"?"active":""} onClick={()=>setTab("commercial")}>方案與權限</button>}<button className={tab==="members"?"active":""} onClick={()=>setTab("members")}>會員管理</button><button className={tab==="security"?"active":""} onClick={()=>setTab("security")}>登入狀態</button><button className={tab==="documents"?"active":""} onClick={()=>setTab("documents")}>文件上傳</button><button className={tab==="questions"?"active":""} onClick={()=>setTab("questions")}>文件題庫</button><button className={tab==="guided"?"active":""} onClick={()=>setTab("guided")}>引導內容</button></nav>
  <section className="medtech-admin-hero"><div><span>醫檢師 · 獨立資料管理</span><h1>{heading}</h1><p>{tab==="questions"?"以一份原始文件為單位，對照管理該文件拆出的全部題目。":tab==="explanations"?"AI、老師與語音解析腳本的生成與編輯都在文件題庫工作區內完成，本頁只查看狀態。":tab==="audio"?"錄音完成後，依 TXT 檔名自動驗證並綁定對應題庫。":tab==="security"?"查看學員目前登入裝置、最近活動，以及系統標記的異常登入風險。":"醫檢會員與教材均獨立管理。"}</p></div><b>{heroCount}<small>{heroLabel}</small></b></section>
  {tab==="commercial"&&product&&<section className="medtech-admin-panel"><h2>解題書商品設定</h2><p className="medtech-admin-help">只有總管理者可修改。LINE Pay 下單金額、活動價、付款後開通天數及免費題數均以此處為準。</p><div className="medtech-commercial-grid"><label>商品名稱<input value={product.title} disabled/></label><label>定價 NT$<input type="number" min="1" value={product.listPrice} onChange={e=>setProduct({...product,listPrice:Number(e.target.value)})}/></label><label>活動價 NT$<input type="number" min="1" value={product.salePrice??""} placeholder="未設定" onChange={e=>setProduct({...product,salePrice:e.target.value?Number(e.target.value):null})}/></label><label>活動名稱<input value={product.saleLabel} placeholder="例如：開學優惠" onChange={e=>setProduct({...product,saleLabel:e.target.value})}/></label><label>活動開始<input type="datetime-local" value={product.saleStartsAt?.slice(0,16)??""} onChange={e=>setProduct({...product,saleStartsAt:e.target.value||null})}/></label><label>活動結束<input type="datetime-local" value={product.saleEndsAt?.slice(0,16)??""} onChange={e=>setProduct({...product,saleEndsAt:e.target.value||null})}/></label><label>開通天數<input type="number" min="1" max="3650" value={product.accessDays} onChange={e=>setProduct({...product,accessDays:Number(e.target.value)})}/></label><label>免費體驗題數<input type="number" min="0" value={product.trialQuestions} onChange={e=>setProduct({...product,trialQuestions:Number(e.target.value)})}/></label></div><div className="medtech-commercial-summary"><b>目前售價：NT${product.effectivePrice}</b><span>{product.saleActive?`活動「${product.saleLabel||"優惠價"}」進行中`:`原價方案 · ${product.accessDays} 天`}</span></div><div className="medtech-commercial-actions"><button type="button" className="medtech-save-product-button" onClick={()=>void saveProduct()} disabled={savingProduct} aria-busy={savingProduct}>{savingProduct?"儲存中…":"儲存商品設定"}</button>{notice&&<p className="medtech-admin-notice" role="status" aria-live="polite">{notice}</p>}</div></section>}
  {tab==="commercial"&&canManageCommercial&&<CommercialMemberControls members={members} onReload={loadMembers}/>}
  {tab==="members"&&<><section className="medtech-admin-panel"><h2>新增醫檢師會員</h2><div className="medtech-member-form"><label>姓名<input value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Email<input value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>班級<input value={draft.className} onChange={e=>setDraft({...draft,className:e.target.value})}/></label><label>身分<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="student">學員</option><option value="teacher">老師／導師</option></select></label><label className="check"><input type="checkbox" checked={draft.canAdmin} onChange={e=>setDraft({...draft,canAdmin:e.target.checked})}/>管理員</label><button onClick={()=>void create()} disabled={creatingMember} aria-busy={creatingMember}>{creatingMember?<span className="medtech-loading-label"><i className="medtech-loading-spinner" aria-hidden="true"/>建立中…</span>:"新增會員"}</button></div>{notice&&<p className="medtech-admin-notice">{notice}</p>}</section><section className="medtech-admin-panel"><h2>醫檢會員名單</h2><p className="medtech-admin-help">會員可先免費體驗 30 題；付款後依方案開通，不再使用點數。</p><div className="medtech-admin-list">{members.map(m=><article key={m.id}><div><b>{m.displayName}</b><span>{m.email}</span><span>{m.lastSeenAt ? `最近登入：${new Date(m.lastSeenAt).toLocaleString("zh-TW", { hour12: false, timeZone: "Asia/Taipei" })}` : "尚未登入"}</span>{m.practiceStats&&<div className="medtech-admin-study-summary"><span>刷題 {m.practiceStats.sessions} 次 · 完成 {m.practiceStats.completed} 次 · 作答 {m.practiceStats.answered} 題</span><span>累計 {m.practiceStats.durationMinutes} 分鐘 · 答對率 <b>{m.practiceStats.accuracy}%</b>{m.practiceStats.topWrong&&<> · 最常錯 <em>{m.practiceStats.topWrong.year} 年第 {m.practiceStats.topWrong.questionNumber} 題（{m.practiceStats.topWrong.count} 次）</em></>}</span></div>}</div><label>班級<input value={m.className} onChange={e=>setMembers(list=>list.map(x=>x.id===m.id?{...x,className:e.target.value}:x))} onBlur={e=>void update(m.id,{className:e.target.value})}/></label><label>狀態<select value={m.status} onChange={e=>void update(m.id,{status:e.target.value as Member["status"]})}><option value="active">使用中</option><option value="disabled">已停用</option></select></label><label className="check"><input type="checkbox" checked={m.canAdmin} onChange={e=>void update(m.id,{canAdmin:e.target.checked})}/>管理員</label><label className="check"><input type="checkbox" checked={(m.permissions||[]).includes("questions")} onChange={e=>void togglePermission(m,"questions",e.target.checked)}/>文件題庫編修</label></article>)}</div></section></>}
  {tab==="documents"&&<><section className="medtech-admin-panel"><h2>上傳醫檢教材</h2><div className="medtech-upload-form"><label>書籍名稱<input value={bookTitle} onChange={e=>setBookTitle(e.target.value)} placeholder="例如：醫檢師國考題詳解（Ⅲ）臨床病毒學（下）"/></label><label>科目<select value={subject} onChange={e=>setSubject(e.target.value)}>{[...new Set([...subjects,...docs.map(item=>item.subject)])].map(x=><option key={x}>{x}</option>)}<option value="__custom__">＋ 自訂科目</option></select>{subject==="__custom__"&&<input autoFocus value={customSubject} onChange={e=>setCustomSubject(e.target.value)} placeholder="輸入自訂科目名稱"/>}</label><label>類型<select value={documentType} onChange={e=>setDocumentType(e.target.value)}><option>教材</option><option>題庫</option><option>講義</option><option>考古題</option></select></label><label className="file">文件<input type="file" accept=".pdf,.html,.htm,.docx,.txt,.md,.json,.jsonl,.zip" onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{file?.name??"尚未選擇文件"}</span></label><button disabled={busy} onClick={()=>void upload()}>{busy?"處理中…":"上傳並自動處理"}</button></div>{notice&&<p className="medtech-admin-notice">{notice}</p>}</section><section className="medtech-admin-panel"><h2>醫檢教材清單</h2><div className="medtech-document-list">{docs.map(d=><article key={d.id}><div className="doc-main"><span>{d.bookTitle||"尚未設定書籍名稱"}</span><h3>{d.name}</h3><small>{d.subject} · {d.type} · {(d.sizeBytes/1048576).toFixed(2)} MB</small></div><div className={`doc-status ${d.processingStage}`}><b>{d.processingStage==="completed"?"處理完成":d.status==="failed"?"處理失敗":"處理中"}</b><span>{d.error||d.processingMessage}</span></div><div className="doc-counts"><span>{d.chapterCount}<small> 章節</small></span><span>{d.questionCount}<small> 題目</small></span></div><div className="doc-actions"><button onClick={()=>void updateDocBookTitle(d)}>修改書籍名稱</button><button onClick={()=>void updateDocSubject(d)}>修改科目</button>{d.processingStage!=="completed"&&<button onClick={()=>void process(d.id,d.status==="failed")}>{d.status==="failed"?"重新處理":"立即繼續"}</button>}{d.processingStage==="completed"&&d.questionCount===0&&<button onClick={()=>void process(d.id,false,true)}>重新辨識題目</button>}<button className="danger" onClick={()=>void removeDoc(d.id)}>刪除</button></div></article>)}</div></section></>}
  {tab==="questions"&&<DocumentQuestionLibrary/>}
  {tab==="guided"&&<MedtechGuidedContentBatch/>}
  {tab==="audio"&&<MedtechAudioImport/>}
  {tab==="explanations"&&<MedtechExplanationBatch/>}
  {tab==="security"&&<><section className="medtech-admin-panel"><div className="medtech-security-heading"><div><h2>目前登入裝置</h2><p>同一帳號最多同時使用 2 台；超過時學員會看到提示並可自行踢出其中一台。</p></div><button type="button" onClick={()=>void loadSecurity()}>重新整理</button></div><p className="medtech-admin-help">{security?.note??"IP 僅以雜湊保存；異常事件是風險提示，不單靠 IP 判定。"}</p><div className="medtech-security-session-list">{security?.sessions.filter((item)=>item.status==="active").length?security.sessions.filter((item)=>item.status==="active").map((item)=><article key={item.id}><div><b>{item.displayName}</b><span>{item.userKey}</span></div><div><strong>{item.deviceLabel}</strong><span>最近活動：{adminTime(item.lastSeenAt)}</span></div><span className="medtech-security-status">使用中</span></article>):<p className="medtech-security-empty">目前沒有裝置活動資料。</p>}</div></section><section className="medtech-admin-panel"><div className="medtech-security-heading"><div><h2>異常登入與裝置事件</h2><p>保留登入、超過上限、踢出裝置與風險提示，方便追查使用情形。</p></div></div><div className="medtech-security-event-list">{security?.events.length?security.events.map((event)=><article key={event.id} className={event.outcome==="review"||event.outcome==="blocked"?"risk":""}><div><b>{securityEventLabel(event.eventType)}</b><span>{event.displayName} · {event.userKey}</span></div><div><strong>{event.deviceLabel}</strong><span>{adminTime(event.createdAt)}</span></div><em>{event.outcome==="allowed"?"已放行":event.outcome==="blocked"?"已阻擋":"需要留意"}</em></article>):<p className="medtech-security-empty">目前沒有異常事件。</p>}</div></section></>}
 </main>
}
