"use client";
import "./question-bank.css";
import { useEffect,useState } from "react";

type Category="medtech"|"accounting";
type Question={id:number;examType?:string;year:string;subject:string;questionNumber:string;stem:string;options:Record<string,string>;correctAnswer:string|null;explanation:string;completeExplanation?:string;teacherAnswer?:string;answerSource:string;status:string};
const plain=(value:string)=>value.replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim();

export default function QuestionBank({category="medtech"}:{category?:Category}){
 const accounting=category==="accounting",label=accounting?"中會":"醫檢",endpoint=accounting?"/api/accounting/admin/questions":"/api/medtech/admin/questions",workbench=accounting?"/accounting/admin/question-workbench":"/medtech/admin/question-workbench";
 const [items,setItems]=useState<Question[]>([]),[total,setTotal]=useState(0),[draftTotal,setDraftTotal]=useState(0),[page,setPage]=useState(1),[years,setYears]=useState<string[]>([]),[subjects,setSubjects]=useState<string[]>([]),[query,setQuery]=useState(""),[year,setYear]=useState(""),[subject,setSubject]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(false),[publishing,setPublishing]=useState(false),[message,setMessage]=useState("");const limit=30;
 async function load(nextPage=page){setLoading(true);const p=new URLSearchParams({page:String(nextPage),limit:String(limit)});if(query)p.set("query",query);if(year)p.set("year",year);if(subject)p.set("subject",subject);if(status)p.set("status",status);const r=await fetch(endpoint+"?"+p,{cache:"no-store"});const d=await r.json() as {items?:Question[];total?:number;draftTotal?:number;years?:string[];subjects?:string[];error?:string};if(r.ok){setItems(d.items??[]);setTotal(d.total??0);setDraftTotal(d.draftTotal??0);setYears(d.years??[]);setSubjects(d.subjects??[]);setPage(nextPage)}else setMessage(d.error??"題庫讀取失敗");setLoading(false)}
 useEffect(()=>{void load(1)},[]);
 async function toggle(item:Question){await fetch(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,status:item.status==="published"?"disabled":"published"})});await load()}
 async function publishAll(){if(!draftTotal){setMessage("目前沒有待發布的"+label+"草稿題目。");return}if(!confirm("確定要發布全部 "+draftTotal.toLocaleString()+" 題"+label+"草稿？發布後會立即出現在學生端。"))return;setPublishing(true);setMessage("正在發布"+label+"題目…");const r=await fetch(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({publishAllDrafts:true})});const d=await r.json() as {updated?:number;error?:string};if(r.ok)setMessage("已發布 "+Number(d.updated??0).toLocaleString()+" 題"+label+"題目，前台現在可以開始練習。");else setMessage(d.error??"發布失敗，請稍後再試。");setPublishing(false);await load(1)}
 async function remove(item:Question){if(!confirm("確定刪除第 "+item.questionNumber+" 題？此操作無法復原。"))return;await fetch(endpoint,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id})});setMessage("題目已刪除。");await load(Math.min(page,Math.max(1,Math.ceil((total-1)/limit))))}
 const pages=Math.max(1,Math.ceil(total/limit));
 return <><section className="medtech-admin-panel question-tools"><div className="medtech-admin-heading"><div><h2>{label}題庫總覽</h2><p>共 {total.toLocaleString()} 題，只顯示{label}類科。{draftTotal?" 另有 "+draftTotal.toLocaleString()+" 題草稿尚未發布。":""}</p></div><div className="question-tools-actions"><button className="refresh" onClick={()=>void load(1)}>重新整理</button><button className="publish-all" disabled={publishing||!draftTotal} onClick={()=>void publishAll()}>{publishing?"發布中…":draftTotal?"全部發布（"+draftTotal.toLocaleString()+" 題）":"沒有待發布題目"}</button></div></div><div className="question-filters"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load(1)} placeholder="搜尋題幹、題號或解析"/><select value={year} onChange={e=>setYear(e.target.value)}><option value="">全部年份</option>{years.map(x=><option key={x}>{x}</option>)}</select><select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">全部科目</option>{subjects.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部狀態</option><option value="published">已啟用</option><option value="disabled">已停用</option><option value="draft">草稿</option></select><button onClick={()=>void load(1)}>搜尋</button></div>{message&&<p className="medtech-admin-notice">{message}</p>}</section><section className="medtech-admin-panel"><div className="medtech-question-admin-list">{loading?<p>正在讀取題庫…</p>:items.map(item=><article key={item.id}><header><div><span>{item.year} 年 · {item.subject} · 第 {item.questionNumber} 題</span><b className={item.status}>{item.status==="published"?"已啟用":item.status==="disabled"?"已停用":"草稿"}</b></div><h3>{plain(item.stem)}</h3></header><details><summary>查看選項、答案與解析</summary>{item.examType!=="essay"&&<div className="admin-question-options">{Object.entries(item.options).map(([key,value])=><div className={key===item.correctAnswer?"correct":""} key={key}><b>{key}</b><span>{plain(value)}</span></div>)}</div>}<div className="admin-question-explanation"><b>{item.examType==="essay"?"老師解答":"正確答案："+(item.correctAnswer||"未設定")}</b>{item.examType==="essay"?<p>{plain(item.teacherAnswer||item.explanation)||"尚無老師解答"}</p>:<><strong>解析（題目原有簡要解析）</strong><p>{plain(item.explanation)||"題目原稿未附簡要解析"}</p><strong>完整解析（老師／語音文本）</strong><p>{plain(item.completeExplanation||"")||"尚未補充完整解析"}</p></>}<small>來源：{item.answerSource||"未標示"}</small></div></details><footer><button onClick={()=>{window.location.href=workbench+"?id="+item.id}}>開啟題目工作台</button><button onClick={()=>void toggle(item)}>{item.status==="published"?"停用":"啟用"}</button><button className="danger" onClick={()=>void remove(item)}>刪除</button></footer></article>)}{!loading&&!items.length&&<p>沒有符合條件的題目。</p>}</div><div className="question-pagination"><button disabled={page<=1} onClick={()=>void load(page-1)}>上一頁</button><span>第 {page}／{pages} 頁</span><button disabled={page>=pages} onClick={()=>void load(page+1)}>下一頁</button></div></section></>;
}
