"use client";
import { FormEvent, useState } from "react";
import CourseVideoPlayer from "../../../course-video-player";

type Highlight={id:number;title:string;summary:string;startSeconds:number|null};
type Props={courseId:number;title:string;sourceUrl:string;owned:boolean;expiresAt:string|null;price:number;accessDays:number;previewStartSeconds:number;previewDurationSeconds:number;salesEnabled:boolean;signedIn:boolean;highlights:Highlight[]};
function timeLabel(value:number|null){const total=Math.max(0,Math.floor(Number(value)||0)),hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return hours?`${hours}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`:`${minutes}:${String(seconds).padStart(2,"0")}`}
export default function PosnerCourseAccess(p:Props){
 const[ended,setEnded]=useState(false),[busy,setBusy]=useState(false),[code,setCode]=useState(""),[notice,setNotice]=useState(""),[seekSeconds,setSeekSeconds]=useState(p.owned?0:p.previewStartSeconds),[seekToken,setSeekToken]=useState(0),[activeMoment,setActiveMoment]=useState<number|null>(null);
 const login=()=>{location.href=`/member-login?return_to=${encodeURIComponent(`/posner/course/${p.courseId}`)}`};
 async function buy(){if(!p.signedIn)return login();setBusy(true);setNotice("");const r=await fetch("/api/posner/line-pay/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId:p.courseId})}),d=await r.json()as{paymentUrl?:string;redirectUrl?:string;error?:string};if(d.paymentUrl)location.href=d.paymentUrl;else if(d.redirectUrl)location.href=d.redirectUrl;else{setNotice(d.error||"目前無法建立付款");setBusy(false)}}
 async function redeem(e:FormEvent){e.preventDefault();if(!p.signedIn)return login();setBusy(true);setNotice("");const r=await fetch("/api/posner/redeem",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId:p.courseId,code})}),d=await r.json()as{ok?:boolean;error?:string};if(d.ok)location.reload();else{setNotice(d.error||"兌換失敗");setBusy(false)}}
 const previewEnd=p.previewStartSeconds+p.previewDurationSeconds;
 const visibleHighlights=p.owned?p.highlights:p.highlights.filter(moment=>{const seconds=Math.max(0,Math.floor(Number(moment.startSeconds)||0));return seconds>=p.previewStartSeconds&&seconds<previewEnd});
 const lockedHighlightCount=Math.max(0,p.highlights.length-visibleHighlights.length);
 const actions=<><button onClick={()=>void buy()} disabled={busy||!p.salesEnabled}>{p.salesEnabled?`LINE Pay NT$${p.price} 購買`:"目前未開放購買"}</button><form onSubmit={redeem}><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="輸入兌換碼"/><button disabled={busy||!code.trim()}>立即兌換</button></form></>;
 function jumpTo(moment:Highlight){const seconds=Math.max(0,Math.floor(Number(moment.startSeconds)||0)),previewEnd=p.previewStartSeconds+p.previewDurationSeconds;if(!p.owned&&(seconds<p.previewStartSeconds||seconds>=previewEnd)){setEnded(true);return}setEnded(false);setSeekSeconds(seconds);setSeekToken(token=>token+1);setActiveMoment(moment.id)}
 return <section className="posner-watch">
  <div className="posner-player-grid"><div className="posner-player-wrap"><CourseVideoPlayer resourceId={p.courseId} sourceUrl={p.sourceUrl} title={p.title} startSeconds={seekSeconds} seekToken={seekToken} playOnSeek onTimeChange={s=>{if(!p.owned&&p.previewDurationSeconds>0&&s>=p.previewStartSeconds+p.previewDurationSeconds-1)setEnded(true)}}/>{!p.owned&&ended&&<div className="posner-preview-lock"><div><span>精彩試看已結束</span><h2>繼續看完整課程</h2><p>LINE Pay 付款或輸入兌換碼後，立即從這裡繼續觀看。</p>{actions}{notice&&<small role="alert">{notice}</small>}</div></div>}</div><aside className="posner-timeline-preview"><span>KEY MOMENTS</span><h2>重點時間軸</h2>{visibleHighlights.length?visibleHighlights.map(moment=><button type="button" className={activeMoment===moment.id?"active":""} onClick={()=>jumpTo(moment)} key={moment.id}><time>{timeLabel(moment.startSeconds)}</time><span><b>{moment.title||"課堂重點"}</b><small>{moment.summary}</small></span></button>):<div className="posner-summary-pending"><b>{p.highlights.length?"此試聽片段沒有公開摘要":"本機字幕與摘要準備中"}</b><span>{p.highlights.length?"購買或兌換後即可查看完整重點時間軸。":"完成後，每個時間點都能直接跳轉播放。"}</span></div>}{!p.owned&&lockedHighlightCount>0&&<div className="posner-timeline-locked"><b>完整課程另有 {lockedHighlightCount} 個重點</b><span>購買或輸入兌換碼後解鎖完整摘要與時間跳轉。</span></div>}</aside></div>
  <div className="posner-access-bar"><div><b>{p.owned?"完整課程已開通":`免費試看 ${Math.floor(p.previewDurationSeconds/60)} 分 ${p.previewDurationSeconds%60} 秒`}</b><span>{p.owned&&p.expiresAt?`可觀看至 ${new Date(p.expiresAt).toLocaleDateString("zh-TW")}`:`精彩片段從 ${Math.floor(p.previewStartSeconds/60)}:${String(p.previewStartSeconds%60).padStart(2,"0")} 開始`}</span></div>{!p.owned&&<div className="posner-buy-actions"><button onClick={()=>void buy()} disabled={busy||!p.salesEnabled}>{p.salesEnabled?`LINE Pay NT$${p.price}｜觀看 ${p.accessDays} 天`:"暫停銷售"}</button><form onSubmit={redeem}><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="兌換碼"/><button disabled={busy||!code.trim()}>兌換</button></form></div>}</div>
  {notice&&<p className="posner-payment-notice" role="alert">{notice}</p>}
 </section>
}
