"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Question = { id:number; year:string; questionNumber:string; stem:string; options:Record<string,string>; answer:string; explanation:string; answerSource:string; subject:string };
const letters = ["A", "B", "C", "D"];

export default function MedtechPractice() {
  const [rows,setRows]=useState<Question[]>([]); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Record<number,string>>({});
  const [submitted,setSubmitted]=useState(false); const [flagged,setFlagged]=useState<number[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{ fetch("/api/medtech/questions?limit=30").then(async response=>{const result=await response.json() as {items?:Question[];error?:string};if(!response.ok)throw new Error(result.error||"題庫讀取失敗");setRows(result.items??[]);if(!result.items?.length)setError("目前沒有已發布的醫檢師題目。");}).catch(reason=>setError(reason instanceof Error?reason.message:"題庫讀取失敗")).finally(()=>setLoading(false)); },[]);
  const q=rows[index]; const score=useMemo(()=>rows.filter(item=>answers[item.id]===item.answer).length,[answers,rows]); const answered=Object.keys(answers).length;
  const top=<header className="medtech-top" data-no-navigation-feedback><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師備考</b><small>臨床病毒學</small></div></a><nav><a href="/medtech">首頁</a><a href="/medtech/practice" className="active">練國考題</a></nav></header>;
  if(loading||error||!q)return <main className="medtech-practice">{top}<section className="medtech-result"><span>{loading?"讀取中":"題庫狀態"}</span><h1>{loading?"正在準備題目…":error}</h1>{!loading&&<Link href="/medtech">返回醫檢師首頁</Link>}</section></main>;
  if(submitted) {
    const userAnswer=answers[q.id]||""; const isCorrect=userAnswer===q.answer;
    return <main className="medtech-practice medtech-review">{top}<section className="medtech-review-summary"><div><span>本回成績</span><b>{score}<small>／{rows.length}</small></b><p>答對率 {Math.round(score/rows.length*100)}% · 已作答 {answered} 題</p></div><button onClick={()=>{setSubmitted(false);setIndex(0);setAnswers({});setFlagged([])}}>重新抽題</button></section><div className="medtech-exam-grid"><aside className="medtech-question-map"><header><b>逐題檢討</b><span>{index+1}／{rows.length}</span></header><div>{rows.map((item,i)=>{const picked=answers[item.id];return <button key={item.id} className={`${i===index?"active":""} ${picked===item.answer?"review-right":"review-wrong"}`} onClick={()=>setIndex(i)}>{i+1}</button>})}</div><small>綠色＝答對 · 紅色＝答錯或未作答</small></aside><section className="medtech-question medtech-review-question"><header><span>第 {index+1} 題 · {q.year} 年專技</span><strong className={isCorrect?"review-status right":"review-status wrong"}>{isCorrect?"答對":"答錯"}</strong></header><h2>{q.stem}</h2><div className="medtech-review-answer-line"><span>你的答案：<b>{userAnswer||"未作答"}</b></span><span>正確答案：<b>{q.answer}</b></span></div><div className="medtech-options medtech-review-options">{letters.map(letter=><div className={`${letter===q.answer?"correct":""} ${letter===userAnswer&&letter!==q.answer?"wrong":""}`} key={letter}><b>{letter}</b><span>{q.options[letter]}</span>{letter===q.answer&&<em>正確答案</em>}{letter===userAnswer&&letter!==q.answer&&<em>你的答案</em>}</div>)}</div><section className="medtech-explanation"><span>教材解析</span><p>{q.explanation?.trim()||`本題教材答案為 ${q.answer}；此題原稿未附文字解析。`}</p><small>來源：{q.answerSource}</small></section><footer><button disabled={index===0} onClick={()=>setIndex(index-1)}>上一題</button><span>逐題核對作答與教材答案</span><button disabled={index===rows.length-1} onClick={()=>setIndex(index+1)}>下一題</button></footer></section></div></main>;
  }
  return <main className="medtech-practice">{top}<section className="medtech-exam-head"><div><span>正式題庫 · 隨機 30 題</span><h1>臨床病毒學（下）</h1><p>第 {index+1}／{rows.length} 題 · {q.year} 年專技</p></div><button onClick={()=>setSubmitted(true)}>交卷</button></section><div className="medtech-exam-grid"><aside className="medtech-question-map"><header><b>題號</b><span>{answered}／{rows.length} 已作答</span></header><div>{rows.map((item,i)=><button key={item.id} className={`${i===index?"active":""} ${answers[item.id]?"answered":""} ${flagged.includes(item.id)?"flagged":""}`} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><small>實心＝已作答 · 圓點＝待確認</small></aside><section className="medtech-question"><header><span>第 {index+1} 題</span><button onClick={()=>setFlagged(value=>value.includes(q.id)?value.filter(id=>id!==q.id):[...value,q.id])}>{flagged.includes(q.id)?"取消標記":"標記待確認"}</button></header><h2>{q.stem}</h2><div className="medtech-options">{letters.map(letter=><button className={answers[q.id]===letter?"selected":""} key={letter} onClick={()=>setAnswers({...answers,[q.id]:letter})}><b>{letter}</b><span>{q.options[letter]}</span></button>)}</div><footer><button disabled={index===0} onClick={()=>setIndex(index-1)}>上一題</button><span>答案在交卷前不顯示</span><button disabled={index===rows.length-1} onClick={()=>setIndex(index+1)}>下一題</button></footer></section></div></main>;
}
