import {eq,like} from "drizzle-orm";
import {accountingProducts,appSettings,medtechProducts} from "../../../../db/schema";
import {requireAdmin} from "../../../../lib/member-auth";
const OWNER="iamflashon@gmail.com";
function int(value:unknown,min:number,max:number){const n=Number(value);if(!Number.isFinite(n))throw new Error("數值格式不正確");return Math.min(max,Math.max(min,Math.round(n)))}
function date(value:unknown){if(value===null||value==="")return null;const d=new Date(String(value));if(Number.isNaN(d.getTime()))throw new Error("活動日期格式不正確");return d}
function key(category:string){return category+"-book-"+Date.now().toString(36)+"-"+crypto.randomUUID().slice(0,8)}
export async function GET(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;const[accounting,medtech,covers]=await Promise.all([auth.db.select().from(accountingProducts),auth.db.select().from(medtechProducts),auth.db.select().from(appSettings).where(like(appSettings.key,"central_product_cover:%"))]);const coverMap=new Map(covers.map(row=>[row.key.slice("central_product_cover:".length),row.value]));return Response.json({products:[...accounting.map(item=>({...item,category:"accounting",centralCoverKey:coverMap.get(`accounting:${item.productKey}`)??item.coverStorageKey??null})),...medtech.map(item=>({...item,category:"medtech",centralCoverKey:coverMap.get(`medtech:${item.productKey}`)??null}))]},{headers:{"cache-control":"no-store"}})}
export async function POST(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;if(auth.member.email.toLowerCase()!==OWNER)return Response.json({error:"只有總管理者可建立商品"},{status:403});try{const body=await request.json() as Record<string,unknown>,category=String(body.category||""),title=String(body.title||"").trim();if(!title)return Response.json({error:"缺少書名"},{status:400});if(!["accounting","medtech"].includes(category))return Response.json({error:"目前先開放會計與醫檢商品"},{status:400});const productKey=key(category);if(category==="accounting")await auth.db.insert(accountingProducts).values({productKey,title,subtitle:"",descriptionHtml:"",listPrice:249,accessDays:90,trialQuestions:10,status:"draft",renewalMode:"extend",sortOrder:100});else await auth.db.insert(medtechProducts).values({productKey,title,listPrice:199,accessDays:90,trialQuestions:30,status:"disabled"});return Response.json({ok:true,productKey})}catch(e){return Response.json({error:e instanceof Error?e.message:"建立商品失敗"},{status:400})}}
export async function PATCH(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;if(auth.member.email.toLowerCase()!==OWNER)return Response.json({error:"只有總管理者可修改商品"},{status:403});try{const body=await request.json() as Record<string,unknown>,category=String(body.category||""),productKey=String(body.productKey||"");if(!productKey)return Response.json({error:"缺少商品編號"},{status:400});const values={listPrice:int(body.listPrice,1,1000000),salePrice:body.salePrice===null||body.salePrice===""?null:int(body.salePrice,1,1000000),saleLabel:String(body.saleLabel||"").trim().slice(0,80),saleStartsAt:date(body.saleStartsAt),saleEndsAt:date(body.saleEndsAt),accessDays:int(body.accessDays,1,3650),trialQuestions:int(body.trialQuestions,0,5000),status:["draft","active","disabled"].includes(String(body.status))?String(body.status):"draft",updatedAt:new Date()};if(values.saleStartsAt&&values.saleEndsAt&&values.saleStartsAt>values.saleEndsAt)throw new Error("活動結束必須晚於開始");if(category==="accounting")await auth.db.update(accountingProducts).set(values).where(eq(accountingProducts.productKey,productKey));else if(category==="medtech")await auth.db.update(medtechProducts).set({...values,status:values.status==="draft"?"disabled":values.status}).where(eq(medtechProducts.productKey,productKey));else return Response.json({error:"不支援的類科"},{status:400});return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"儲存商品失敗"},{status:400})}}
