"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Job={id:string;sourceFile:string;status:string;message?:string;extractedChars?:number;chunkCount?:number;pageCount?:number|null;documentId?:number;indexStatus?:string;subject?:string;examCategory?:string;documentType?:string;bookTitle?:string};
type InboxFile={name:string;sizeBytes:number;modifiedAt:number};
type NodePayload={connected?:boolean;node?:{version?:string;inboxFiles?:InboxFile[]}|null};
const labels:Record<string,string>={queued:"排隊中",claimed:"本機處理中",completed:"已完成",failed:"失敗",cancelled:"已取消"};
const MAX_BATCH=10;
const JOBS_PER_PAGE=10;

export default function LocalNodeJobsPanel(){
 const [jobs,setJobs]=useState<Job[]>([]),[inboxFiles,setInboxFiles]=useState<InboxFile[]>([]),[selected,setSelected]=useState<string[]>([]),[sourceFile,setSourceFile]=useState(""),[examCategory,setExamCategory]=useState("law"),[subject,setSubject]=useState("法律"),[documentType,setDocumentType]=useState("核心教材"),[bookTitle,setBookTitle]=useState(""),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false),[scanning,setScanning]=useState(false),[nodeVersion,setNodeVersion]=useState(""),[jobsExpanded,setJobsExpanded]=useState(true),[jobsPage,setJobsPage]=useState(1);
 const load=useCallback(async()=>{const [jobsResponse,nodeResponse]=await Promise.all([fetch("/api/admin/local-node/jobs",{cache:"no-store"}),fetch("/api/admin/local-node",{cache:"no-store"})]);if(jobsResponse.ok)setJobs(((await jobsResponse.json()) as {jobs?:Job[]}).jobs??[]);if(nodeResponse.ok){const node=(await nodeResponse.json()) as NodePayload;setNodeVersion(node.node?.version??"");setInboxFiles(node.node?.inboxFiles??[])}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[load]);
 const latestByFile=useMemo(()=>{const map=new Map<string,Job>();for(const job of jobs)if(!map.has(job.sourceFile.toLowerCase()))map.set(job.sourceFile.toLowerCase(),job);return map},[jobs]);
 const selectable=useMemo(()=>inboxFiles.filter(file=>!(["queued","claimed","completed"].includes(latestByFile.get(file.name.toLowerCase())?.status??""))),[inboxFiles,latestByFile]);
 const jobsPageCount=Math.max(1,Math.ceil(jobs.length/JOBS_PER_PAGE));
 const visibleJobs=jobs.slice((jobsPage-1)*JOBS_PER_PAGE,jobsPage*JOBS_PER_PAGE);
 useEffect(()=>{setJobsPage(current=>Math.min(current,jobsPageCount))},[jobsPageCount]);
 function changeCategory(value:string){setExamCategory(value);setSubject(value==="accounting"?"中級會計":value==="medtech"?"醫檢師":value==="data-structure"?"資料結構":"法律")}
 async function send(payload:Record<string,unknown>){const response=await fetch("/api/admin/local-node/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string;created?:number;skipped?:Array<{sourceFile:string;reason:string}>};if(!response.ok)throw new Error(result.error??"無法建立本機工作");return result}
 async function submit(event:FormEvent){event.preventDefault();setSubmitting(true);setMessage("");try{await send({sourceFile,examCategory,subject,documentType,bookTitle});setSourceFile("");setBookTitle("");setMessage("已送入公司本機佇列");await load()}catch(error){setMessage(error instanceof Error?error.message:"無法建立本機工作")}finally{setSubmitting(false)}}
 async function scanInbox(){setScanning(true);setMessage("");try{await load();setMessage("已重新讀取本機節點狀態；新放入的檔案最晚會在下一次 30 秒心跳後出現。") }finally{setScanning(false)}}
 async function submitBatch(){if(!selected.length)return;setSubmitting(true);setMessage("");try{const result=await send({sourceFiles:selected.slice(0,MAX_BATCH),examCategory,subject,documentType});setSelected([]);setMessage(`已加入 ${result.created??0} 份；${result.skipped?.length??0} 份重複或已完成，自動跳過。RTX 4090 將逐份處理。`);await load()}catch(error){setMessage(error instanceof Error?error.message:"批次加入失敗")}finally{setSubmitting(false)}}
 async function retry(job:Job){setSubmitting(true);try{await send({sourceFile:job.sourceFile,examCategory:job.examCategory??examCategory,subject:job.subject??subject,documentType:job.documentType??documentType,bookTitle:job.bookTitle});setMessage(`「${job.sourceFile}」已重新排隊。`);await load()}catch(error){setMessage(error instanceof Error?error.message:"重試失敗")}finally{setSubmitting(false)}}
 return <section className="panel local-node-jobs-panel"><div className="local-node-title"><div><p>PRIVATE PROCESSING QUEUE</p><h2>公司本機 OCR／索引佇列</h2><span>原稿留在 C:\iBrain-local-node\inbox；雲端只接收逐頁文字切片。RTX 4090 永遠逐份處理。</span></div><div><a href="/iBrain-local-node-v0.4.2.zip" download>下載本機節點 v0.4.2</a><button type="button" onClick={()=>void scanInbox()} disabled={scanning}>{scanning?"掃描中…":"掃描本機 inbox"}</button></div></div>
 <form onSubmit={submit}><div className="local-node-job-fields"><input value={sourceFile} onChange={event=>setSourceFile(event.target.value)} placeholder="單筆檔名，例如：刑法教材.pdf" aria-label="本機 inbox 檔名"/><select value={examCategory} onChange={event=>changeCategory(event.target.value)} aria-label="類科"><option value="law">法律</option><option value="accounting">會計</option><option value="medtech">醫檢師</option><option value="data-structure">資料結構</option></select><input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="科目"/><select value={documentType} onChange={event=>setDocumentType(event.target.value)} aria-label="文件類型"><option>核心教材</option><option>題庫</option><option>年度解題</option><option>申論題庫</option></select><input value={bookTitle} onChange={event=>setBookTitle(event.target.value)} placeholder="書名（未填則採檔名）"/></div><button type="submit" disabled={submitting||!sourceFile.trim()}>{submitting?"送出中…":"交給 RTX 4090"}</button></form>
 {!!inboxFiles.length&&<div className="local-inbox-browser"><header><div><strong>本機 inbox</strong><small>{inboxFiles.length} 份支援檔案 · 節點 {nodeVersion||"等待回報"}</small></div><label><input type="checkbox" checked={selectable.length>0&&selectable.slice(0,MAX_BATCH).every(file=>selected.includes(file.name))} onChange={event=>setSelected(event.target.checked?selectable.slice(0,MAX_BATCH).map(file=>file.name):[])} />選取下一批（最多 {MAX_BATCH} 份）</label><button type="button" onClick={()=>void submitBatch()} disabled={submitting||!selected.length}>加入處理佇列（{selected.length}）</button></header><div>{inboxFiles.map(file=>{const job=latestByFile.get(file.name.toLowerCase());const disabled=Boolean(job&&["queued","claimed","completed"].includes(job.status));return <label key={file.name} className={disabled?"disabled":""}><input type="checkbox" disabled={disabled||(!selected.includes(file.name)&&selected.length>=MAX_BATCH)} checked={selected.includes(file.name)} onChange={event=>setSelected(current=>event.target.checked?[...current,file.name]:current.filter(name=>name!==file.name))}/><span><b>{file.name}</b><small>{(file.sizeBytes/1024/1024).toFixed(1)} MB · {new Date(file.modifiedAt).toLocaleString("zh-TW")}</small></span><em className={`job-${job?.status??"available"}`}>{job?labels[job.status]??job.status:"可加入"}</em></label>})}</div></div>}
 {message&&<p className="local-node-job-message">{message}</p>}
 <div className="local-node-history">
  <button className="local-node-history-toggle" type="button" onClick={()=>setJobsExpanded(value=>!value)} aria-expanded={jobsExpanded}>
   <span><strong>處理佇列與紀錄</strong><small>共 {jobs.length} 份 · 每頁 {JOBS_PER_PAGE} 份</small></span><b>{jobsExpanded?"收合 ▲":"展開 ▼"}</b>
  </button>
  {jobsExpanded&&<><div className="local-node-job-list">{jobs.length?visibleJobs.map(job=><div key={job.id}><strong>{job.sourceFile}</strong><span className={`job-${job.status}`}>{labels[job.status]??job.status}</span><small>{job.subject?`${job.subject} · `:""}{job.message??""}{job.status==="completed"?` · ${(job.extractedChars??0).toLocaleString()} 字／${job.chunkCount??0} 切片${job.pageCount?`／${job.pageCount} 頁`:""}${job.documentId?` · 教材 #${job.documentId} 等待索引`:""}`:""}</small>{job.status==="failed"&&<button type="button" onClick={()=>void retry(job)} disabled={submitting}>重新排隊</button>}</div>):<p>目前沒有本機工作。</p>}</div>
  {jobsPageCount>1&&<nav className="local-node-pagination" aria-label="處理紀錄分頁"><button type="button" onClick={()=>setJobsPage(page=>Math.max(1,page-1))} disabled={jobsPage===1}>上一頁</button><span>第 {jobsPage}／{jobsPageCount} 頁</span><button type="button" onClick={()=>setJobsPage(page=>Math.min(jobsPageCount,page+1))} disabled={jobsPage===jobsPageCount}>下一頁</button></nav>}</>}
 </div></section>
}
