"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
type Job={id:string;sourceFile:string;status:string;message?:string;extractedChars?:number;chunkCount?:number;pageCount?:number|null;documentId?:number;indexStatus?:string;subject?:string};
const labels:Record<string,string>={queued:"排隊中",claimed:"本機處理中",completed:"已完成",failed:"失敗",cancelled:"已取消"};
export default function LocalNodeJobsPanel(){
 const [jobs,setJobs]=useState<Job[]>([]),[sourceFile,setSourceFile]=useState(""),[examCategory,setExamCategory]=useState("law"),[subject,setSubject]=useState("法律"),[documentType,setDocumentType]=useState("核心教材"),[bookTitle,setBookTitle]=useState(""),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false);
 const load=useCallback(async()=>{const response=await fetch("/api/admin/local-node/jobs",{cache:"no-store"});if(response.ok)setJobs(((await response.json()) as {jobs?:Job[]}).jobs??[])},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[load]);
 function changeCategory(value:string){setExamCategory(value);setSubject(value==="accounting"?"中級會計":value==="medtech"?"醫檢師":value==="data-structure"?"資料結構":"法律")}
 async function submit(event:FormEvent){event.preventDefault();setSubmitting(true);setMessage("");try{const response=await fetch("/api/admin/local-node/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceFile,examCategory,subject,documentType,bookTitle})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??"無法建立本機工作");setSourceFile("");setBookTitle("");setMessage("已送入公司本機佇列");await load()}catch(error){setMessage(error instanceof Error?error.message:"無法建立本機工作")}finally{setSubmitting(false)}}
 return <section className="panel local-node-jobs-panel"><div><p>PRIVATE PROCESSING QUEUE</p><h2>公司本機 OCR／索引佇列</h2><span>將 PDF／Word／文字檔放入 C:\iBrain-local-node\inbox。原稿不離開公司；雲端只接收逐頁文字切片，並接續平台既有全文／向量索引。</span></div><form onSubmit={submit}><div className="local-node-job-fields"><input value={sourceFile} onChange={event=>setSourceFile(event.target.value)} placeholder="本機完整檔名，例如：刑法教材.pdf" aria-label="本機 inbox 檔名"/><select value={examCategory} onChange={event=>changeCategory(event.target.value)} aria-label="類科"><option value="law">法律</option><option value="accounting">會計</option><option value="medtech">醫檢師</option><option value="data-structure">資料結構</option></select><input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="科目"/><select value={documentType} onChange={event=>setDocumentType(event.target.value)} aria-label="文件類型"><option>核心教材</option><option>題庫</option><option>年度解題</option><option>申論題庫</option></select><input value={bookTitle} onChange={event=>setBookTitle(event.target.value)} placeholder="書名（未填則採檔名）"/></div><button type="submit" disabled={submitting||!sourceFile.trim()}>{submitting?"送出中…":"交給 RTX 4090"}</button></form>{message&&<p className="local-node-job-message">{message}</p>}<div className="local-node-job-list">{jobs.length?jobs.slice(0,8).map(job=><div key={job.id}><strong>{job.sourceFile}</strong><span className={`job-${job.status}`}>{labels[job.status]??job.status}</span><small>{job.subject?`${job.subject} · `:""}{job.message??""}{job.status==="completed"?` · ${(job.extractedChars??0).toLocaleString()} 字／${job.chunkCount??0} 切片${job.pageCount?`／${job.pageCount} 頁`:""}${job.documentId?` · 教材 #${job.documentId} 等待索引`:""}`:""}</small></div>):<p>目前沒有本機工作。</p>}</div></section>
}
