"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type InboxFile={name:string;sizeBytes:number;modifiedAt:number};
type Job={id:string;kind:string;sourceFile:string;status:string;message?:string;bookTitle?:string;creator?:string;resourceId?:number;durationSeconds?:number;segmentCount?:number};

export default function LocalVideoJobsPanel(){
 const [files,setFiles]=useState<InboxFile[]>([]),[jobs,setJobs]=useState<Job[]>([]),[sourceFile,setSourceFile]=useState(""),[title,setTitle]=useState(""),[creator,setCreator]=useState("鄭泓"),[subject,setSubject]=useState("中級會計學"),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[connected,setConnected]=useState(false),[version,setVersion]=useState("");
 const load=useCallback(async()=>{const [nodeResponse,jobsResponse]=await Promise.all([fetch("/api/admin/local-node",{cache:"no-store"}),fetch("/api/admin/local-node/jobs",{cache:"no-store"})]);if(nodeResponse.ok){const data=await nodeResponse.json() as {connected?:boolean;node?:{version?:string;videoInboxFiles?:InboxFile[]}|null};setConnected(Boolean(data.connected));setVersion(data.node?.version??"");setFiles(data.node?.videoInboxFiles??[])}if(jobsResponse.ok){const data=await jobsResponse.json() as {jobs?:Job[]};setJobs((data.jobs??[]).filter(job=>job.kind==="transcode_video"))}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[load]);
 const available=useMemo(()=>files.filter(file=>!jobs.some(job=>job.sourceFile.toLowerCase()===file.name.toLowerCase()&&["queued","claimed","completed"].includes(job.status))),[files,jobs]);
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setNotice("");try{const response=await fetch("/api/admin/local-node/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"transcode_video",sourceFile,bookTitle:title||sourceFile.replace(/\.[^.]+$/u,""),creator,subject,examCategory:"accounting",documentType:"影音課程"})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error??"無法建立影音工作");setSourceFile("");setTitle("");setNotice("已送到 RTX 4090：本機轉 HLS 後才會上傳 R2，原始影片不會上雲。");await load()}catch(error){setNotice(error instanceof Error?error.message:"建立失敗")}finally{setSaving(false)}}
 return <section className="panel local-video-jobs-panel"><div className="local-video-head"><div><p>LOCAL VIDEO PIPELINE</p><h2>本機影音上傳</h2><span>把影片放入 C:\iBrain-local-node\video-inbox；RTX 4090 會轉成單畫質 HLS、產生縮圖與字幕，再上傳私人 R2。</span></div><b className={connected?"online":"offline"}>{connected?`節點已連線 · ${version}`:"本機節點未連線"}</b></div><form onSubmit={submit}><label>本機影片<select value={sourceFile} onChange={event=>{setSourceFile(event.target.value);if(!title)setTitle(event.target.value.replace(/\.[^.]+$/u,""))}}><option value="">請選擇 video-inbox 影片</option>{available.map(file=><option value={file.name} key={file.name}>{file.name}（{(file.sizeBytes/1024/1024/1024).toFixed(2)} GB）</option>)}</select></label><label>課程名稱<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="例如：金融資產第一講"/></label><label>老師<input value={creator} onChange={event=>setCreator(event.target.value)}/></label><label>科目<input value={subject} onChange={event=>setSubject(event.target.value)}/></label><button disabled={saving||!sourceFile}>{saving?"建立中…":"本機轉檔並上傳"}</button></form>{!files.length&&<p className="local-video-empty">目前 video-inbox 沒有可處理的 MP4、MOV、M4V 或 MKV。</p>}{notice&&<p className="local-node-job-message">{notice}</p>}<div className="local-video-history">{jobs.slice(0,10).map(job=><article key={job.id}><div><strong>{job.bookTitle||job.sourceFile}</strong><span>{job.creator||"未設定老師"} · {job.sourceFile}</span></div><em className={`job-${job.status}`}>{job.status==="queued"?"排隊中":job.status==="claimed"?"本機處理中":job.status==="completed"?"待後台預覽":"處理失敗"}</em><small>{job.message}{job.status==="completed"?` · ${job.segmentCount??0} 個切片 · ${Math.round((job.durationSeconds??0)/60)} 分鐘` : ""}</small></article>)}</div></section>
}
