"use client";
import { useEffect,useState } from "react";
import { RichQuestionEditor,SourceWorkspace } from "../RichQuestionEditor";
import "../question-bank.css";
import "../question-workbench.css";
import "./page.css";
type Question={id:number;year:string;subject:string;questionNumber:string;stem:string;options:Record<string,string>;correctAnswer:string|null;explanation:string;answerSource:string;status:string};
export default function QuestionWorkbenchPage(){
 const [item,setItem]=useState<Question|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{const id=new URLSearchParams(location.search).get("id");if(!id){setNotice("缺少題目編號");setLoading(false);return}fetch(`/api/medtech/admin/questions?id=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>({ok:r.ok,data:await r.json() as {item?:Question;error?:string}})).then(({ok,data})=>{if(ok&&data.item)setItem(data.item);else setNotice(data.error||"題目讀取失敗")}).finally(()=>setLoading(false))},[]);
 async function save(){if(!item)return;setSaving(true);setNotice("正在儲存題目與版面…");const response=await fetch("/api/medtech/admin/questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(item)});setNotice(response.ok?"已儲存。可繼續編輯或返回題庫。":"儲存失敗，請稍後再試。");setSaving(false)}
 if(loading)return <main className="standalone-workbench-state">正在開啟題目工作台…</main>;
 if(!item)return <main className="standalone-workbench-state"><p>{notice}</p><a href="/medtech/admin">返回醫檢後台</a></main>;
 return <main className="standalone-workbench"><header><div><a href="/medtech/admin">← 返回題庫</a><h1>題目工作台</h1><p>{item.year} 年 · {item.subject} · 第 {item.questionNumber} 題</p></div><div><span className={notice.startsWith("已儲存")?"saved":""}>{notice}</span><button disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存題目"}</button></div></header><section className="standalone-workbench-grid"><SourceWorkspace/><article className="standalone-question-editor"><div className="question-editor-meta"><label>年份<input value={item.year} onChange={e=>setItem({...item,year:e.target.value})}/></label><label>科目<input value={item.subject} onChange={e=>setItem({...item,subject:e.target.value})}/></label><label>題號<input value={item.questionNumber} onChange={e=>setItem({...item,questionNumber:e.target.value})}/></label><label>正確答案<select value={item.correctAnswer??""} onChange={e=>setItem({...item,correctAnswer:e.target.value})}><option value="">未設定</option>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select></label></div><RichQuestionEditor label="題幹" value={item.stem} onChange={stem=>setItem({...item,stem})}/>{["A","B","C","D"].map(key=><RichQuestionEditor compact key={key} label={`選項 ${key}`} value={item.options[key]??""} onChange={value=>setItem({...item,options:{...item.options,[key]:value}})}/>) }<RichQuestionEditor label="解析" value={item.explanation} onChange={explanation=>setItem({...item,explanation})}/><label className="source-label">答案來源<input value={item.answerSource} onChange={e=>setItem({...item,answerSource:e.target.value})}/></label><footer><button disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存題目"}</button></footer></article></section></main>
}
