"use client";
import { useEffect,useState } from "react";
import { RichQuestionEditor,SourceWorkspace } from "../RichQuestionEditor";
import "../question-bank.css";
import "../question-workbench.css";
import "./page.css";
type Category="medtech"|"accounting";
type Question={id:number;examType?:string;year:string;subject:string;questionNumber:string;stem:string;options:Record<string,string>;correctAnswer:string|null;explanation:string;teacherAnswer?:string;answerSource:string;status:string};
export default function QuestionWorkbenchPage({category="medtech"}:{category?:Category}){
 const accounting=category==="accounting", endpoint=accounting?"/api/accounting/admin/questions":"/api/medtech/admin/questions", back=accounting?"/accounting/admin":"/medtech/admin";
 const [item,setItem]=useState<Question|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{const id=new URLSearchParams(location.search).get("id");if(!id){setNotice("缺少題目編號");setLoading(false);return}fetch(`${endpoint}?id=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>({ok:r.ok,data:await r.json() as {item?:Question;error?:string}})).then(({ok,data})=>{if(ok&&data.item)setItem(data.item);else setNotice(data.error||"題目讀取失敗")}).finally(()=>setLoading(false))},[endpoint]);
 async function save(){if(!item)return;setSaving(true);setNotice("正在儲存題目與版面…");const response=await fetch(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(item)});setNotice(response.ok?"已儲存。可繼續編輯或返回題庫。":"儲存失敗，請稍後再試。");setSaving(false)}
 if(loading)return <main className="standalone-workbench-state">正在開啟題目工作台…</main>;
 if(!item)return <main className="standalone-workbench-state"><p>{notice}</p><a href={back}>返回管理後台</a></main>;
 const essay=item.examType==="essay";
 return <main className="standalone-workbench"><header><div><a href={back}>← 返回題庫</a><h1>題目工作台</h1><p>{item.year} 年 · {item.subject} · 第 {item.questionNumber} 題</p></div><div><span className={notice.startsWith("已儲存")?"saved":""}>{notice}</span><button disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存題目"}</button></div></header><section className="standalone-workbench-grid"><SourceWorkspace/><article className="standalone-question-editor"><div className="question-editor-meta"><label>年份<input value={item.year} onChange={e=>setItem({...item,year:e.target.value})}/></label><label>科目<input value={item.subject} onChange={e=>setItem({...item,subject:e.target.value})}/></label><label>題號<input value={item.questionNumber} onChange={e=>setItem({...item,questionNumber:e.target.value})}/></label>{!essay&&<label>正確答案<select value={item.correctAnswer??""} onChange={e=>setItem({...item,correctAnswer:e.target.value})}><option value="">未設定</option>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select></label>}</div><RichQuestionEditor label="題幹" value={item.stem} onChange={stem=>setItem({...item,stem})}/>{!essay&&["A","B","C","D"].map(key=><RichQuestionEditor compact key={key} label={`選項 ${key}`} value={item.options[key]??""} onChange={value=>setItem({...item,options:{...item.options,[key]:value}})}/>)}<RichQuestionEditor label={essay?"老師解答／解析":"解析"} value={essay?(item.teacherAnswer||item.explanation):item.explanation} onChange={value=>setItem(essay?{...item,teacherAnswer:value,explanation:value}:{...item,explanation:value})}/><label className="source-label">答案來源<input value={item.answerSource} onChange={e=>setItem({...item,answerSource:e.target.value})}/></label><footer><button disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存題目"}</button></footer></article></section></main>
}
