"use client";
import { useEffect, useState } from "react";

type Question={id:number;examType:string;year:string;examName:string;subject:string;questionNumber:string;stem:string;optionsJson:string|null;correctAnswer:string|null;explanation:string;teacherAnswer:string;teacherNotes:string;status:string;sourceUrl:string};
export default function AccountingQuestionReview(){
 const [items,setItems]=useState<Question[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[status,setStatus]=useState("all"),[type,setType]=useState("all"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(target=page){const r=await fetch(`/api/exam-questions?examCategory=accounting&status=${status}&examType=${type}&page=${target}`,{cache:"no-store"});const d=await r.json() as {items?:Question[];total?:number;error?:string};setItems(d.items??[]);setTotal(d.total??0);if(!r.ok)setNotice(d.error??"題庫讀取失敗")}
 useEffect(()=>{void load(1)},[status,type]);
 async function setQuestion(id:number,next:string){setBusy(true);const r=await fetch("/api/exam-questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:next})});const d=await r.json() as {error?:string};setNotice(r.ok?(next==="published"?"題目已發布到學生端。":"題目已退回草稿。"):(d.error??"更新失敗"));setBusy(false);await load()}
 async function publishAll(){setBusy(true);const r=await fetch("/api/exam-questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({publishAllDrafts:true,examCategory:"accounting"})});const d=await r.json() as {updated?:number;error?:string};setNotice(r.ok?`已發布 ${d.updated??0} 題；選擇題會進入練真題，申論題會進入解申論。`:(d.error??"發布失敗"));setBusy(false);await load(1)}
 return <main className="accounting-admin-page accounting-question-review"><header className="accounting-top"><a href="/accounting/admin" className="accounting-brand"><span>中</span><div><b>中會拆題審核</b><small>QUESTION REVIEW</small></div></a><nav><a href="/accounting/admin">教材管理</a><a href="/accounting/practice">學生練題</a><a href="/accounting/essay">學生申論</a></nav></header>
 <section className="accounting-admin-hero"><span>真正入庫的題目</span><h1>拆解內容檢查與發布</h1><p>這裡看到完整題幹才代表拆解成功。草稿不會出現在學生端，確認後再發布。</p></section>
 <section className="accounting-admin-panel"><div className="accounting-review-toolbar"><div><b>共 {total} 題</b><select value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="all">全部狀態</option><option value="draft">待審核</option><option value="published">已發布</option></select><select value={type} onChange={e=>{setPage(1);setType(e.target.value)}}><option value="all">全部題型</option><option value="mcq">選擇題</option><option value="essay">申論／計算題</option></select></div><button disabled={busy} onClick={()=>void publishAll()}>發布所有答案完整題目</button></div>{notice&&<p className="accounting-admin-notice">{notice}</p>}
 <div className="accounting-review-list">{items.map(q=>{let options:Record<string,string>={};try{options=JSON.parse(q.optionsJson||"{}") as Record<string,string>}catch{}return <article key={q.id}><header><span>{q.examType==="mcq"?"選擇題":"申論／計算題"}</span><b>{q.status==="published"?"已發布":"待審核"}</b><small>{q.year}｜{q.examName}｜第 {q.questionNumber} 題</small></header><h2>{q.stem}</h2>{q.examType==="mcq"&&<ol>{["A","B","C","D"].map(k=><li key={k}><b>{k}</b>{options[k]||"（未拆出）"}</li>)}</ol>}<div className="accounting-review-answer"><b>{q.examType==="mcq"?`答案：${q.correctAnswer||"未拆出"}`:"教材解答"}</b><p>{q.examType==="mcq"?q.explanation:(q.teacherAnswer||"尚未拆出教材解答")}</p></div><footer><small>{q.teacherNotes||q.subject}</small><button disabled={busy} onClick={()=>void setQuestion(q.id,q.status==="published"?"draft":"published")}>{q.status==="published"?"退回草稿":"確認並發布"}</button></footer></article>})}{!items.length&&<p>目前沒有符合條件的題目。請回教材管理按「重新拆解題目」。</p>}</div>
 <nav className="accounting-review-pages"><button disabled={page<=1} onClick={()=>{const p=page-1;setPage(p);void load(p)}}>上一頁</button><span>第 {page} / {Math.max(1,Math.ceil(total/10))} 頁</span><button disabled={page*10>=total} onClick={()=>{const p=page+1;setPage(p);void load(p)}}>下一頁</button></nav></section></main>;
}
