"use client";
import { useEffect,useRef,useState } from "react";
type Question={id:number;year:string;stem:string;options:Record<string,string>;answer:string;explanation:string;answerSource:string;topic?:string}; type Message={role:"student"|"mentor";text:string;source?:string;usage?:{model:string;inputTokens:number;outputTokens:number;durationMs:number;estimatedCostUsd:number}}; const topics=["臨床病毒學總論","DNA 病毒","RNA 病毒","全真模擬試題"];
function plainText(v:string){return v.replace(/^#{1,6}\s*/gm,"").replace(/\*\*([^*]+)\*\*/g,"$1").replace(/__([^_]+)__/g,"$1").replace(/`([^`]+)`/g,"$1").replace(/^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$/gm,"").replace(/^\s*\|(.+)\|\s*$/gm,(_,r:string)=>r.split("|").map(c=>c.trim()).filter(Boolean).join("　｜　")).replace(/^[*_]{3,}\s*$/gm,"").replace(/\n{3,}/g,"\n\n").trim()}
export default function MedtechAiStudy(){
 const [level,setLevel]=useState("入門"),[topic,setTopic]=useState(""),[question,setQuestion]=useState<Question|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[questionLoading,setQuestionLoading]=useState(true),[error,setError]=useState(""),[selectedAnswer,setSelectedAnswer]=useState(""); const chatRef=useRef<HTMLElement|null>(null),answerRef=useRef<HTMLDivElement|null>(null);
 async function loadQuestion(nextTopic=topic){setQuestionLoading(true);setError("");setSelectedAnswer("");try{const query=new URLSearchParams({limit:"1"});if(nextTopic)query.set("topic",nextTopic);const response=await fetch(`/api/medtech/questions?${query}`);const result=await response.json() as {items?:Question[];error?:string};if(!response.ok||!result.items?.[0])throw new Error(result.error||"目前沒有可用題目");setQuestion(result.items[0]);setMessages([{role:"mentor",text:"請直接點選 A、B、C 或 D 作答；也可以先索取提示。"}])}catch(e){setError(e instanceof Error?e.message:"題目讀取失敗")}finally{setQuestionLoading(false)}}
 useEffect(()=>{void loadQuestion("")},[]); useEffect(()=>{if(!loading&&messages.length<2)return;answerRef.current?.scrollIntoView({behavior:"smooth",block:"start"});requestAnimationFrame(()=>chatRef.current?.scrollTo({top:chatRef.current.scrollHeight,behavior:"smooth"}))},[loading,messages.length]);
 async function send(text=input){const value=text.trim();if(!value||!question||loading)return;const next=[...messages,{role:"student" as const,text:value}];setMessages(next);setInput("");setLoading(true);setError("");requestAnimationFrame(()=>answerRef.current?.scrollIntoView({behavior:"smooth",block:"start"}));try{const response=await fetch("/api/medtech/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionId:question.id,level,messages:next})});const result=await response.json() as {reply?:string;source?:string;usage?:Message["usage"];error?:string};if(!response.ok||!result.reply)throw new Error(result.error||"AI 回答失敗");setMessages(current=>[...current,{role:"mentor",text:plainText(result.reply!),source:result.source,usage:result.usage}])}catch(e){setError(e instanceof Error?e.message:"AI 回答失敗")}finally{setLoading(false)}}
 function chooseAnswer(letter:string){if(loading||selectedAnswer)return;setSelectedAnswer(letter);void send(`我選 ${letter}。請先明確告訴我答對或答錯，再說明判斷關鍵，並逐項解釋其他選項。`)}
 return <main className="medtech-ai-page"><header className="medtech-top" data-no-navigation-feedback><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師備考</b><small>AI STUDY</small></div></a><nav><a href="/medtech">首頁</a><a href="/medtech/practice">練國考題</a><a href="/medtech/ai-study" className="active">AI 學習</a></nav></header><section className="medtech-ai-shell"><aside className="medtech-ai-settings"><span>醫檢 AI 學習</span><h1>從一道題，真正弄懂一個觀念</h1><p>AI 只讀取醫檢題庫資料，不使用司律教材。</p><label>我的程度<div>{["入門","進階","考前衝刺"].map(x=><button className={level===x?"active":""} onClick={()=>setLevel(x)} key={x}>{x}</button>)}</div></label><label>學習主題<select value={topic} onChange={e=>{setTopic(e.target.value);void loadQuestion(e.target.value)}}><option value="">全部主題</option>{topics.map(x=><option key={x}>{x}</option>)}</select></label><button className="medtech-new-question" onClick={()=>void loadQuestion()} disabled={questionLoading}>換一道題</button><small>教材未附解析時，回答會明確標示為 AI 補充，不會冒充教材原文。</small></aside><section className="medtech-ai-workspace">{questionLoading?<div className="medtech-ai-empty">正在從正式題庫抽題…</div>:question?<><article className="medtech-ai-question"><header><span>{question.topic||topic||"臨床病毒學"}</span><small>{question.year} 年專技</small></header><h2>{question.stem}</h2><div>{Object.entries(question.options).map(([key,value])=><button type="button" disabled={loading||Boolean(selectedAnswer)} className={selectedAnswer===key?"selected":""} onClick={()=>chooseAnswer(key)} key={key}><b>{key}</b><span>{value}</span>{selectedAnswer===key&&<em>已選擇</em>}</button>)}</div><small className="medtech-answer-hint">直接點選答案，AI 會判斷正誤並說明。</small></article><div className="medtech-ai-quick"><button onClick={()=>void send("先不要公布答案，請給我一個判斷提示。")}>給我提示</button><button onClick={()=>void send("請逐項比較四個選項，但先讓我看懂判斷關鍵。")}>比較選項</button><button onClick={()=>void send("請公布正確答案並完整解析這一題。")}>完整解析</button></div><div ref={answerRef}/><section className="medtech-ai-chat" ref={chatRef}>{messages.map((m,i)=><article className={m.role} key={i}><b>{m.role==="mentor"?"醫檢 AI 助教":"我"}</b><p>{plainText(m.text)}</p>{m.role==="mentor"&&m.source&&<small>{m.source}{m.usage?` · ${m.usage.model} · ${m.usage.inputTokens+m.usage.outputTokens} tokens · ${(m.usage.durationMs/1000).toFixed(1)} 秒 · 約 NT$ ${(m.usage.estimatedCostUsd*32.5).toFixed(3)}`:""}</small>}</article>)}{loading&&<article className="mentor loading"><b>醫檢 AI 助教</b><p>正在核對答案並整理解析…</p></article>}</section><form onSubmit={e=>{e.preventDefault();void send()}}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="例如：為什麼 B 才是正確答案？其他選項錯在哪裡？" rows={3}/><button disabled={loading||!input.trim()}>送出問題</button></form></>:<div className="medtech-ai-empty">{error||"目前沒有可用題目"}</div>}{error&&question&&<p className="medtech-ai-error">{error}</p>}</section></section></main>
}
