"use client";

import { useEffect, useState } from "react";

type Question = { id:number; year:string; stem:string; options:Record<string,string>; answer:string; explanation:string; answerSource:string; topic?:string };
type Message = { role:"student"|"mentor"; text:string; source?:string; usage?:{model:string;inputTokens:number;outputTokens:number;durationMs:number;estimatedCostUsd:number} };
const topics=["總論與培養","病毒檢驗","DNA 病毒","RNA 病毒","肝炎病毒","抗病毒藥物與疫苗"];

export default function MedtechAiStudy(){
  const [level,setLevel]=useState("入門"); const [topic,setTopic]=useState(""); const [question,setQuestion]=useState<Question|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [questionLoading,setQuestionLoading]=useState(true); const [error,setError]=useState("");
  async function loadQuestion(nextTopic=topic){setQuestionLoading(true);setError("");try{const query=new URLSearchParams({limit:"1"});if(nextTopic)query.set("topic",nextTopic);const response=await fetch(`/api/medtech/questions?${query}`);const result=await response.json() as {items?:Question[];error?:string};if(!response.ok||!result.items?.[0])throw new Error(result.error||"目前沒有可用題目");setQuestion(result.items[0]);setMessages([{role:"mentor",text:"先讀題，不必急著猜。我可以用提示帶你判斷，也可以直接逐項解析。你想從哪一步開始？"}]);}catch(reason){setError(reason instanceof Error?reason.message:"題目讀取失敗");}finally{setQuestionLoading(false)}}
  useEffect(()=>{void loadQuestion("")},[]);
  async function send(text=input){const value=text.trim();if(!value||!question||loading)return;const next=[...messages,{role:"student" as const,text:value}];setMessages(next);setInput("");setLoading(true);setError("");try{const response=await fetch("/api/medtech/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionId:question.id,level,messages:next})});const result=await response.json() as {reply?:string;source?:string;usage?:Message["usage"];error?:string};if(!response.ok||!result.reply)throw new Error(result.error||"AI 回答失敗");setMessages(current=>[...current,{role:"mentor",text:result.reply!,source:result.source,usage:result.usage}]);}catch(reason){setError(reason instanceof Error?reason.message:"AI 回答失敗");}finally{setLoading(false)}}
  return <main className="medtech-ai-page"><header className="medtech-top" data-no-navigation-feedback><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師備考</b><small>AI STUDY</small></div></a><nav><a href="/medtech">首頁</a><a href="/medtech/practice">練國考題</a><a href="/medtech/ai-study" className="active">AI 學習</a></nav></header><section className="medtech-ai-shell"><aside className="medtech-ai-settings"><span>醫檢 AI 學習</span><h1>從一道題，真正弄懂一個觀念</h1><p>AI 只讀取醫檢題庫資料，不使用司律教材。</p><label>我的程度<div>{["入門","進階","考前衝刺"].map(item=><button className={level===item?"active":""} onClick={()=>setLevel(item)} key={item}>{item}</button>)}</div></label><label>學習主題<select value={topic} onChange={event=>{const value=event.target.value;setTopic(value);void loadQuestion(value)}}><option value="">全部主題</option>{topics.map(item=><option key={item}>{item}</option>)}</select></label><button className="medtech-new-question" onClick={()=>void loadQuestion()} disabled={questionLoading}>換一道題</button><small>教材未附解析時，回答會明確標示為 AI 補充，不會冒充教材原文。</small></aside><section className="medtech-ai-workspace">{questionLoading?<div className="medtech-ai-empty">正在從正式題庫抽題…</div>:question?<><article className="medtech-ai-question"><header><span>{question.topic||topic||"臨床病毒學"}</span><small>{question.year} 年專技</small></header><h2>{question.stem}</h2><div>{Object.entries(question.options).map(([key,value])=><p key={key}><b>{key}</b>{value}</p>)}</div></article><div className="medtech-ai-quick"><button onClick={()=>void send("先不要公布答案，請給我一個判斷提示。")}>給我提示</button><button onClick={()=>void send("請逐項比較四個選項，但先讓我看懂判斷關鍵。")}>比較選項</button><button onClick={()=>void send("請公布正確答案並完整解析這一題。")}>完整解析</button></div><section className="medtech-ai-chat">{messages.map((message,index)=><article className={message.role} key={index}><b>{message.role==="mentor"?"醫檢 AI 助教":"我"}</b><p>{message.text}</p>{message.role==="mentor"&&message.source&&<small>{message.source}{message.usage?` · ${message.usage.model} · ${message.usage.inputTokens+message.usage.outputTokens} tokens · ${(message.usage.durationMs/1000).toFixed(1)} 秒 · 約 NT$ ${(message.usage.estimatedCostUsd*32.5).toFixed(3)}`:""}</small>}</article>)}{loading&&<article className="mentor loading"><b>醫檢 AI 助教</b><p>正在依題庫資料整理說明…</p></article>}</section><form onSubmit={event=>{event.preventDefault();void send()}}><textarea value={input} onChange={event=>setInput(event.target.value)} placeholder="例如：為什麼 B 才是正確答案？其他選項錯在哪裡？" rows={3}/><button disabled={loading||!input.trim()}>送出問題</button></form></>:<div className="medtech-ai-empty">{error||"目前沒有可用題目"}</div>}{error&&question&&<p className="medtech-ai-error">{error}</p>}</section></section></main>
}
