"use client";
import { useEffect, useMemo, useState } from "react";
type Item={question:{id:number;topic:string;aiReply:string;studentQuestion:string;verificationResult:string;status:string;teacherReply:string};email:string|null;displayName:string|null};
type Filter="all"|"pending_teacher"|"answered"|"verified";
const labels:Record<Filter,string>={all:"全部",pending_teacher:"待老師回覆",answered:"已回覆",verified:"AI 已查證"};
export default function PengliQuestionAdmin(){
 const[rows,setRows]=useState<Item[]>([]),[drafts,setDrafts]=useState<Record<number,string>>({}),[filter,setFilter]=useState<Filter>("pending_teacher"),[busy,setBusy]=useState<number|null>(null),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/pengli-questions",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"讀取疑問失敗");setRows(data.rows||[])}catch(error){setNotice(error instanceof Error?error.message:"讀取疑問失敗")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const counts=useMemo(()=>({all:rows.length,pending_teacher:rows.filter(row=>row.question.status==="pending_teacher").length,answered:rows.filter(row=>row.question.status==="answered").length,verified:rows.filter(row=>row.question.status==="verified").length}),[rows]);
 const visible=filter==="all"?rows:rows.filter(row=>row.question.status===filter);
 async function reply(id:number){const value=(drafts[id]||"").trim();if(!value)return;setBusy(id);setNotice("");try{const response=await fetch("/api/admin/pengli-questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,teacherReply:value})});const data=await response.json();if(!response.ok)throw new Error(data.error||"回覆失敗");setDrafts(current=>({...current,[id]:""}));setNotice("老師回覆已送出，學生的『我的筆記』會顯示新信件。");await load()}catch(error){setNotice(error instanceof Error?error.message:"回覆失敗")}finally{setBusy(null)}}
 return <section className="pengli-inbox"><nav className="pengli-inbox-filters" aria-label="疑問狀態">{(Object.keys(labels)as Filter[]).map(id=><button key={id} className={filter===id?"active":""} onClick={()=>setFilter(id)}>{labels[id]}<b>{counts[id]}</b></button>)}</nav>{notice&&<p className="pengli-inbox-notice" role="status">{notice}</p>}{loading?<div className="central-admin-card pengli-inbox-empty">正在整理學生疑問…</div>:visible.length===0?<div className="central-admin-card pengli-inbox-empty">目前沒有「{labels[filter]}」的疑問。</div>:<div className="pengli-inbox-list">{visible.map(({question:q,email,displayName})=><article className="central-admin-card pengli-inbox-card" key={q.id}><header><div><span className={`status ${q.status}`}>{q.status==="pending_teacher"?"待老師回覆":q.status==="answered"?"已回覆":"AI 已查證"}</span><small>#{q.id}・{q.topic}</small></div><b>{displayName||email||"學生"}</b></header><section className="student-question"><small>學生真正想問</small><p>{q.studentQuestion}</p></section><details><summary>查看原 AI 回覆與查證內容</summary><div className="pengli-inbox-evidence"><section><h3>原 AI 回覆</h3><p>{q.aiReply}</p></section><section><h3>AI 查證</h3><p>{q.verificationResult}</p></section></div></details>{q.status==="pending_teacher"&&<div className="pengli-inbox-reply"><label>彭狸老師回覆<textarea value={drafts[q.id]||""} onChange={event=>setDrafts(current=>({...current,[q.id]:event.target.value}))} placeholder="直接回答學生的疑問；可補充法條、裁判或考場提醒。"/></label><button className="primary-button" disabled={busy===q.id||!(drafts[q.id]||"").trim()} onClick={()=>void reply(q.id)}>{busy===q.id?"送出中…":"送出老師回覆"}</button></div>}{q.teacherReply&&<section className="teacher-reply"><small>老師已回覆</small><p>{q.teacherReply}</p></section>}</article>)}</div>}</section>
}
