"use client";
import { useEffect, useMemo, useState } from "react";

type Question={id:number;topic:string;aiReply:string;studentQuestion:string;verificationResult:string;status:string;teacherReply:string;assignedTeacherId:number|null};
type Item={question:Question;email:string|null;displayName:string|null};
type TeacherCandidate={id:number;email:string;displayName:string;role:string};
type Filter="all"|"pending_review"|"pending_teacher"|"answered";
const labels:Record<Filter,string>={all:"全部",pending_review:"待管理員確認",pending_teacher:"已轉交老師",answered:"已回覆"};

export default function PengliQuestionAdmin(){
 const[rows,setRows]=useState<Item[]>([]),[teacherCandidates,setTeacherCandidates]=useState<TeacherCandidate[]>([]),[selected,setSelected]=useState<Record<number,number>>({}),[filter,setFilter]=useState<Filter>("pending_review"),[busy,setBusy]=useState<number|null>(null),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/pengli-questions",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"讀取疑問失敗");const candidates:TeacherCandidate[]=data.teacherCandidates||[];const preferred=candidates.find(item=>item.role==="teacher")||candidates[0];setRows(data.rows||[]);setTeacherCandidates(candidates);setSelected(current=>{const next={...current};for(const row of data.rows||[])if(!next[row.question.id]&&preferred)next[row.question.id]=preferred.id;return next})}catch(error){setNotice(error instanceof Error?error.message:"讀取疑問失敗")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const effectiveStatus=(q:Question)=>q.status==="pending_teacher"&&!q.assignedTeacherId?"pending_review":q.status;
 const counts=useMemo(()=>({all:rows.length,pending_review:rows.filter(row=>effectiveStatus(row.question)==="pending_review").length,pending_teacher:rows.filter(row=>effectiveStatus(row.question)==="pending_teacher").length,answered:rows.filter(row=>row.question.status==="answered").length}),[rows]);
 const visible=filter==="all"?rows:rows.filter(row=>effectiveStatus(row.question)===filter);
 const teacherName=(id:number|null)=>teacherCandidates.find(item=>item.id===id)?.displayName||teacherCandidates.find(item=>item.id===id)?.email||"尚未指定";
 async function assign(id:number){const teacherId=selected[id];if(!teacherId)return;setBusy(id);setNotice("");try{const response=await fetch("/api/admin/pengli-questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:"assign",teacherId})});const data=await response.json();if(!response.ok)throw new Error(data.error||"轉交失敗");setNotice("已確認並轉交老師；老師登入後會在『我的待回答』看到這筆疑問。");await load()}catch(error){setNotice(error instanceof Error?error.message:"轉交失敗")}finally{setBusy(null)}}
 return <section className="pengli-inbox"><nav className="pengli-inbox-filters" aria-label="疑問狀態">{(Object.keys(labels)as Filter[]).map(id=><button key={id} className={filter===id?"active":""} onClick={()=>setFilter(id)}>{labels[id]}<b>{counts[id]}</b></button>)}</nav>{notice&&<p className="pengli-inbox-notice" role="status">{notice}</p>}{!teacherCandidates.length&&!loading&&<p className="pengli-inbox-warning">目前沒有可選擇的啟用帳號，請先到「會員總管理」確認老師帳號已啟用。</p>}{loading?<div className="central-admin-card pengli-inbox-empty">正在整理學生疑問…</div>:visible.length===0?<div className="central-admin-card pengli-inbox-empty">目前沒有「{labels[filter]}」的疑問。</div>:<div className="pengli-inbox-list">{visible.map(({question:q,email,displayName})=>{const selectedAccount=teacherCandidates.find(item=>item.id===selected[q.id]);const existingTeachers=teacherCandidates.filter(item=>item.role==="teacher");const otherAccounts=teacherCandidates.filter(item=>item.role!=="teacher");return <article className="central-admin-card pengli-inbox-card" key={q.id}><header><div><span className={`status ${effectiveStatus(q)}`}>{labels[effectiveStatus(q) as Exclude<Filter,"all">]||q.status}</span><small>#{q.id}・{q.topic}</small></div><b>{displayName||email||"學生"}</b></header><section className="student-question"><small>學生真正想問</small><p>{q.studentQuestion}</p></section><details><summary>查看原 AI 回覆與查證內容</summary><div className="pengli-inbox-evidence"><section><h3>原 AI 回覆</h3><p>{q.aiReply}</p></section><section><h3>AI 查證</h3><p>{q.verificationResult}</p></section></div></details>{effectiveStatus(q)==="pending_review"&&<div className="pengli-assignment"><label>轉交老師<select value={selected[q.id]||""} onChange={event=>setSelected(current=>({...current,[q.id]:Number(event.target.value)}))}><option value="">請選擇帳號</option>{existingTeachers.length>0&&<optgroup label="老師帳號">{existingTeachers.map(teacher=><option key={teacher.id} value={teacher.id}>{teacher.displayName||teacher.email}</option>)}</optgroup>}{otherAccounts.length>0&&<optgroup label="其他啟用帳號（轉交時設為老師）">{otherAccounts.map(account=><option key={account.id} value={account.id}>{account.displayName||account.email}（目前非老師）</option>)}</optgroup>}</select>{!existingTeachers.length&&<small>目前沒有已設定的老師；可選擇現有帳號，確認轉交時會將該帳號設為老師。</small>}</label><button className="primary-button" disabled={busy===q.id||!selected[q.id]} onClick={()=>void assign(q.id)}>{busy===q.id?"轉交中…":selectedAccount?.role==="teacher"?"確認並轉交老師":"設為老師並轉交"}</button></div>}{effectiveStatus(q)==="pending_teacher"&&<p className="pengli-assigned-note">已轉交：{teacherName(q.assignedTeacherId)}，等待老師回答。</p>}{q.teacherReply&&<section className="teacher-reply"><small>{teacherName(q.assignedTeacherId)}已回覆</small><p>{q.teacherReply}</p></section>}</article>})}</div>}</section>
}
