import { and, eq, inArray } from "drizzle-orm";
import { getDb } from "../../../../db";
import { documents, examQuestions } from "../../../../db/schema";
import { requireAccountingAdmin } from "../../../../lib/member-auth";
import { contentTypeForDocument, documentExtension, isSupportedDocument, MAX_DOCUMENT_BYTES } from "../../../../lib/document-processing";
import { DELETE as deleteDocuments, GET as getDocuments, PATCH as patchDocument, POST as postDocument } from "../../documents/route";

export async function GET(request:Request){const auth=await requireAccountingAdmin(request);if("error" in auth)return auth.error;const url=new URL(request.url);url.searchParams.set("category","accounting");return getDocuments(new Request(url,{headers:request.headers}))}
export async function POST(request:Request){const auth=await requireAccountingAdmin(request);if("error" in auth)return auth.error;const form=await request.formData();form.set("examCategory","accounting");const headers=new Headers(request.headers);headers.delete("content-type");headers.delete("content-length");return postDocument(new Request(request.url,{method:"POST",headers,body:form}))}
export async function PUT(request:Request){const auth=await requireAccountingAdmin(request);if("error" in auth)return auth.error;try{const form=await request.formData(),id=Number(form.get("id")),file=form.get("file");if(!Number.isInteger(id)||id<1||!(file instanceof File)||!isSupportedDocument(file.name,file.type))return Response.json({error:"請選擇正確的 PDF、HTML 或 Word 原稿"},{status:400});if(file.size>MAX_DOCUMENT_BYTES)return Response.json({error:"文件不可超過 55MB"},{status:413});const db=await getDb(),[current]=await db.select().from(documents).where(and(eq(documents.id,id),eq(documents.examCategory,"accounting"))).limit(1);if(!current)return Response.json({error:"找不到中會文件"},{status:404});const {env}=await import("cloudflare:workers");if(!env.BUCKET)return Response.json({error:"文件儲存空間尚未就緒"},{status:503});const safeName=file.name.replace(/[^\p{L}\p{N}._-]+/gu,"-").slice(-120),key=`documents/${Date.now()}-${crypto.randomUUID()}-${safeName}`;await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:contentTypeForDocument(file.name,file.type)},customMetadata:{subject:current.subject,documentType:current.documentType,originalName:file.name}});let result:Record<string,unknown>={};try{result=JSON.parse(current.processingResultJson) as Record<string,unknown>}catch{}const variants=Array.isArray(result.sourceVariants)?result.sourceVariants.filter((x):x is Record<string,unknown>=>Boolean(x&&typeof x==="object"&&typeof (x as Record<string,unknown>).storageKey==="string")):[];const currentKind=documentExtension(current.fileName)??"other",nextKind=documentExtension(file.name)??"other";const retained=variants.filter((item)=>item.kind!=="html"&&item.kind!==nextKind);retained.push({kind:currentKind,storageKey:current.storageKey,fileName:current.fileName,contentType:current.contentType,sizeBytes:current.sizeBytes,createdAt:new Date().toISOString()});await db.update(documents).set({storageKey:key,fileName:file.name,contentType:contentTypeForDocument(file.name,file.type),sizeBytes:file.size,processingMessage:`已新增 ${nextKind.toUpperCase()} 原稿版本；既有題目與解析均保留`,processingResultJson:JSON.stringify({...result,sourceVariants:retained}),indexError:null}).where(eq(documents.id,id));return Response.json({replaced:true,variant:nextKind,id,name:file.name})}catch(error){return Response.json({error:error instanceof Error?error.message.slice(0,240):"更換文件失敗"},{status:500})}}
export async function PATCH(request:Request){const auth=await requireAccountingAdmin(request);if("error" in auth)return auth.error;const body=await request.json() as {id?:number;homepageSearchEnabled?:boolean;subject?:string},db=await getDb(),[row]=await db.select().from(documents).where(and(eq(documents.id,Number(body.id)),eq(documents.examCategory,"accounting"))).limit(1);if(!row)return Response.json({error:"找不到中會教材"},{status:404});if(typeof body.subject==="string"){const subject=body.subject.replace(/\s+/gu," ").trim().slice(0,80);if(!subject)return Response.json({error:"請輸入科目名稱"},{status:400});await db.update(documents).set({subject}).where(eq(documents.id,row.id));await db.update(examQuestions).set({subject}).where(and(eq(examQuestions.examCategory,"accounting"),eq(examQuestions.sourceUrl,`document:${row.id}`)));return Response.json({id:row.id,subject})}return patchDocument(new Request(request.url,{method:"PATCH",headers:request.headers,body:JSON.stringify(body)}))}
export async function DELETE(request:Request){const auth=await requireAccountingAdmin(request);if("error" in auth)return auth.error;const body=await request.json() as {ids?:unknown[]},ids=(body.ids??[]).map(Number).filter(Number.isInteger),db=await getDb(),allowed=ids.length?await db.select({id:documents.id}).from(documents).where(and(eq(documents.examCategory,"accounting"),inArray(documents.id,ids))):[];return deleteDocuments(new Request(request.url,{method:"DELETE",headers:request.headers,body:JSON.stringify({ids:allowed.map(row=>row.id)})}))}
