"use client";
import {useEffect,useMemo,useState} from "react";
type CatalogFile={id:number;examCategory:string;bookTitle:string;fileName:string;subject:string;documentType:string;questionCount:number};
function normalized(value:string){return value.replace(/\.pdf$/iu,"").replace(/[（）()\s_－—-]/gu,"").replace(/全書$/u,"").toLocaleLowerCase("zh-TW")}
export default function CentralBookCatalog(){const[files,setFiles]=useState<CatalogFile[]>([]),[query,setQuery]=useState("");
 useEffect(()=>{void fetch("/api/admin/question-bank-summary",{cache:"no-store"}).then(r=>r.json()).then(d=>setFiles(d.files??[]))},[]);
 const books=useMemo(()=>{const map=new Map<string,{title:string;categories:Set<string>;subjects:Set<string>;files:number;questions:number}>();for(const file of files){const title=(file.bookTitle||file.fileName.replace(/\.pdf$/iu,"")).trim(),key=normalized(title),row=map.get(key)??{title,categories:new Set<string>(),subjects:new Set<string>(),files:0,questions:0};row.categories.add(file.examCategory);row.subjects.add(file.subject);row.files++;row.questions+=Number(file.questionCount||0);map.set(key,row)}const needle=normalized(query);return[...map.values()].filter(row=>!needle||normalized(row.title).includes(needle)).sort((a,b)=>a.title.localeCompare(b.title,"zh-TW"))},[files,query]);
 const configured=["醫檢師國考題詳解Ⅲ臨床病毒學下","會研所中級會計學題庫制霸"].map(normalized);
 return <section className="central-book-catalog"><header><div><h2>中央教材書籍目錄</h2><p>教材庫有書就會列出；未設定價格的書不會再消失。</p></div><label>搜尋書籍<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="輸入完整或部分書名"/></label></header><div className="central-book-grid">{books.map(book=>{const key=normalized(book.title),ready=configured.some(title=>title===key||title.includes(key)||key.includes(title));return <article key={key}><div><span>{[...book.categories].map(value=>value==="accounting"?"會計":value==="medtech"?"醫檢":value==="law"?"司律":"資構").join("／")}</span><h3>{book.title}</h3><p>{[...book.subjects].join("、")} · {book.files} 份文件 · {book.questions.toLocaleString()} 題</p></div><b className={ready?"ready":"pending"}>{ready?"已有商品設定":"待建立商品設定"}</b></article>})}{!books.length&&<p>目前找不到符合條件的書籍。</p>}</div></section>}
