"use client";
import {useEffect,useState} from "react";
import AccountingProductPanel from "../../accounting/admin/AccountingProductPanel";
import CentralBookCatalog from "./CentralBookCatalog";
import CentralAdminTabs from "../CentralAdminTabs";
import {RichQuestionEditor} from "../../medtech/admin/RichQuestionEditor";
import "../../accounting/admin/product.css";
import "../../medtech/admin/question-workbench.css";
type Product={productKey:string;title:string;descriptionHtml:string;listPrice:number;salePrice:number|null;saleLabel:string;saleStartsAt:string|null;saleEndsAt:string|null;accessDays:number;trialQuestions:number;status:string;effectivePrice:number;saleActive:boolean};
function MedtechProductPanel(){const[product,setProduct]=useState<Product|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[canManage,setCanManage]=useState(false);
 async function load(){const r=await fetch("/api/medtech/admin/product",{cache:"no-store"}),d=await r.json();if(r.ok){setProduct(d.product);setCanManage(d.canManageCommercial===true)}else setNotice(d.error||"讀取醫檢商品失敗")}
 useEffect(()=>{void load()},[]);
 async function save(){if(!product)return;setBusy(true);const r=await fetch("/api/medtech/admin/product",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(product)}),d=await r.json();setBusy(false);if(r.ok){setProduct(d.product);setNotice("醫檢書籍設定已儲存，各學生端會讀取這份中央設定。")}else setNotice(d.error||"儲存失敗")}
 if(!product)return <section className="central-product-card"><p>{notice||"正在讀取醫檢書籍商品…"}</p></section>;
 const set=<K extends keyof Product>(key:K,value:Product[K])=>setProduct({...product,[key]:value});
 return <section className="central-product-card"><header><div><span>醫檢師</span><h2>{product.title}</h2><p>原有醫檢商品資料直接接入中央，不重建、不改變學生權益。</p></div><b>{product.status==="active"?"已上架":"未上架"}</b></header><div className="central-product-fields"><label>上架狀態<select value={product.status} onChange={e=>set("status",e.target.value)}><option value="active">正式上架</option><option value="disabled">暫停販售</option></select></label><label>定價 NT$<input type="number" min="1" value={product.listPrice} onChange={e=>set("listPrice",Number(e.target.value))}/></label><label>活動價 NT$<input type="number" min="1" value={product.salePrice??""} placeholder="未設定" onChange={e=>set("salePrice",e.target.value?Number(e.target.value):null)}/></label><label>活動名稱<input value={product.saleLabel} placeholder="例如：開學優惠" onChange={e=>set("saleLabel",e.target.value)}/></label><label>活動開始<input type="datetime-local" value={product.saleStartsAt?.slice(0,16)??""} onChange={e=>set("saleStartsAt",e.target.value||null)}/></label><label>活動結束<input type="datetime-local" value={product.saleEndsAt?.slice(0,16)??""} onChange={e=>set("saleEndsAt",e.target.value||null)}/></label><label>開通天數<input type="number" min="1" max="3650" value={product.accessDays} onChange={e=>set("accessDays",Number(e.target.value))}/></label><label>免費體驗題數<input type="number" min="0" value={product.trialQuestions} onChange={e=>set("trialQuestions",Number(e.target.value))}/></label></div><details className="product-rich-editor-collapsible"><summary><span><b>前台商品介紹</b><small>{product.descriptionHtml?"已設定內容":"尚未設定內容"}</small></span><strong>展開富文字編輯</strong></summary><div><RichQuestionEditor category="medtech" label="前台商品介紹（完整富文）" value={product.descriptionHtml||""} onChange={value=>set("descriptionHtml",value)}/></div></details><div className="central-product-summary"><b>目前售價：NT$ {product.effectivePrice}</b><span>{product.accessDays} 天 · 免費體驗 {product.trialQuestions} 題</span></div><button type="button" disabled={busy||!canManage} onClick={()=>void save()}>{busy?"儲存中…":"儲存中央商品設定"}</button>{notice&&<p className="central-product-notice">{notice}</p>}</section>}
export default function CentralProductManagement(){return <main className="central-products"><header className="central-products-top"><a href="/admin">← 返回總管理處</a><span>CONTENT PUBLISHING & COMMERCE</span><h1>教材與題庫發布管理</h1><p>從中央教材直接發布該書題目，再設定學生端商品、權限、價格與使用天數。</p></header><CentralAdminTabs active="products"/><section className="central-products-rule"><b>以書為單位</b><span>題目發布與商品上架分開控制；發布一本書不會影響其他教材草稿。</span></section><CentralBookCatalog/><MedtechProductPanel/><section className="central-accounting-product"><AccountingProductPanel/></section></main>}
