"use client";
import {useEffect,useState} from "react";
import AccountingProductPanel from "../../accounting/admin/AccountingProductPanel";
import CentralBookCatalog from "./CentralBookCatalog";
import "../../accounting/admin/product.css";
import "../../medtech/admin/question-workbench.css";
type Product={productKey:string;title:string;listPrice:number;salePrice:number|null;saleLabel:string;saleStartsAt:string|null;saleEndsAt:string|null;accessDays:number;trialQuestions:number;status:string;effectivePrice:number;saleActive:boolean};
function MedtechProductPanel(){const[product,setProduct]=useState<Product|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[canManage,setCanManage]=useState(false);
 async function load(){const r=await fetch("/api/medtech/admin/product",{cache:"no-store"}),d=await r.json();if(r.ok){setProduct(d.product);setCanManage(d.canManageCommercial===true)}else setNotice(d.error||"讀取醫檢商品失敗")}
 useEffect(()=>{void load()},[]);
 async function save(){if(!product)return;setBusy(true);const r=await fetch("/api/medtech/admin/product",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(product)}),d=await r.json();setBusy(false);if(r.ok){setProduct(d.product);setNotice("醫檢書籍設定已儲存，各學生端會讀取這份中央設定。")}else setNotice(d.error||"儲存失敗")}
 if(!product)return <section className="central-product-card"><p>{notice||"正在讀取醫檢書籍商品…"}</p></section>;
 const set=<K extends keyof Product>(key:K,value:Product[K])=>setProduct({...product,[key]:value});
 return <section className="central-product-card"><header><div><span>醫檢師</span><h2>{product.title}</h2><p>原有醫檢商品資料直接接入中央，不重建、不改變學生權益。</p></div><b>{product.status==="active"?"已上架":"未上架"}</b></header><div className="central-product-fields"><label>上架狀態<select value={product.status} onChange={e=>set("status",e.target.value)}><option value="active">正式上架</option><option value="disabled">暫停販售</option></select></label><label>定價 NT$<input type="number" min="1" value={product.listPrice} onChange={e=>set("listPrice",Number(e.target.value))}/></label><label>活動價 NT$<input type="number" min="1" value={product.salePrice??""} placeholder="未設定" onChange={e=>set("salePrice",e.target.value?Number(e.target.value):null)}/></label><label>活動名稱<input value={product.saleLabel} placeholder="例如：開學優惠" onChange={e=>set("saleLabel",e.target.value)}/></label><label>活動開始<input type="datetime-local" value={product.saleStartsAt?.slice(0,16)??""} onChange={e=>set("saleStartsAt",e.target.value||null)}/></label><label>活動結束<input type="datetime-local" value={product.saleEndsAt?.slice(0,16)??""} onChange={e=>set("saleEndsAt",e.target.value||null)}/></label><label>開通天數<input type="number" min="1" max="3650" value={product.accessDays} onChange={e=>set("accessDays",Number(e.target.value))}/></label><label>免費體驗題數<input type="number" min="0" value={product.trialQuestions} onChange={e=>set("trialQuestions",Number(e.target.value))}/></label></div><div className="central-product-summary"><b>目前售價：NT$ {product.effectivePrice}</b><span>{product.accessDays} 天 · 免費體驗 {product.trialQuestions} 題</span></div><button type="button" disabled={busy||!canManage} onClick={()=>void save()}>{busy?"儲存中…":"儲存中央商品設定"}</button>{notice&&<p className="central-product-notice">{notice}</p>}</section>}
export default function CentralProductManagement(){return <main className="central-products"><header className="central-products-top"><a href="/admin">← 返回總管理處</a><span>CENTRAL CATALOG & COMMERCE</span><h1>中央書籍與商品管理</h1><p>書籍內容來自中央教材母庫；定價、活動、使用天數、體驗題數與上下架只在此維護。</p></header><nav className="central-products-nav"><a href="/admin/library">教材向量庫</a><a href="/admin/question-bank">總題庫管理</a><a className="active" href="/admin/products">書籍與商品</a><a href="/admin/members">會員總管理</a><a href="/admin/ai-access">AI方案</a></nav><section className="central-products-rule"><b>單一資料來源</b><span>各類科學生端直接讀取中央設定；類科後台不再另存價格與天數。</span></section><CentralBookCatalog/><MedtechProductPanel/><section className="central-accounting-product"><AccountingProductPanel/></section></main>}
