"use client";
import {useEffect,useMemo,useState} from "react";
import "./central-cover.css";
type CatalogFile={id:number;examCategory:string;bookTitle:string;fileName:string;subject:string;documentType:string;questionCount:number};
type Product={productKey:string;title:string;category:string;centralCoverKey:string|null;listPrice:number;salePrice:number|null;saleLabel:string;saleStartsAt:string|null;saleEndsAt:string|null;accessDays:number;trialQuestions:number;status:string};
function normalized(value:string){return value.replace(/\.pdf$/iu,"").replace(/[（）()\s_－—-]/gu,"").replace(/全書$/u,"").toLocaleLowerCase("zh-TW")}
export default function CentralBookCatalog(){
 const[files,setFiles]=useState<CatalogFile[]>([]),[products,setProducts]=useState<Product[]>([]),[query,setQuery]=useState(""),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 async function load(){const[a,b]=await Promise.all([fetch("/api/admin/question-bank-summary",{cache:"no-store"}),fetch("/api/admin/products",{cache:"no-store"})]),[docs,catalog]=await Promise.all([a.json(),b.json()]);setFiles(docs.files??[]);setProducts(catalog.products??[])}
 useEffect(()=>{void load()},[]);
 const books=useMemo(()=>{const map=new Map<string,{title:string;category:string;categories:Set<string>;subjects:Set<string>;files:number;questions:number}>();for(const file of files){const title=(file.bookTitle||file.fileName.replace(/\.pdf$/iu,"")).trim(),key=normalized(title),row=map.get(key)??{title,category:file.examCategory,categories:new Set<string>(),subjects:new Set<string>(),files:0,questions:0};row.categories.add(file.examCategory);row.subjects.add(file.subject);row.files++;row.questions+=Number(file.questionCount||0);map.set(key,row)}const needle=normalized(query);return[...map.values()].filter(row=>!needle||normalized(row.title).includes(needle)).sort((a,b)=>a.title.localeCompare(b.title,"zh-TW"))},[files,query]);
 function match(title:string){const key=normalized(title);return products.find(product=>{const p=normalized(product.title);return p===key||p.includes(key)||key.includes(p)})}
 function change(productKey:string,patch:Partial<Product>){setProducts(rows=>rows.map(row=>row.productKey===productKey?{...row,...patch}:row))}
 async function create(title:string,category:string){if(!["accounting","medtech"].includes(category)){setNotice("司律與資構商品規則尚未啟用；教材仍保留於中央母庫。");return}setBusy(normalized(title));const r=await fetch("/api/admin/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,category})}),d=await r.json();if(r.ok){setNotice("已建立「"+title+"」商品設定，請在下方設定價格與天數。");await load()}else setNotice(d.error||"建立商品失敗");setBusy("")}
 async function save(product:Product){setBusy(product.productKey);const r=await fetch("/api/admin/products",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(product)}),d=await r.json();setBusy("");if(r.ok){setNotice("「"+product.title+"」已儲存。");await load()}else setNotice(d.error||"儲存失敗")}
 async function upload(product:Product,file:File){setBusy(product.productKey);const form=new FormData();form.set("category",product.category);form.set("productKey",product.productKey);form.set("file",file);const r=await fetch("/api/admin/products/cover",{method:"POST",body:form}),d=await r.json();setBusy("");if(r.ok){setNotice("「"+product.title+"」書封已上傳。");await load()}else setNotice(d.error||"書封上傳失敗")}
 async function removeCover(product:Product){if(!window.confirm("確定移除「"+product.title+"」的書封？"))return;setBusy(product.productKey);const q=new URLSearchParams({category:product.category,productKey:product.productKey});const r=await fetch("/api/admin/products/cover?"+q,{method:"DELETE"}),d=await r.json();setBusy("");if(r.ok){setNotice("書封已移除。");await load()}else setNotice(d.error||"移除書封失敗")}
 return <><section className="central-book-catalog"><header><div><h2>中央教材書籍目錄</h2><p>教材庫有書就會列出；未設定價格的書可直接建立商品。</p></div><label>搜尋書籍<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="輸入完整或部分書名"/></label></header>{notice&&<p className="central-catalog-notice">{notice}</p>}<div className="central-book-grid">{books.map(book=>{const product=match(book.title),key=normalized(book.title);return <article key={key}><div><span>{[...book.categories].map(value=>value==="accounting"?"會計":value==="medtech"?"醫檢":value==="law"?"司律":"資構").join("／")}</span><h3>{book.title}</h3><p>{[...book.subjects].join("、")} · {book.files} 份文件 · {book.questions.toLocaleString()} 題</p></div>{product?<b className="ready">已有商品設定</b>:<button disabled={busy===key} onClick={()=>void create(book.title,book.category)}>{busy===key?"建立中…":"建立商品設定"}</button>}</article>})}{!books.length&&<p>目前找不到符合條件的書籍。</p>}</div></section><section className="central-created-products"><header><h2>全部商品設定</h2><span>{products.length} 本</span></header>{products.map(product=>{const cover=`/api/admin/products/cover?${new URLSearchParams({category:product.category,productKey:product.productKey})}`;return <article key={product.category+product.productKey}><div className="central-product-cover">{product.centralCoverKey?<img src={cover} alt={`${product.title}書封`}/>:<span>尚無<br/>書封</span>}<label>{product.centralCoverKey?"更換":"上傳"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy===product.productKey} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(product,file);e.currentTarget.value=""}}/></label>{product.centralCoverKey&&<button type="button" onClick={()=>void removeCover(product)}>移除</button>}</div><div className="central-created-title"><span>{product.category==="accounting"?"會計":"醫檢"}</span><h3>{product.title}</h3></div><div className="central-created-fields"><label>狀態<select value={product.status} onChange={e=>change(product.productKey,{status:e.target.value})}><option value="draft">草稿</option><option value="active">上架</option><option value="disabled">停用</option></select></label><label>定價<input type="number" value={product.listPrice} onChange={e=>change(product.productKey,{listPrice:Number(e.target.value)})}/></label><label>活動價<input type="number" value={product.salePrice??""} placeholder="未設定" onChange={e=>change(product.productKey,{salePrice:e.target.value?Number(e.target.value):null})}/></label><label>天數<input type="number" value={product.accessDays} onChange={e=>change(product.productKey,{accessDays:Number(e.target.value)})}/></label><label>免費題數<input type="number" value={product.trialQuestions} onChange={e=>change(product.productKey,{trialQuestions:Number(e.target.value)})}/></label></div><button disabled={busy===product.productKey} onClick={()=>void save(product)}>{busy===product.productKey?"儲存中…":"儲存"}</button></article>})}</section></>;
}
