"use client";
import { useEffect, useMemo, useState } from "react";

type Item={question:{id:number;topic:string;aiReply:string;studentQuestion:string;verificationResult:string;status:string;teacherReply:string};studentEmail:string|null;studentName:string|null};

export default function TeacherInbox(){
 const[rows,setRows]=useState<Item[]>([]),[drafts,setDrafts]=useState<Record<number,string>>({}),[filter,setFilter]=useState<"pending_teacher"|"answered">("pending_teacher"),[busy,setBusy]=useState<number|null>(null),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const response=await fetch("/api/teachers/pengli/teacher-inbox",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"讀取待回答疑問失敗");setRows(data.rows||[])}catch(error){setNotice(error instanceof Error?error.message:"讀取待回答疑問失敗")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const counts=useMemo(()=>({pending_teacher:rows.filter(row=>row.question.status==="pending_teacher").length,answered:rows.filter(row=>row.question.status==="answered").length}),[rows]);
 const visible=rows.filter(row=>row.question.status===filter);
 async function reply(id:number){const teacherReply=(drafts[id]||"").trim();if(!teacherReply)return;setBusy(id);setNotice("");try{const response=await fetch("/api/teachers/pengli/teacher-inbox",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,teacherReply})});const data=await response.json();if(!response.ok)throw new Error(data.error||"送出回覆失敗");setDrafts(current=>({...current,[id]:""}));setNotice("回覆已送出；學生的『我的筆記』會顯示未讀信件。");await load()}catch(error){setNotice(error instanceof Error?error.message:"送出回覆失敗")}finally{setBusy(null)}}
 return <section className="pengli-inbox"><nav className="pengli-inbox-filters"><button className={filter==="pending_teacher"?"active":""} onClick={()=>setFilter("pending_teacher")}>待回答<b>{counts.pending_teacher}</b></button><button className={filter==="answered"?"active":""} onClick={()=>setFilter("answered")}>已回答<b>{counts.answered}</b></button></nav>{notice&&<p className="pengli-inbox-notice" role="status">{notice}</p>}{loading?<div className="central-admin-card pengli-inbox-empty">正在讀取分派問題…</div>:visible.length===0?<div className="central-admin-card pengli-inbox-empty">目前沒有{filter==="pending_teacher"?"待回答":"已回答"}的疑問。</div>:<div className="pengli-inbox-list">{visible.map(({question:q,studentEmail,studentName})=><article className="central-admin-card pengli-inbox-card" key={q.id}><header><div><span className={`status ${q.status}`}>{q.status==="answered"?"已回答":"待回答"}</span><small>#{q.id}・{q.topic}</small></div><b>{studentName||studentEmail||"學生"}</b></header><section className="student-question"><small>學生真正想問</small><p>{q.studentQuestion}</p></section><details open={q.status==="pending_teacher"}><summary>查看原 AI 回覆與查證內容</summary><div className="pengli-inbox-evidence"><section><h3>原 AI 回覆</h3><p>{q.aiReply}</p></section><section><h3>AI 查證</h3><p>{q.verificationResult}</p></section></div></details>{q.status==="pending_teacher"?<div className="pengli-teacher-reply"><label>老師回覆<textarea value={drafts[q.id]||""} onChange={event=>setDrafts(current=>({...current,[q.id]:event.target.value}))} placeholder="直接回答學生的疑問；可補充法條、裁判或考場提醒。"/></label><button className="primary-button" disabled={busy===q.id||!(drafts[q.id]||"").trim()} onClick={()=>void reply(q.id)}>{busy===q.id?"送出中…":"送出老師回覆"}</button></div>:<section className="teacher-reply"><small>我的回覆</small><p>{q.teacherReply}</p></section>}</article>)}</div>}</section>
}
