"use client";
import { useEffect, useState } from "react";
type State={plan:{enabled:boolean;name:string;price:number;quota:number;durationDays:number;coachRounds:number};aiAccess:{active:boolean;quotaTotal:number;quotaUsed:number;remaining:number;startsAt:string|null;expiresAt:string|null};medtechAccess:{active:boolean;productKey?:string;expiresAt?:string}};
export default function AiAccessPanel(){
 const[state,setState]=useState<State|null>(null),[code,setCode]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const response=await fetch("/api/ai-access",{cache:"no-store"});if(response.ok)setState(await response.json()as State)}
 useEffect(()=>{void load();const payment=new URLSearchParams(location.search).get("ai_payment");if(payment==="success")setNotice("LINE Pay 付款成功，AI 學習方案已開通。");else if(payment==="cancelled")setNotice("已取消付款，未收取費用。");else if(payment==="failed"||payment==="invalid"||payment==="missing")setNotice("付款尚未完成，沒有新增 AI 使用額度。")},[]);
 async function redeem(){if(!code.trim())return;setBusy(true);setNotice("");try{const response=await fetch("/api/ai-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})}),data=await response.json()as State&{error?:string;benefitType?:string};if(!response.ok)throw new Error(data.error??"兌換失敗");setCode("");setNotice(data.benefitType==="medtech_book"?"醫檢書籍方案已開通。":"AI 學習方案已開通。");await load()}catch(error){setNotice(error instanceof Error?error.message:"兌換失敗")}finally{setBusy(false)}}
 async function buy(){setBusy(true);setNotice("");try{const response=await fetch("/api/ai-access/line-pay/request",{method:"POST"}),data=await response.json()as{paymentUrl?:string;error?:string};if(!response.ok||!data.paymentUrl)throw new Error(data.error??"無法建立付款");location.href=data.paymentUrl}catch(error){setNotice(error instanceof Error?error.message:"無法建立付款");setBusy(false)}}
 if(!state)return <div id="ai-access" className="account-section"><h2>AI 學習方案</h2><p>讀取方案中…</p></div>;
 return <div id="ai-access" className="account-section ai-member-access"><div className="account-section-heading"><h2>AI 學習與啟用碼</h2><small>單次購買，不自動續約</small></div>{state.aiAccess.active?<div className="ai-member-status"><strong>AI 方案使用中</strong><b>剩餘 {state.aiAccess.remaining}／{state.aiAccess.quotaTotal} 次</b><span>有效至 {new Date(state.aiAccess.expiresAt!).toLocaleString("zh-TW")}</span></div>:<div className="ai-member-offer"><div><strong>{state.plan.name}</strong><span>購買日起 {state.plan.durationDays} 天 · AI 教練每 {state.plan.coachRounds} 輪算 1 次</span></div><b>NT${state.plan.price}</b>{state.plan.enabled?<button type="button" onClick={()=>void buy()} disabled={busy}>使用 LINE Pay 單次購買</button>:<em>目前尚未開放購買</em>}</div>}{state.medtechAccess.active&&<div className="ai-member-status medtech"><strong>醫檢書籍方案使用中</strong><span>有效至 {new Date(state.medtechAccess.expiresAt!).toLocaleString("zh-TW")}</span></div>}<div className="activation-redeem"><label>免費啟用碼<input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} placeholder="IB-AI-XXXX-XXXX 或 IB-MT-XXXX-XXXX"/></label><button type="button" onClick={()=>void redeem()} disabled={busy||!code.trim()}>{busy?"處理中…":"兌換"}</button></div>{notice&&<p className="account-note" role="status">{notice}</p>}<p className="account-note">啟用碼一碼限一個會員兌換一次；有效方案期間不可重複購買或疊加。</p></div>
}
