"use client";
import { useEffect, useState } from "react";
type Q={id:number;year:string;examName:string;questionNumber:string;stem:string;optionsJson:string|null;correctAnswer:string|null;explanation:string;teacherNotes:string};
export default function AccountingPracticeClient(){
 const [items,setItems]=useState<Q[]>([]),[index,setIndex]=useState(0),[selected,setSelected]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[notice,setNotice]=useState("正在載入已發布的中會選擇題…");
 async function load(target=1){const r=await fetch(`/api/exam-questions?examCategory=accounting&status=published&examType=mcq&page=${target}`,{cache:"no-store"});const d=await r.json() as {items?:Q[];total?:number};const rows=d.items??[];setItems(rows);setTotal(d.total??0);setIndex(0);setSelected("");setPage(target);setNotice(rows.length?"先自己選答案，送出後才顯示教材解析。":"目前尚無已發布選擇題，請由管理後台先檢查並發布。")}
 useEffect(()=>{void load()},[]);
 const q=items[index];let options:Record<string,string>={};try{options=JSON.parse(q?.optionsJson||"{}") as Record<string,string>}catch{}
 const answered=Boolean(selected);
 return <section className="accounting-practice-shell"><header><span>中會選擇題真題</span><h1>一題一題練，作答後逐項核對</h1><p>{notice}</p></header>{q?<article className="accounting-practice-card"><small>{q.year}｜{q.examName}｜第 {q.questionNumber} 題　·　題庫第 {index+1}/{items.length} 題</small><h2>{q.stem}</h2><div className="accounting-options">{["A","B","C","D"].map(key=><button className={answered?(key===q.correctAnswer?"correct":key===selected?"wrong":""):selected===key?"selected":""} disabled={answered} onClick={()=>setSelected(key)} key={key}><b>{key}</b><span>{options[key]}</span></button>)}</div>{answered&&<section className="accounting-practice-explanation"><b>{selected===q.correctAnswer?"答對了":"這題答案是 "+(q.correctAnswer||"尚待核對")}</b><p>{q.explanation||"教材目前沒有獨立解析，可回首頁把這題交給中會 AI 逐步講解。"}</p>{q.teacherNotes&&<small>教材分類：{q.teacherNotes}</small>}</section>}<footer><button disabled={index===0} onClick={()=>{setIndex(v=>v-1);setSelected("")}}>上一題</button><button disabled={!selected} onClick={()=>{if(index<items.length-1){setIndex(v=>v+1);setSelected("")}else if(page*10<total)void load(page+1)}}>{index<items.length-1||page*10<total?"下一題":"本頁完成"}</button></footer></article>:<div className="accounting-practice-empty"><b>學生端還沒有題目</b><p>拆解完成後，仍需在後台「拆題審核」確認發布，才會出現在這裡。</p><a href="/accounting/admin/questions">前往拆題審核</a></div>}</section>;
}
