"use client";
import { useEffect, useState } from "react";
type Q={id:number;year:string;examName:string;questionNumber:string;stem:string;optionsJson:string|null;correctAnswer:string|null;explanation:string;teacherNotes:string};
type Facets={sourceBooks:string[];chapters:string[];years:string[]};
export default function AccountingPracticeClient(){
 const [items,setItems]=useState<Q[]>([]),[index,setIndex]=useState(0),[selected,setSelected]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[notice,setNotice]=useState("正在載入已發布的中會選擇題…");
 const [sourceBook,setSourceBook]=useState("all"),[chapter,setChapter]=useState("all"),[examSource,setExamSource]=useState("all"),[facets,setFacets]=useState<Facets>({sourceBooks:[],chapters:[],years:[]});
 async function load(target=1){const r=await fetch(`/api/exam-questions?examCategory=accounting&status=published&examType=mcq&page=${target}&sourceBook=${encodeURIComponent(sourceBook)}&chapter=${encodeURIComponent(chapter)}&year=${encodeURIComponent(examSource)}`,{cache:"no-store"});const d=await r.json() as {items?:Q[];total?:number;filters?:Partial<Facets>};const rows=d.items??[];setItems(rows);setTotal(d.total??0);setFacets(old=>({sourceBooks:d.filters?.sourceBooks??old.sourceBooks,chapters:d.filters?.chapters??old.chapters,years:d.filters?.years??old.years}));setIndex(0);setSelected("");setPage(target);setNotice(rows.length?`目前篩選共 ${d.total??0} 題；作答後顯示教材解析。`:"目前條件下沒有已發布選擇題。")}
 useEffect(()=>{void load()},[]);
 const q=items[index];let options:Record<string,string>={};try{options=JSON.parse(q?.optionsJson||"{}") as Record<string,string>}catch{}
 const answered=Boolean(selected);
 return <section className="accounting-practice-shell"><header><span>中會選擇題真題</span><h1>先挑主題，再一題一題練</h1><p>{notice}</p></header>
 <div className="accounting-bank-filters"><label>來源題庫<select value={sourceBook} onChange={e=>setSourceBook(e.target.value)}><option value="all">三本題庫全部</option>{facets.sourceBooks.map(v=><option key={v}>{v}</option>)}</select></label><label>章節主題<select value={chapter} onChange={e=>setChapter(e.target.value)}><option value="all">全部章節</option>{facets.chapters.map(v=><option key={v}>{v}</option>)}</select></label><label>考試類科／來源<select value={examSource} onChange={e=>setExamSource(e.target.value)}><option value="all">全部考試來源</option>{facets.years.map(v=><option key={v}>{v}</option>)}</select></label><button onClick={()=>void load(1)}>套用選題</button></div>
 {q?<article className="accounting-practice-card"><small>{q.year}｜{q.examName}｜第 {q.questionNumber} 題　·　第 {index+1}/{items.length} 題</small><h2>{q.stem}</h2><div className="accounting-options">{["A","B","C","D"].map(key=><button className={answered?(key===q.correctAnswer?"correct":key===selected?"wrong":""):selected===key?"selected":""} disabled={answered} onClick={()=>setSelected(key)} key={key}><b>{key}</b><span>{options[key]}</span></button>)}</div>{answered&&<section className="accounting-practice-explanation"><b>{selected===q.correctAnswer?"答對了":"這題答案是 "+(q.correctAnswer||"尚待核對")}</b><p>{q.explanation||"教材目前沒有獨立解析，可回首頁把這題交給中會 AI 逐步講解。"}</p>{q.teacherNotes&&<small>教材分類：{q.teacherNotes}</small>}</section>}<footer><button disabled={index===0} onClick={()=>{setIndex(v=>v-1);setSelected("")}}>上一題</button><button disabled={!selected} onClick={()=>{if(index<items.length-1){setIndex(v=>v+1);setSelected("")}else if(page*10<total)void load(page+1)}}>{index<items.length-1||page*10<total?"下一題":"本頁完成"}</button></footer></article>:<div className="accounting-practice-empty"><b>目前條件下沒有題目</b><p>請更換來源書、章節或考試類科。</p></div>}</section>;
}
