"use client";
import { FormEvent, useEffect, useState } from "react";
import { formatTwd } from "../../../lib/currency";
type Question={id:number;year:string;examName:string;subject:string;questionNumber:string;stem:string;teacherNotes:string};
type Usage={model:string;inputTokens:number;outputTokens:number;cachedTokens:number;durationMs:number;estimatedCostUsd:number}; type Message={role:"student"|"mentor";text:string;usage?:Usage}; type Facets={sourceBooks:string[];chapters:string[];years:string[]};
const steps=["讀題要求","整理條件","判斷準則","列計算式／分錄","完整作答","核對答案"];
const simulatedAnswers=["這題資料很多，我應該先找題目最後要我算什麼，對嗎？","我不確定哪些數字要用，可以先幫我分出已知條件和干擾資料嗎？","我知道要算，但不知道這題應該套用哪一個會計準則或判斷原則。","我不會列式，可以先告訴我第一個算式應該從哪個數字開始嗎？","我算出數字了，但不知道考試時要怎麼把計算過程和結論寫完整。","我想核對答案，請幫我找出最可能算錯或分錄方向寫反的地方。"];
export default function AccountingEssayCoach(){
 const [questions,setQuestions]=useState<Question[]>([]),[selected,setSelected]=useState<Question|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[step,setStep]=useState(0),[loading,setLoading]=useState(false),[notice,setNotice]=useState("正在載入已發布的中會申論題…"),[page,setPage]=useState(1),[total,setTotal]=useState(0),[questionOpen,setQuestionOpen]=useState(true);
 const [sourceBook,setSourceBook]=useState("all"),[chapter,setChapter]=useState("all"),[examSource,setExamSource]=useState("all"),[facets,setFacets]=useState<Facets>({sourceBooks:[],chapters:[],years:[]});
 async function load(target=1){setLoading(true);try{const r=await fetch(`/api/exam-questions?status=published&examType=essay&examCategory=accounting&page=${target}&sourceBook=${encodeURIComponent(sourceBook)}&chapter=${encodeURIComponent(chapter)}&year=${encodeURIComponent(examSource)}`,{cache:"no-store"});const data=await r.json() as {items?:Question[];total?:number;filters?:Partial<Facets>};const rows=data.items??[];setQuestions(rows);setTotal(data.total??0);setPage(target);setFacets(old=>({sourceBooks:data.filters?.sourceBooks??old.sourceBooks,chapters:data.filters?.chapters??old.chapters,years:data.filters?.years??old.years}));setNotice(rows.length?`目前條件共 ${data.total??0} 題，請挑一題開始逐步解題。`:"目前條件下沒有已發布的申論／計算題。")}catch{setNotice("申論題庫暫時無法讀取。")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function choose(question:Question){setSelected(question);setStep(0);setQuestionOpen(true);setMessages([{role:"mentor",text:"我們先不看完整答案。第一步只做讀題：請你用一句話說明，這題最後要你求什麼或寫出什麼？"}]);setInput("")}
 async function send(){if(!selected||!input.trim()||loading)return;const next=[...messages,{role:"student" as const,text:input.trim()}];setMessages(next);setInput("");setLoading(true);try{const response=await fetch("/api/accounting/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:[{role:"mentor",text:`申論題：${selected.stem}`},...next],mode:"guided",level:"入門",stage:["讀題","條件","準則","計算","計算","核對"][step],questionType:"計算題"})});const data=await response.json() as {reply?:string;usage?:Usage;error?:string};if(!response.ok||!data.reply)throw new Error(data.error||"老師暫時無法回答");const cost=data.usage?`\n\n${data.usage.model}｜輸入 ${data.usage.inputTokens.toLocaleString()}・輸出 ${data.usage.outputTokens.toLocaleString()}・合計 ${(data.usage.inputTokens+data.usage.outputTokens).toLocaleString()} Tokens｜約 NT$ ${formatTwd(data.usage.estimatedCostUsd,4)}｜${(data.usage.durationMs/1000).toFixed(1)} 秒`:"";setMessages(rows=>[...rows,{role:"mentor",text:`${data.reply}${cost}`,usage:data.usage}]);setStep(current=>Math.min(current+1,steps.length-1))}catch(error){setMessages(rows=>[...rows,{role:"mentor",text:error instanceof Error?error.message:"老師暫時無法回答"}])}finally{setLoading(false)}}
 return <section className="accounting-essay-coach"><header><span>中會申論解題</span><h1>依教材主題挑題，老師陪你逐步拆解</h1><p>不先公布完整解答；每次只完成一個解題步驟。</p></header><nav className="accounting-essay-steps">{steps.map((item,index)=><span className={index===step&&selected?"active":index<step?"done":""} key={item}><b>{index+1}</b>{item}</span>)}</nav>{!selected?<section className="accounting-question-picker"><div className="accounting-bank-filters"><label>來源題庫<select value={sourceBook} onChange={e=>setSourceBook(e.target.value)}><option value="all">三本題庫全部</option>{facets.sourceBooks.map(v=><option key={v}>{v}</option>)}</select></label><label>章節主題<select value={chapter} onChange={e=>setChapter(e.target.value)}><option value="all">全部章節</option>{facets.chapters.map(v=><option key={v}>{v}</option>)}</select></label><label>考試類科／來源<select value={examSource} onChange={e=>setExamSource(e.target.value)}><option value="all">全部考試來源</option>{facets.years.map(v=><option key={v}>{v}</option>)}</select></label><button onClick={()=>void load(1)}>套用選題</button></div><h2>選擇申論／計算題</h2><p>{notice}</p>{questions.map(question=><button type="button" onClick={()=>choose(question)} key={question.id}><small>{question.year}｜{question.examName}｜第 {question.questionNumber} 題</small><b>{question.stem.slice(0,180)}{question.stem.length>180?"…":""}</b></button>)}<nav className="accounting-review-pages"><button disabled={page<=1||loading} onClick={()=>void load(page-1)}>上一頁</button><span>第 {page} / {Math.max(1,Math.ceil(total/10))} 頁</span><button disabled={page*10>=total||loading} onClick={()=>void load(page+1)}>下一頁</button></nav></section>:<div className="accounting-essay-workspace"><article className={`accounting-essay-question-panel ${questionOpen?"open":""}`}><header><div><button type="button" onClick={()=>setSelected(null)}>← 重新選題</button><small>{selected.year}｜{selected.examName}｜第 {selected.questionNumber} 題</small></div><button type="button" className="toggle" onClick={()=>setQuestionOpen(value=>!value)}>{questionOpen?"收合題目 ↑":"展開題目 ↓"}</button></header>{questionOpen&&<p>{selected.stem}</p>}</article><section><div className="accounting-chat">{messages.map((message,index)=><article className={message.role} key={index}><b>{message.role==="mentor"?"中會老師":"學生"}</b><p>{message.text}</p></article>)}{loading&&<article className="mentor loading"><b>中會老師</b><p>正在檢查這一步…</p></article>}</div><div className="accounting-simulated-answer"><span>不知道怎麼回答？模擬學生可能會說：</span><button type="button" onClick={()=>setInput(simulatedAnswers[step])}>{simulatedAnswers[step]}</button></div><form onSubmit={(event:FormEvent)=>{event.preventDefault();void send()}}><textarea rows={4} value={input} onChange={event=>setInput(event.target.value)} placeholder={`回答目前步驟：${steps[step]}…`}/><button disabled={loading||!input.trim()}>送出</button></form></section></div>}</section>}
