"use client";
import { FormEvent, useEffect, useState } from "react";
import { formatTwd } from "../../../lib/currency";
import { accountingDisplayBlocks, removeAccountingPageFurniture } from "../../../lib/accounting-question";
type Question={id:number;year:string;examName:string;subject:string;questionNumber:string;stem:string;teacherNotes:string};
type Usage={model:string;inputTokens:number;outputTokens:number;cachedTokens:number;durationMs:number;estimatedCostUsd:number};
type Message={role:"student"|"mentor";text:string;usage?:Usage}; type Facets={sourceBooks:string[];chapters:string[];years:string[]};
const steps=["拆解各子題","整理已知條件","選用會計準則","逐步計算／分錄","組織完整答案","檢查金額與格式"];
function cleanStem(stem:string){let child=0;return removeAccountingPageFurniture(stem).replace(/□\s*(?=[^\n]{2,80}?[？?])/gu,()=>`\n（${++child}）`).replace(/([^\n])\s+(（\d+）)/gu,"$1\n$2").replace(/\s*\n\s*/g,"\n").trim()}
function QuestionBody({text}:{text:string}){return <div className="accounting-question-body">{accountingDisplayBlocks(text).map((block,index)=>block.type==="table"?<div className="accounting-table-wrap" key={index}><table><tbody>{block.rows.map((row,rowIndex)=><tr key={rowIndex}><th>{row.label}</th>{row.values.map((value,valueIndex)=><td key={valueIndex}>{value}</td>)}</tr>)}</tbody></table></div>:<div className="accounting-question-copy" key={index}>{block.lines.map((line,lineIndex)=><p key={lineIndex}>{line}</p>)}</div>)}</div>}
function UsageLine({usage}:{usage:Usage}){return <div className="accounting-usage"><b>{usage.model}</b><span>輸入 {usage.inputTokens.toLocaleString()}・輸出 {usage.outputTokens.toLocaleString()}・合計 {(usage.inputTokens+usage.outputTokens).toLocaleString()} Tokens</span><span>約 NT$ {formatTwd(usage.estimatedCostUsd,4)}・{(usage.durationMs/1000).toFixed(1)} 秒</span></div>}
export default function AccountingEssayCoach(){
 const [questions,setQuestions]=useState<Question[]>([]),[selected,setSelected]=useState<Question|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[step,setStep]=useState(0),[loading,setLoading]=useState(false),[notice,setNotice]=useState("正在載入已發布的中會申論題…"),[page,setPage]=useState(1),[total,setTotal]=useState(0),[questionOpen,setQuestionOpen]=useState(true),[simulating,setSimulating]=useState(false),[simulated,setSimulated]=useState("");
 const [sourceBook,setSourceBook]=useState("all"),[chapter,setChapter]=useState("all"),[examSource,setExamSource]=useState("all"),[facets,setFacets]=useState<Facets>({sourceBooks:[],chapters:[],years:[]});
 async function load(target=1){setLoading(true);try{const r=await fetch(`/api/exam-questions?status=published&examType=essay&examCategory=accounting&page=${target}&sourceBook=${encodeURIComponent(sourceBook)}&chapter=${encodeURIComponent(chapter)}&year=${encodeURIComponent(examSource)}`,{cache:"no-store"});const data=await r.json() as {items?:Question[];total?:number;filters?:Partial<Facets>};const rows=data.items??[];setQuestions(rows);setTotal(data.total??0);setPage(target);setFacets(old=>({sourceBooks:data.filters?.sourceBooks??old.sourceBooks,chapters:data.filters?.chapters??old.chapters,years:data.filters?.years??old.years}));setNotice(rows.length?`目前條件共 ${data.total??0} 題，請挑一題開始逐步解題。`:"目前條件下沒有已發布的申論／計算題。")}catch{setNotice("申論題庫暫時無法讀取。")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function choose(question:Question){setSelected({...question,stem:cleanStem(question.stem)});setStep(0);setQuestionOpen(true);setSimulated("");setMessages([{role:"mentor",text:"我們先不看完整答案。第一步只做讀題：請先找出這一大題共有幾個子題，再說明每一小題分別要求計算或作答什麼？"}]);setInput("")}
 async function submitStudent(text:string,studentUsage?:Usage){if(!selected||!text.trim()||loading)return;setSimulated("");const next=[...messages,{role:"student" as const,text:text.trim(),usage:studentUsage}];setMessages(next);setInput("");setLoading(true);try{const response=await fetch("/api/accounting/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:[{role:"mentor",text:`申論題全文（包含所有子題）：${selected.stem}`},...next],mode:"guided",level:"入門",stage:["讀題","條件","準則","計算","計算","核對"][step],questionType:"計算題"})});const data=await response.json() as {reply?:string;usage?:Usage;error?:string};if(!response.ok||!data.reply)throw new Error(data.error||"老師暫時無法回答");setMessages(rows=>[...rows,{role:"mentor",text:data.reply!,usage:data.usage}]);setStep(current=>Math.min(current+1,steps.length-1))}catch(error){setMessages(rows=>[...rows,{role:"mentor",text:error instanceof Error?error.message:"老師暫時無法回答"}])}finally{setLoading(false)}}
 async function simulateStudent(){if(!selected||simulating||loading)return;setSimulating(true);setSimulated("");try{const teacher=messages.filter(message=>message.role==="mentor").at(-1)?.text||"請先說明你會如何開始解這題。";const response=await fetch("/api/accounting/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:[{role:"mentor",text:`申論題全文（包含所有子題）：${selected.stem}`},{role:"mentor",text:teacher},{role:"student",text:`請讀完整題目，模擬入門學生在「${steps[step]}」階段的真實回答。`}],mode:"guided",level:"入門",stage:["讀題","條件","準則","計算","計算","核對"][step],questionType:"計算題",simulateStudent:true})});const data=await response.json() as {reply?:string;usage?:Usage;error?:string};if(!response.ok||!data.reply)throw new Error(data.error||"AI 暫時無法模擬學生");await submitStudent(data.reply,data.usage)}catch(error){setSimulated(error instanceof Error?error.message:"AI 暫時無法模擬學生")}finally{setSimulating(false)}}
 async function send(){await submitStudent(input)}
 return <section className="accounting-essay-coach"><header><span>中會申論解題</span><h1>依教材主題挑題，老師陪你逐步拆解</h1><p>不先公布完整解答；每次只完成一個解題步驟。</p></header>
 <nav className="accounting-essay-steps">{steps.map((item,index)=><span className={index===step&&selected?"active":index<step?"done":""} key={item}><b>{index+1}</b>{item}</span>)}</nav>
 {!selected?<section className="accounting-question-picker"><div className="accounting-bank-filters"><label>來源題庫<select value={sourceBook} onChange={e=>setSourceBook(e.target.value)}><option value="all">三本題庫全部</option>{facets.sourceBooks.map(v=><option key={v}>{v}</option>)}</select></label><label>章節主題<select value={chapter} onChange={e=>setChapter(e.target.value)}><option value="all">全部章節</option>{facets.chapters.map(v=><option key={v}>{v}</option>)}</select></label><label>考試類科／來源<select value={examSource} onChange={e=>setExamSource(e.target.value)}><option value="all">全部考試來源</option>{facets.years.map(v=><option key={v}>{v}</option>)}</select></label><button onClick={()=>void load(1)}>套用選題</button></div><h2>選擇申論／計算題</h2><p>{notice}</p>{questions.map(question=><button type="button" onClick={()=>choose(question)} key={question.id}><small>{question.year}｜{question.examName}｜第 {question.questionNumber} 題</small><b>{cleanStem(question.stem).slice(0,180)}{question.stem.length>180?"…":""}</b></button>)}<nav className="accounting-review-pages"><button disabled={page<=1||loading} onClick={()=>void load(page-1)}>上一頁</button><span>第 {page} / {Math.max(1,Math.ceil(total/10))} 頁</span><button disabled={page*10>=total||loading} onClick={()=>void load(page+1)}>下一頁</button></nav></section>:
 <div className="accounting-essay-workspace"><article className="accounting-essay-question-panel"><header><div><button type="button" onClick={()=>setSelected(null)}>← 重新選題</button><small>{selected.year}｜{selected.examName}｜第 {selected.questionNumber} 題</small></div><button type="button" className="toggle" onClick={()=>setQuestionOpen(value=>!value)}>{questionOpen?"收合題目 ↑":"展開題目 ↓"}</button></header>{questionOpen&&<QuestionBody text={selected.stem}/>}</article><section><div className="accounting-chat">{messages.map((message,index)=><article className={message.role} key={index}><b>{message.role==="mentor"?"中會老師":"學生"}</b><p>{message.text}</p>{message.usage&&<UsageLine usage={message.usage}/>}</article>)}{loading&&<article className="mentor loading"><b>中會老師</b><p>正在檢查這一步…</p></article>}</div><div className="accounting-simulated-answer"><span>不知道怎麼回答？按一次就由 AI 模擬學生並直接送給老師：</span><button type="button" disabled={simulating||loading} onClick={()=>void simulateStudent()}>{simulating?"AI 正在作答並送出…":"AI 模擬學生並送出"}</button>{simulated&&<p>{simulated}</p>}</div><form onSubmit={(event:FormEvent)=>{event.preventDefault();void send()}}><textarea rows={4} value={input} onChange={event=>setInput(event.target.value)} placeholder={`回答目前步驟：${steps[step]}…`}/><button disabled={loading||!input.trim()}>送出</button></form></section></div>}</section>
}
