"use client";
import { useEffect, useState } from "react";
import { RichQuestionEditor } from "../../medtech/admin/RichQuestionEditor";
type Product={productKey:string;title:string;subtitle:string;descriptionHtml:string;coverStorageKey:string|null;listPrice:number;salePrice:number|null;saleLabel:string;saleStartsAt:string|null;saleEndsAt:string|null;accessDays:number;trialQuestions:number;renewalMode:string;status:string;effectivePrice:number;saleActive:boolean};
export default function AccountingProductPanel(){const[product,setProduct]=useState<Product|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[canManage,setCanManage]=useState(false);
 async function load(){const r=await fetch("/api/accounting/admin/product",{cache:"no-store"}),d=await r.json();if(r.ok){setProduct(d.product);setCanManage(d.canManageCommercial)}else setNotice(d.error||"讀取商品設定失敗")}
 useEffect(()=>{void load()},[]);
 async function save(){if(!product)return;setBusy(true);const r=await fetch("/api/accounting/admin/product",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(product)}),d=await r.json();setBusy(false);if(r.ok){setProduct(d.product);setNotice("商品設定已儲存；前台價格、天數與免費題數會依此設定。") }else setNotice(d.error||"儲存失敗")}
 if(!product)return <section className="accounting-admin-panel"><p>{notice||"正在讀取書籍商品設定…"}</p></section>;
 const set=<K extends keyof Product>(key:K,value:Product[K])=>setProduct({...product,[key]:value});
 return <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>第一本書｜商品與購書規則</h2><small>預設 NT$249／90天；所有數值都可調整，不寫死於前台。</small></div></div>
 <div className="medtech-commercial-grid"><label>書名<input value={product.title} disabled/></label><label>上架狀態<select value={product.status} onChange={e=>set("status",e.target.value)}><option value="draft">草稿（前台不販售）</option><option value="active">正式上架</option><option value="disabled">暫停販售</option></select></label><label>定價 NT$<input type="number" min="1" value={product.listPrice} onChange={e=>set("listPrice",Number(e.target.value))}/></label><label>活動價 NT$<input type="number" min="1" value={product.salePrice??""} placeholder="未設定" onChange={e=>set("salePrice",e.target.value?Number(e.target.value):null)}/></label><label>活動名稱<input value={product.saleLabel} placeholder="例如：新書上線優惠" onChange={e=>set("saleLabel",e.target.value)}/></label><label>活動開始<input type="datetime-local" value={product.saleStartsAt?.slice(0,16)??""} onChange={e=>set("saleStartsAt",e.target.value||null)}/></label><label>活動結束<input type="datetime-local" value={product.saleEndsAt?.slice(0,16)??""} onChange={e=>set("saleEndsAt",e.target.value||null)}/></label><label>使用天數<input type="number" min="1" max="3650" value={product.accessDays} onChange={e=>set("accessDays",Number(e.target.value))}/></label><label>免費體驗題數<input type="number" min="0" max="5000" value={product.trialQuestions} onChange={e=>set("trialQuestions",Number(e.target.value))}/></label><label>續購規則<input value="有效期接續延長，不吃掉剩餘天數" disabled/></label></div>
 <details className="product-rich-editor-collapsible"><summary><span><b>前台商品介紹</b><small>{product.descriptionHtml?"已設定內容":"尚未設定內容"}</small></span><strong>展開富文字編輯</strong></summary><div><RichQuestionEditor category="accounting" label="前台商品介紹（完整富文）" value={product.descriptionHtml} onChange={value=>set("descriptionHtml",value)}/></div></details>
 <div className="medtech-commercial-summary"><b>目前顯示：NT${product.effectivePrice}／{product.accessDays}天</b><span>{product.status==="active"?"可販售":product.status==="draft"?"草稿中，學生尚不能購買":"已暫停販售"} · 免費 {product.trialQuestions} 題</span></div>
 <button type="button" onClick={()=>void save()} disabled={busy||!canManage}>{busy?"儲存中…":"儲存商品設定"}</button>{!canManage&&<p>只有總管理者可調整商業設定。</p>}{notice&&<p className="accounting-admin-notice" role="status">{notice}</p>}</section>}
