"use client";
import { useEffect, useState } from "react";
type Member={id:number;email:string;displayName:string;status:"active"|"disabled";canAdmin:boolean;className:string};
export default function AccountingMemberManager(){
 const [members,setMembers]=useState<Member[]>([]),[notice,setNotice]=useState("");
 const [draft,setDraft]=useState({displayName:"",email:"",className:"",role:"student",status:"active",canAdmin:false});
 async function load(){const r=await fetch("/api/accounting/members");const d=await r.json() as {members?:Member[];error?:string};setMembers(d.members??[]);if(!r.ok)setNotice(d.error??"讀取失敗")}
 useEffect(()=>{void load()},[]);
 async function create(){const r=await fetch("/api/accounting/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});const d=await r.json() as {error?:string};if(r.ok){setNotice("中級會計會員已新增。");setDraft({displayName:"",email:"",className:"",role:"student",status:"active",canAdmin:false});await load()}else setNotice(d.error??"新增失敗，請檢查資料。")}
 async function update(id:number,patch:Partial<Member>){const r=await fetch("/api/accounting/members",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});const d=await r.json() as {error?:string};if(r.ok)setMembers(list=>list.map(x=>x.id===id?{...x,...patch}:x));else setNotice(d.error??"更新失敗")}
 return <><section className="medtech-admin-panel"><h2>新增中級會計會員</h2><div className="medtech-member-form"><label>姓名<input value={draft.displayName} onChange={e=>setDraft({...draft,displayName:e.target.value})}/></label><label>Email<input value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>班級<input value={draft.className} onChange={e=>setDraft({...draft,className:e.target.value})}/></label><label>身分<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="student">學員</option><option value="teacher">老師／導師</option></select></label><label className="check"><input type="checkbox" checked={draft.canAdmin} onChange={e=>setDraft({...draft,canAdmin:e.target.checked})}/>管理員</label><button onClick={()=>void create()}>新增會員</button></div>{notice&&<p className="medtech-admin-notice">{notice}</p>}</section><section className="medtech-admin-panel"><h2>中級會計會員名單</h2><div className="medtech-admin-list">{members.map(m=><article key={m.id}><div><b>{m.displayName}</b><span>{m.email}</span></div><label>班級<input value={m.className} onChange={e=>setMembers(list=>list.map(x=>x.id===m.id?{...x,className:e.target.value}:x))} onBlur={e=>void update(m.id,{className:e.target.value})}/></label><label>狀態<select value={m.status} onChange={e=>void update(m.id,{status:e.target.value as Member["status"]})}><option value="active">使用中</option><option value="disabled">已停用</option></select></label><label className="check"><input type="checkbox" checked={m.canAdmin} onChange={e=>void update(m.id,{canAdmin:e.target.checked})}/>管理員</label></article>)}</div></section></>;
}
