"use client";
import { useEffect, useState } from "react";
import { RichQuestionEditor } from "../../medtech/admin/RichQuestionEditor";
type Product={productKey:string;title:string;subtitle:string;descriptionHtml:string;coverStorageKey:string|null;listPrice:number;salePrice:number|null;saleLabel:string;saleStartsAt:string|null;saleEndsAt:string|null;accessDays:number;trialQuestions:number;renewalMode:string;status:string;effectivePrice:number;saleActive:boolean};
export default function AccountingProductPanel(){const[product,setProduct]=useState<Product|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[canManage,setCanManage]=useState(false),[coverVersion,setCoverVersion]=useState(Date.now());
 async function load(){const r=await fetch("/api/accounting/admin/product",{cache:"no-store"}),d=await r.json();if(r.ok){setProduct(d.product);setCanManage(d.canManageCommercial)}else setNotice(d.error||"讀取商品設定失敗")}
 useEffect(()=>{void load()},[]);
 async function save(){if(!product)return;setBusy(true);const r=await fetch("/api/accounting/admin/product",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(product)}),d=await r.json();setBusy(false);if(r.ok){setProduct(d.product);setNotice("商品設定已儲存；前台價格、天數與免費題數會依此設定。") }else setNotice(d.error||"儲存失敗")}
 async function uploadCover(file:File){setBusy(true);const form=new FormData();form.set("file",file);const r=await fetch("/api/accounting/admin/product/cover",{method:"POST",body:form}),d=await r.json();setBusy(false);if(r.ok){setProduct({...product!,coverStorageKey:"uploaded"});setCoverVersion(Date.now());setNotice("書封已上傳並套用到學生書庫。") }else setNotice(d.error||"書封上傳失敗")}
 async function removeCover(){if(!window.confirm("確定移除目前書封？"))return;setBusy(true);const r=await fetch("/api/accounting/admin/product/cover",{method:"DELETE"}),d=await r.json();setBusy(false);if(r.ok){setProduct({...product!,coverStorageKey:null});setNotice("書封已移除。") }else setNotice(d.error||"移除失敗")}
 if(!product)return <section className="accounting-admin-panel"><p>{notice||"正在讀取書籍商品設定…"}</p></section>;
 const set=<K extends keyof Product>(key:K,value:Product[K])=>setProduct({...product,[key]:value});
 return <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>第一本書｜商品與購書規則</h2><small>預設 NT$249／90天；所有數值都可調整，不寫死於前台。</small></div></div>
 <div className="accounting-cover-admin"><div className="accounting-cover-preview">{product.coverStorageKey?<img src={`/api/accounting/product/cover?v=${coverVersion}`} alt={`${product.title}書封`}/>:<span><b>尚未上傳書封</b><small>建議使用直式封面圖</small></span>}</div><div><h3>書封圖片</h3><p>支援 JPG、PNG、WebP，最大 8MB。更換後學生書庫會自動使用新書封。</p><label className="accounting-cover-upload">{busy?"處理中…":product.coverStorageKey?"更換書封":"上傳書封"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!canManage} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadCover(file);e.currentTarget.value=""}}/></label>{product.coverStorageKey&&<button type="button" onClick={()=>void removeCover()} disabled={busy||!canManage}>移除書封</button>}</div></div>
 <div className="medtech-commercial-grid"><label>書名<input value={product.title} disabled/></label><label>上架狀態<select value={product.status} onChange={e=>set("status",e.target.value)}><option value="draft">草稿（前台不販售）</option><option value="active">正式上架</option><option value="disabled">暫停販售</option></select></label><label>定價 NT$<input type="number" min="1" value={product.listPrice} onChange={e=>set("listPrice",Number(e.target.value))}/></label><label>活動價 NT$<input type="number" min="1" value={product.salePrice??""} placeholder="未設定" onChange={e=>set("salePrice",e.target.value?Number(e.target.value):null)}/></label><label>活動名稱<input value={product.saleLabel} placeholder="例如：新書上線優惠" onChange={e=>set("saleLabel",e.target.value)}/></label><label>活動開始<input type="datetime-local" value={product.saleStartsAt?.slice(0,16)??""} onChange={e=>set("saleStartsAt",e.target.value||null)}/></label><label>活動結束<input type="datetime-local" value={product.saleEndsAt?.slice(0,16)??""} onChange={e=>set("saleEndsAt",e.target.value||null)}/></label><label>使用天數<input type="number" min="1" max="3650" value={product.accessDays} onChange={e=>set("accessDays",Number(e.target.value))}/></label><label>免費體驗題數<input type="number" min="0" max="5000" value={product.trialQuestions} onChange={e=>set("trialQuestions",Number(e.target.value))}/></label><label>續購規則<input value="有效期接續延長，不吃掉剩餘天數" disabled/></label></div>
 <RichQuestionEditor category="accounting" label="前台商品介紹（完整富文）" value={product.descriptionHtml} onChange={value=>set("descriptionHtml",value)}/>
 <div className="medtech-commercial-summary"><b>目前顯示：NT${product.effectivePrice}／{product.accessDays}天</b><span>{product.status==="active"?"可販售":product.status==="draft"?"草稿中，學生尚不能購買":"已暫停販售"} · 免費 {product.trialQuestions} 題</span></div>
 <div className="accounting-admin-panel" style={{marginTop:16}}><h3>固定購書規則</h3><ul><li>單次購買，不自動續約。</li><li>付款成功才開始計算使用期限。</li><li>有效期內續購，從原到期日再加上本次天數。</li><li>已開始使用的數位內容不按剩餘題數比例退費；實際退費依前台揭露條款辦理。</li><li>AI追問與未來申論批改不包含在書籍無限使用權內，另依AI額度計次。</li></ul></div>
 <button type="button" onClick={()=>void save()} disabled={busy||!canManage}>{busy?"儲存中…":"儲存商品設定"}</button>{!canManage&&<p>只有總管理者可調整商業設定。</p>}{notice&&<p className="accounting-admin-notice" role="status">{notice}</p>}</section>}
