"use client";
import { useEffect, useState } from "react";

type Doc={id:number;name:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;error?:string;chapterCount:number;questionCount:number;homepageSearchEnabled:boolean;vectorIndexed:boolean};
const presets=[
  ["中級會計學霸（上）","核心教材"],["中級會計學霸（下）","核心教材"],
  ["會研所中級會計學題庫制霸","章節題庫"],["中級會計學申論題完全制霸","申論題庫"],["泓觀稱霸中級會計學 114 年解題全攻略","年度解題"]
];
export default function AccountingAdmin(){
 const [docs,setDocs]=useState<Doc[]>([]),[file,setFile]=useState<File|null>(null),[subject,setSubject]=useState("中級會計學"),[type,setType]=useState("核心教材"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[processingId,setProcessingId]=useState<number|null>(null);
 async function load(){const r=await fetch("/api/accounting/documents",{cache:"no-store"});const d=await r.json() as {documents?:Doc[];error?:string};setDocs(d.documents??[]);if(!r.ok)setNotice(d.error??"讀取失敗")}
 useEffect(()=>{void load()},[]);
 async function process(id:number,retry=false,reanalyze=false){if(processingId!==null)return;const target=docs.find(doc=>doc.id===id);setProcessingId(id);setNotice(reanalyze?(target?.type==="核心教材"?"已開始重新建立內容索引，正在讀取章節、準則與觀念…":"已開始重新拆解題目，正在盤點完整題幹與題型…"):"教材處理中…");try{for(let i=0;i<30;i++){const r=await fetch("/api/accounting/documents/process",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,retry:retry&&i===0,reanalyze:reanalyze&&i===0})});const d=await r.json() as {status?:string;message?:string;error?:string};setNotice(d.message??d.error??"處理中…");await load();if(!r.ok||d.status==="completed")return;await new Promise(resolve=>setTimeout(resolve,2200))}setNotice("索引仍在建立，可稍後繼續處理。")}catch(error){setNotice(error instanceof Error?error.message:"重新處理失敗，請再試一次。")}finally{setProcessingId(null);await load()}}
 async function upload(){if(!file){setNotice("請先選擇 PDF。");return}setBusy(true);try{const contentType=file.name.toLowerCase().endsWith(".pdf")?"application/pdf":file.type||"application/octet-stream";setNotice("正在建立大型教材分段上傳…");const initResponse=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"init",fileName:file.name,contentType})});const init=await initResponse.json() as {key?:string;uploadId?:string;error?:string};if(!initResponse.ok||!init.key||!init.uploadId)throw new Error(init.error||"無法開始上傳");const chunkSize=5*1024*1024,parts:Array<{partNumber:number;etag:string}>=[];for(let start=0,partNumber=1;start<file.size;start+=chunkSize,partNumber++){setNotice(`教材上傳中：${Math.min(100,Math.round(start/file.size*100))}%`);const response=await fetch(`/api/documents/multipart?key=${encodeURIComponent(init.key)}&uploadId=${encodeURIComponent(init.uploadId)}&partNumber=${partNumber}`,{method:"PUT",headers:{"content-type":"application/octet-stream"},body:file.slice(start,Math.min(start+chunkSize,file.size))});const part=await response.json() as {partNumber?:number;etag?:string;error?:string};if(!response.ok||!part.partNumber||!part.etag)throw new Error(part.error||`第 ${partNumber} 段上傳失敗`);parts.push({partNumber:part.partNumber,etag:part.etag})}const completeResponse=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",key:init.key,uploadId:init.uploadId,parts,fileName:file.name,contentType,sizeBytes:file.size,examCategory:"accounting",subject,documentType:type})});const completed=await completeResponse.json() as {document?:{id:number};error?:string};if(!completeResponse.ok||!completed.document)throw new Error(completed.error||"無法完成文件上傳");setNotice("上傳完成，正在擷取目錄、章節並建立索引…");setFile(null);await load();await process(completed.document.id)}catch(error){setNotice(error instanceof Error?error.message:"教材上傳失敗")}finally{setBusy(false)}}
 async function toggle(doc:Doc){const r=await fetch("/api/accounting/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,homepageSearchEnabled:!doc.homepageSearchEnabled})});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error??"設定失敗");if(r.status===409)void process(doc.id);return}await load()}
 return <main className="accounting-admin-page"><header className="accounting-top"><a href="/accounting" className="accounting-brand"><span>中</span><div><b>中級會計管理後台</b><small>CONTENT ADMIN</small></div></a><nav><a href="/accounting">學生首頁</a><a href="/accounting/admin/questions">拆題審核</a></nav></header>
 <section className="accounting-admin-hero"><span>中級會計 · 獨立教材空間</span><h1>教材上傳與自動拆解</h1><p>固定歸入中會類科；不會混入司律或醫檢師的教材與搜尋結果。</p></section>
 <section className="accounting-admin-panel"><h2>五本教材匯入順序</h2><div className="accounting-import-map">{presets.map(([name,role],i)=><article key={name}><b>{i+1}</b><div><h3>{name}</h3><p>{role}</p></div></article>)}</div></section>
 <section className="accounting-admin-panel"><h2>上傳教材</h2><div className="accounting-upload-form"><label>科目<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>用途<select value={type} onChange={e=>setType(e.target.value)}><option>核心教材</option><option>章節題庫</option><option>申論題庫</option><option>年度解題</option></select></label><label className="file">選擇 PDF<input type="file" accept=".pdf,.docx,.txt,.md,.json,.jsonl,.zip" onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{file?.name??"尚未選擇文件"}</span></label><button disabled={busy} onClick={()=>void upload()}>{busy?"自動處理中…":"上傳並自動處理"}</button></div>{notice&&<p className="accounting-admin-notice">{notice}</p>}</section>
 <section className="accounting-admin-panel"><div className="accounting-admin-heading"><h2>中會教材清單</h2><div><a href="/accounting/admin/questions">查看拆解題庫</a><button onClick={()=>void load()}>重新整理</button></div></div><div className="accounting-document-list">{docs.map(doc=><article key={doc.id}><div><small>{doc.subject} · {doc.type}</small><h3>{doc.name}</h3><p>{(doc.sizeBytes/1024/1024).toFixed(2)} MB</p></div><div><b>{processingId===doc.id?"正在重新處理…":doc.processingStage==="completed"?"處理完成":"處理中"}</b><p>{processingId===doc.id?(doc.type==="核心教材"?"正在建立章節與觀念索引，請勿重複點擊":"正在完整盤點題目，完成後會自動更新題數"):doc.error||doc.processingMessage}</p></div><div className="counts"><b>{doc.chapterCount}<small> 章</small></b>{doc.type==="核心教材"?<b><small>內容索引</small></b>:<b>{doc.questionCount}<small> 題庫草稿</small></b>}</div><div className="actions">{doc.processingStage!=="completed"?<button disabled={processingId!==null} onClick={()=>void process(doc.id,doc.status==="failed")}>{processingId===doc.id?"處理中…":"繼續處理"}</button>:<button disabled={processingId!==null} onClick={()=>void process(doc.id,false,true)}>{processingId===doc.id?"處理中…":doc.type==="核心教材"?"重新建立索引":"重新拆解並入庫"}</button>}{doc.type!=="核心教材"&&<a href={`/accounting/admin/questions`}>檢查內容</a>}<label><input type="checkbox" checked={doc.homepageSearchEnabled} onChange={()=>void toggle(doc)} disabled={!doc.vectorIndexed||processingId!==null}/>允許中會 AI 搜尋</label></div></article>)}{!docs.length&&<p>尚未匯入中會教材；請依上方順序上傳五本 PDF。</p>}</div></section></main>;
}
