"use client";
import { unzipSync } from "fflate";
import { useEffect, useState } from "react";
import AccountingMemberManager from "./AccountingMemberManager";
import DocumentQuestionLibrary from "../../medtech/admin/DocumentQuestionLibrary";
import QuestionBank from "../../medtech/admin/QuestionBank";

type Doc={id:number;name:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;error?:string;chapterCount:number;questionCount:number;homepageSearchEnabled:boolean;vectorIndexed:boolean};
type BatchRow={id:string;name:string;size:number;status:"waiting"|"uploading"|"processing"|"completed"|"failed"|"skipped";progress:number;message:string};
const allowed=/\.(pdf|docx|txt)$/i;
function mime(name:string){const ext=name.split(".").pop()?.toLowerCase();return ext==="pdf"?"application/pdf":ext==="docx"?"application/vnd.openxmlformats-officedocument.wordprocessingml.document":"text/plain"}
function isWordQuiz(doc:Pick<Doc,"name">){return /\.docx$/iu.test(doc.name)&&/(?:小考|模擬考|考題|題庫|測驗)/u.test(doc.name)}
const presets=[
  ["中級會計學霸（上）","核心教材"],["中級會計學霸（下）","核心教材"],
  ["會研所中級會計學題庫制霸","章節題庫"],["中級會計學申論題完全制霸","申論題庫"],["泓觀稱霸中級會計學 114 年解題全攻略","年度解題"]
];
export default function AccountingAdmin(){
 const [tab,setTab]=useState<"members"|"documents"|"questions"|"bank">("documents");
 const [docs,setDocs]=useState<Doc[]>([]),[files,setFiles]=useState<File[]>([]),[subject,setSubject]=useState("中級會計學"),[type,setType]=useState("核心教材"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[processingId,setProcessingId]=useState<number|null>(null),[wordBankCount,setWordBankCount]=useState<number|null>(null),[batch,setBatch]=useState<BatchRow[]>([]);
 async function load(){const r=await fetch("/api/accounting/documents",{cache:"no-store"});const d=await r.json() as {documents?:Doc[];error?:string};setDocs(d.documents??[]);if(!r.ok)setNotice(d.error??"讀取失敗")}
 useEffect(()=>{void load();const requested=new URLSearchParams(window.location.search).get("tab");if(requested==="members"||requested==="documents"||requested==="questions"||requested==="bank")setTab(requested)},[]);
 async function importWordBank(){setBusy(true);setNotice("正在匯入獨立 Word 選擇題庫…");try{const r=await fetch("/api/accounting/word-bank",{method:"POST"});const d=await r.json() as {imported?:number;source?:string;error?:string};if(!r.ok)throw new Error(d.error??"Word 題庫匯入失敗");setWordBankCount(d.imported??0);setNotice(`已匯入 ${d.imported??0} 題，前台來源統一為「${d.source}」；原始小考名稱只留在後台。`)}catch(error){setNotice(error instanceof Error?error.message:"Word 題庫匯入失敗")}finally{setBusy(false)}}
 function updateBatch(id:string,patch:Partial<BatchRow>){setBatch(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))}
 async function process(id:number,retry=false,reanalyze=false,onMessage?:(message:string)=>void){if(processingId!==null&&!onMessage)return;const target=docs.find(doc=>doc.id===id);setProcessingId(id);const initial=reanalyze?(target?.type==="核心教材"?"已開始重新建立內容索引，正在讀取章節、準則與觀念…":"已開始逐頁拆解，題目會分批進入待審核題庫…"):"教材處理中…";setNotice(initial);onMessage?.(initial);try{if(reanalyze&&target?.type!=="核心教材"){let offset=0;for(let i=0;i<30;i++){const r=await fetch("/api/accounting/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,offset,limit:60})});const d=await r.json() as {status?:string;message?:string;error?:string;nextOffset?:number;parsed?:number;stats?:{mcq:number;essay:number;missingAnswer:number}};const message=d.message??d.error??"逐頁拆解中…";setNotice(message);onMessage?.(message);if(!r.ok)throw new Error(d.error??"拆解失敗");offset=d.nextOffset??offset;if(d.status==="completed"){const done=`${d.message}；選擇題 ${d.stats?.mcq??0}、申論／計算 ${d.stats?.essay??0}、缺答案 ${d.stats?.missingAnswer??0}`;setNotice(done);onMessage?.(done);return}await load()}throw new Error("拆解時間較長，已保留進度，可稍後繼續處理")}for(let i=0;i<30;i++){const r=await fetch("/api/accounting/documents/process",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,retry:retry&&i===0,reanalyze:reanalyze&&i===0})});const d=await r.json() as {status?:string;message?:string;error?:string};const message=d.message??d.error??"處理中…";setNotice(message);onMessage?.(message);await load();if(!r.ok)throw new Error(d.error??message);if(d.status==="completed")return;await new Promise(resolve=>setTimeout(resolve,2200))}throw new Error("索引仍在建立，已保留進度，可稍後繼續處理")}finally{setProcessingId(null);await load()}}
 async function expand(selected:File[]){const expanded:File[]=[];for(const file of selected){if(!file.name.toLowerCase().endsWith(".zip")){if(allowed.test(file.name))expanded.push(file);continue}const entries=unzipSync(new Uint8Array(await file.arrayBuffer()));for(const [path,bytes] of Object.entries(entries)){const name=path.split("/").pop()||"";if(!name||path.includes("__MACOSX")||path.split("/").some(part=>part.startsWith("."))||!allowed.test(name))continue;expanded.push(new File([new Uint8Array(bytes)],name,{type:mime(name)}))}}return expanded.slice(0,50)}
 async function choose(selected:File[]){try{const unpacked=await expand(selected);setFiles(unpacked);setBatch(unpacked.map(file=>({id:crypto.randomUUID(),name:file.name,size:file.size,status:"waiting",progress:0,message:"等待上傳"})));setNotice(unpacked.length?`已選取 ${unpacked.length} 本教材；可開始批次上傳。`:"沒有找到可處理的 PDF、Word 或 TXT。")}catch{setFiles([]);setBatch([]);setNotice("ZIP 無法解壓縮，請確認檔案未加密且格式正確。")}}
 async function uploadOne(file:File,row:BatchRow){const contentType=mime(file.name);updateBatch(row.id,{status:"uploading",message:"準備上傳"});const initResponse=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"init",fileName:file.name,contentType})}),init=await initResponse.json() as {key?:string;uploadId?:string;error?:string};if(!initResponse.ok||!init.key||!init.uploadId)throw new Error(init.error||"無法開始上傳");const chunkSize=5*1024*1024,parts:Array<{partNumber:number;etag:string}>=[];for(let start=0,partNumber=1;start<file.size;start+=chunkSize,partNumber++){const progress=Math.min(99,Math.round(start/file.size*100));updateBatch(row.id,{progress,message:`上傳中 ${progress}%`});const response=await fetch(`/api/documents/multipart?key=${encodeURIComponent(init.key)}&uploadId=${encodeURIComponent(init.uploadId)}&partNumber=${partNumber}`,{method:"PUT",headers:{"content-type":"application/octet-stream"},body:file.slice(start,Math.min(start+chunkSize,file.size))}),part=await response.json() as {partNumber?:number;etag?:string;error?:string};if(!response.ok||!part.partNumber||!part.etag)throw new Error(part.error||`第 ${partNumber} 段上傳失敗`);parts.push({partNumber:part.partNumber,etag:part.etag})}const completeResponse=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",key:init.key,uploadId:init.uploadId,parts,fileName:file.name,contentType,sizeBytes:file.size,examCategory:"accounting",subject,documentType:type})}),completed=await completeResponse.json() as {document?:{id:number};error?:string};if(!completeResponse.ok||!completed.document)throw new Error(completed.error||"無法完成文件上傳");updateBatch(row.id,{status:"processing",progress:100,message:"上傳完成，正在拆解與索引"});await process(completed.document.id,false,false,message=>updateBatch(row.id,{message}));updateBatch(row.id,{status:"completed",progress:100,message:"教材拆解與索引完成"})}
 async function upload(){if(!files.length){setNotice("請先選擇教材文件或 ZIP。");return}setBusy(true);const existing=new Set(docs.map(doc=>doc.name.toLowerCase())),rows=[...batch];let completed=0,failed=0,skipped=0;for(let index=0;index<files.length;index++){const file=files[index],row=rows[index];if(existing.has(file.name.toLowerCase())){updateBatch(row.id,{status:"skipped",message:"已有同名教材，已略過"});skipped++;continue}try{await uploadOne(file,row);existing.add(file.name.toLowerCase());completed++}catch(error){updateBatch(row.id,{status:"failed",message:error instanceof Error?error.message:"處理失敗"});failed++}}setBusy(false);await load();setFiles([]);setNotice(`批次完成：成功 ${completed} 本${skipped?`、略過 ${skipped} 本`:""}${failed?`、失敗 ${failed} 本`:""}。`)}
 async function recountWordQuizzes(){const targets=docs.filter(isWordQuiz);if(!targets.length){setNotice("目前沒有需要重新檢查的 Word 試卷。");return}setBusy(true);let completed=0,failed=0;for(const doc of targets){try{setNotice(`正在重新辨識 Word 題數：${doc.name}`);await process(doc.id,false,true,()=>undefined);completed++}catch{failed++}}setBusy(false);await load();setNotice(`Word 試卷題數檢查完成：成功 ${completed} 份${failed?`、失敗 ${failed} 份`:""}。`)}
 async function enableAllLunaSearch(){const targets=docs.filter(doc=>doc.processingStage==="completed"&&doc.vectorIndexed&&!doc.homepageSearchEnabled);if(!targets.length){setNotice(docs.some(doc=>doc.homepageSearchEnabled)?"目前所有可搜尋的教材都已允許 Luna 搜尋。":"目前沒有已完成索引、可開放給 Luna 搜尋的教材。");return}setBusy(true);let completed=0,failed=0;for(const doc of targets){setNotice(`正在開放 Luna 搜尋：${doc.name}`);try{const r=await fetch("/api/accounting/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,homepageSearchEnabled:true})});if(!r.ok)throw new Error();completed++}catch{failed++}}setBusy(false);await load();setNotice(`Luna 搜尋設定完成：已開放 ${completed} 份教材${failed?`、${failed} 份設定失敗`:""}。`)}
 async function toggle(doc:Doc){const r=await fetch("/api/accounting/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,homepageSearchEnabled:!doc.homepageSearchEnabled})});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error??"設定失敗");if(r.status===409)void process(doc.id);return}await load()}
 const tabs=<nav className="medtech-admin-tabs"><button className={tab==="members"?"active":""} onClick={()=>setTab("members")}>會員管理</button><button className={tab==="documents"?"active":""} onClick={()=>setTab("documents")}>文件上傳</button><button className={tab==="questions"?"active":""} onClick={()=>setTab("questions")}>文件題庫</button><button className={tab==="bank"?"active":""} onClick={()=>setTab("bank")}>題庫總覽</button></nav>;
 const header=<><header className="accounting-top"><a href="/accounting" className="accounting-brand"><span>中</span><div><b>中級會計管理後台</b><small>CONTENT ADMIN</small></div></a><nav><a href="/accounting">學生首頁</a></nav></header>{tabs}</>;
 if(tab!=="documents")return <main className="accounting-admin-page medtech-admin-page">{header}<section className="accounting-admin-hero"><span>中級會計 · 獨立資料管理</span><h1>{tab==="members"?"會員與帳號管理":tab==="questions"?"中會文件題庫":"中會題庫總覽"}</h1><p>只管理中級會計會員、教材與題目，不會混入醫檢或其他類科資料。</p></section>{tab==="members"?<AccountingMemberManager/>:tab==="questions"?<DocumentQuestionLibrary category="accounting"/>:<QuestionBank category="accounting"/>}</main>;
 return <main className="accounting-admin-page medtech-admin-page">{header}
 <section className="accounting-admin-hero"><span>中級會計 · 獨立教材空間</span><h1>教材上傳與自動拆解</h1><p>固定歸入中會類科；不會混入司律或醫檢師的教材與搜尋結果。</p></section>
 <section className="accounting-admin-panel"><h2>五本教材匯入順序</h2><div className="accounting-import-map">{presets.map(([name,role],i)=><article key={name}><b>{i+1}</b><div><h3>{name}</h3><p>{role}</p></div></article>)}</div></section>
 <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>批次上傳教材</h2><small>可一次選取多個 PDF、Word、TXT，或上傳 ZIP 自動解壓；每批最多 50 本。</small></div></div><div className="accounting-upload-form"><label>科目<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>用途<select value={type} onChange={e=>setType(e.target.value)}><option>核心教材</option><option>章節題庫</option><option>申論題庫</option><option>年度解題</option></select></label><label className="file">選擇教材／ZIP<input type="file" multiple accept=".pdf,.docx,.txt,.zip" onChange={e=>void choose(Array.from(e.target.files??[]))}/><span>{files.length?`已選取 ${files.length} 本教材`:"可多選檔案或選擇 ZIP"}</span></label><button disabled={busy||!files.length} onClick={()=>void upload()}>{busy?"批次處理中…":`上傳並自動處理${files.length?`（${files.length}）`:""}`}</button></div>{notice&&<p className="accounting-admin-notice">{notice}</p>}{batch.length>0&&<div className="data-batch-list">{batch.map(row=><article key={row.id} className={row.status}><div><b>{row.name}</b><small>{(row.size/1024/1024).toFixed(2)} MB</small></div><div className="data-batch-progress"><i style={{width:`${row.progress}%`}}/><span>{row.message}</span></div><strong>{row.status==="waiting"?"等待中":row.status==="uploading"?"上傳中":row.status==="processing"?"拆解中":row.status==="completed"?"已完成":row.status==="skipped"?"已略過":"失敗"}</strong></article>)}</div>}</section>
 <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>獨立 Word 選擇題庫</h2><small>前台來源：115年會計研究所班 中級會計學；檔名時間碼與小考次序只供後台辨識。</small></div><button disabled={busy} onClick={()=>void importWordBank()}>{busy?"匯入中…":wordBankCount===null?"匯入 Word 題庫":"重新匯入 Word 題庫"}</button></div>{wordBankCount!==null&&<p className="accounting-admin-notice">目前已匯入 {wordBankCount} 題，與舊 PDF 題庫分開保存。</p>}</section>
 <section className="accounting-admin-panel"><div className="accounting-admin-heading"><h2>中會教材清單</h2><div><a href="/accounting/admin/questions">查看拆解題庫</a><button disabled={busy||processingId!==null} onClick={()=>void enableAllLunaSearch()}>{busy?"設定中…":"全部允許 Luna 搜尋"}</button><button disabled={busy||processingId!==null} onClick={()=>void recountWordQuizzes()}>{busy?"檢查中…":"重新檢查 Word 題數"}</button><button onClick={()=>void load()}>重新整理</button></div></div><div className="accounting-document-list">{docs.map(doc=><article key={doc.id}><div><small>{doc.subject} · {doc.type}</small><h3>{doc.name}</h3><p>{(doc.sizeBytes/1024/1024).toFixed(2)} MB</p></div><div><b>{processingId===doc.id?"正在逐頁拆解…":doc.processingStage==="completed"?"處理完成":"處理中"}</b><p>{processingId===doc.id?(isWordQuiz(doc)?"正在核對 Word 表格中的完整題目與教師答案列…":doc.type==="核心教材"?"正在建立章節與觀念索引，請勿重複點擊":"正在辨識題號、合併跨頁題幹並分批入庫，請勿關閉頁面"):doc.error||doc.processingMessage}</p></div><div className="counts">{isWordQuiz(doc)?<b>{doc.questionCount}<small> 題目索引</small></b>:<><b>{doc.chapterCount}<small> 章</small></b>{doc.type==="核心教材"?<b><small>內容索引</small></b>:<b>{doc.questionCount}<small> 題庫草稿</small></b>}</>}</div><div className="actions">{doc.processingStage!=="completed"?<button disabled={processingId!==null} onClick={()=>void process(doc.id,doc.status==="failed")}>{processingId===doc.id?"處理中…":"繼續處理"}</button>:<button disabled={processingId!==null} onClick={()=>void process(doc.id,false,true)}>{processingId===doc.id?"逐頁拆解中…":isWordQuiz(doc)?"重新核對題數":doc.type==="核心教材"?"重新建立索引":"重新逐頁拆解並入庫"}</button>}{doc.type!=="核心教材"&&<a href={`/accounting/admin/questions`}>檢查內容</a>}<label><input type="checkbox" checked={doc.homepageSearchEnabled} onChange={()=>void toggle(doc)} disabled={!doc.vectorIndexed||processingId!==null}/>允許Luna 助教 搜尋</label></div></article>)}{!docs.length&&<p>正在讀取已上傳教材…</p>}</div></section></main>;
}
