import { and, desc, eq, gt } from "drizzle-orm";
import { activationCodes, medtechMemberEntitlements, memberExamAccess } from "../../../db/schema";
import { getActiveAiEntitlement, getAiPlan, grantAiAccess, publicAiAccess } from "../../../lib/ai-access";
import { MEDTECH_DEFAULT_PRODUCT_KEY } from "../../../lib/medtech-product-settings";
import { requireMember } from "../../../lib/member-auth";

async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value.trim().toUpperCase())))).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function state(auth:Exclude<Awaited<ReturnType<typeof requireMember>>, {error:Response}>){const now=new Date();const[plan,ai,[medtech]]=await Promise.all([getAiPlan(auth.db),getActiveAiEntitlement(auth.db,auth.member.id),auth.db.select().from(medtechMemberEntitlements).where(and(eq(medtechMemberEntitlements.memberId,auth.member.id),eq(medtechMemberEntitlements.status,"active"),gt(medtechMemberEntitlements.expiresAt,now))).orderBy(desc(medtechMemberEntitlements.expiresAt)).limit(1)]);return{plan,aiAccess:publicAiAccess(ai),medtechAccess:medtech?{active:true,productKey:medtech.productKey,startsAt:medtech.startsAt.toISOString(),expiresAt:medtech.expiresAt.toISOString(),source:medtech.source}:{active:false}}}

export async function GET(request:Request){const auth=await requireMember(request);if("error"in auth)return auth.error;return Response.json(await state(auth),{headers:{"cache-control":"no-store"}})}
export async function POST(request:Request){const auth=await requireMember(request);if("error"in auth)return auth.error;const body=await request.json()as{code?:string};const raw=String(body.code??"").trim().toUpperCase();if(!/^IB-(AI|MT)-[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(raw))return Response.json({error:"啟用碼格式不正確"},{status:400});const codeHash=await digest(raw),[code]=await auth.db.select().from(activationCodes).where(eq(activationCodes.codeHash,codeHash)).limit(1);if(!code)return Response.json({error:"找不到此啟用碼"},{status:404});if(code.status!=="unused")return Response.json({error:code.status==="redeemed"?"此啟用碼已兌換":"此啟用碼已停用或過期"},{status:409});if(code.redeemBy&&code.redeemBy<new Date()){await auth.db.update(activationCodes).set({status:"expired",updatedAt:new Date()}).where(eq(activationCodes.id,code.id));return Response.json({error:"此啟用碼已超過兌換期限"},{status:410})}
 if(code.benefitType==="ai_access"){if(await getActiveAiEntitlement(auth.db,auth.member.id))return Response.json({error:"目前已有使用中的 AI 方案，請於額度用完或到期後再兌換"},{status:409})}
 if(code.benefitType==="medtech_book"){const[active]=await auth.db.select().from(medtechMemberEntitlements).where(and(eq(medtechMemberEntitlements.memberId,auth.member.id),eq(medtechMemberEntitlements.productKey,code.productKey||MEDTECH_DEFAULT_PRODUCT_KEY),eq(medtechMemberEntitlements.status,"active"),gt(medtechMemberEntitlements.expiresAt,new Date()))).limit(1);if(active)return Response.json({error:"目前已有使用中的醫檢書籍方案，請於到期後再兌換"},{status:409})}
 const[claimed]=await auth.db.update(activationCodes).set({status:"redeemed",redeemedAt:new Date(),redeemedByMemberId:auth.member.id,updatedAt:new Date()}).where(and(eq(activationCodes.id,code.id),eq(activationCodes.status,"unused"))).returning();if(!claimed)return Response.json({error:"此啟用碼剛剛已被其他帳號兌換"},{status:409});
 try{if(code.benefitType==="ai_access")await grantAiAccess(auth.db,{memberId:auth.member.id,quota:code.quota||30,durationDays:code.durationDays,source:"activation_code",referenceId:code.id,note:`啟用碼 ••••-${code.last4}`});else if(code.benefitType==="medtech_book"){const now=new Date(),expiresAt=new Date(now.getTime()+code.durationDays*86400000),productKey=code.productKey||MEDTECH_DEFAULT_PRODUCT_KEY;await auth.db.insert(memberExamAccess).values({memberId:auth.member.id,examCategory:"medtech",status:"active",className:auth.member.className||"未分班"}).onConflictDoUpdate({target:[memberExamAccess.memberId,memberExamAccess.examCategory],set:{status:"active",updatedAt:now}});await auth.db.insert(medtechMemberEntitlements).values({memberId:auth.member.id,productKey,status:"active",source:"activation_code",startsAt:now,expiresAt,note:`免費啟用碼 ••••-${code.last4}`,updatedBy:"activation_code"}).onConflictDoUpdate({target:[medtechMemberEntitlements.memberId,medtechMemberEntitlements.productKey],set:{status:"active",source:"activation_code",startsAt:now,expiresAt,note:`免費啟用碼 ••••-${code.last4}`,updatedBy:"activation_code",updatedAt:now}})}else throw new Error("UNSUPPORTED_BENEFIT")}catch(error){await auth.db.update(activationCodes).set({status:"unused",redeemedAt:null,redeemedByMemberId:null,updatedAt:new Date()}).where(eq(activationCodes.id,code.id));throw error}
 return Response.json({ok:true,benefitType:code.benefitType,...await state(auth)})
}
