"use client";
import { useEffect, useMemo, useState } from "react";
import { formatTwd } from "../../lib/currency";
type Question = { id: number; year: string; examName: string; subject: string; questionNumber: string; stem: string; answerSource: string };
type SampleLevel = "basic" | "intermediate" | "advanced";
type Result = { analysis: string; model: string; modelId: string; reason: string; answerSource: string; sampleLabel?: string | null; usage: { inputTokens: number; outputTokens: number; cachedTokens: number; estimatedCostUsd: number; durationMs: number } };

function cleanAnalysisLine(line: string) {
  return line
    .replace(/^\s{0,3}#{1,6}\s*/u, "")
    .replace(/^\s*```(?:\w+)?\s*$/u, "")
    .replace(/\*\*([^*]+)\*\*/gu, "$1")
    .replace(/__([^_]+)__/gu, "$1")
    .replace(/(?<!\*)\*([^*\n]+)\*(?!\*)/gu, "$1")
    .replace(/(?<!_)_([^_\n]+)_(?!_)/gu, "$1")
    .replace(/`([^`]+)`/gu, "$1")
    .replace(/\*\*/gu, "")
    .trim();
}

export function IssuePractice() {
  const [questions, setQuestions] = useState<Question[]>([]); const [questionId, setQuestionId] = useState(0); const [subject, setSubject] = useState("全部"); const [year, setYear] = useState("全部"); const [studentIssues, setStudentIssues] = useState(""); const [sampleLevel, setSampleLevel] = useState<SampleLevel | null>(null); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [sampleLoading, setSampleLoading] = useState<SampleLevel | null>(null); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/issue-practice").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "讀取失敗"); setQuestions(data.questions || []); }).catch((reason) => setError(reason instanceof Error ? reason.message : "題庫讀取失敗")); }, []);
  const subjects = useMemo(() => ["全部", ...new Set(questions.map((item) => item.subject).filter(Boolean))], [questions]); const years = useMemo(() => ["全部", ...new Set(questions.map((item) => item.year).filter(Boolean))], [questions]);
  const filtered = questions.filter((item) => (subject === "全部" || item.subject === subject) && (year === "全部" || item.year === year)); const selected = questions.find((item) => item.id === questionId) ?? null;
  async function submit(model: "luna" | "sol") { if (!selected || studentIssues.trim().length < 10 || loading) return; setLoading(true); setError(""); const response = await fetch("/api/issue-practice", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ questionId: selected.id, studentIssues, model, sampleLevel }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.error || "AI 比對失敗"); setResult(data as Result); }
  async function loadSample(level: SampleLevel) { if (!selected || sampleLoading) return; setSampleLoading(level); setError(""); setResult(null); const response = await fetch("/api/issue-practice", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "sample", questionId: selected.id, sampleLevel: level }) }); const data = await response.json(); setSampleLoading(null); if (!response.ok) return setError(data.error || "測試擬答讀取失敗"); setStudentIssues(String(data.text || "")); setSampleLevel(level); }
  function choose(value: number) { setQuestionId(value); setStudentIssues(""); setSampleLevel(null); setResult(null); setError(""); }
  return <section className="student-issue-practice" aria-label="練爭點">
    <header className="student-issue-hero"><div><span>ISSUE SPOTTING PRACTICE</span><h2>練爭點</h2><p>先自己找，再讓 AI 依同題老師擬答逐項比對。重點不是背答案，而是看見自己漏在哪一層。</p></div><aside><b>{questions.length}</b><span>題已核對擬答</span><small>只顯示可可靠比對的題目</small></aside></header>
    <div className="student-issue-steps"><span className={selected ? "done" : "active"}><b>1</b> 選真題</span><span className={selected && !result ? "active" : result ? "done" : ""}><b>2</b> 寫爭點</span><span className={result ? "active" : ""}><b>3</b> 看比對</span></div>
    <section className="student-issue-picker"><div><label>科目<select value={subject} onChange={(event) => { setSubject(event.target.value); choose(0); }}>{subjects.map((item) => <option key={item}>{item}</option>)}</select></label><label>年度<select value={year} onChange={(event) => { setYear(event.target.value); choose(0); }}>{years.map((item) => <option key={item}>{item}</option>)}</select></label></div><label>歷屆題目<select value={questionId} onChange={(event) => choose(Number(event.target.value))}><option value={0}>{questions.length ? "請選擇一題" : "正在讀取題庫…"}</option>{filtered.map((item) => <option key={item.id} value={item.id}>{item.year}｜{item.subject}｜{item.examName || "司律二試"}第 {item.questionNumber} 題</option>)}</select></label></section>
    {selected ? <><article className="student-issue-question"><header><div><span>{selected.subject}</span><b>{selected.year}｜{selected.examName || "司律二試"}第 {selected.questionNumber} 題</b></div><small>本題已連結：{selected.answerSource || "老師參考擬答"}</small></header><p>{selected.stem}</p></article><section className="student-issue-answer"><header><div><span>YOUR ISSUE LIST</span><h3>你認為本題有哪些爭點？</h3></div><small>可依「行為人 → 行為 → 罪名／法律問題」逐行列出</small></header><div className="issue-sample-tools"><div><b>助教辨識力測試</b><span>帶入三種程度的測試擬答，檢查 Luna 是否正確判級與指出缺漏。</span></div><div>{([["basic","基礎擬答","明顯缺漏"],["intermediate","中等擬答","大致命中"],["advanced","高分擬答","完整有層次"]] as const).map(([level,label,note]) => <button type="button" className={sampleLevel === level ? "active" : ""} disabled={Boolean(sampleLoading)} onClick={() => void loadSample(level)} key={level}><b>{sampleLoading === level ? "載入中…" : label}</b><small>{note}</small></button>)}</div></div><textarea rows={10} value={studentIssues} onChange={(event) => { setStudentIssues(event.target.value); if (sampleLevel) setSampleLevel(null); }} placeholder={'例如：\n一、甲……是否成立……罪？\n二、乙……涉及何種總則爭點？\n三、甲、乙間是否成立共同正犯？'} /><footer><span>{studentIssues.trim().length} 字{sampleLevel ? ` · 測試樣本：${sampleLevel === "basic" ? "基礎" : sampleLevel === "intermediate" ? "中等" : "高分"}` : ""}</span><button type="button" onClick={() => void submit("luna")} disabled={loading || studentIssues.trim().length < 10}>{loading ? "AI 正在逐項比對…" : "送出給 Luna 助教比對"}</button></footer></section></> : <div className="student-issue-empty"><b>先選一題開始</b><span>題目不會立即顯示答案；請先完成自己的爭點清單。</span></div>}
    {error && <p className="student-issue-error">{error}</p>}
    {result && <section className="student-issue-result"><header><div><span>AI COMPARISON</span><h3>{result.model}的逐項分析</h3></div><b>已完成比對</b></header>{result.sampleLabel && <div className="issue-sample-verdict"><span>測試預期</span><b>{result.sampleLabel}</b><small>請核對下方「程度判定」是否一致；不一致代表助教分級仍需調整。</small></div>}<div className="student-issue-analysis">{result.analysis.split("\n").map((line, index) => { const cleanLine = cleanAnalysisLine(line); return cleanLine ? <p className={/^[一二三四五六]、/.test(cleanLine) ? "heading" : ""} key={index}>{cleanLine}</p> : <br key={index} />; })}</div><footer><div><b>此次對話使用 {result.model}</b><span>原因：{result.reason}</span><small>{result.modelId} · {(result.usage.inputTokens + result.usage.outputTokens).toLocaleString()} tokens · {result.usage.cachedTokens.toLocaleString()} cached · {(result.usage.durationMs / 1000).toFixed(1)} 秒 · 約 US$ {result.usage.estimatedCostUsd.toFixed(5)}／NT$ {formatTwd(result.usage.estimatedCostUsd)}</small></div>{result.model === "Luna 助教" && <button type="button" onClick={() => void submit("sol")} disabled={loading}>{loading ? "Sol 覆核中…" : "✦ 請 Sol 學霸再評斷"}</button>}</footer></section>}
  </section>;
}
