"use client";
import { FormEvent, useState } from "react";
type JudicialResult = { id: number; jid: string; court: string; year: string; caseType: string; caseNo: string; judgmentDate: string; title: string; fullText: string; excerpt: string };
function escapeRegExp(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function Highlight({ text, query }: { text: string; query: string }) { const term = query.trim(); if (term.length < 2) return <>{text}</>; const matcher = new RegExp(`(${escapeRegExp(term)})`, "gi"); return <>{text.split(matcher).map((part, index) => part.toLowerCase() === term.toLowerCase() ? <mark className="search-hit" key={index}>{part}</mark> : <span key={index}>{part}</span>)}</>; }
export function JudicialSearch({ onResultCount }: { onResultCount?: (count: number) => void }) {
  const [query, setQuery] = useState(""); const [court, setCourt] = useState(""); const [year, setYear] = useState("");
  const [results, setResults] = useState<JudicialResult[]>([]); const [expanded, setExpanded] = useState<number | null>(null);
  const [loading, setLoading] = useState(false); const [searched, setSearched] = useState(false); const [error, setError] = useState("");
  async function search(event?: FormEvent) { event?.preventDefault(); setLoading(true); setError(""); setSearched(true); try { const response = await fetch(`/api/judicial-search?q=${encodeURIComponent(query.trim())}&court=${encodeURIComponent(court.trim())}&year=${encodeURIComponent(year.trim())}`); const data = await response.json() as { results?: JudicialResult[]; error?: string }; if (!response.ok) throw new Error(data.error ?? "裁判搜尋失敗"); setResults(data.results ?? []); onResultCount?.((data.results ?? []).length); } catch (reason) { setResults([]); onResultCount?.(0); setError(reason instanceof Error ? reason.message : "裁判搜尋失敗"); } finally { setLoading(false); } }
  return <section className="legal-search-panel judicial-search-panel" aria-label="司法院裁判搜尋">
    <div className="legal-search-head"><div><p>JUDICIAL DECISION SEARCH</p><h2>司法院裁判搜尋</h2><span>搜尋已下載的司法院公開裁判；可用案號、法院或全文關鍵字查找。</span></div><strong>真實資料</strong></div>
    <form className="judicial-search-form" onSubmit={search}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="案號或關鍵字，例如：損害賠償、詐欺" aria-label="裁判關鍵字" /><input value={court} onChange={(e) => setCourt(e.target.value)} placeholder="法院（可不填）" aria-label="法院" /><input value={year} onChange={(e) => setYear(e.target.value)} inputMode="numeric" placeholder="年度" aria-label="裁判年度" /><button className="primary-btn" disabled={loading}>{loading ? "搜尋中…" : "搜尋裁判"}</button></form>
    <div className="judicial-search-hint"><span>目前搜尋的是已下載至平台的裁判，下載尚未完成時，結果會持續增加。</span><button type="button" onClick={async () => { setQuery(""); setCourt(""); setYear(""); setLoading(true); setSearched(true); const response = await fetch("/api/judicial-search"); const data = await response.json() as { results?: JudicialResult[] }; setResults(data.results ?? []); onResultCount?.((data.results ?? []).length); setLoading(false); }}>查看最近裁判</button></div>
    {error && <p className="legal-search-error">{error}</p>}{searched && !loading && !error && !results.length && <div className="legal-search-empty">目前下載的裁判中沒有相符結果，可縮短關鍵字或改用案號搜尋。</div>}
    <div className="judicial-result-list">{results.map((result) => <article className="judicial-result" key={result.id}><header><span>{result.court || "司法院裁判"}</span><div><h3><Highlight text={result.title} query={query} /></h3><small>{result.year}年度 {result.caseType}字第{result.caseNo}號 · {result.judgmentDate || "日期未載"}</small></div></header><p>{result.excerpt ? <Highlight text={result.excerpt} query={query} /> : "此筆官方下載資料目前僅有案件資訊，尚未附裁判全文。"}</p>{expanded === result.id && result.fullText && <section className="judicial-fulltext"><b>裁判全文</b><p><Highlight text={result.fullText} query={query} /></p></section>}<footer><span>資料來源：司法院裁判資料開放平臺</span><button type="button" disabled={!result.fullText} onClick={() => setExpanded(expanded === result.id ? null : result.id)}>{!result.fullText ? "尚無全文" : expanded === result.id ? "收合全文" : "查看全文"}</button></footer></article>)}</div>
  </section>;
}
