"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import styles from "./mcp-control.module.css";

type Knowledge = { id:string; title:string; category:string; content:string; sourceUrl:string; status:string; reviewNote:string };
type Enterprise = { id:string; name:string; code:string; status:string; monthlyCallLimit:number; notes:string; accountCount:number; monthCalls:number };
type Account = { id:string; email:string; displayName:string; accountType:string; enterpriseId:string|null; enterpriseName:string|null; status:string; dailyCallLimit:number; scopesJson:string; notes:string; todayCalls:number };
type SiteAccount = { id:number; memberId:number; email:string; displayName:string; status:string; createdAt:number; updatedAt:number; lastSeenAt:number|null; todayCalls:number };
type Data = { knowledge:Knowledge[]; enterprises:Enterprise[]; accounts:Account[]; siteAccounts:SiteAccount[]; usage:{calls:number;activeUsers:number;failures:number} };

const blankKnowledge = { id:"", title:"", category:"一般", content:"", sourceUrl:"", status:"draft", reviewNote:"" };
const blankEnterprise = { id:"", name:"", code:"", status:"active", monthlyCallLimit:10000, notes:"" };
const blankAccount = { id:"", email:"", displayName:"", accountType:"individual", enterpriseId:"", status:"active", dailyCallLimit:100, scopes:["resources.read","progress.read"], notes:"" };

export default function McpControlClient() {
  const [tab,setTab]=useState<"knowledge"|"siteAccounts"|"accounts"|"enterprises">("knowledge");
  const [data,setData]=useState<Data|null>(null);
  const [notice,setNotice]=useState("");
  const [knowledge,setKnowledge]=useState(blankKnowledge);
  const [enterprise,setEnterprise]=useState(blankEnterprise);
  const [account,setAccount]=useState(blankAccount);
  const [siteAccount,setSiteAccount]=useState<SiteAccount|null>(null);
  const load=useCallback(async()=>{const r=await fetch("/api/mcp-control",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"讀取失敗");setData(j);},[]);
  useEffect(()=>{
    const controller=new AbortController();
    fetch("/api/mcp-control",{cache:"no-store",signal:controller.signal})
      .then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"讀取失敗");return j;})
      .then(j=>setData(j))
      .catch(e=>{if(!controller.signal.aborted)setNotice(e instanceof Error?e.message:"讀取失敗");});
    return ()=>controller.abort();
  },[]);
  async function save(event:FormEvent,payload:Record<string,unknown>){event.preventDefault();setNotice("儲存中…");const r=await fetch("/api/mcp-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){setNotice(j.error||"儲存失敗");return;}setNotice("已儲存");await load();}
  return <main className={styles.page}>
    <header><div><span>智</span><div><strong>MCP 管控中心</strong><small>獨立管理資料、會員與企業</small></div></div><Link href="/">回到對話</Link></header>
    <section className={styles.summary}><article><b>{data?.knowledge.length??0}</b><span>知識資料</span></article><article><b>{data?.siteAccounts.filter(item=>item.status==="active").length??0}/10</b><span>AnglePedia 網站測試</span></article><article><b>{data?.siteAccounts.filter(item=>item.status==="pending").length??0}</b><span>網站候補申請</span></article><article><b>{data?.accounts.filter(item=>item.id.startsWith("beta_auto_")).length??0}/10</b><span>GPT MCP 測試</span></article><article><b>{data?.accounts.filter(item=>item.status==="pending").length??0}</b><span>MCP 待審核</span></article><article><b>{data?.usage.calls??0}</b><span>近 30 天 MCP 呼叫</span></article></section>
    <nav><button className={tab==="knowledge"?styles.active:""} onClick={()=>setTab("knowledge")}>資料編輯與檢審</button><button className={tab==="siteAccounts"?styles.active:""} onClick={()=>setTab("siteAccounts")}>網站測試會員</button><button className={tab==="accounts"?styles.active:""} onClick={()=>setTab("accounts")}>GPT MCP 會員</button><button className={tab==="enterprises"?styles.active:""} onClick={()=>setTab("enterprises")}>企業管控</button></nav>
    {notice&&<p className={styles.notice}>{notice}</p>}
    {tab==="knowledge"&&<section className={styles.workspace}><form onSubmit={e=>void save(e,{action:"save_knowledge",...knowledge})}><h2>{knowledge.id?"編輯資料":"新增資料"}</h2><label>標題<input value={knowledge.title} onChange={e=>setKnowledge({...knowledge,title:e.target.value})}/></label><div className={styles.row}><label>分類<input value={knowledge.category} onChange={e=>setKnowledge({...knowledge,category:e.target.value})}/></label><label>狀態<select value={knowledge.status} onChange={e=>setKnowledge({...knowledge,status:e.target.value})}><option value="draft">草稿</option><option value="review">待檢審</option><option value="published">已通過</option><option value="rejected">退回</option></select></label></div><label>拆解內容<textarea rows={11} value={knowledge.content} onChange={e=>setKnowledge({...knowledge,content:e.target.value})}/></label><label>來源網址<input value={knowledge.sourceUrl} onChange={e=>setKnowledge({...knowledge,sourceUrl:e.target.value})}/></label><label>檢審意見<textarea rows={3} value={knowledge.reviewNote} onChange={e=>setKnowledge({...knowledge,reviewNote:e.target.value})}/></label><div className={styles.actions}><button type="button" onClick={()=>setKnowledge(blankKnowledge)}>清空</button><button type="submit">儲存</button></div></form><div className={styles.list}>{data?.knowledge.map(item=><button key={item.id} onClick={()=>setKnowledge(item)}><span className={styles[item.status]}>{item.status==="published"?"已通過":item.status==="review"?"待檢審":item.status==="rejected"?"退回":"草稿"}</span><strong>{item.title}</strong><small>{item.category}</small></button>)}</div></section>}
    {tab==="siteAccounts"&&<section className={styles.workspace}><form onSubmit={e=>siteAccount&&void save(e,{action:"save_site_account",id:siteAccount.id,status:siteAccount.status})}><h2>AnglePedia 網站測試會員</h2>{siteAccount?<><label>Email<input value={siteAccount.email} disabled/></label><label>名稱<input value={siteAccount.displayName||"未提供"} disabled/></label><label>狀態<select value={siteAccount.status} onChange={e=>setSiteAccount({...siteAccount,status:e.target.value})}><option value="active">啟用</option><option value="pending">待審核</option><option value="paused">停用</option></select></label><p className={styles.accountMeta}>今日 AI 使用 {siteAccount.todayCalls} 次<br/>最近連線：{siteAccount.lastSeenAt?new Date(siteAccount.lastSeenAt*1000).toLocaleString("zh-TW"):"尚無紀錄"}</p><div className={styles.actions}><button type="submit">儲存狀態</button></div></>:<p className={styles.emptyHint}>從右側選擇會員，即可開通或停用。</p>}</form><div className={styles.list}>{data?.siteAccounts.map(item=><button key={item.id} onClick={()=>setSiteAccount(item)}><span className={item.status==="active"?styles.published:item.status==="pending"?styles.review:styles.rejected}>{item.status==="active"?"啟用":item.status==="pending"?"待審核":"停用"}</span><strong>{item.displayName||item.email}</strong><small>{item.email}・今日 AI {item.todayCalls} 次・{item.lastSeenAt?`最近 ${new Date(item.lastSeenAt*1000).toLocaleString("zh-TW")}`:"尚未使用"}</small></button>)}</div></section>}
    {tab==="accounts"&&<section className={styles.workspace}><form onSubmit={e=>void save(e,{action:"save_account",...account})}><h2>{account.id?"編輯會員":"新增 MCP 會員"}</h2><label>Email<input type="email" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/></label><label>名稱<input value={account.displayName} onChange={e=>setAccount({...account,displayName:e.target.value})}/></label><div className={styles.row}><label>類型<select value={account.accountType} onChange={e=>setAccount({...account,accountType:e.target.value})}><option value="individual">個人</option><option value="enterprise">企業</option></select></label><label>狀態<select value={account.status} onChange={e=>setAccount({...account,status:e.target.value})}><option value="active">啟用</option><option value="pending">待審核</option><option value="paused">停用</option></select></label></div>{account.accountType==="enterprise"&&<label>所屬企業<select value={account.enterpriseId} onChange={e=>setAccount({...account,enterpriseId:e.target.value})}><option value="">請選擇</option>{data?.enterprises.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>每日呼叫上限<input type="number" value={account.dailyCallLimit} onChange={e=>setAccount({...account,dailyCallLimit:Number(e.target.value)})}/></label><fieldset><legend>可使用的 MCP 能力</legend>{[["resources.read","搜尋資料"],["progress.read","讀取進度"],["progress.write","保存打卡"]].map(([scope,label])=><label key={scope}><input type="checkbox" checked={account.scopes.includes(scope)} onChange={e=>setAccount({...account,scopes:e.target.checked?[...account.scopes,scope]:account.scopes.filter(item=>item!==scope)})}/>{label}</label>)}</fieldset><label>備註<textarea rows={4} value={account.notes} onChange={e=>setAccount({...account,notes:e.target.value})}/></label><div className={styles.actions}><button type="button" onClick={()=>setAccount(blankAccount)}>清空</button><button type="submit">儲存</button></div></form><div className={styles.list}>{data?.accounts.map(item=><button key={item.id} onClick={()=>setAccount({...item,enterpriseId:item.enterpriseId||"",scopes:JSON.parse(item.scopesJson||"[]")})}><span className={item.status==="active"?styles.published:item.status==="pending"?styles.review:styles.rejected}>{item.status==="active"?"啟用":item.status==="pending"?"待審核":"停用"}</span><strong>{item.displayName||item.email}</strong><small>{item.enterpriseName||"個人"}・今日 {item.todayCalls}/{item.dailyCallLimit} 次</small></button>)}</div></section>}
    {tab==="enterprises"&&<section className={styles.workspace}><form onSubmit={e=>void save(e,{action:"save_enterprise",...enterprise})}><h2>{enterprise.id?"編輯企業":"新增企業"}</h2><label>企業名稱<input value={enterprise.name} onChange={e=>setEnterprise({...enterprise,name:e.target.value})}/></label><label>企業代碼<input value={enterprise.code} onChange={e=>setEnterprise({...enterprise,code:e.target.value})}/></label><div className={styles.row}><label>狀態<select value={enterprise.status} onChange={e=>setEnterprise({...enterprise,status:e.target.value})}><option value="active">啟用</option><option value="paused">停用</option></select></label><label>每月呼叫上限<input type="number" value={enterprise.monthlyCallLimit} onChange={e=>setEnterprise({...enterprise,monthlyCallLimit:Number(e.target.value)})}/></label></div><label>備註<textarea rows={4} value={enterprise.notes} onChange={e=>setEnterprise({...enterprise,notes:e.target.value})}/></label><div className={styles.actions}><button type="button" onClick={()=>setEnterprise(blankEnterprise)}>清空</button><button type="submit">儲存</button></div></form><div className={styles.list}>{data?.enterprises.map(item=><button key={item.id} onClick={()=>setEnterprise(item)}><span className={item.status==="active"?styles.published:styles.rejected}>{item.status==="active"?"啟用":"停用"}</span><strong>{item.name}</strong><small>{item.accountCount} 位會員・本月 {item.monthCalls}/{item.monthlyCallLimit} 次</small></button>)}</div></section>}
  </main>;
}
