"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type ResponseRow = { id: number; comparisonId: number; label: string; model: string; text: string; error?: string | null; inputTokens: number; outputTokens: number; durationMs: number; estimatedCostUsdMicros: number };
type Rating = { responseId: number; score: number; note: string };
type Run = { id: number; promptText: string; createdAt: string; meta: { subject?: string; selected?: string[] }; responses: ResponseRow[]; ratings: Rating[] };
type EssayQuestion = { id: number; year: string; subject: string; questionNumber: string; stem: string; hasTeacherAnswer?: boolean; answerSource?: string };
type ModelKey = "sol" | "terra" | "sonnet" | "opus" | "gemini" | "deepseek" | "glm" | "kimi";
const vendors: Array<{ name: string; models: Array<{ key: ModelKey; label: string }> }> = [
  { name: "OpenAI", models: [{ key: "sol", label: "Sol" }, { key: "terra", label: "Terra" }] },
  { name: "Anthropic", models: [{ key: "opus", label: "Claude Opus 5" }, { key: "sonnet", label: "Claude Sonnet 5" }] },
  { name: "Google", models: [{ key: "gemini", label: "Gemini 3.6 Flash｜Medium" }] },
  { name: "DeepSeek", models: [{ key: "deepseek", label: "DeepSeek V4-Pro" }] },
  { name: "智譜 AI", models: [{ key: "glm", label: "GLM-5.2" }] },
  { name: "Moonshot AI／月之暗面", models: [{ key: "kimi", label: "Kimi K3" }] },
];
const dimensions = [{ key: "coverage", label: "爭點完整度" }, { key: "accuracy", label: "法律精準度" }, { key: "facts", label: "事實對應度" }, { key: "priority", label: "得分排序" }] as const;

export default function IssueLab() {
  const [runs, setRuns] = useState<Run[]>([]); const [activeId, setActiveId] = useState<number | null>(null); const [prompt, setPrompt] = useState(""); const [subject, setSubject] = useState("刑法");
  const [questions, setQuestions] = useState<EssayQuestion[]>([]); const [questionYear, setQuestionYear] = useState("114"); const [questionId, setQuestionId] = useState(""); const [questionScope, setQuestionScope] = useState("完整刑法題"); const [questionLoading, setQuestionLoading] = useState(true);
  const [selected, setSelected] = useState<ModelKey[]>(["sol", "opus", "gemini", "kimi"]); const [running, setRunning] = useState(false); const [error, setError] = useState(""); const [revealed, setRevealed] = useState(false); const [status, setStatus] = useState("");
  const [drafts, setDrafts] = useState<Record<number, { coverage: number; accuracy: number; facts: number; priority: number; note: string }>>({});
  async function load(preferId?: number) { const response = await fetch("/api/issue-lab"); const result = await response.json() as { runs?: Run[]; error?: string }; if (!response.ok) throw new Error(result.error || "讀取失敗"); setRuns(result.runs || []); setActiveId(preferId ?? result.runs?.[0]?.id ?? null); }
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "讀取失敗")); void fetch("/api/practice?type=essay&list=1").then(async (response) => { const result = await response.json() as { questions?: EssayQuestion[]; error?: string }; if (!response.ok) throw new Error(result.error || "真題讀取失敗"); setQuestions((result.questions || []).filter((item) => /刑法/.test(item.subject) && ["109", "110", "111", "112", "113", "114"].includes(item.year))); }).catch((e) => setError(e instanceof Error ? e.message : "真題讀取失敗")).finally(() => setQuestionLoading(false)); }, []);
  const active = runs.find((run) => run.id === activeId) || null; const responses = active?.responses || [];
  const totalCost = useMemo(() => responses.reduce((sum, row) => sum + row.estimatedCostUsdMicros / 1e6, 0), [responses]);
  function toggle(key: ModelKey) { setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]); }
  const yearQuestions = questions.filter((item) => item.year === questionYear);
  function chooseQuestion(value: string) { setQuestionId(value); const question = questions.find((item) => item.id === Number(value)); if (!question) return; setSubject("刑法"); setPrompt(question.stem); setStatus(`${question.year} 年第 ${question.questionNumber} 題已帶入；可直接測試，或在下方調整題目範圍。`); }
  async function start() { setRunning(true); setError(""); setStatus(`正在讓 ${selected.length} 個模型同時抓爭點…`); setRevealed(false); const response = await fetch("/api/issue-lab", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt, subject, models: selected }) }); const result = await response.json() as { comparisonId?: number; error?: string }; setRunning(false); if (!response.ok || !result.comparisonId) return setError(result.error || "測試失敗"); await load(result.comparisonId); setStatus("模型都已完成；建議先匿名評分，再揭曉模型。"); }
  async function rate(row: ResponseRow) { const draft = drafts[row.id]; if (!draft) return; const response = await fetch("/api/issue-lab", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "rate", comparisonId: row.comparisonId, responseId: row.id, scores: draft, note: draft.note }) }); const result = await response.json() as { error?: string }; if (!response.ok) return setError(result.error || "評分失敗"); await load(activeId || undefined); setStatus("這個模型的評分已保存。"); }
  async function copyPack() { if (!active) return; const text = [`【司律備考｜爭點辨識模型評測包】`, `科目：${active.meta.subject || "綜合"}`, `題目：${active.promptText}`, `評測要求：請比較各模型是否完整、精準地辨識爭點，是否對應題示事實、排序得當，並指出遺漏、誤抓或過度延伸之處。`, ...responses.map((row, index) => `\n【模型 ${String.fromCharCode(65 + index)}｜${row.label}｜${row.model}】\n${row.text || `呼叫失敗：${row.error}`}`)].join("\n"); await navigator.clipboard.writeText(text); setStatus("評測包已複製，可以直接貼到 ChatGPT 給我評測；網站不會增加評審成本。"); }
  return <main className="issue-lab-shell">
    <header className="model-lab-top"><Link href="/" className="model-lab-brand"><span>爭</span><div><b>爭點辨識模型擂台</b><small>同題多模型 · 匿名評分 · Kimi K3</small></div></Link><nav><Link href="/model-lab">50 題單模型測試</Link><Link href="/">回到司律備考</Link></nav></header>
    <section className="issue-lab-hero"><div><span>ISSUE SPOTTING ARENA</span><h1>同一題，誰抓爭點最準？</h1><p>模型只做爭點辨識，不寫完整擬答。先匿名看答案、人工評分，再揭曉模型。</p></div><aside><b>{selected.length}</b><span>個模型同場測試</span><small>API 來源：TeamoRouter</small></aside></section>
    <section className="issue-lab-layout">
      <aside className="issue-history"><header><b>歷次測試</b><span>{runs.length} 筆</span></header>{runs.map((run) => <button key={run.id} className={run.id === activeId ? "active" : ""} onClick={() => { setActiveId(run.id); setRevealed(false); }}><b>{run.meta.subject || "綜合"}｜{run.promptText.slice(0, 24)}…</b><small>{new Date(run.createdAt).toLocaleString("zh-TW", { hour12: false })} · {run.responses.length} 模型</small></button>)}</aside>
      <div className="issue-workspace">
        <section className="issue-setup"><div className="issue-setup-head"><div><span>NEW TEST</span><h2>建立一場爭點辨識測試</h2></div><div className="issue-source-badge">司律二試｜刑法</div></div><div className="issue-question-picker"><header><div><b>從司律二試刑法真題挑選</b><small>目前先收錄 109～114 年；只顯示站內已匯入並發布的真題</small></div><button type="button" onClick={() => { setQuestionId(""); setPrompt(""); setStatus("已切換為自行貼題。"); }}>自行貼題</button></header><div><label>年度<select value={questionYear} onChange={(e) => { setQuestionYear(e.target.value); setQuestionId(""); }}>{["114", "113", "112", "111", "110", "109"].map((year) => <option key={year}>{year}</option>)}</select></label><label className="issue-question-select">題號／小題<select value={questionId} onChange={(e) => chooseQuestion(e.target.value)} disabled={questionLoading || !yearQuestions.length}><option value="">{questionLoading ? "讀取真題中…" : yearQuestions.length ? "請選擇題目" : "本年度尚無已發布刑法題"}</option>{yearQuestions.map((item) => <option key={item.id} value={item.id}>第 {item.questionNumber} 題{item.hasTeacherAnswer ? "｜已有老師擬答" : ""}</option>)}</select></label><label>測試範圍<select value={questionScope} onChange={(e) => setQuestionScope(e.target.value)}><option>完整刑法題</option><option>指定小題</option></select></label></div>{questionId && <p>已選：{questionYear} 年第 {questions.find((item) => item.id === Number(questionId))?.questionNumber} 題 · {questionScope}。選「指定小題」時，可在下方刪除不測的段落。</p>}</div><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={8} placeholder="可從上方選擇司律二試刑法真題，或自行貼上完整題目。模型會依相同提示整理核心爭點、觸發事實、隱藏爭點、干擾項與待補事實。" /><div className="issue-model-groups">{vendors.map((vendor) => <fieldset key={vendor.name}><legend>{vendor.name}</legend>{vendor.models.map((model) => <label key={model.key} className={selected.includes(model.key) ? "selected" : ""}><input type="checkbox" checked={selected.includes(model.key)} onChange={() => toggle(model.key)} /><span>{model.label}</span></label>)}</fieldset>)}</div><footer><small>至少選 2 個；每個候選模型各產生一次 API 成本，外部評測不另計費。</small><button onClick={() => void start()} disabled={running || selected.length < 2 || prompt.trim().length < 30}>{running ? "模型辨識中…" : `開始 ${selected.length} 模型匿名比較`}</button></footer></section>
        {error && <p className="issue-error">{error}</p>}{status && <p className="issue-status">{status}</p>}
        {active && <section className="issue-results"><header><div><span>BLIND RESULTS</span><h2>{active.meta.subject}｜本題模型回答</h2><p>{active.promptText}</p></div><div><button onClick={() => setRevealed((value) => !value)}>{revealed ? "隱藏模型名稱" : "揭曉模型"}</button><button onClick={() => void copyPack()}>複製到 ChatGPT 評測</button><small>{responses.reduce((sum, row) => sum + row.inputTokens + row.outputTokens, 0).toLocaleString()} tokens · 約 NT$ {(totalCost * 32.5).toFixed(2)}</small></div></header><div className="issue-response-grid">{responses.map((row, index) => { const prior = active.ratings.find((rating) => rating.responseId === row.id); const draft = drafts[row.id] || { coverage: 0, accuracy: 0, facts: 0, priority: 0, note: "" }; return <article className="issue-response-card" key={row.id}><header><span>模型 {String.fromCharCode(65 + index)}</span><div><b>{revealed ? row.label : "匿名候選模型"}</b><small>{revealed ? row.model : "評分後再揭曉"}</small></div>{prior ? <strong>{prior.score} 分</strong> : null}</header>{row.error ? <p className="issue-model-error">呼叫失敗：{row.error}</p> : <pre>{row.text}</pre>}<div className="issue-metrics"><span>{row.inputTokens + row.outputTokens} tokens</span><span>{(row.durationMs / 1000).toFixed(1)} 秒</span><span>NT$ {(row.estimatedCostUsdMicros / 1e6 * 32.5).toFixed(3)}</span></div>{!row.error && <div className="issue-rubric">{dimensions.map((dimension) => <label key={dimension.key}><span>{dimension.label}</span><select value={draft[dimension.key]} onChange={(e) => setDrafts((current) => ({ ...current, [row.id]: { ...draft, [dimension.key]: Number(e.target.value) } }))}><option value={0}>評分</option>{[1,2,3,4,5].map((score) => <option key={score} value={score}>{score}</option>)}</select></label>)}<textarea rows={2} value={draft.note} onChange={(e) => setDrafts((current) => ({ ...current, [row.id]: { ...draft, note: e.target.value } }))} placeholder="遺漏或誤抓的爭點（選填）" /><button onClick={() => void rate(row)} disabled={dimensions.some((dimension) => !draft[dimension.key])}>{prior ? "再存一次評分" : "保存評分"}</button></div>}</article>; })}</div></section>}
      </div>
    </section>
  </main>;
}
