"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type ResponseRow = { id: number; comparisonId: number; label: string; model: string; text: string; error?: string | null; inputTokens: number; outputTokens: number; durationMs: number; estimatedCostUsdMicros: number };
type Rating = { responseId: number; score: number; note: string; feedbackType: string; createdAt?: string };
type Run = { id: number; promptText: string; createdAt: string; meta: { subject?: string; selected?: string[]; gateways?: string[]; evidenceTest?: boolean }; responses: ResponseRow[]; ratings: Rating[] };
type EssayQuestion = { id: number; year: string; examName?: string; subject: string; questionNumber: string; stem: string; hasTeacherAnswer?: boolean; answerSource?: string };
type ModelKey = "luna" | "sol" | "terra" | "sonnet" | "opus" | "gemini" | "deepseek" | "glm" | "kimi";
const vendors: Array<{ name: string; models: Array<{ key: ModelKey; label: string }> }> = [
  { name: "OpenAI", models: [{ key: "luna", label: "Luna" }, { key: "sol", label: "Sol" }, { key: "terra", label: "Terra" }] },
  { name: "Anthropic", models: [{ key: "opus", label: "Claude Opus 5" }, { key: "sonnet", label: "Claude Sonnet 5" }] },
  { name: "Google", models: [{ key: "gemini", label: "Gemini 3.6 Flash｜Medium" }] },
  { name: "DeepSeek", models: [{ key: "deepseek", label: "DeepSeek V4-Pro" }] },
  { name: "智譜 AI", models: [{ key: "glm", label: "GLM-5.2" }] },
  { name: "Moonshot AI／月之暗面", models: [{ key: "kimi", label: "Kimi K3" }] },
];
export default function IssueLab() {
  const [runs, setRuns] = useState<Run[]>([]); const [activeId, setActiveId] = useState<number | null>(null); const [prompt, setPrompt] = useState(""); const [subject, setSubject] = useState("刑法");
  const [questions, setQuestions] = useState<EssayQuestion[]>([]); const [questionYear, setQuestionYear] = useState("114"); const [questionId, setQuestionId] = useState(""); const [questionScope, setQuestionScope] = useState("完整刑法題"); const [questionLoading, setQuestionLoading] = useState(true);
  const [selected, setSelected] = useState<ModelKey[]>(["sol"]); const [repetitions, setRepetitions] = useState<1 | 3 | 5>(1); const [running, setRunning] = useState(false); const [error, setError] = useState(""); const [revealed, setRevealed] = useState(false); const [status, setStatus] = useState("");
  const [gateways, setGateways] = useState<Array<"direct" | "teamorouter">>(["teamorouter"]); const [evidenceTest, setEvidenceTest] = useState(false);
  const [review, setReview] = useState(""); const [savingReview, setSavingReview] = useState(false); const [retrying, setRetrying] = useState<number | null>(null);
  async function load(preferId?: number) { const response = await fetch("/api/issue-lab"); const result = await response.json() as { runs?: Run[]; error?: string }; if (!response.ok) throw new Error(result.error || "讀取失敗"); setRuns(result.runs || []); setActiveId(preferId ?? result.runs?.[0]?.id ?? null); }
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "讀取失敗")); void fetch("/api/practice?type=essay&list=1").then(async (response) => { const result = await response.json() as { questions?: EssayQuestion[]; error?: string }; if (!response.ok) throw new Error(result.error || "真題讀取失敗"); setQuestions((result.questions || []).filter((item) => /刑法/.test(item.subject) && ["109", "110", "111", "112", "113", "114"].includes(item.year))); }).catch((e) => setError(e instanceof Error ? e.message : "真題讀取失敗")).finally(() => setQuestionLoading(false)); }, []);
  const active = runs.find((run) => run.id === activeId) || null; const responses = active?.responses || [];
  const savedReview = active?.ratings.filter((rating) => rating.feedbackType === "issue-unified-review").at(-1)?.note || "";
  const totalCost = useMemo(() => responses.reduce((sum, row) => sum + row.estimatedCostUsdMicros / 1e6, 0), [responses]);
  function toggle(key: ModelKey) { setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]); }
  const yearQuestions = questions.filter((item) => item.year === questionYear);
  function chooseQuestion(value: string) { setQuestionId(value); const question = questions.find((item) => item.id === Number(value)); if (!question) return; setSubject("刑法"); setPrompt(question.stem); if (!question.hasTeacherAnswer) setEvidenceTest(false); setStatus(`${question.year} 年第 ${question.questionNumber} 題已帶入；${question.hasTeacherAnswer ? "可啟用『有擬答／無擬答』A/B 測試。" : "本題尚無老師擬答，只能測試題目本身。"}`); }
  function toggleGateway(value: "direct" | "teamorouter") { setGateways((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function start() { const attempts = selected.length === 1 && gateways.length === 1 && !evidenceTest ? repetitions : 1; setRunning(true); setError(""); const resultCount = selected.length * gateways.length * (evidenceTest ? 2 : 1); setStatus(evidenceTest ? `正在執行同題擬答 A/B 測試（共 ${resultCount} 組）…` : resultCount > 1 ? `正在執行 ${resultCount} 組來源／模型對照…` : "正在執行單題爭點辨識…"); setRevealed(false); const response = await fetch("/api/issue-lab", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt, subject, models: selected, gateways, evidenceTest, questionId: questionId ? Number(questionId) : undefined, repetitions: attempts }) }); const result = await response.json() as { comparisonId?: number; error?: string }; setRunning(false); if (!response.ok || !result.comparisonId) return setError(result.error || "測試失敗"); await load(result.comparisonId); setStatus(evidenceTest ? "A/B 回覆已保存；請比較同一模型在取得老師擬答前後的爭點完整度與法條精準度。" : selected.length === 1 && attempts > 1 ? `同一模型 ${attempts} 次回覆已保存，可檢查核心爭點是否穩定。` : "模型回覆已結束；請查看完成、截斷或失敗狀態。"); }
  async function saveReview() { if (!active) return; const value = (review || savedReview).trim(); if (!value) return; setSavingReview(true); const response = await fetch("/api/issue-lab", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "save-review", comparisonId: active.id, review: value }) }); const result = await response.json() as { error?: string }; setSavingReview(false); if (!response.ok) return setError(result.error || "評測保存失敗"); await load(active.id); setStatus("本輪統一評測內容已保存。"); }
  async function retry(row: ResponseRow) { setRetrying(row.id); setError(""); const response = await fetch("/api/issue-lab", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "retry", comparisonId: row.comparisonId, responseId: row.id }) }); const result = await response.json() as { error?: string }; setRetrying(null); if (!response.ok) return setError(result.error || "重試失敗"); await load(row.comparisonId); setStatus(`${row.label} 已重試，請查看最新狀態。`); }
  async function copyPack() { if (!active) return; const text = [`【司律備考｜爭點辨識模型評測包】`, `科目：${active.meta.subject || "綜合"}`, `題目：${active.promptText}`, `評測要求：請比較各模型是否完整、精準地辨識爭點，是否對應題示事實、排序得當，並指出遺漏、誤抓或過度延伸之處。`, ...responses.map((row, index) => `\n【模型 ${String.fromCharCode(65 + index)}｜${row.label}｜${row.model}】\n${row.text || `呼叫失敗：${row.error}`}`)].join("\n"); await navigator.clipboard.writeText(text); setStatus("評測包已複製，可以直接貼到 ChatGPT 給我評測；網站不會增加評審成本。"); }
  return <main className="issue-lab-shell">
    <header className="model-lab-top"><Link href="/law" className="model-lab-brand"><span>爭</span><div><b>爭點辨識模型擂台</b><small>同題多模型 · 匿名評分 · Kimi K3</small></div></Link><nav><Link href="/model-lab">50 題單模型測試</Link><Link href="/law">回到司律備考</Link></nav></header>
    <section className="issue-lab-hero"><div><span>ISSUE SPOTTING ARENA</span><h1>{evidenceTest ? "同一模型，有擬答會差多少？" : selected.length === 1 ? "單一模型，也能完整測試" : "同一題，誰抓爭點最準？"}</h1><p>同題、同模型、同提示詞，分離比較 API 來源與老師擬答檢索效果。</p></div><aside><b>{selected.length * gateways.length * (evidenceTest ? 2 : 1)}</b><span>組實際回答</span><small>{gateways.map((item) => item === "direct" ? "原廠 API" : "TeamoRouter").join("＋")}</small></aside></section>
    <section className="issue-lab-layout">
      <aside className="issue-history"><header><b>歷次測試</b><span>{runs.length} 筆</span></header>{runs.map((run) => <button key={run.id} className={run.id === activeId ? "active" : ""} onClick={() => { setActiveId(run.id); setRevealed(false); }}><b>{run.meta.subject || "綜合"}｜{run.promptText.slice(0, 24)}…</b><small>{new Date(run.createdAt).toLocaleString("zh-TW", { hour12: false })} · {run.responses.length} 模型</small></button>)}</aside>
      <div className="issue-workspace">
        <section className="issue-setup"><div className="issue-setup-head"><div><span>NEW TEST</span><h2>建立一場爭點辨識測試</h2></div><div className="issue-source-badge">司律二試｜刑法</div></div><div className="issue-question-picker"><header><div><b>從司律二試刑法真題挑選</b><small>目前先收錄 109～114 年；已有擬答的題目可做知識檢索 A/B 測試</small></div><button type="button" onClick={() => { setQuestionId(""); setPrompt(""); setEvidenceTest(false); setStatus("已切換為自行貼題；自行貼題不會使用站內擬答。"); }}>自行貼題</button></header><div><label>年度<select value={questionYear} onChange={(e) => { setQuestionYear(e.target.value); setQuestionId(""); setEvidenceTest(false); }}>{["114", "113", "112", "111", "110", "109"].map((year) => <option key={year}>{year}</option>)}</select></label><label className="issue-question-select">題號／小題<select value={questionId} onChange={(e) => chooseQuestion(e.target.value)} disabled={questionLoading || !yearQuestions.length}><option value="">{questionLoading ? "讀取真題中…" : yearQuestions.length ? "請選擇題目" : "本年度尚無已發布刑法題"}</option>{yearQuestions.map((item) => <option key={item.id} value={item.id}>{item.examName || "類科待辨識"}｜第 {item.questionNumber} 題{item.hasTeacherAnswer ? "｜已有老師擬答" : "｜尚無擬答"}</option>)}</select></label><label>測試範圍<select value={questionScope} onChange={(e) => { setQuestionScope(e.target.value); if (e.target.value !== "完整刑法題") setEvidenceTest(false); }}><option>完整刑法題</option><option>指定小題</option></select></label></div>{questionId && <p>已選：{questionYear} 年第 {questions.find((item) => item.id === Number(questionId))?.questionNumber} 題 · {questionScope}。擬答 A/B 測試需保留完整原題，確保公平。</p>}</div><textarea value={prompt} onChange={(e) => { setPrompt(e.target.value); if (e.target.value !== questions.find((item) => item.id === Number(questionId))?.stem) setEvidenceTest(false); }} rows={8} placeholder="可從上方選擇司律二試刑法真題，或自行貼上完整題目。模型會依相同提示整理核心爭點、次要爭點與簡短排除。" />
        <section className="issue-test-design"><div><b>① API 來源</b><p>勾選兩個可直接比較官方直連與第三方路由；失敗不會自動切換來源。</p><label className={gateways.includes("direct") ? "selected" : ""}><input type="checkbox" checked={gateways.includes("direct")} onChange={() => toggleGateway("direct")} />原廠官方 API</label><label className={gateways.includes("teamorouter") ? "selected" : ""}><input type="checkbox" checked={gateways.includes("teamorouter")} onChange={() => toggleGateway("teamorouter")} />TeamoRouter</label></div><div><b>② 擬答檢索對照</b><p>同一模型各跑一次：A 組只有題目；B 組由系統取得同一題老師擬答。</p><label className={evidenceTest ? "selected" : ""}><input type="checkbox" checked={evidenceTest} disabled={!questionId || questionScope !== "完整刑法題" || !questions.find((item) => item.id === Number(questionId))?.hasTeacherAnswer} onChange={(event) => setEvidenceTest(event.target.checked)} />有擬答 vs 無擬答 A/B 測試</label><small>{!questionId ? "請先選站內真題" : !questions.find((item) => item.id === Number(questionId))?.hasTeacherAnswer ? "這題尚未連結老師擬答" : "擬答只在伺服器端依題目 ID 取得，不混入 A 組"}</small></div></section>
        <div className="issue-model-groups">{vendors.map((vendor) => <fieldset key={vendor.name}><legend>{vendor.name}</legend>{vendor.models.map((model) => <label key={model.key} className={selected.includes(model.key) ? "selected" : ""}><input type="checkbox" checked={selected.includes(model.key)} onChange={() => toggle(model.key)} /><span>{model.label}</span></label>)}</fieldset>)}</div>{selected.length === 1 && gateways.length === 1 && !evidenceTest && <label className="issue-repeat-picker"><span>同一模型測試次數</span><select value={repetitions} onChange={(event) => setRepetitions(Number(event.target.value) as 1 | 3 | 5)} disabled={running}><option value={1}>1 次｜快速單測</option><option value={3}>3 次｜檢查穩定性</option><option value={5}>5 次｜完整穩定性測試</option></select><small>每次結果分開保存，不會互相覆蓋。</small></label>}<footer><small>{evidenceTest ? `將產生 ${selected.length * gateways.length * 2} 組回答；A、B 各自計費。` : gateways.length === 2 ? `每個模型會由官方與 TeamoRouter 各呼叫一次。` : `每次回答各計一次 API 成本。`}</small><button onClick={() => void start()} disabled={running || selected.length < 1 || gateways.length < 1 || prompt.trim().length < 30}>{running ? "模型辨識中…" : evidenceTest ? "開始擬答 A/B 對照" : gateways.length === 2 ? "開始 API 來源對照" : selected.length === 1 ? `開始單獨測試${repetitions > 1 ? ` ${repetitions} 次` : ""}` : `開始 ${selected.length} 模型匿名比較`}</button></footer></section>
        {error && <p className="issue-error">{error}</p>}{status && <p className="issue-status">{status}</p>}
        {active && <section className="issue-results"><header><div><span>BLIND RESULTS</span><h2>{active.meta.subject}｜本題模型回答</h2><p>{active.promptText}</p></div><div><button onClick={() => setRevealed((value) => !value)}>{revealed ? "隱藏模型名稱" : "揭曉模型"}</button><button onClick={() => void copyPack()}>複製到 ChatGPT 評測</button><small>{responses.reduce((sum, row) => sum + row.inputTokens + row.outputTokens, 0).toLocaleString()} tokens · 約 NT$ {(totalCost * 32.5).toFixed(2)}</small></div></header><div className="issue-response-grid">{responses.map((row, index) => { const state = row.error ? (row.text ? "內容截斷" : row.error.includes("HTTP 524") ? "路由逾時" : row.error.startsWith("無正文") ? "有計費、無正文" : row.error.includes("空白") ? "空白回覆" : "API 錯誤") : "完整完成"; return <article className="issue-response-card" key={row.id}><header><span>模型 {String.fromCharCode(65 + index)}</span><div><b>{revealed ? row.label : "匿名候選模型"}</b><small>{revealed ? row.model : "統一評測後再揭曉"}</small></div><strong className={row.error ? "failed" : "scored"}>{state}</strong></header>{row.text && <pre>{row.text}</pre>}{row.error && <p className="issue-model-error">{row.error}</p>}<div className="issue-metrics"><span>{row.inputTokens + row.outputTokens} tokens</span><span>{(row.durationMs / 1000).toFixed(1)} 秒</span><span>NT$ {(row.estimatedCostUsdMicros / 1e6 * 32.5).toFixed(3)}</span></div>{row.error && <button className="issue-retry" onClick={() => void retry(row)} disabled={retrying === row.id}>{retrying === row.id ? "重試中…" : "單獨重試此模型（會再次計費）"}</button>}</article>; })}</div><section className="issue-unified-review"><header><div><span>UNIFIED REVIEW</span><h3>本輪統一評測</h3></div><b>{savedReview ? "已保存" : "尚未保存"}</b></header><p>只需記錄一份整體比較、排名、重要遺漏與法律定性，不必逐模型另外打分數。</p><textarea rows={9} value={review || savedReview} onChange={(event) => setReview(event.target.value)} placeholder="將 ChatGPT 的整體評論貼在這裡，或直接輸入本輪統一結論。" /><button onClick={() => void saveReview()} disabled={savingReview || !(review || savedReview).trim()}>{savingReview ? "保存中…" : savedReview ? "更新統一評測" : "保存統一評測"}</button></section></section>}
      </div>
    </section>
  </main>;
}
