"use client";
import { useEffect,useMemo,useState } from "react";

type Issue={field:string;kind:string;severity:"P0"|"P1"|"P2";message:string;excerpt:string;autoFixable:boolean};
type Item={id:number;documentId:number;documentName:string;year:string;subject:string;questionNumber:string;issues:Issue[]};
type Summary={questionsScanned:number;questionsWithIssues:number;p0:number;p1:number;autoFixable:number};
type Doc={id:number;fileName:string;subject:string;questionCount:number};

export default function ContentQualityPage(){
 const [items,setItems]=useState<Item[]>([]),[summary,setSummary]=useState<Summary>({questionsScanned:0,questionsWithIssues:0,p0:0,p1:0,autoFixable:0}),[docs,setDocs]=useState<Doc[]>([]),[docId,setDocId]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){setBusy(true);try{const r=await fetch(`/api/medtech/admin/content-quality${docId?`?documentId=${docId}`:""}`,{cache:"no-store"});const d=await r.json() as {summary?:Summary;items?:Item[];documents?:Doc[];error?:string};if(!r.ok)throw new Error(d.error||"品質掃描失敗");setSummary(d.summary||summary);setItems(d.items||[]);setDocs(d.documents||[]);setNotice(`掃描完成：${d.summary?.questionsScanned??0} 題。`)}catch(error){setNotice(error instanceof Error?error.message:"品質掃描失敗")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[docId]);
 const affectedIds=useMemo(()=>items.filter(item=>item.issues.some(issue=>issue.autoFixable)).map(item=>item.id),[items]);
 async function dryRun(){setBusy(true);try{const r=await fetch("/api/medtech/admin/content-quality",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionIds:affectedIds,dryRun:true})});const d=await r.json() as {changed?:number;error?:string};if(!r.ok)throw new Error(d.error||"預覽失敗");setNotice(`高信心規則預覽：${d.changed??0} 題會被修改，尚未寫入資料庫。`)}catch(error){setNotice(error instanceof Error?error.message:"預覽失敗")}finally{setBusy(false)}}
 async function apply(){if(!affectedIds.length)return;if(!confirm(`確定只套用高信心字元規則到 ${affectedIds.length} 題？章節、表格與公式不會自動猜測。`))return;setBusy(true);try{const r=await fetch("/api/medtech/admin/content-quality",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({questionIds:affectedIds,dryRun:false})});const d=await r.json() as {changed?:number;error?:string};if(!r.ok)throw new Error(d.error||"修復失敗");setNotice(`已修復 ${d.changed??0} 題高信心特殊字元，正在重新掃描。`);await load()}catch(error){setNotice(error instanceof Error?error.message:"修復失敗")}finally{setBusy(false)}}
 return <main style={{maxWidth:1280,margin:"0 auto",padding:"28px 20px 64px",fontFamily:"system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",marginBottom:22}}><div><div style={{fontSize:13,color:"#667085"}}>MEDTECH CONTENT QUALITY</div><h1 style={{margin:"4px 0 6px"}}>醫檢教材品質中心</h1><p style={{margin:0,color:"#475467"}}>先掃描、再預覽、最後只套用高信心規則；無法確定的內容保留給 PDF 原稿人工覆核。</p></div><div style={{display:"flex",gap:8}}><a href="/medtech/admin?tab=questions" style={{padding:"10px 14px",border:"1px solid #d0d5dd",borderRadius:8,textDecoration:"none",color:"#344054"}}>返回文件題庫</a><button onClick={()=>void load()} disabled={busy} style={{padding:"10px 14px"}}>{busy?"處理中…":"重新掃描"}</button></div></header>
  <section style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:12,marginBottom:18}}>{[["掃描題數",summary.questionsScanned],["異常題目",summary.questionsWithIssues],["P0 內容風險",summary.p0],["P1 結構風險",summary.p1],["可高信心修復",summary.autoFixable]].map(([label,value])=><article key={String(label)} style={{padding:16,border:"1px solid #e4e7ec",borderRadius:12,background:"white"}}><div style={{fontSize:13,color:"#667085"}}>{label}</div><strong style={{fontSize:28}}>{value}</strong></article>)}</section>
  <section style={{display:"flex",gap:10,alignItems:"center",padding:14,border:"1px solid #e4e7ec",borderRadius:12,marginBottom:18,background:"#f9fafb"}}><label>文件：</label><select value={docId} onChange={e=>setDocId(Number(e.target.value))} style={{padding:"8px 10px",minWidth:320}}><option value={0}>全部醫檢文件</option>{docs.map(doc=><option key={doc.id} value={doc.id}>{doc.fileName}（{doc.questionCount} 題）</option>)}</select><button disabled={busy||!affectedIds.length} onClick={()=>void dryRun()}>預覽高信心修復</button><button disabled={busy||!affectedIds.length} onClick={()=>void apply()}>套用高信心修復</button><span style={{marginLeft:"auto",color:"#475467"}}>{notice}</span></section>
  <section style={{display:"grid",gap:12}}>{items.length===0?<div style={{padding:30,textAlign:"center",border:"1px dashed #d0d5dd",borderRadius:12}}>目前沒有偵測到問題。</div>:items.map(item=><article key={item.id} style={{border:"1px solid #e4e7ec",borderRadius:12,background:"white",overflow:"hidden"}}><header style={{display:"flex",justifyContent:"space-between",gap:12,padding:"12px 14px",background:"#f9fafb"}}><div><strong>第 {item.questionNumber||"?"} 題</strong>　{item.year||"未標示年份"} · {item.subject||"未分類"}<div style={{fontSize:12,color:"#667085",marginTop:4}}>{item.documentName}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><a href={`/medtech/admin/content-quality/review?documentId=${item.documentId}&questionId=${item.id}`} style={{padding:"7px 10px",borderRadius:8,background:"#175cd3",color:"white",textDecoration:"none"}}>PDF 原稿校對</a><a href={`/medtech/admin/document-workspace?id=${item.documentId}`} style={{padding:"7px 10px",border:"1px solid #d0d5dd",borderRadius:8,textDecoration:"none",color:"#344054"}}>完整工作區</a></div></header><div style={{display:"grid",gap:8,padding:12}}>{item.issues.map((issue,index)=><div key={index} style={{padding:"10px 12px",borderRadius:8,border:`1px solid ${issue.severity==="P0"?"#fda29b":"#fec84b"}`,background:issue.severity==="P0"?"#fff5f3":"#fffaeb"}}><div><strong>{issue.severity}｜{issue.field}</strong>　{issue.message}</div><code style={{display:"block",whiteSpace:"pre-wrap",marginTop:6}}>{issue.excerpt}</code><small>{issue.autoFixable?"✓ 可由高信心規則處理":"需回 PDF 原稿確認，不自動猜測"}</small></div>)}</div></article>)}</section>
 </main>;
}
