"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
type Verdict={score:number;weighted:number;breakdown?:Record<string,number>;fatal:string[];summary:string;correction:string;model:string;judgeCostUsd:number};
type ResponseRow={id:number;label:string;model:string;text:string;inputTokens:number;outputTokens:number;durationMs:number;estimatedCostUsdMicros:number;verdict:Verdict|null};
type Question={id:number;group:string;round:number;subject:string;title:string;prompt:string;rule:string;expected:string;forbidden:string[];fatal:string[];responses:ResponseRow[]};
type Run={id:string;label:string;startedAt:string;completed:number;total:number};type Data={target:number;judge:string;runId:string|null;runs:Run[];questions:Question[]};
const providers=["luna","sonnet","deepseek","glm52"]as const;const providerLabels:Record<string,string>={luna:"Luna",sonnet:"Claude Sonnet 5",deepseek:"DeepSeek V4-Pro",glm52:"GLM-5.2"};
function summarize(questions:Question[]){const map=new Map<string,{label:string;model:string;scores:number[],fatal:number,cost:number,time:number,tokens:number}>();for(const q of questions)for(const r of q.responses){if(!r.verdict)continue;const x=map.get(r.label)??{label:r.label,model:r.model,scores:[],fatal:0,cost:0,time:0,tokens:0};x.scores.push(r.verdict.score);x.fatal+=r.verdict.fatal.length||r.verdict.score===0?1:0;x.cost+=r.estimatedCostUsdMicros/1e6+(r.verdict.judgeCostUsd||0);x.time+=r.durationMs;x.tokens+=r.inputTokens+r.outputTokens;map.set(r.label,x)}return[...map.values()].map(x=>({...x,avg:x.scores.reduce((a,b)=>a+b,0)/x.scores.length,pass:x.scores.filter(s=>s>=70).length/x.scores.length*100,costPass:x.cost/Math.max(1,x.scores.filter(s=>s>=70).length)})).sort((a,b)=>b.avg-a.avg)}
export default function ModelLab(){const[data,setData]=useState<Data|null>(null),[running,setRunning]=useState(false),[status,setStatus]=useState(""),[view,setView]=useState<"results"|"questions"|"history">("results"),[detail,setDetail]=useState<{q:Question;r:ResponseRow}|null>(null);const load=(runId?:string)=>fetch(`/api/model-evaluation${runId?`?runId=${encodeURIComponent(runId)}`:""}`).then(r=>r.json()).then(setData);useEffect(()=>{void load()},[]);const rows=useMemo(()=>summarize(data?.questions??[]),[data]);
async function startRun(){if(running)return;const r=await fetch("/api/model-evaluation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-run"})}),x=await r.json()as{runId?:string;error?:string};if(!r.ok||!x.runId){setStatus(x.error||"無法建立測試批次");return}await load(x.runId);setStatus("新測試已建立，準備逐題作答")}
async function runAll(){if(!data?.runId||running)return;setRunning(true);for(const q of data.questions)for(const provider of providers){if(q.responses.some(r=>r.label===providerLabels[provider]))continue;setStatus(`第 ${q.id}/50 題｜${providerLabels[provider]} 作答並由 Sol 判卷中`);const r=await fetch("/api/model-evaluation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({runId:data.runId,questionId:q.id,provider})});if(!r.ok){const e=await r.json();setStatus(`第 ${q.id} 題暫停：${e.error||"發生錯誤"}`);setRunning(false);await load(data.runId);return}await load(data.runId)}setStatus("50 題全部完成，Sol 已判卷並保存本次結果");setRunning(false)}
const completed=(data?.questions??[]).reduce((n,q)=>n+q.responses.filter(r=>r.verdict).length,0),total=(data?.target??50)*providers.length,current=data?.runs.find(r=>r.id===data.runId);
return <main className="model-lab-shell"><header className="model-lab-top"><Link href="/" className="model-lab-brand"><span>律</span><div><b>法律模型自動評測</b><small>50 題 · Sol 統一判卷</small></div></Link><nav><button className={view==="results"?"active":""} onClick={()=>setView("results")}>總統計</button><button className={view==="questions"?"active":""} onClick={()=>setView("questions")}>查看 50 題</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}>歷次比較</button><Link href="/">回到司律備考</Link></nav></header>
<section className="model-lab-hero"><div><span className="eyebrow">AUTOMATED LEGAL BENCHMARK</span><h1>{view==="questions"?"先看清楚測什麼，再開始":"每次測試都留存，才能真正比較"}</h1><p>題目、原始回答、Sol 分項判決、Token、成本與耗時皆按測試批次保存。</p></div><div className="lab-progress"><b>{completed}<small> / {total} 則</small></b><span>{current?.label||"尚未建立測試"}</span><div><i style={{width:`${total?completed/total*100:0}%`}}/></div><small>{status||"可先查看完整 50 題與判卷標準"}</small></div></section>
{view==="questions"&&<QuestionBank questions={data?.questions??[]}/>} {view==="results"&&<section className="results-panel"><div className="benchmark-actions"><div><b>{data?.runId?`目前批次｜${current?.label||data.runId}`:"尚未建立測試批次"}</b><span>開始新一輪不會刪除或覆蓋舊結果</span></div><div className="benchmark-buttons"><button className="secondary" onClick={()=>void startRun()} disabled={running}>＋ 開始新一輪</button><button onClick={()=>void runAll()} disabled={running||!data?.runId||completed===total}>{running?"測試進行中…":completed?"繼續未完成測試":"執行本輪 50 題"}</button></div></div><div className="summary-strip"><div><span>Sol 判卷完成</span><b>{completed}</b><small>共 {total} 則回答</small></div><div><span>目前領先</span><b>{rows[0]?.label||"—"}</b><small>{rows[0]?`${rows[0].avg.toFixed(1)} 分`:"等待測試"}</small></div><div><span>致命錯誤</span><b>{rows.reduce((s,r)=>s+r.fatal,0)}</b><small>命中即 0 分</small></div><div><span>已保存批次</span><b>{data?.runs.length||0}</b><small>可至歷次比較切換</small></div></div><Leaderboard rows={rows}/><details className="human-review"><summary>最後人工覆核｜題目 → 各模型原始回答 → Sol 判決</summary><div className="review-question-list">{data?.questions.map(q=><section key={q.id}><b>{String(q.id).padStart(2,"0")}｜{q.title}</b><p>{q.prompt}</p><div>{q.responses.filter(r=>r.verdict).map(r=><button key={r.id} onClick={()=>setDetail({q,r})}><span>{r.label}</span><strong className={r.verdict!.score>=70?"safe":"danger"}>{r.verdict!.score}分</strong></button>)}</div></section>)}</div></details></section>}
{view==="history"&&<section className="history-panel"><header><div><span>RUN HISTORY</span><h2>歷次測試比較表</h2></div><small>切換批次後可回看完整統計與逐題判決</small></header><div className="run-table"><div className="run-row run-head"><span>測試批次</span><span>完成進度</span><span>狀態</span><span>查看</span></div>{[...(data?.runs||[])].reverse().map(run=><div className="run-row" key={run.id}><span><b>{run.label}</b><small>{run.id}</small></span><span>{run.completed}/{run.total}</span><span className={run.completed===run.total?"safe":"warning"}>{run.completed===run.total?"完整測試":"未完成"}</span><span><button onClick={async()=>{await load(run.id);setView("results")}}>查看比較表</button></span></div>)}</div><p className="history-note">每一批均保留模型版本、原始回答、Sol 評分與評語、致命錯誤、Token、耗時及成本，可比較模型更新前後是否真的進步。</p></section>}
{detail&&<VerdictModal detail={detail} close={()=>setDetail(null)}/>}</main>}
function QuestionBank({questions}:{questions:Question[]}){return <section className="question-bank"><header><div><span>BENCHMARK QUESTION BANK</span><h2>50 題完整題庫與 Sol 標準卡</h2></div><small>20 題單輪核心＋25 題連續追問＋5 題資料查核</small></header>{questions.map(q=><details key={q.id}><summary><i>{String(q.id).padStart(2,"0")}</i><span><b>{q.title}</b><small>{q.group} · {q.subject}{q.round>1?` · 第 ${q.round} 輪`:""}</small></span></summary><div className="question-bank-body"><section><b>實際送出題目</b><p>{q.prompt}</p></section><section className="standard-card"><b>Sol 判卷標準卡</b><dl><dt>正確法律判準</dt><dd>{q.rule}</dd><dt>預期方向</dt><dd>{q.expected}</dd><dt>不得自行補充</dt><dd>{q.forbidden.join("、")||"無特別項目"}</dd><dt>致命錯誤</dt><dd>{q.fatal.join("、")||"依通用致命錯誤規則"}</dd></dl></section></div></details>)}</section>}
function Leaderboard({rows}:{rows:ReturnType<typeof summarize>}){return <div className="leaderboard"><header><div><span>AUTOMATIC RANKING</span><h2>本批次模型比較表</h2></div><small>依 Sol 判卷結果自動排序</small></header>{rows.length?<div className="leader-table"><div className="leader-row leader-head"><span>排名／模型</span><span>平均分</span><span>合格率</span><span>致命錯誤率</span><span>平均耗時</span><span>每則合格成本</span></div>{rows.map((r,i)=><div className="leader-row" key={r.label}><span><i>{i+1}</i><b>{r.label}</b><small>{r.scores.length}/50 題 · {r.tokens.toLocaleString()} tokens</small></span><span><strong>{r.avg.toFixed(1)}</strong>/100</span><span>{r.pass.toFixed(0)}%</span><span className={r.fatal?"danger":"safe"}>{(r.fatal/r.scores.length*100).toFixed(0)}%</span><span>{(r.time/r.scores.length/1000).toFixed(1)}秒</span><span>NT$ {(r.costPass*32.5).toFixed(3)}</span></div>)}</div>:<div className="lab-empty">建立新一輪後，統計會隨 Sol 判卷即時更新並保存。</div>}</div>}
function VerdictModal({detail,close}:{detail:{q:Question;r:ResponseRow};close:()=>void}){const names:Record<string,string>={rule:"判準",application:"涵攝",premise:"抗迎合",facts:"事實",sources:"來源",continuity:"承接",teaching:"教學"};return <div className="verdict-modal" onClick={close}><article onClick={e=>e.stopPropagation()}><button onClick={close}>關閉</button><span>SOL JUDGMENT</span><h2>{detail.q.id}. {detail.q.title}｜{detail.r.label}</h2><h3>{detail.r.verdict?.score} 分</h3>{detail.r.verdict?.breakdown&&<div className="score-breakdown">{Object.entries(detail.r.verdict.breakdown).map(([k,v])=><span key={k}>{names[k]||k}<b>{v}</b></span>)}</div>}<b>Sol 評語</b><p>{detail.r.verdict?.summary}</p><b>正確核心</b><p>{detail.r.verdict?.correction}</p>{Boolean(detail.r.verdict?.fatal.length)&&<><b className="danger">致命錯誤</b><p>{detail.r.verdict?.fatal.join("、")}</p></>}<details><summary>查看候選模型原始回答</summary><p>{detail.r.text}</p></details><small>模型 {detail.r.model} · {detail.r.inputTokens+detail.r.outputTokens} tokens · {(detail.r.durationMs/1000).toFixed(1)} 秒</small></article></div>}
