"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
type Verdict={score:number;fatal:string[];judgeCostUsd:number};
type ResponseRow={id:number;label:string;model:string;text:string;inputTokens:number;outputTokens:number;durationMs:number;estimatedCostUsdMicros:number;verdict:Verdict|null};
type Question={id:number;group:string;round:number;subject:string;title:string;prompt:string;rule:string;expected:string;forbidden:string[];fatal:string[];responses:ResponseRow[]};
type Run={id:string;label:string;startedAt:string;completed:number;answered?:number;total:number};type Data={target:number;judge:string;runId:string|null;runs:Run[];questions:Question[]};
const providers=["luna","sonnet","deepseek","glm52"]as const,letters=["A","B","C","D"],providerLabels=["Luna","Claude Sonnet 5","DeepSeek V4-Pro","GLM-5.2"];
function summarize(questions:Question[]){const map=new Map<string,{label:string;scores:number[],fatal:number,cost:number,time:number,tokens:number}>();for(const q of questions)for(const r of q.responses){if(!r.verdict)continue;const x=map.get(r.label)??{label:r.label,scores:[],fatal:0,cost:0,time:0,tokens:0};x.scores.push(r.verdict.score);x.fatal+=r.verdict.fatal?.length?1:0;x.cost+=r.estimatedCostUsdMicros/1e6;x.time+=r.durationMs;x.tokens+=r.inputTokens+r.outputTokens;map.set(r.label,x)}return[...map.values()].map(x=>({...x,avg:x.scores.reduce((a,b)=>a+b,0)/x.scores.length,pass:x.scores.filter(s=>s>=70).length/x.scores.length*100})).sort((a,b)=>b.avg-a.avg)}
function buildPack(q:Question){const answers=providerLabels.map(label=>q.responses.find(r=>r.label===label));return [`【司律備考｜第 ${q.id} 題匿名評測】`,`題目：${q.prompt}`,`正確法律判準：${q.rule}`,`預期方向：${q.expected}`,`致命錯誤：${q.fatal.join("、")||"依通用規則"}`,...answers.flatMap((r,i)=>["",`【回答 ${letters[i]}】`,r?.text||"（系統錯誤／無回答）",`Token：${r?r.inputTokens+r.outputTokens:"—"}｜成本：${r?`US$ ${(r.estimatedCostUsdMicros/1e6).toFixed(6)}`:"—"}｜耗時：${r?`${(r.durationMs/1000).toFixed(1)} 秒`:"—"}`]),"","請依固定標準評分，最後只需附一行評分碼，例如：A88 B81 C54! D-"] .join("\n")}
export default function ModelLab(){const[data,setData]=useState<Data|null>(null),[running,setRunning]=useState(false),[status,setStatus]=useState(""),[error,setError]=useState(""),[scoreCode,setScoreCode]=useState(""),[view,setView]=useState<"results"|"questions"|"history">("results");
const load=async(runId?:string)=>{const r=await fetch(`/api/model-evaluation${runId?`?runId=${encodeURIComponent(runId)}`:""}`),x=await r.json().catch(()=>({error:"伺服器沒有回傳可讀資料"}))as Data&{error?:string};if(!r.ok){setError(`測試資料讀取失敗：${x.error||r.status}`);throw new Error(x.error)}setError("");setData(x);return x};useEffect(()=>{void load().catch(()=>undefined)},[]);
const rows=useMemo(()=>summarize(data?.questions??[]),[data]),answered=(data?.questions??[]).reduce((n,q)=>n+q.responses.length,0),scored=(data?.questions??[]).reduce((n,q)=>n+q.responses.filter(r=>r.verdict).length,0),total=(data?.target??50)*4,current=data?.runs.find(r=>r.id===data.runId),readyQuestion=data?.questions.find(q=>q.responses.length===4&&q.responses.some(r=>!r.verdict)),nextQuestion=data?.questions.find(q=>q.responses.length<4);
async function startRun(){if(running)return;if(answered>0&&answered<total&&!confirm("目前批次尚未完成。建立新一輪會重新產生模型費用，仍要建立嗎？"))return;const r=await fetch("/api/model-evaluation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-run"})}),x=await r.json()as{runId?:string;error?:string};if(!r.ok||!x.runId){setError(x.error||"無法建立測試批次");return}await load(x.runId);setStatus("新測試已建立")}
async function runOneQuestion(){if(!data?.runId||running||readyQuestion)return;const q=nextQuestion;if(!q){setStatus("全部候選模型均已作答");return}setRunning(true);setError("");for(let i=0;i<providers.length;i++){if(q.responses.some(r=>r.label===providerLabels[i]))continue;setStatus(`第 ${q.id} 題｜${providerLabels[i]} 作答中`);const r=await fetch("/api/model-evaluation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({runId:data.runId,questionId:q.id,provider:providers[i]})}),x=await r.json()as{error?:string};if(!r.ok){setError(`${providerLabels[i]} 作答失敗：${x.error||"未知錯誤"}。不評分也不扣人工評測分。`);setRunning(false);await load(data.runId);return}await load(data.runId)}setRunning(false);setStatus(`第 ${q.id} 題已完成，請複製評測包貼到 ChatGPT 評分`);await load(data.runId)}
async function copyPack(){if(!readyQuestion)return;await navigator.clipboard.writeText(buildPack(readyQuestion));setStatus(`第 ${readyQuestion.id} 題評測包已複製，可直接貼到 ChatGPT`)}
async function saveScore(){if(!data?.runId||!readyQuestion)return;const r=await fetch("/api/model-evaluation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"manual-score",runId:data.runId,questionId:readyQuestion.id,scoreCode})}),x=await r.json()as{error?:string};if(!r.ok){setError(x.error||"評分碼無法保存");return}setScoreCode("");setStatus(`第 ${readyQuestion.id} 題評分已保存，可以開始下一題`);await load(data.runId)}
return <main className="model-lab-shell"><header className="model-lab-top"><Link href="/" className="model-lab-brand"><span>律</span><div><b>法律模型人工盲測</b><small>每題完成即暫停 · 不使用 Sol 判卷</small></div></Link><nav><button className={view==="results"?"active":""} onClick={()=>setView("results")}>本輪評測</button><button className={view==="questions"?"active":""} onClick={()=>setView("questions")}>查看 50 題</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}>歷次比較</button><Link href="/">回到司律備考</Link></nav></header>
<section className="model-lab-hero"><div><span className="eyebrow">HUMAN-IN-THE-LOOP BENCHMARK</span><h1>模型只作答，評分交給你貼回</h1><p>每題四個模型完成後立即停止；匿名複製、ChatGPT 評分、一行回填。</p></div><div className="lab-progress"><b>{answered}<small> / {total} 則作答</small></b><span>{current?.label||"尚未建立測試"}</span><div><i style={{width:`${total?answered/total*100:0}%`}}/></div><small>{status||`已評分 ${scored} 則`}</small></div></section>
{view==="results"&&<section className="results-panel"><div className="benchmark-actions"><div><b>{data?.runId?`目前批次｜${current?.label||data.runId}`:"尚未建立測試批次"}</b><span>Sol 自動評審已關閉；系統錯誤不列入分數</span></div><div className="benchmark-buttons"><button className="secondary" onClick={()=>void startRun()} disabled={running}>＋ 開始新一輪</button><button onClick={()=>void runOneQuestion()} disabled={running||!data?.runId||Boolean(readyQuestion)||!nextQuestion}>{running?"本題模型作答中…":readyQuestion?"請先回填本題分數":"開始下一題"}</button></div></div>{error&&<div className="benchmark-error"><b>本次未完成</b><span>{error}</span></div>}{readyQuestion&&<section className="manual-score-card"><header><div><span>READY FOR REVIEW</span><h2>第 {readyQuestion.id} 題已完成，等待人工評分</h2></div><b>四個回答已匿名化為 A／B／C／D</b></header><div className="manual-score-actions"><button onClick={()=>void copyPack()}>複製本題評測包</button><div><input value={scoreCode} onChange={e=>setScoreCode(e.target.value)} placeholder="貼上：A88 B81 C54! D-"/><button onClick={()=>void saveScore()} disabled={!scoreCode.trim()}>保存評分並進入下一題</button></div><small>數字＝總分　!＝致命錯誤　-＝系統錯誤／不評分</small></div><details><summary>先在網站內查看匿名回答</summary><pre>{buildPack(readyQuestion)}</pre></details></section>}<div className="summary-strip"><div><span>候選模型作答</span><b>{answered}</b><small>共 {total} 則</small></div><div><span>人工評分完成</span><b>{scored}</b><small>不產生 Sol API 費用</small></div><div><span>目前領先</span><b>{rows[0]?.label||"—"}</b><small>{rows[0]?`${rows[0].avg.toFixed(1)} 分`:"等待回填"}</small></div><div><span>歷次測試</span><b>{data?.runs.length||0} 批</b><small>舊資料完整保留</small></div></div><Leaderboard rows={rows}/></section>}
{view==="questions"&&<QuestionBank questions={data?.questions??[]}/>} {view==="history"&&<section className="history-panel"><header><div><span>RUN HISTORY</span><h2>歷次測試比較表</h2></div><small>舊批次 Sol 評分與新批次人工評分都會保留</small></header><div className="run-table"><div className="run-row run-head"><span>測試批次</span><span>作答／評分</span><span>狀態</span><span>查看</span></div>{[...(data?.runs||[])].reverse().map(run=><div className="run-row" key={run.id}><span><b>{run.label}</b><small>{run.id}</small></span><span>{run.answered??run.completed}/{run.completed}</span><span className={run.completed===run.total?"safe":"warning"}>{run.completed===run.total?"完整測試":"進行中"}</span><span><button onClick={async()=>{await load(run.id);setView("results")}}>查看</button></span></div>)}</div></section>}</main>}
function QuestionBank({questions}:{questions:Question[]}){return <section className="question-bank"><header><div><span>BENCHMARK QUESTION BANK</span><h2>50 題完整題庫與評分標準</h2></div><small>題目不變，只改用人工貼回評分</small></header>{questions.map(q=><details key={q.id}><summary><i>{String(q.id).padStart(2,"0")}</i><span><b>{q.title}</b><small>{q.group} · {q.subject}</small></span></summary><div className="question-bank-body"><section><b>實際送出題目</b><p>{q.prompt}</p></section><section className="standard-card"><b>人工評分標準卡</b><dl><dt>正確法律判準</dt><dd>{q.rule}</dd><dt>預期方向</dt><dd>{q.expected}</dd><dt>致命錯誤</dt><dd>{q.fatal.join("、")||"依通用規則"}</dd></dl></section></div></details>)}</section>}
function Leaderboard({rows}:{rows:ReturnType<typeof summarize>}){return <div className="leaderboard"><header><div><span>MANUAL RANKING</span><h2>已回填分數比較表</h2></div><small>依 ChatGPT 對話人工評測結果排序</small></header>{rows.length?<div className="leader-table"><div className="leader-row leader-head"><span>排名／模型</span><span>平均分</span><span>合格率</span><span>致命錯誤率</span><span>平均耗時</span><span>模型作答成本</span></div>{rows.map((r,i)=><div className="leader-row" key={r.label}><span><i>{i+1}</i><b>{r.label}</b><small>{r.scores.length} 則已評分</small></span><span><strong>{r.avg.toFixed(1)}</strong>/100</span><span>{r.pass.toFixed(0)}%</span><span>{(r.fatal/r.scores.length*100).toFixed(0)}%</span><span>{(r.time/r.scores.length/1000).toFixed(1)}秒</span><span>NT$ {(r.cost*32.5).toFixed(3)}</span></div>)}</div>:<div className="lab-empty">完成一題並貼回評分碼後，統計會自動出現。</div>}</div>}
