"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Course={id:number;title:string;subject:string;creator:string;description:string;status:string;accessType:string;sourceUrl:string;hasCover:string|null};
type Draft={title:string;subject:string;creator:string;description:string;published:boolean};
const empty:Draft={title:"",subject:"主題講座",creator:"陳友心",description:"",published:false};

export default function PosnerAdmin(){
  const[courses,setCourses]=useState<Course[]>([]),[selectedId,setSelectedId]=useState<number|null>(null),[draft,setDraft]=useState<Draft>(empty),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
  const selected=useMemo(()=>courses.find(item=>item.id===selectedId)??null,[courses,selectedId]);
  async function load(){const response=await fetch("/api/admin/posner-courses",{cache:"no-store"});const data=await response.json() as{courses?:Course[];error?:string};if(!response.ok)throw new Error(data.error||"無法讀取影音課程");setCourses(data.courses??[])}
  useEffect(()=>{void load().catch(error=>setNotice(error instanceof Error?error.message:"讀取失敗"))},[]);
  function choose(course:Course){setSelectedId(course.id);setDraft({title:course.title,subject:course.subject,creator:course.creator||"陳友心",description:course.description,published:course.accessType==="posner"&&course.status==="active"});setFile(null);setNotice("")}
  async function save(event:FormEvent){event.preventDefault();if(!selectedId)return;setSaving(true);setNotice("");try{const response=await fetch("/api/admin/posner-courses",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:selectedId,...draft})});const data=await response.json()as{error?:string};if(!response.ok)throw new Error(data.error||"儲存失敗");if(file){const form=new FormData();form.set("id",String(selectedId));form.set("file",file);const upload=await fetch("/api/admin/posner-courses",{method:"POST",body:form});const result=await upload.json()as{error?:string};if(!upload.ok)throw new Error(result.error||"縮圖上傳失敗")}await load();setFile(null);setNotice(draft.published?"已儲存並發布到波斯納前台。":"已儲存為草稿，前台不會顯示。")}catch(error){setNotice(error instanceof Error?error.message:"儲存失敗")}finally{setSaving(false)}}
  return <main className="posner-admin"><header><div><span>POSNER VIDEO STUDIO</span><h1>波斯納影音課程</h1><p>選擇已完成轉檔的影片，再整理學生會看到的課程資料。</p></div><a href="/posner">查看前台</a></header><div className="posner-admin-workspace"><aside><h2>影音素材</h2><p>原始檔名只在後台顯示。</p><div className="posner-admin-list">{courses.map(course=><button type="button" className={selectedId===course.id?"active":""} key={course.id} onClick={()=>choose(course)}><span>{course.sourceUrl?"影片已就緒":"處理中"}</span><b>{course.title}</b><small>{course.creator||"尚未設定講師"} · {course.accessType==="posner"&&course.status==="active"?"前台已發布":"草稿"}</small></button>)}</div></aside><section className="posner-admin-editor">{selected?<form onSubmit={save}><div className="posner-admin-preview"><div className="posner-admin-cover">{selected.hasCover?<img src={`/api/resources/cover?id=${selected.id}`} alt="目前課程縮圖"/>:<span>尚未上傳縮圖</span>}</div><div><small>前台卡片預覽</small><b>{draft.title||"課程名稱"}</b><span>{draft.creator||"講師姓名"} · {draft.subject||"課程分類"}</span></div></div><div className="posner-admin-fields"><label className="wide">課程名稱<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="輸入前台顯示的課程名稱"/></label><label>講師<input value={draft.creator} onChange={e=>setDraft({...draft,creator:e.target.value})}/></label><label>課程分類<input value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})} placeholder="例如：法律講座"/></label><label className="wide">課程說明<textarea rows={7} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="介紹課程內容、適合對象及學習重點"/></label><label className="wide file">課程縮圖<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{file?.name||"建議使用 16:9 圖片，JPG、PNG 或 WebP"}</span></label></div><label className="posner-publish-check"><input type="checkbox" checked={draft.published} onChange={e=>setDraft({...draft,published:e.target.checked})}/><span><b>發布到波斯納前台</b><small>關閉時只儲存草稿，學生看不到。</small></span></label><div className="posner-admin-actions"><span role="status">{notice}</span><button disabled={saving||!draft.title.trim()||!selected.sourceUrl}>{saving?"儲存中…":draft.published?"儲存並發布":"儲存草稿"}</button></div></form>:<div className="posner-admin-empty"><b>選擇一支影音素材</b><span>即可設定陳友心老師的課程名稱、說明與縮圖。</span></div>}</section></div></main>
}
