import {eq} from "drizzle-orm";
import {appSettings} from "../../../../../db/schema";
import {requireAdmin} from "../../../../../lib/member-auth";
const OWNER="iamflashon@gmail.com",allowed=new Set(["image/jpeg","image/png","image/webp"]);
function setting(category:string,productKey:string){return `central_product_cover:${category}:${productKey}`}
function identify(request:Request){const url=new URL(request.url),category=url.searchParams.get("category")??"",productKey=url.searchParams.get("productKey")??"";if(!["accounting","medtech"].includes(category)||!productKey)return null;return{category,productKey,key:setting(category,productKey)}}
export async function GET(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;const id=identify(request);if(!id)return new Response("not found",{status:404});const[row]=await auth.db.select().from(appSettings).where(eq(appSettings.key,id.key)).limit(1);if(!row)return new Response("not found",{status:404});const{env}=await import("cloudflare:workers"),object=await env.BUCKET.get(row.value);if(!object)return new Response("not found",{status:404});const headers=new Headers();object.writeHttpMetadata(headers);headers.set("etag",object.httpEtag);headers.set("cache-control","private, max-age=300");return new Response(object.body,{headers})}
export async function POST(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;if(auth.member.email.toLowerCase()!==OWNER)return Response.json({error:"只有總管理者可更換書封"},{status:403});const form=await request.formData(),category=String(form.get("category")??""),productKey=String(form.get("productKey")??""),file=form.get("file");if(!["accounting","medtech"].includes(category)||!productKey)return Response.json({error:"商品資料不完整"},{status:400});if(!(file instanceof File)||!allowed.has(file.type))return Response.json({error:"請上傳 JPG、PNG 或 WebP 書封"},{status:400});if(file.size>8*1024*1024)return Response.json({error:"書封檔案不可超過 8MB"},{status:413});const settingKey=setting(category,productKey),[old]=await auth.db.select().from(appSettings).where(eq(appSettings.key,settingKey)).limit(1),ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg",storageKey=`central/product-covers/${category}-${productKey}-${crypto.randomUUID()}.${ext}`,{env}=await import("cloudflare:workers");await env.BUCKET.put(storageKey,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{category,productKey,originalName:file.name}});await auth.db.insert(appSettings).values({key:settingKey,value:storageKey,updatedAt:new Date()}).onConflictDoUpdate({target:appSettings.key,set:{value:storageKey,updatedAt:new Date()}});if(old?.value)await env.BUCKET.delete(old.value);return Response.json({ok:true})}
export async function DELETE(request:Request){const auth=await requireAdmin(request);if("error"in auth)return auth.error;if(auth.member.email.toLowerCase()!==OWNER)return Response.json({error:"只有總管理者可移除書封"},{status:403});const id=identify(request);if(!id)return Response.json({error:"商品資料不完整"},{status:400});const[row]=await auth.db.select().from(appSettings).where(eq(appSettings.key,id.key)).limit(1),{env}=await import("cloudflare:workers");if(row?.value)await env.BUCKET.delete(row.value);await auth.db.delete(appSettings).where(eq(appSettings.key,id.key));return Response.json({ok:true})}
