"use client";

import { useEffect, useMemo, useState } from "react";
import MedtechTabs from "../MedtechTabs";
import MedtechHeaderActions from "../MedtechHeaderActions";

type Note = { id:number; title:string; content:string; subject:string; tags:string; sourceLabel:string; updatedAt:string };
const blank = ():Note => ({ id:0,title:"",content:"",subject:"醫檢師｜臨床病毒學",tags:"醫檢師、待複習",sourceLabel:"醫檢師引導學習",updatedAt:new Date().toISOString() });

export default function MedtechNotesPage(){
  const [notes,setNotes]=useState<Note[]>([]),[noteCount,setNoteCount]=useState(0),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[draft,setDraft]=useState<Note|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  async function load(){setLoading(true);const response=await fetch("/api/notes?category=medtech");if(response.ok){const data=(await response.json()) as {notes?:Note[];noteCount?:number};setNotes(data.notes??[]);setNoteCount(Number(data.noteCount??data.notes?.length??0))}setLoading(false)}
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return !term?notes:notes.filter(note=>[note.title,note.content,note.subject,note.tags].some(value=>value?.toLowerCase().includes(term)))},[notes,query]);
  async function save(){if(!draft?.title.trim()||!draft.content.trim()){setMessage("請填寫標題與內容。");return}setSaving(true);setMessage("");const response=await fetch("/api/notes",{method:draft.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:draft.id,category:"medtech",sourceType:"note",sourceId:draft.id?undefined:`medtech-manual-${Date.now()}`,title:draft.title,content:draft.content,originalContent:draft.content,subject:draft.subject,tags:draft.tags.includes("醫檢師")?draft.tags:`醫檢師、${draft.tags}`,sourceLabel:draft.sourceLabel})});setSaving(false);if(!response.ok){const data=await response.json().catch(()=>({}));setMessage(typeof data.error==="string"?data.error:"目前無法儲存，請稍後再試。");return}await load();setDraft(null)}
  async function remove(){if(!draft?.id||!window.confirm("確定刪除這則醫檢筆記？"))return;const response=await fetch(`/api/notes?id=${draft.id}&category=medtech`,{method:"DELETE"});if(response.ok){setNotes(items=>items.filter(item=>item.id!==draft.id));setDraft(null)}}
  return <main className="medtech-notes-page"><header className="medtech-top" data-no-navigation-feedback><a href="/medtech" className="medtech-brand"><span>醫</span><div><b>醫檢師備考</b><small>MY NOTES</small></div></a><MedtechHeaderActions /></header><MedtechTabs active="notes"/><section className="medtech-notes-head"><span>MEDTECH STUDY NOTES</span><h1>我的醫檢筆記</h1><p>框選保存的名詞與 AI 白話解析都集中在這裡，不與司律筆記混用。</p><small className="medtech-note-policy">目前已保存 {noteCount} 筆；前 5 筆免費，第 6 筆起新增每筆扣 1 點。查看與編輯既有筆記不扣點。</small></section><section className="medtech-notes-tools"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜尋名詞、內容、科目或標籤…"/><button type="button" onClick={()=>setDraft(blank())}>＋ 新增筆記</button></section>{loading?<div className="medtech-notes-empty">正在讀取醫檢筆記…</div>:visible.length?<section className="medtech-note-list">{visible.map(note=><article className="medtech-note-card" key={note.id}><small>{note.subject} · {note.tags}</small><h2>{note.title}</h2><p>{note.content}</p><button type="button" onClick={()=>setDraft(note)}>查看／編輯</button></article>)}</section>:<div className="medtech-notes-empty">{query?"找不到符合條件的醫檢筆記。":"還沒有醫檢筆記；在引導學習框選名詞後，按「加入筆記」即可保存。"}</div>}{draft&&<div className="medtech-note-backdrop" onMouseDown={()=>setDraft(null)}><section className="medtech-note-dialog" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><header><h2>{draft.id?"查看與編輯":"新增醫檢筆記"}</h2><button type="button" onClick={()=>setDraft(null)}>×</button></header><label>標題<input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>科目<input value={draft.subject} onChange={event=>setDraft({...draft,subject:event.target.value})}/></label><label>標籤<input value={draft.tags} onChange={event=>setDraft({...draft,tags:event.target.value})}/></label><label>筆記內容<textarea rows={12} value={draft.content} onChange={event=>setDraft({...draft,content:event.target.value})}/></label>{message&&<small>{message}</small>}<footer>{draft.id?<button type="button" className="danger" onClick={()=>void remove()}>刪除</button>:<span/>}<div><button type="button" onClick={()=>setDraft(null)}>取消</button><button type="button" className="primary" disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存筆記"}</button></div></footer></section></div>}</main>
}
