"use client";
import {useEffect,useMemo,useState} from "react";
import {RichQuestionEditor} from "../../../medtech/admin/RichQuestionEditor";
import "../../../medtech/admin/question-workbench.css";
import "./quality.css";
import "./search-results.css";
import "./answer-review.css";
import "./bulk-replace.css";
import "./editor-actions.css";

type Doc={id:number;examCategory:string;bookTitle:string;fileName:string;subject:string;questionCount:number};
type Question={id:number;examType?:string;year:string;subject:string;questionNumber:string;stem:string;options?:Record<string,string>;correctAnswer?:string|null;teacherAnswer?:string|null;explanation?:string};
type Flag={severity:"P0"|"P1"|"P2";message:string;auto:boolean;action?:"spacing"|"linebreak"|"classify-open"};
type AnswerSuggestion={answer:string;reason:string;confidence:"high"|"medium"|"low";mustReview:boolean};
function plain(value:string){return String(value??"").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim()}
function hasSuspiciousLineBreak(value:string){return /[\u4e00-\u9fff](?:\s*<br\s*\/?\s*>\s*|\r?\n\s*)[\u4e00-\u9fff]/iu.test(value||"")}
function removeSuspiciousLineBreaks(value:string){return String(value||"").replace(/([\u4e00-\u9fff])(?:\s*<br\s*\/?\s*>\s*|\r?\n\s*)(?=[\u4e00-\u9fff])/giu,"$1")}
function flags(q:Question){
 const result:Flag[]=[],options=["A","B","C","D"].map(k=>plain(q.options?.[k]||"")),answer=String(q.teacherAnswer||q.correctAnswer||"").trim().toUpperCase(),openEnded=["short_answer","essay","calculation"].includes(q.examType||""),hasAnyOption=options.some(Boolean),likelyOpen=!openEnded&&!hasAnyOption&&Boolean(plain(q.explanation||""));
 if(!plain(q.stem))result.push({severity:"P0",message:"題幹為空或拆題失敗",auto:false});
 if(likelyOpen)result.push({severity:"P1",message:"疑似簡答／申論題：沒有選項，但已有解析；請確認題型",auto:false,action:"classify-open"});
 if(!openEnded&&!likelyOpen&&!options.every(Boolean))result.push({severity:"P0",message:"A～D 選項不完整",auto:false});
 if(!openEnded&&!likelyOpen&&!/^(?:[A-D]|NONE)$/.test(answer))result.push({severity:"P0",message:"缺少有效老師答案",auto:false});
 if(!openEnded&&!likelyOpen&&answer==="NONE")result.push({severity:"P0",message:"老師確認 A～D 均無適合答案；本題暫不發布",auto:false});
 if(options.some(v=>/(?:解析|解答|計算過程|答案)\s*[：:]/u.test(v)))result.push({severity:"P0",message:"解析或答案疑似混入選項",auto:false});
 if(/[\uE000-\uF8FF�]/u.test([q.stem,...options,q.explanation||""].join(" ")))result.push({severity:"P0",message:"偵測到私人使用區或無法辨識的特殊字元",auto:false});
 if(/(?:[\u4e00-\u9fff]\s+){3,}[\u4e00-\u9fff]/u.test([plain(q.stem),...options].join(" ")))result.push({severity:"P1",message:"偵測到中文字間異常空格",auto:true,action:"spacing"});
 if([q.stem,...Object.values(q.options||{}),q.explanation||""].some(hasSuspiciousLineBreak))result.push({severity:"P1",message:"疑似中文字被強制斷行",auto:true,action:"linebreak"});
 if(openEnded&&options.every(Boolean))result.push({severity:"P1",message:"題型標為非選擇題，但仍有完整選項",auto:false});
 return result;
}
function endpoints(category:string){return category==="medtech"?"/api/medtech/admin/questions":category==="data-structure"?"/api/data-structure/admin/questions":"/api/accounting/admin/questions"}
const LAST_DOCUMENT_KEY="central-quality-last-document";
function lastQuestionKey(documentId:number){return `central-quality-last-question:${documentId}`}
function cacheKey(documentId:number){return `central-quality-scan:${documentId}`}
function draftKey(documentId:number,questionId:number){return `central-quality-draft:${documentId}:${questionId}`}
function countLiteral(value:string,needle:string){if(!needle)return 0;return value.split(/(<[^>]*>)/g).filter(part=>!part.startsWith("<")).reduce((total,part)=>total+Math.max(0,part.split(needle).length-1),0)}
function replaceLiteral(value:string,needle:string,replacement:string){if(!needle)return value;return value.split(/(<[^>]*>)/g).map(part=>part.startsWith("<")?part:part.split(needle).join(replacement)).join("")}
function replaceQuestion(q:Question,needle:string,replacement:string){return {...q,stem:replaceLiteral(q.stem||"",needle,replacement),options:Object.fromEntries(Object.entries(q.options||{}).map(([key,value])=>[key,replaceLiteral(value||"",needle,replacement)])),explanation:replaceLiteral(q.explanation||"",needle,replacement)}}
function questionMatchCount(q:Question,needle:string){return countLiteral(q.stem||"",needle)+Object.values(q.options||{}).reduce((total,value)=>total+countLiteral(value||"",needle),0)+countLiteral(q.explanation||"",needle)}

export default function CentralQualityPage(){
 const[docs,setDocs]=useState<Doc[]>([]),[documentId,setDocumentId]=useState(0),[questions,setQuestions]=useState<Question[]>([]),[activeId,setActiveId]=useState(0),[pdfPage,setPdfPage]=useState(1),[pageMatched,setPageMatched]=useState(false),[draftSaved,setDraftSaved]=useState(false),[findText,setFindText]=useState(""),[replaceText,setReplaceText]=useState(""),[replaceBusy,setReplaceBusy]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[answerBusy,setAnswerBusy]=useState(false),[suggestion,setSuggestion]=useState<AnswerSuggestion|null>(null),[notice,setNotice]=useState(""),[severity,setSeverity]=useState("all"),[query,setQuery]=useState(""),[docQuery,setDocQuery]=useState(""),[focus,setFocus]=useState(false),[listCollapsed,setListCollapsed]=useState(false);
 useEffect(()=>{try{setFocus(localStorage.getItem("central-quality-focus")==="1");setListCollapsed(localStorage.getItem("central-quality-list-collapsed")==="1")}catch{}},[]);
 function toggleFocus(){setFocus(value=>{const next=!value;try{localStorage.setItem("central-quality-focus",next?"1":"0")}catch{}return next})}
 function toggleList(){setListCollapsed(value=>{const next=!value;try{localStorage.setItem("central-quality-list-collapsed",next?"1":"0")}catch{}return next})}
 useEffect(()=>{void fetch("/api/admin/question-bank-summary",{cache:"no-store"}).then(r=>r.json()).then(d=>{const rows=(d.files??[]).filter((x:Doc)=>["accounting","medtech","data-structure"].includes(x.examCategory));setDocs(rows);const requested=Number(new URLSearchParams(location.search).get("id"));let remembered=0;try{remembered=Number(localStorage.getItem(LAST_DOCUMENT_KEY))}catch{}setDocumentId(rows.some((x:Doc)=>x.id===requested)?requested:rows.some((x:Doc)=>x.id===remembered)?remembered:rows[0]?.id||0)})},[]);
 const doc=docs.find(x=>x.id===documentId);
 const visibleDocs=useMemo(()=>{const needle=docQuery.trim().toLocaleLowerCase();return needle?docs.filter(d=>[d.bookTitle,d.fileName,d.subject].join(" ").toLocaleLowerCase().includes(needle)):docs},[docs,docQuery]);
 useEffect(()=>{if(docQuery.trim()&&visibleDocs.length===1&&visibleDocs[0].id!==documentId)chooseDocument(visibleDocs[0].id)},[docQuery,visibleDocs,documentId]);
 function chooseDocument(id:number){setDocumentId(id);setDocQuery("");try{localStorage.setItem(LAST_DOCUMENT_KEY,String(id))}catch{}}
 function openQuestion(id:number){let draft:Question|null=null;try{draft=JSON.parse(localStorage.getItem(draftKey(documentId,id))||"null");localStorage.setItem(lastQuestionKey(documentId),String(id))}catch{}if(draft?.id===id)setQuestions(rows=>rows.map(q=>q.id===id?{...q,...draft}:q));setDraftSaved(Boolean(draft));setActiveId(id)}
 useEffect(()=>{if(!doc||!activeId)return;const base=doc.examCategory==="medtech"?"medtech":doc.examCategory==="data-structure"?"data-structure":"accounting";void fetch(`/api/${base}/admin/document-page?documentId=${doc.id}&questionId=${activeId}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{setPdfPage(Number(d.page)||1);setPageMatched(d.matched===true)}).catch(()=>{setPdfPage(1);setPageMatched(false)})},[activeId,doc?.id,doc?.examCategory]);
 function showScan(all:Question[],preferred?:number,restored=false){const bad=all.filter(q=>flags(q).length);let remembered=0;try{remembered=Number(localStorage.getItem(lastQuestionKey(documentId)))}catch{}const next=preferred&&bad.some(q=>q.id===preferred)?preferred:bad.some(q=>q.id===remembered)?remembered:bad[0]?.id||0;let draft:Question|null=null;try{draft=next?JSON.parse(localStorage.getItem(draftKey(documentId,next))||"null"):null}catch{}const rows=draft?.id===next?all.map(q=>q.id===next?{...q,...draft}:q):all;setQuestions(rows);setDraftSaved(Boolean(draft));setActiveId(next);if(next)try{localStorage.setItem(LAST_DOCUMENT_KEY,String(documentId));localStorage.setItem(lastQuestionKey(documentId),String(next))}catch{}setNotice(draft?`已回到上次編修的第 ${draft.questionNumber} 題，並還原尚未儲存的內容。`:restored?`已載入上次掃描結果：${all.length} 題、${bad.length} 題需要處理。`:`已掃描 ${all.length} 題，找到 ${bad.length} 題需要處理。`)}
 async function scan(preferred?:number){if(!doc)return;setLoading(true);setNotice("正在掃描本文件全部題目…");try{const api=endpoints(doc.examCategory);let all:Question[]=[],page=1,total=1;do{const r=await fetch(`${api}?documentId=${documentId}&limit=100&page=${page}&order=source`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"讀取題目失敗");all.push(...(d.items??[]));total=Number(d.total??all.length);page++}while(all.length<total&&page<=50);try{localStorage.setItem(cacheKey(documentId),JSON.stringify(all))}catch{}showScan(all,preferred,false)}catch(e){setNotice(e instanceof Error?e.message:"掃描失敗")}finally{setLoading(false)}}
 useEffect(()=>{if(!doc)return;let cached:Question[]=[];try{cached=JSON.parse(localStorage.getItem(cacheKey(documentId))||"[]")}catch{}if(cached.length)showScan(cached,undefined,true);else void scan()},[documentId,doc?.examCategory]);
 const issues=useMemo(()=>questions.map(q=>({q,flags:flags(q)})).filter(x=>x.flags.length),[questions]);
 const filtered=issues.filter(item=>{const categoryMatch=severity==="all"||item.flags.some(flag=>flag.severity===severity)||(severity==="garbled"&&item.flags.some(flag=>flag.message.includes("特殊字元")))||(severity==="missing-answer"&&item.flags.some(flag=>flag.message.includes("老師答案")))||(severity==="open-ended"&&item.flags.some(flag=>flag.action==="classify-open"))||(severity==="linebreak"&&item.flags.some(flag=>flag.action==="linebreak"));return categoryMatch&&(!query||[item.q.year,item.q.subject,item.q.questionNumber,item.q.stem,...item.flags.map(f=>f.message)].join(" ").toLocaleLowerCase().includes(query.toLocaleLowerCase()))});
 const active=questions.find(q=>q.id===activeId)||null,activeIssues=active?flags(active):[],activeOpenEnded=Boolean(active&&["short_answer","essay","calculation"].includes(active.examType||""));
 useEffect(()=>{setSuggestion(null)},[activeId]);
 const summary={p0:issues.filter(x=>x.flags.some(f=>f.severity==="P0")).length,p1:issues.filter(x=>x.flags.some(f=>f.severity==="P1")).length,auto:issues.filter(x=>x.flags.some(f=>f.auto)).length};
 function update(patch:Partial<Question>){if(active)setQuestions(rows=>rows.map(q=>{if(q.id!==active.id)return q;const next={...q,...patch};try{localStorage.setItem(draftKey(documentId,q.id),JSON.stringify(next));localStorage.setItem(lastQuestionKey(documentId),String(q.id));localStorage.setItem(LAST_DOCUMENT_KEY,String(documentId));setDraftSaved(true)}catch{}return next}))}
 async function save(){if(!active||!doc)return;setSaving(true);try{const r=await fetch(endpoints(doc.examCategory),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(active)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"儲存失敗");try{localStorage.removeItem(draftKey(documentId,active.id));const cached:Question[]=JSON.parse(localStorage.getItem(cacheKey(documentId))||"[]");localStorage.setItem(cacheKey(documentId),JSON.stringify(cached.map(q=>q.id===active.id?active:q)));localStorage.setItem(lastQuestionKey(documentId),String(active.id))}catch{}setDraftSaved(false);setNotice("本題已儲存；請再次確認，沒問題後再按「下一題」。")}catch(e){setNotice(e instanceof Error?e.message:"儲存失敗")}finally{setSaving(false)}}
 function openNextQuestion(){if(!filtered.length){setNotice("目前篩選條件下沒有其他待處理題目。");return}const index=filtered.findIndex(item=>item.q.id===activeId),candidate=index>=0?(filtered[index+1]?.q||filtered[0]?.q):filtered[0]?.q;if(!candidate||candidate.id===activeId){setNotice("目前已是最後一題；請重新掃描或更換篩選條件。");return}openQuestion(candidate.id);setNotice(`已開啟第 ${candidate.questionNumber} 題。`)}
 function removeSpacing(){if(!active)return;const clean=(v:string)=>v.replace(/([\u4e00-\u9fff])\s+(?=[\u4e00-\u9fff])/gu,"$1");update({stem:clean(active.stem),options:Object.fromEntries(Object.entries(active.options||{}).map(([k,v])=>[k,clean(v)]))});setNotice("已移除本題中文字間異常空格；請核對原稿後儲存。")}
 function fixLineBreaks(){if(!active)return;update({stem:removeSuspiciousLineBreaks(active.stem),options:Object.fromEntries(Object.entries(active.options||{}).map(([key,value])=>[key,removeSuspiciousLineBreaks(value)])),explanation:removeSuspiciousLineBreaks(active.explanation||"")});setNotice("已自動合併本題中文字中的疑似斷行；請核對 PDF 後儲存。")}
 async function suggestAnswer(){if(!active||!doc)return;setAnswerBusy(true);setSuggestion(null);try{const r=await fetch("/api/admin/question-answer-suggestion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:active.id,category:doc.examCategory})}),d=await r.json();if(!r.ok)throw new Error(d.error||"答案判斷失敗");setSuggestion(d.suggestion);setNotice("已產生答案建議；請對照左側原稿後，由老師確認是否套用。")}catch(e){setNotice(e instanceof Error?e.message:"答案判斷失敗")}finally{setAnswerBusy(false)}}
 const replaceStats=useMemo(()=>{if(!findText)return{questions:0,matches:0};let affected=0,matches=0;for(const q of questions){const count=questionMatchCount(q,findText);if(count){affected++;matches+=count}}return{questions:affected,matches}},[questions,findText]);
 async function applyBulkReplace(){
  if(!doc||!findText||!replaceStats.matches)return;
  const target=replaceText?`「${replaceText}」`:"空白（刪除）";
  if(!window.confirm(`目前文件共有 ${replaceStats.questions} 題、${replaceStats.matches} 處命中。確定將「${findText}」取代為${target}並直接儲存嗎？`))return;
  setReplaceBusy(true);setNotice(`正在批次處理 ${replaceStats.questions} 題…`);
  const changed=questions.filter(q=>questionMatchCount(q,findText)>0).map(q=>replaceQuestion(q,findText,replaceText));
  const succeeded=new Set<number>();let failed=0;
  for(let index=0;index<changed.length;index+=8){const batch=changed.slice(index,index+8);const results=await Promise.all(batch.map(async q=>{try{const response=await fetch(endpoints(doc.examCategory),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(q)});return response.ok}catch{return false}}));results.forEach((ok,itemIndex)=>{if(ok)succeeded.add(batch[itemIndex].id);else failed++})}
  const nextQuestions=questions.map(q=>{const replacement=changed.find(item=>item.id===q.id);return replacement&&succeeded.has(q.id)?replacement:q});
  setQuestions(nextQuestions);try{localStorage.setItem(cacheKey(documentId),JSON.stringify(nextQuestions));for(const id of succeeded)localStorage.removeItem(draftKey(documentId,id))}catch{}
  if(succeeded.has(activeId))setDraftSaved(false);
  setNotice(failed?`批次取代完成 ${succeeded.size} 題，另有 ${failed} 題儲存失敗；請重新掃描後再處理。`:`批次取代完成：${succeeded.size} 題、${replaceStats.matches} 處。`);setReplaceBusy(false)
 }
 const category=doc?.examCategory==="medtech"?"medtech":doc?.examCategory==="data-structure"?"data-structure":"accounting";
 return <main className={`central-quality${focus?" focus-mode":""}${listCollapsed?" list-collapsed":""}`}>
  <nav className="quality-focus-bar"><button onClick={toggleFocus}>{focus?"退出專注":"專注編修"}</button><button onClick={toggleList}>{listCollapsed?"展開題目列":"收合題目列"}</button>{focus&&<span>{doc?.bookTitle||doc?.fileName||"中央題庫"}{active?` · 第 ${active.questionNumber} 題`:""}</span>}</nav>
  <header><div><a href="/admin/question-bank">← 返回總題庫管理</a><span>CENTRAL QUESTION QA</span><h1>中央題庫品質修復中心</h1><p>自動掃描所有類科文件；儲存後留在原題，確認無誤再前往下一題。</p></div><button onClick={()=>void scan(activeId)} disabled={loading}>{loading?"掃描中…":"重新掃描"}</button></header>
  <section className="quality-summary"><article><span>已掃描</span><b>{questions.length}</b></article><article><span>異常題目</span><b>{issues.length}</b></article><article><span>P0 影響題意</span><b>{summary.p0}</b></article><article><span>P1 結構風險</span><b>{summary.p1}</b></article><article><span>可安全處理</span><b>{summary.auto}</b></article></section>
  <section className="quality-tools"><label className="quality-document-search">搜尋文件<input value={docQuery} onChange={e=>setDocQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&visibleDocs[0])chooseDocument(visibleDocs[0].id)}} placeholder="書名、檔名或科目…"/>{docQuery.trim()&&<div className="quality-document-results">{visibleDocs.slice(0,8).map(d=><button type="button" key={d.id} onClick={()=>chooseDocument(d.id)}><b>{d.bookTitle||d.fileName}</b><span>{d.subject} · {d.questionCount} 題</span></button>)}{!visibleDocs.length&&<p>找不到符合的文件</p>}</div>}</label><label>文件<select value={documentId} onChange={e=>chooseDocument(Number(e.target.value))}>{docs.map(d=><option key={d.id} value={d.id}>{d.bookTitle||d.fileName}（{d.questionCount} 題）</option>)}</select></label><label>嚴重度<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">全部</option><option value="P0">P0 影響題意</option><option value="P1">P1 結構風險</option><option value="P2">P2 顯示問題</option><option value="garbled">亂碼／異常字元</option><option value="missing-answer">缺少老師答案</option><option value="open-ended">疑似簡答／申論</option><option value="linebreak">疑似斷行</option></select></label><label>搜尋題目<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="題號、題幹、問題…"/></label></section>
  <section className="quality-bulk-replace"><div><b>批次搜尋取代</b><span>目前文件的題幹、A～D 選項與老師解析；保留富文字格式。</span></div><label>搜尋內容<input value={findText} onChange={e=>setFindText(e.target.value)} placeholder="例如：□ 或錯誤文字"/></label><label>取代為<input value={replaceText} onChange={e=>setReplaceText(e.target.value)} placeholder="留空即批次刪除"/></label><p>{findText?`命中 ${replaceStats.matches} 處・影響 ${replaceStats.questions} 題`:"輸入搜尋內容後，會先計算影響範圍。"}</p><button disabled={replaceBusy||!replaceStats.matches} onClick={()=>void applyBulkReplace()}>{replaceBusy?"批次儲存中…":"確認並全部取代"}</button></section>
  {notice&&<p className="quality-notice">{notice}</p>}
  {active&&!/^(?:[A-D]|NONE)$/.test(String(active.teacherAnswer||active.correctAnswer||"").trim().toUpperCase())&&<section className="quality-answer-review"><div><b>本題沒有正式答案</b><span>維持 P0 並禁止發布；AI 只能提供老師核對用的建議。</span></div><button disabled={answerBusy} onClick={()=>void suggestAnswer()}>{answerBusy?"判斷中…":"AI 協助判斷"}</button>{suggestion&&<article><strong>建議 {suggestion.answer==="NONE"?"無適合選項":suggestion.answer} · {suggestion.confidence==="high"?"較高信心":suggestion.confidence==="medium"?"中等信心":"低信心"}</strong><p>{suggestion.reason}</p><button onClick={()=>{update({teacherAnswer:suggestion.answer,correctAnswer:suggestion.answer});setNotice(`已暫套用建議答案 ${suggestion.answer==="NONE"?"無適合選項":suggestion.answer}；請核對 PDF 後先儲存本題。`)}}>老師確認後套用 {suggestion.answer==="NONE"?"無適合選項":suggestion.answer}</button></article>}</section>}
  <section className="quality-workspace">
   <aside><header><b>待處理問題</b><span>{filtered.length} 題</span></header>{filtered.map(({q,flags:found})=><button className={q.id===activeId?"active":""} key={q.id} onClick={()=>openQuestion(q.id)}><b>第 {q.questionNumber} 題</b><span>{q.year} · {q.subject}</span><small>{found[0].message}</small><em>{found.some(f=>f.severity==="P0")?"P0":found.some(f=>f.severity==="P1")?"P1":"P2"}</em></button>)}</aside>
   <section className="quality-source">{active&&doc?<><header><b>PDF／原稿對照</b><span>{doc.bookTitle||doc.fileName} · {pageMatched?`已定位第 ${pdfPage} 頁`:`暫開第 ${pdfPage} 頁`}</span></header><iframe title="原稿" src={`/api/${category}/admin/document-source?id=${doc.id}#page=${pdfPage}&zoom=page-width`}/></>:<p>選擇待修題目。</p>}</section>
   <article className="quality-editor">{active?<><header><div><b>第 {active.questionNumber} 題</b><span>{active.year} · {active.subject} · {active.examType==="short_answer"?"簡答題":active.examType==="essay"?"申論題":active.examType==="calculation"?"計算題":"選擇題"}{draftSaved?" · 草稿已自動保留":""}</span></div><span className="quality-editor-actions"><button disabled={saving} onClick={()=>void save()}>{saving?"儲存中…":"儲存本題"}</button><button type="button" disabled={saving||!filtered.length} onClick={openNextQuestion}>下一題</button></span></header><div className="quality-detected">{activeIssues.map((f,i)=><p className={f.severity.toLocaleLowerCase()} key={i}><b>{f.severity}</b>{f.message}{f.action==="spacing"&&<button onClick={removeSpacing}>套用安全修復</button>}{f.action==="linebreak"&&<button onClick={fixLineBreaks}>自動合併斷行</button>}{f.action==="classify-open"&&<><button onClick={()=>update({examType:"short_answer"})}>標為簡答題</button><button onClick={()=>update({examType:"essay"})}>標為申論題</button></>}</p>)}</div><div className="quality-meta"><label>年度<input value={active.year} onChange={e=>update({year:e.target.value})}/></label><label>科目<input value={active.subject} onChange={e=>update({subject:e.target.value})}/></label><label>題號<input value={active.questionNumber} onChange={e=>update({questionNumber:e.target.value})}/></label><label>題型<select value={active.examType||"mcq"} onChange={e=>update({examType:e.target.value})}><option value="mcq">選擇題</option><option value="short_answer">簡答題</option><option value="essay">申論題</option><option value="calculation">計算題</option></select></label>{!activeOpenEnded&&<label>老師答案<select value={active.teacherAnswer||active.correctAnswer||""} onChange={e=>update({teacherAnswer:e.target.value,correctAnswer:e.target.value})}><option value="">未設定</option>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}<option value="NONE">無適合選項（A～D 皆不正確）</option></select></label>}</div><RichQuestionEditor category={category} label="題幹" value={active.stem} onChange={stem=>update({stem})}/>{!activeOpenEnded&&["A","B","C","D"].map(key=><RichQuestionEditor compact key={key} category={category} label={`選項 ${key}`} value={active.options?.[key]||""} onChange={value=>update({options:{...active.options,[key]:value}})}/>)}<RichQuestionEditor category={category} label={activeOpenEnded?"老師解答／解析":"解析"} value={active.explanation||""} onChange={explanation=>update({explanation})}/></>:<p>目前沒有待處理題目。</p>}</article>
  </section>
 </main>;
}
