import { requireAccountingAdmin } from "../../../../../lib/member-auth";
import { getOpenAIKey, openAIJson } from "../../../../../lib/openai";

type NodeItem={id:string;label:string;x:number;y:number};
type EdgeItem={from:string;to:string;cost:string;directed:boolean;uncertain:boolean};
type DiagramLabel={text:string;x:number;y:number};
type TableItem={title:string;headers:string[];rows:string[][]};
type DiagramResult={question_text:string;nodes:NodeItem[];edges:EdgeItem[];diagram_labels:DiagramLabel[];tables:TableItem[];extra_text:string[];warnings:string[];confidence:"high"|"medium"|"low"};
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
function outputText(payload:Record<string,unknown>){if(typeof payload.output_text==="string")return payload.output_text.trim();for(const item of Array.isArray(payload.output)?payload.output:[]){const content=item&&typeof item==="object"&&Array.isArray((item as {content?:unknown[]}).content)?(item as {content:unknown[]}).content:[];for(const part of content)if(part&&typeof part==="object"&&typeof (part as {text?:unknown}).text==="string")return (part as {text:string}).text.trim()}return ""}
function svgOf(nodes:NodeItem[],edges:EdgeItem[],labels:DiagramLabel[]){
 const cleanNodes=nodes.slice(0,40).map((node,index)=>({id:String(node.id||index+1).slice(0,24),label:String(node.label||node.id||index+1).slice(0,24),x:Math.max(55,Math.min(745,Number(node.x)||100+index*80)),y:Math.max(55,Math.min(445,Number(node.y)||100))}));
 const byId=new Map(cleanNodes.map(node=>[node.id,node]));
 const cleanLabels=labels.slice(0,20).map(label=>({text:String(label.text||"").slice(0,30),x:Math.max(15,Math.min(785,Number(label.x)||30)),y:Math.max(20,Math.min(480,Number(label.y)||30))}));
 const allX=[...cleanNodes.map(node=>node.x),...cleanLabels.map(label=>label.x)],allY=[...cleanNodes.map(node=>node.y),...cleanLabels.map(label=>label.y)];
 const minX=Math.min(...allX)-48,maxX=Math.max(...allX)+48,minY=Math.min(...allY)-48,maxY=Math.max(...allY)+48;
 const viewWidth=Math.max(180,maxX-minX),viewHeight=Math.max(140,maxY-minY),displayWidth=Math.min(900,Math.max(520,viewWidth*1.4));
 const edgeSvg=edges.slice(0,100).map((edge,index)=>{const from=byId.get(String(edge.from)),to=byId.get(String(edge.to));if(!from||!to)return "";const dx=to.x-from.x,dy=to.y-from.y,length=Math.max(1,Math.hypot(dx,dy)),startX=from.x+dx/length*22,startY=from.y+dy/length*22,endX=to.x-dx/length*25,endY=to.y-dy/length*25,midX=(startX+endX)/2,midY=(startY+endY)/2;return `<g data-edge="${esc(edge.from)}-${esc(edge.to)}" data-from="${esc(edge.from)}" data-to="${esc(edge.to)}"><line x1="${startX}" y1="${startY}" x2="${endX}" y2="${endY}" stroke="#173f5f" stroke-width="2" ${edge.uncertain?'stroke-dasharray="6 4"':""} ${edge.directed?'marker-end="url(#arrowhead)"':""}/><text x="${midX}" y="${midY-7}" text-anchor="middle" font-size="15" fill="#173f5f" paint-order="stroke" stroke="#fff" stroke-width="4">${esc(edge.cost)}</text></g>`}).join("");
 const nodeSvg=cleanNodes.map(node=>`<g data-node="${esc(node.id)}"><circle cx="${node.x}" cy="${node.y}" r="21" fill="#fff" stroke="#173f5f" stroke-width="2"/><text x="${node.x}" y="${node.y+5}" text-anchor="middle" font-size="16" font-weight="700" fill="#173f5f">${esc(node.label)}</text></g>`).join("");
 const labelSvg=cleanLabels.map(label=>`<text x="${label.x}" y="${label.y}" font-size="20" font-weight="800" fill="#173f5f">${esc(label.text)}</text>`).join("");
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${viewWidth} ${viewHeight}" role="img" aria-label="資料結構有向圖" style="display:block;width:min(100%,${displayWidth}px);height:auto;background:transparent"><defs><marker id="arrowhead" markerWidth="10" markerHeight="8" refX="9" refY="4" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L10,4 L0,8 z" fill="#173f5f"/></marker></defs>${edgeSvg}${nodeSvg}${labelSvg}</svg>`;
}
function tableOf(table:TableItem){const width=Math.max(table.headers.length,...table.rows.map(row=>row.length),1);const headers=Array.from({length:width},(_,index)=>`<th>${esc(table.headers[index]||"")}</th>`).join("");const rows=table.rows.map(row=>`<tr>${Array.from({length:width},(_,index)=>`<td>${esc(row[index]||"")}</td>`).join("")}</tr>`).join("");return `<section><p><strong>${esc(table.title)}</strong></p><table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table></section>`}

export async function POST(request:Request){
 const auth=await requireAccountingAdmin(request);if("error" in auth)return auth.error;if(!await getOpenAIKey())return Response.json({error:"資構 AI 模型尚未設定"},{status:503});
 const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||!file.type.startsWith("image/"))return Response.json({error:"請提供資構題目截圖"},{status:400});if(file.size>8_000_000)return Response.json({error:"圖片太大，請先縮小後再辨識"},{status:413});
 const base64=Buffer.from(await file.arrayBuffer()).toString("base64");
 const payload=await openAIJson("/responses",{method:"POST",body:JSON.stringify({model:"gpt-5.6-luna",instructions:"你是資料結構教材圖形辨識員。完整讀取整張題目截圖，不解題、不補造。分開擷取題幹文字、圖中的所有節點、每條連線的起點終點、箭頭方向、cost、表格與表格外文字。節點座標請依原圖相對位置映射到 x=55..745、y=55..445。initial、①、②、③、Step 1 等用來標示各子圖狀態的文字不可放入 question_text 或 extra_text，必須放入 diagram_labels，並提供其在對應子圖左上或旁邊的 x、y。邊方向或 cost 看不清楚時仍列出但 uncertain=true，並寫入 warnings。若無箭頭則 directed=false。BFS/DFS、queue、stack、processSet 等表格必須逐格保留。",input:[{role:"user",content:[{type:"input_text",text:"請將這張資料結構題目拆成可核對的文字、節點、邊、cost、子圖標籤與表格。"},{type:"input_image",image_url:`data:${file.type};base64,${base64}`,detail:"high"}]}],text:{format:{type:"json_schema",name:"data_structure_diagram",strict:true,schema:{type:"object",additionalProperties:false,properties:{question_text:{type:"string"},nodes:{type:"array",items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},label:{type:"string"},x:{type:"number"},y:{type:"number"}},required:["id","label","x","y"]}},edges:{type:"array",items:{type:"object",additionalProperties:false,properties:{from:{type:"string"},to:{type:"string"},cost:{type:"string"},directed:{type:"boolean"},uncertain:{type:"boolean"}},required:["from","to","cost","directed","uncertain"]}},diagram_labels:{type:"array",items:{type:"object",additionalProperties:false,properties:{text:{type:"string"},x:{type:"number"},y:{type:"number"}},required:["text","x","y"]}},tables:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},headers:{type:"array",items:{type:"string"}},rows:{type:"array",items:{type:"array",items:{type:"string"}}}},required:["title","headers","rows"]}},extra_text:{type:"array",items:{type:"string"}},warnings:{type:"array",items:{type:"string"}},confidence:{type:"string",enum:["high","medium","low"]}},required:["question_text","nodes","edges","diagram_labels","tables","extra_text","warnings","confidence"]}}},max_output_tokens:5000})});
 let result:DiagramResult;try{result=JSON.parse(outputText(payload)) as DiagramResult}catch{return Response.json({error:"AI 圖形辨識結果格式錯誤"},{status:502})}
 const question=result.question_text?`<p>${esc(result.question_text).replace(/\n/g,"<br>")}</p>`:"";const extras=result.extra_text.map(text=>`<p>${esc(text)}</p>`).join("");const tables=result.tables.map(tableOf).join("");const warnings=result.warnings.length?`<aside data-diagram-review="true" style="margin:10px 0;padding:10px;border:1px solid #d9a441;background:#fff9e8"><strong>圖形核對提醒</strong><ul>${result.warnings.map(item=>`<li>${esc(item)}</li>`).join("")}</ul></aside>`:"";
 const diagram=result.nodes.length?`<figure data-structure-diagram="true">${svgOf(result.nodes,result.edges,result.diagram_labels||[])}<figcaption>節點 ${result.nodes.length} 個；邊 ${result.edges.length} 條</figcaption></figure>`:"";
 if(!question&&!tables&&!diagram&&!extras)return Response.json({error:"沒有辨識到可轉換的文字、表格或節點圖，請重新裁切後再試"},{status:422});
 return Response.json({html:`${question}${diagram}${tables}${extras}${warnings}`,nodes:result.nodes,edges:result.edges,warnings:result.warnings,confidence:result.confidence});
}
