import { eq } from "drizzle-orm";
import { accountingProducts } from "../../../../../db/schema";
import { requireAccountingAdmin } from "../../../../../lib/member-auth";
import { ACCOUNTING_FIRST_PRODUCT_KEY, getAccountingProductSettings } from "../../../../../lib/accounting-product-settings";
const OWNER="iamflashon@gmail.com";
function date(v:unknown){if(!v)return null;const d=new Date(String(v));if(Number.isNaN(d.getTime()))throw new Error("日期格式錯誤");return d}
function int(v:unknown,min:number,max:number){const n=Number(v);if(!Number.isInteger(n))throw new Error("請輸入完整數字");return Math.min(max,Math.max(min,n))}
export async function GET(request:Request){const auth=await requireAccountingAdmin(request);if("error"in auth)return auth.error;return Response.json({product:await getAccountingProductSettings(auth.db),canManageCommercial:auth.member.email.toLowerCase()===OWNER})}
export async function PATCH(request:Request){const auth=await requireAccountingAdmin(request);if("error"in auth)return auth.error;if(auth.member.email.toLowerCase()!==OWNER)return Response.json({error:"只有總管理者可修改商品設定"},{status:403});try{const b=await request.json();await getAccountingProductSettings(auth.db);const start=date(b.saleStartsAt),end=date(b.saleEndsAt);if(start&&end&&start>end)throw new Error("活動結束時間必須晚於開始時間");await auth.db.update(accountingProducts).set({listPrice:int(b.listPrice,1,1000000),salePrice:b.salePrice===null||b.salePrice===""?null:int(b.salePrice,1,1000000),saleLabel:String(b.saleLabel??"").trim().slice(0,80),saleStartsAt:start,saleEndsAt:end,accessDays:int(b.accessDays,1,3650),trialQuestions:int(b.trialQuestions,0,5000),status:["draft","active","disabled"].includes(b.status)?b.status:"draft",descriptionHtml:String(b.descriptionHtml??"").slice(0,50000),updatedAt:new Date()}).where(eq(accountingProducts.productKey,ACCOUNTING_FIRST_PRODUCT_KEY));return Response.json({product:await getAccountingProductSettings(auth.db)})}catch(e){return Response.json({error:e instanceof Error?e.message:"儲存失敗"},{status:400})}}
