"use client";
import { ClipboardEvent, FormEvent, useRef, useState } from "react";
type Message={role:"student"|"mentor";text:string;source?:string;usage?:{model:string;inputTokens:number;outputTokens:number;durationMs:number;estimatedCostUsd:number}};
type Photo={id:string;src:string;rotation:number;crop:number;enhance:boolean};
const chapters=["財務報導之觀念架構","財務報表的表達","複利及年金","收入認列與衡量","現金及應收帳款","存貨","營業用資產","無形資產、投資性不動產及生物資產","金融工具","負債","股東權益與每股盈餘","租賃","員工福利","所得稅","現金流量表","會計變動及錯誤更正","財務報表分析"];
const starters=["收入認列五步驟怎麼判斷？","請帶我拆解金融資產分類","折舊、減損與重估差在哪裡？"];
const opening="先選章節與題型，再把題目完整貼上來。我不會直接公布答案，第一步會先陪你確認：這一題到底要你求什麼？";
export default function AccountingCoach(){
 const [mode,setMode]=useState<"guided"|"free">("guided"),[level,setLevel]=useState("入門"),[stage,setStage]=useState("讀題"),[chapter,setChapter]=useState(chapters[0]),[questionType,setQuestionType]=useState("選擇題");
 const [messages,setMessages]=useState<Message[]>([{role:"mentor",text:opening}]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[photos,setPhotos]=useState<Photo[]>([]);const endRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null);
 async function renderPhoto(photo:Photo){const image=new Image();image.src=photo.src;await image.decode();const turn=Math.abs(photo.rotation/90)%2===1,margin=Math.round(Math.min(image.width,image.height)*photo.crop/100),sw=image.width-margin*2,sh=image.height-margin*2;const canvas=document.createElement("canvas");canvas.width=turn?sh:sw;canvas.height=turn?sw:sh;const context=canvas.getContext("2d")!;context.translate(canvas.width/2,canvas.height/2);context.rotate(photo.rotation*Math.PI/180);if(photo.enhance)context.filter="contrast(1.35) brightness(1.08) saturate(.25)";context.drawImage(image,margin,margin,sw,sh,-sw/2,-sh/2,sw,sh);return canvas.toDataURL("image/jpeg",.84)}
 async function addFiles(files:File[]){const images=files.filter(file=>file.type.startsWith("image/")).slice(0,2-photos.length);if(!images.length){setError(photos.length>=2?"一次最多兩張；跨頁請依順序放入第 1、2 頁。":"請選擇圖片檔案。");return}const added=await Promise.all(images.map(file=>new Promise<Photo>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),src:String(reader.result),rotation:0,crop:0,enhance:false});reader.onerror=reject;reader.readAsDataURL(file)})));setPhotos(current=>[...current,...added].slice(0,2));setError("")}
 const body=async(rows:Message[],extra:Record<string,unknown>={})=>({messages:rows,mode,level,stage,chapter,questionType,imageDataUrls:await Promise.all(photos.map(renderPhoto)),...extra});
 async function ask(rows:Message[],extra:Record<string,unknown>={}){const response=await fetch("/api/accounting/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(await body(rows,extra))});const result=await response.json() as {reply?:string;source?:string;usage?:Message["usage"];error?:string};if(!response.ok||!result.reply)throw new Error(result.error||"中會 AI 暫時無法回答");return result}
 async function send(value=input){const text=value.trim()||(photos.length?`請依序閱讀這 ${photos.length} 張題目圖片，先帶我讀題，不要直接公布答案。`:"");if(!text||loading)return;const next=[...messages,{role:"student" as const,text}];setMessages(next);setInput("");setError("");setLoading(true);try{const result=await ask(next);setMessages(current=>[...current,{role:"mentor",text:result.reply!,source:result.source,usage:result.usage}])}catch(cause){setError(cause instanceof Error?cause.message:"中會 AI 暫時無法回答")}finally{setLoading(false);requestAnimationFrame(()=>endRef.current?.scrollIntoView({behavior:"smooth",block:"end"}))}}
 async function simulateStudent(simulationLevel:string){if(loading||messages.length<2)return;setLoading(true);setError("");try{const student=await ask(messages,{mode:"guided",level:simulationLevel,simulateStudent:true});const withStudent=[...messages,{role:"student" as const,text:student.reply!}];setMessages(withStudent);const mentor=await ask(withStudent,{mode:"guided",level:simulationLevel});setMessages(current=>[...current,{role:"mentor",text:mentor.reply!,source:mentor.source,usage:mentor.usage}])}catch(cause){setError(cause instanceof Error?cause.message:"模擬學生回答失敗")}finally{setLoading(false)}}
 function switchMode(next:"guided"|"free"){setMode(next);setStage("讀題");setError("");setMessages([{role:"mentor",text:next==="guided"?opening:"把題目、計算過程或看不懂的觀念貼上來，我會完整說明並逐步核對。"}])}
 return <section className="accounting-coach" id="accounting-coach"><header><div><span>中會 AI 教練</span><h2>從一道題開始，一問一答真正算懂</h2></div><small>只檢索已開放的中級會計教材</small></header>
 <nav className="accounting-coach-modes"><button type="button" className={mode==="guided"?"active":""} onClick={()=>switchMode("guided")}><b>引導學習</b><small>章節練題，一次只追問一個步驟</small></button><button type="button" className={mode==="free"?"active":""} onClick={()=>switchMode("free")}><b>自由提問</b><small>直接詢問觀念、準則、計算或分錄</small></button></nav>
 {mode==="guided"&&<section className="accounting-guide-settings"><div className="accounting-guide-pickers"><label><span>練習章節</span><select value={chapter} onChange={e=>setChapter(e.target.value)}>{chapters.map((item,index)=><option value={item} key={item}>第 {index+1} 章｜{item}</option>)}</select></label><label><span>題型</span><select value={questionType} onChange={e=>setQuestionType(e.target.value)}><option>選擇題</option><option>計算題</option><option>觀念題</option></select></label></div><label><span>教學程度</span><div>{["入門","進階","考前"].map(item=><button type="button" className={level===item?"active":""} onClick={()=>setLevel(item)} key={item}>{item}</button>)}</div></label><label><span>目前步驟</span><div className="accounting-guide-steps">{["讀題","條件","準則","計算","核對"].map((item,index)=><button type="button" className={stage===item?"active":""} onClick={()=>setStage(item)} key={item}><small>0{index+1}</small>{item}</button>)}</div></label></section>}
 <div className="accounting-chat" aria-live="polite">{messages.map((message,index)=><article className={message.role} key={`${message.role}-${index}`}><b>{message.role==="mentor"?"中會 AI 教練":"學生"}</b><p>{message.text}</p>{message.role==="mentor"&&message.source&&<small>{message.source}{message.usage?` · ${message.usage.model} · ${message.usage.inputTokens+message.usage.outputTokens} tokens · ${(message.usage.durationMs/1000).toFixed(1)} 秒 · 約 NT$ ${(message.usage.estimatedCostUsd*32.5).toFixed(3)}`:""}</small>}</article>)}{loading&&<article className="mentor loading"><b>中會 AI 教練</b><p>正在依這一步整理下一個問題…</p></article>}<div ref={endRef}/></div>
 <div className="accounting-starters">{mode==="guided"?<><button type="button" onClick={()=>void send("請先帶我讀題，不要公布答案。")}>先幫我讀題</button><button type="button" onClick={()=>void send("我卡住了，請只給我一層提示。")}>給我一個提示</button><button type="button" onClick={()=>void send("請檢查我目前哪一步有問題，但先不要改完。")}>檢查我的步驟</button></>:starters.map(item=><button type="button" onClick={()=>void send(item)} key={item}>{item}</button>)}</div>
 {mode==="guided"&&<div className="accounting-simulated-students"><span>模擬學生回答</span>{["入門","進階","考前"].map(item=><button type="button" disabled={loading||messages.length<2} onClick={()=>void simulateStudent(item)} key={item}>{item}學生</button>)}</div>}
 <section className="accounting-photo-question" onPaste={(event:ClipboardEvent)=>{const files=Array.from(event.clipboardData.files);if(files.length){event.preventDefault();void addFiles(files)}}}><header><div><b>拍照／截圖問題</b><small>最多兩張，跨頁請依第 1、2 頁順序加入</small></div><button type="button" onClick={()=>fileRef.current?.click()} disabled={photos.length>=2}>＋ 上傳圖片／拍照</button><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>{void addFiles(Array.from(e.target.files||[]));e.target.value=""}}/></header>{photos.length?<div className="accounting-photo-grid">{photos.map((photo,index)=><article key={photo.id}><span>第 {index+1} 頁</span><div className="accounting-photo-preview"><img src={photo.src} alt={`題目第 ${index+1} 頁`} style={{transform:`rotate(${photo.rotation}deg) scale(${photo.crop?1.12:1})`,filter:photo.enhance?"contrast(1.35) brightness(1.08) grayscale(.35)":"none"}}/></div><nav><button type="button" onClick={()=>setPhotos(current=>current.map(item=>item.id===photo.id?{...item,crop:item.crop?0:5}:item))}>{photo.crop?"取消裁切":"裁切邊緣"}</button><button type="button" onClick={()=>setPhotos(current=>current.map(item=>item.id===photo.id?{...item,rotation:item.rotation-90}:item))}>↶ 旋轉</button><button type="button" className={photo.enhance?"active":""} onClick={()=>setPhotos(current=>current.map(item=>item.id===photo.id?{...item,enhance:!item.enhance}:item))}>✨ 文字加強</button><button type="button" onClick={()=>setPhotos(current=>current.filter(item=>item.id!==photo.id))}>移除</button></nav></article>)}</div>:<button type="button" className="accounting-paste-zone" onClick={()=>fileRef.current?.click()}>點此上傳、手機拍照，或在此按 Ctrl＋V 貼上截圖</button>}</section>
 <form onSubmit={(e:FormEvent)=>{e.preventDefault();void send()}}><textarea rows={4} value={input} onChange={e=>setInput(e.target.value)} onPaste={e=>{const files=Array.from(e.clipboardData.files);if(files.length){e.preventDefault();void addFiles(files)}}} placeholder={mode==="guided"?"貼上題目，或回答 AI 剛才提出的一個問題…":"輸入觀念、題目或你的計算過程…"}/><button disabled={loading||(!input.trim()&&!photos.length)}>送出</button></form>{error&&<p className="accounting-chat-error">{error}</p>}</section>
}
