"use client";
import { ClipboardEvent, FormEvent, PointerEvent, useRef, useState } from "react";
import { formatTwd } from "../../lib/currency";
type Usage={model:string;inputTokens:number;outputTokens:number;cachedTokens:number;durationMs:number;estimatedCostUsd:number}; type Message={role:"student"|"mentor";text:string;images?:string[];source?:string;usage?:Usage}; type Crop={x:number;y:number;width:number;height:number}; type Photo={id:string;src:string;rotation:number;crop:Crop;enhance:boolean}; type DragMode="move"|"n"|"ne"|"e"|"se"|"s"|"sw"|"w"|"nw";
const fullCrop:Crop={x:0,y:0,width:100,height:100};

function CropDialog({photo,onCancel,onConfirm}:{photo:Photo;onCancel:()=>void;onConfirm:(crop:Crop)=>void}){
 const [crop,setCrop]=useState<Crop>(photo.crop),drag=useRef<{mode:DragMode;x:number;y:number;crop:Crop}|null>(null),stageRef=useRef<HTMLDivElement>(null);
 const begin=(event:PointerEvent,mode:DragMode)=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);drag.current={mode,x:event.clientX,y:event.clientY,crop:{...crop}}};
 const move=(event:PointerEvent)=>{if(!drag.current||!stageRef.current)return;const rect=stageRef.current.getBoundingClientRect(),dx=(event.clientX-drag.current.x)/rect.width*100,dy=(event.clientY-drag.current.y)/rect.height*100,start=drag.current.crop,min=5;let {x,y,width,height}=start;const mode=drag.current.mode;if(mode==="move"){x=Math.max(0,Math.min(100-width,start.x+dx));y=Math.max(0,Math.min(100-height,start.y+dy))}else{if(mode.includes("w")){x=Math.max(0,Math.min(start.x+start.width-min,start.x+dx));width=start.width+(start.x-x)}if(mode.includes("e"))width=Math.max(min,Math.min(100-start.x,start.width+dx));if(mode.includes("n")){y=Math.max(0,Math.min(start.y+start.height-min,start.y+dy));height=start.height+(start.y-y)}if(mode.includes("s"))height=Math.max(min,Math.min(100-start.y,start.height+dy))}setCrop({x,y,width,height})};
 const handles:DragMode[]=["nw","n","ne","e","se","s","sw","w"];
 return <div className="accounting-crop-backdrop" role="dialog" aria-modal="true" aria-label="裁切題目圖片" onPointerMove={move} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><section className="accounting-crop-dialog">
  <header><div><b>裁切題目圖片</b><small>拖曳四個角或四條框線，框內會保留</small></div><button type="button" aria-label="關閉裁切" onClick={onCancel}>×</button></header>
  <div className="accounting-crop-workspace"><div className="accounting-crop-stage" ref={stageRef}><img src={photo.src} alt="完整待裁切題目" draggable={false}/><div className="accounting-crop-box" style={{left:`${crop.x}%`,top:`${crop.y}%`,width:`${crop.width}%`,height:`${crop.height}%`}} onPointerDown={event=>begin(event,"move")}><i className="crop-grid one"/><i className="crop-grid two"/><i className="crop-grid three"/><i className="crop-grid four"/>{(["n","e","s","w"] as DragMode[]).map(edge=><i key={edge} className={`crop-edge ${edge}`} onPointerDown={event=>begin(event,edge)}/>)}{handles.map(handle=><button key={handle} type="button" className={`crop-handle ${handle}`} aria-label={`拖曳裁切框 ${handle}`} onPointerDown={event=>begin(event,handle)}/>)}</div></div></div>
  <footer><button type="button" onClick={()=>setCrop(fullCrop)}>重設整張</button><span>{Math.round(crop.width)}% × {Math.round(crop.height)}%</span><div><button type="button" onClick={onCancel}>取消</button><button type="button" className="primary" onClick={()=>onConfirm(crop)}>確認裁切</button></div></footer>
 </section></div>
}

export default function AccountingCoach(){
 const [messages,setMessages]=useState<Message[]>([{role:"mentor",text:"中級會計哪裡不懂都可以直接問。可以打字、貼計算過程，或上傳最多兩張跨頁照片。"}]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[photos,setPhotos]=useState<Photo[]>([]),[editingId,setEditingId]=useState<string|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 async function addFiles(files:File[]){const accepted=files.filter(file=>file.type.startsWith("image/")).slice(0,2-photos.length);if(!accepted.length){setError(photos.length>=2?"一次最多兩張；跨頁請依順序加入。":"請選擇圖片檔案。");return}const added=await Promise.all(accepted.map(file=>new Promise<Photo>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),src:String(reader.result),rotation:0,crop:{...fullCrop},enhance:false});reader.onerror=reject;reader.readAsDataURL(file)})));setPhotos(current=>[...current,...added]);setError("")}
 async function render(photo:Photo){const image=new Image();image.src=photo.src;await image.decode();const sx=Math.round(image.width*photo.crop.x/100),sy=Math.round(image.height*photo.crop.y/100),sw=Math.max(1,Math.round(image.width*photo.crop.width/100)),sh=Math.max(1,Math.round(image.height*photo.crop.height/100)),turn=Math.abs(photo.rotation/90)%2===1,canvas=document.createElement("canvas");canvas.width=turn?sh:sw;canvas.height=turn?sw:sh;const context=canvas.getContext("2d")!;context.translate(canvas.width/2,canvas.height/2);context.rotate(photo.rotation*Math.PI/180);if(photo.enhance)context.filter="contrast(1.35) brightness(1.08) saturate(.25)";context.drawImage(image,sx,sy,sw,sh,-sw/2,-sh/2,sw,sh);return canvas.toDataURL("image/jpeg",.84)}
 async function send(value=input){const text=value.trim()||(photos.length?`請依序閱讀這 ${photos.length} 張圖片，回答我的中級會計問題。`:"");if(!text||loading)return;setInput("");setLoading(true);setError("");try{const imageDataUrls=await Promise.all(photos.map(render));const next=[...messages,{role:"student" as const,text,images:imageDataUrls.length?imageDataUrls:undefined}];setMessages(next);setPhotos([]);setEditingId(null);const response=await fetch("/api/accounting/tutor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:next.map(({role,text})=>({role,text})),mode:"free",imageDataUrls})});const result=await response.json() as {reply?:string;source?:string;usage?:Usage;error?:string};if(!response.ok||!result.reply)throw new Error(result.error||"Luna 助教暫時無法回答");setMessages(current=>[...current,{role:"mentor",text:result.reply!,source:result.source,usage:result.usage}])}catch(cause){setError(cause instanceof Error?cause.message:"Luna 助教暫時無法回答")}finally{setLoading(false)}}
 const paste=(event:ClipboardEvent)=>{const files=Array.from(event.clipboardData.files);if(files.length){event.preventDefault();void addFiles(files)}};const editing=photos.find(photo=>photo.id===editingId);
 return <section className="accounting-coach" id="accounting-coach"><header><div><span>Luna 助教答疑</span><h2>把不懂的地方直接問出來</h2></div><small>教材只作為回答依據，不需要選書或選章節</small></header>
 <div className="accounting-chat">{messages.map((message,index)=><article className={message.role} key={index}><b>{message.role==="mentor"?"Luna 助教":"學生"}</b><p>{message.text}</p>{message.images&&<div className="accounting-message-images">{message.images.map((src,imageIndex)=><img src={src} alt={`已送出的題目圖片 ${imageIndex+1}`} key={imageIndex}/>)}</div>}{message.source&&<small>{message.source}</small>}{message.usage&&<div className="accounting-usage"><b>{message.usage.model}</b><span>輸入 {message.usage.inputTokens.toLocaleString()}・輸出 {message.usage.outputTokens.toLocaleString()}・合計 {(message.usage.inputTokens+message.usage.outputTokens).toLocaleString()} Tokens</span><span>約 NT$ {formatTwd(message.usage.estimatedCostUsd,4)}・{(message.usage.durationMs/1000).toFixed(1)} 秒</span></div>}</article>)}{loading&&<article className="mentor loading"><b>Luna 助教</b><p>正在整理你的問題與計算步驟…</p></article>}</div>
 <section className={`accounting-photo-question ${photos.length?"has-photos":"compact"}`} onPaste={paste}><header><div><b>{photos.length?"上傳題目／拍照提問":"圖片提問"}</b>{photos.length&&<small>跨頁最多兩張，依頁面順序一起判讀</small>}</div><button type="button" onClick={()=>fileRef.current?.click()} disabled={photos.length>=2}>＋ 上傳圖片／拍照</button><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>{void addFiles(Array.from(e.target.files||[]));e.target.value=""}}/></header>{photos.length>0&&<div className="accounting-photo-grid">{photos.map((photo,index)=><article key={photo.id}><span>第 {index+1} 頁</span><div className="accounting-photo-preview"><img src={photo.src} alt={`題目第 ${index+1} 頁`} style={{transform:`rotate(${photo.rotation}deg)`,filter:photo.enhance?"contrast(1.35) brightness(1.08) grayscale(.35)":"none"}}/></div><nav><button type="button" onClick={()=>setEditingId(photo.id)}>✂ 裁切圖片</button><button type="button" onClick={()=>setPhotos(rows=>rows.map(item=>item.id===photo.id?{...item,rotation:item.rotation-90}:item))}>↶ 旋轉</button><button type="button" className={photo.enhance?"active":""} onClick={()=>setPhotos(rows=>rows.map(item=>item.id===photo.id?{...item,enhance:!item.enhance}:item))}>✨ 文字加強</button><button type="button" onClick={()=>setPhotos(rows=>rows.filter(item=>item.id!==photo.id))}>移除</button></nav></article>)}</div>}</section>
 <form onSubmit={(event:FormEvent)=>{event.preventDefault();void send()}}><textarea rows={4} value={input} onChange={event=>setInput(event.target.value)} onPaste={paste} placeholder="輸入中會觀念、計算、分錄，或說明照片中哪裡看不懂…"/><button disabled={loading||(!input.trim()&&!photos.length)}>送出</button></form>{error&&<p className="accounting-chat-error">{error}</p>}{editing&&<CropDialog photo={editing} onCancel={()=>setEditingId(null)} onConfirm={crop=>{setPhotos(rows=>rows.map(item=>item.id===editing.id?{...item,crop}:item));setEditingId(null)}}/>}</section>
}
