"use client";
import { useEffect,useState } from "react";
type Doc={id:number;name:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;error?:string;chapterCount:number;questionCount:number;homepageSearchEnabled:boolean;vectorIndexed:boolean};
export default function DataStructureAdmin(){
 const [docs,setDocs]=useState<Doc[]>([]),[file,setFile]=useState<File|null>(null),[type,setType]=useState("核心教材"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[processingId,setProcessingId]=useState<number|null>(null);
 async function load(){const r=await fetch("/api/data-structure/documents",{cache:"no-store"});const d=await r.json() as {documents?:Doc[];error?:string};setDocs(d.documents??[]);if(!r.ok)setNotice(d.error??"讀取失敗")}
 useEffect(()=>{void load()},[]);
 async function process(id:number,retry=false,reanalyze=false){if(processingId!==null)return;setProcessingId(id);setNotice("正在擷取章節、圖表說明、演算法步驟並建立檢索索引…");try{for(let i=0;i<35;i++){const r=await fetch("/api/data-structure/documents/process",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,retry:retry&&i===0,reanalyze:reanalyze&&i===0})});const d=await r.json() as {status?:string;message?:string;error?:string};setNotice(d.message??d.error??"處理中…");await load();if(!r.ok||d.status==="completed")return;await new Promise(resolve=>setTimeout(resolve,2200))}}catch(error){setNotice(error instanceof Error?error.message:"處理失敗") }finally{setProcessingId(null);await load()}}
 async function upload(){if(!file){setNotice("請先選擇教材文件。");return}setBusy(true);try{const contentType=file.name.toLowerCase().endsWith(".pdf")?"application/pdf":file.type||"application/octet-stream";const initR=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"init",fileName:file.name,contentType})});const init=await initR.json() as {key?:string;uploadId?:string;error?:string};if(!initR.ok||!init.key||!init.uploadId)throw new Error(init.error||"無法開始上傳");const chunkSize=5*1024*1024,parts:Array<{partNumber:number;etag:string}>=[];for(let start=0,n=1;start<file.size;start+=chunkSize,n++){setNotice(`教材上傳中：${Math.min(100,Math.round(start/file.size*100))}%`);const r=await fetch(`/api/documents/multipart?key=${encodeURIComponent(init.key)}&uploadId=${encodeURIComponent(init.uploadId)}&partNumber=${n}`,{method:"PUT",headers:{"content-type":"application/octet-stream"},body:file.slice(start,Math.min(start+chunkSize,file.size))});const p=await r.json() as {partNumber?:number;etag?:string;error?:string};if(!r.ok||!p.partNumber||!p.etag)throw new Error(p.error||`第 ${n} 段上傳失敗`);parts.push({partNumber:p.partNumber,etag:p.etag})}const doneR=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",key:init.key,uploadId:init.uploadId,parts,fileName:file.name,contentType,sizeBytes:file.size,examCategory:"data-structure",subject:"資料結構",documentType:type})});const done=await doneR.json() as {document?:{id:number};error?:string};if(!doneR.ok||!done.document)throw new Error(done.error||"無法完成上傳");setFile(null);await load();await process(done.document.id)}catch(error){setNotice(error instanceof Error?error.message:"上傳失敗")}finally{setBusy(false)}}
 async function toggle(doc:Doc){const r=await fetch("/api/data-structure/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,homepageSearchEnabled:!doc.homepageSearchEnabled})});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error??"設定失敗");return}await load()}
 return <main className="accounting-admin-page data-structure-admin-page"><header className="accounting-top"><a href="/data-structure" className="accounting-brand"><span>資</span><div><b>資料結構管理後台</b><small>CONTENT ADMIN</small></div></a><nav><a href="/data-structure">學生首頁</a></nav></header>
  <section className="accounting-admin-hero"><span>資料結構 · 獨立教材空間</span><h1>教材上傳與自動拆解</h1><p>固定歸入資料結構類科，不會混入中會、司律或醫檢師的教材與搜尋結果。</p></section>
  <section className="accounting-admin-panel"><h2>上傳教材</h2><div className="accounting-upload-form"><label>科目<input value="資料結構" readOnly/></label><label>用途<select value={type} onChange={e=>setType(e.target.value)}><option>核心教材</option><option>題庫與解析</option><option>考題與詳解</option><option>補充講義</option></select></label><label className="file">選擇教材<input type="file" accept=".pdf,.docx,.txt,.md,.json,.jsonl,.zip" onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{file?.name??"尚未選擇文件"}</span></label><button disabled={busy} onClick={()=>void upload()}>{busy?"自動處理中…":"上傳並自動處理"}</button></div>{notice&&<p className="accounting-admin-notice">{notice}</p>}</section>
  <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>資料結構教材清單</h2><small>拆解後可個別控制是否提供學生首頁檢索。</small></div><button onClick={()=>void load()}>重新整理</button></div><div className="accounting-document-list">{docs.map(doc=><article key={doc.id}><div><small>{doc.subject} · {doc.type}</small><h3>{doc.name}</h3><p>{(doc.sizeBytes/1024/1024).toFixed(2)} MB</p></div><div><b>{processingId===doc.id?"正在拆解…":doc.processingStage==="completed"?"處理完成":"處理中"}</b><p>{doc.error||doc.processingMessage}</p></div><div className="counts"><b>{doc.chapterCount}<small> 章／單元</small></b><b>{doc.questionCount}<small> 題／例題</small></b></div><div className="actions">{doc.processingStage!=="completed"?<button disabled={processingId!==null} onClick={()=>void process(doc.id,doc.status==="failed")}>{processingId===doc.id?"處理中…":"繼續處理"}</button>:<button disabled={processingId!==null} onClick={()=>void process(doc.id,false,true)}>重新建立索引</button>}<label><input type="checkbox" checked={doc.homepageSearchEnabled} onChange={()=>void toggle(doc)} disabled={!doc.vectorIndexed||processingId!==null}/>允許 Luna 助教搜尋</label></div></article>)}{!docs.length&&<p>尚未上傳資料結構教材。</p>}</div></section>
 </main>
}
