"use client";
import { unzipSync } from "fflate";
import { useEffect,useState } from "react";
type Doc={id:number;name:string;subject:string;type:string;sizeBytes:number;status:string;processingStage:string;processingMessage:string;error?:string;chapterCount:number;questionCount:number;homepageSearchEnabled:boolean;vectorIndexed:boolean};
type BatchRow={id:string;name:string;size:number;status:"waiting"|"uploading"|"processing"|"completed"|"failed"|"skipped";progress:number;message:string};
const allowed=/\.(pdf|docx|txt|md|json|jsonl)$/i;
function mime(name:string){const ext=name.split(".").pop()?.toLowerCase();return ext==="pdf"?"application/pdf":ext==="docx"?"application/vnd.openxmlformats-officedocument.wordprocessingml.document":ext==="json"||ext==="jsonl"?"application/json":"text/plain"}
export default function DataStructureAdmin(){
 const [docs,setDocs]=useState<Doc[]>([]),[files,setFiles]=useState<File[]>([]),[type,setType]=useState("核心教材"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[processingId,setProcessingId]=useState<number|null>(null),[batch,setBatch]=useState<BatchRow[]>([]),[bulkToggling,setBulkToggling]=useState(false);
 async function load(){const r=await fetch("/api/data-structure/documents",{cache:"no-store"});const d=await r.json() as {documents?:Doc[];error?:string};setDocs(d.documents??[]);if(!r.ok)setNotice(d.error??"讀取失敗")}
 useEffect(()=>{void load()},[]);
 function updateBatch(id:string,patch:Partial<BatchRow>){setBatch(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))}
 async function process(id:number,retry=false,reanalyze=false,onMessage?:(message:string)=>void){if(processingId!==null&&!onMessage)return;setProcessingId(id);const initial="正在擷取文字、圖形節點與父子關係，並建立檢索索引…";setNotice(initial);onMessage?.(initial);try{for(let i=0;i<35;i++){const r=await fetch("/api/data-structure/documents/process",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:id,retry:retry&&i===0,reanalyze:reanalyze&&i===0})});const d=await r.json() as {status?:string;message?:string;error?:string};const message=d.message??d.error??"處理中…";setNotice(message);onMessage?.(message);await load();if(!r.ok)throw new Error(d.error||message);if(d.status==="completed")return;await new Promise(resolve=>setTimeout(resolve,2200))}throw new Error("處理時間較長，已保留進度，可稍後按繼續處理")}finally{setProcessingId(null);await load()}}
 async function expand(selected:File[]){const expanded:File[]=[];for(const file of selected){if(!file.name.toLowerCase().endsWith(".zip")){if(allowed.test(file.name))expanded.push(file);continue}const entries=unzipSync(new Uint8Array(await file.arrayBuffer()));for(const [path,bytes] of Object.entries(entries)){const name=path.split("/").pop()||"";if(!name||path.includes("__MACOSX")||name.startsWith(".")||!allowed.test(name))continue;expanded.push(new File([new Uint8Array(bytes)],name,{type:mime(name)}))}}return expanded.slice(0,50)}
 async function choose(selected:File[]){try{const unpacked=await expand(selected);setFiles(unpacked);setBatch(unpacked.map(file=>({id:crypto.randomUUID(),name:file.name,size:file.size,status:"waiting",progress:0,message:"等待上傳"})));setNotice(unpacked.length?`已選取 ${unpacked.length} 本教材；可開始批次上傳。`:"沒有找到可處理的教材檔案。")}catch{setFiles([]);setBatch([]);setNotice("ZIP 無法解壓縮，請確認檔案未加密且格式正確。")}}
 async function uploadOne(file:File,row:BatchRow){const contentType=mime(file.name);updateBatch(row.id,{status:"uploading",message:"準備上傳"});const initR=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"init",fileName:file.name,contentType})}),init=await initR.json() as {key?:string;uploadId?:string;error?:string};if(!initR.ok||!init.key||!init.uploadId)throw new Error(init.error||"無法開始上傳");const chunkSize=5*1024*1024,parts:Array<{partNumber:number;etag:string}>=[];for(let start=0,n=1;start<file.size;start+=chunkSize,n++){const progress=Math.min(99,Math.round(start/file.size*100));updateBatch(row.id,{progress,message:`上傳中 ${progress}%`});const r=await fetch(`/api/documents/multipart?key=${encodeURIComponent(init.key)}&uploadId=${encodeURIComponent(init.uploadId)}&partNumber=${n}`,{method:"PUT",headers:{"content-type":"application/octet-stream"},body:file.slice(start,Math.min(start+chunkSize,file.size))}),part=await r.json() as {partNumber?:number;etag?:string;error?:string};if(!r.ok||!part.partNumber||!part.etag)throw new Error(part.error||`第 ${n} 段上傳失敗`);parts.push({partNumber:part.partNumber,etag:part.etag})}const doneR=await fetch("/api/documents/multipart",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",key:init.key,uploadId:init.uploadId,parts,fileName:file.name,contentType,sizeBytes:file.size,examCategory:"data-structure",subject:"資料結構",documentType:type})}),done=await doneR.json() as {document?:{id:number};error?:string};if(!doneR.ok||!done.document)throw new Error(done.error||"無法完成上傳");updateBatch(row.id,{status:"processing",progress:100,message:"上傳完成，正在拆解與索引"});await process(done.document.id,false,false,message=>updateBatch(row.id,{message}));updateBatch(row.id,{status:"completed",progress:100,message:"教材拆解與索引完成"})}
 async function upload(){if(!files.length){setNotice("請先選擇教材文件或 ZIP。");return}setBusy(true);const existing=new Set(docs.map(doc=>doc.name.toLowerCase())),rows=[...batch];let completed=0,failed=0,skipped=0;for(let index=0;index<files.length;index++){const file=files[index],row=rows[index];if(existing.has(file.name.toLowerCase())){updateBatch(row.id,{status:"skipped",message:"已有同名教材，已略過"});skipped++;continue}try{await uploadOne(file,row);existing.add(file.name.toLowerCase());completed++}catch(error){updateBatch(row.id,{status:"failed",message:error instanceof Error?error.message:"處理失敗"});failed++}}setBusy(false);await load();setFiles([]);setNotice(`批次完成：成功 ${completed} 本${skipped?`、略過 ${skipped} 本`:""}${failed?`、失敗 ${failed} 本`:""}。`)}
 async function toggle(doc:Doc){const r=await fetch("/api/data-structure/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,homepageSearchEnabled:!doc.homepageSearchEnabled})});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error??"設定失敗");return}await load()}
 async function enableAllSearch(){const eligible=docs.filter(doc=>doc.vectorIndexed&&!doc.homepageSearchEnabled);if(!eligible.length){setNotice("所有已完成索引的教材都已開放 Luna 搜尋。");return}setBulkToggling(true);setNotice(`正在開放 ${eligible.length} 本教材供 Luna 搜尋…`);let completed=0,failed=0;for(const doc of eligible){try{const r=await fetch("/api/data-structure/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:doc.id,homepageSearchEnabled:true})});if(r.ok)completed++;else failed++}catch{failed++}}try{await load()}finally{setBulkToggling(false);setNotice(`已開放 ${completed} 本教材供 Luna 搜尋${failed?`；${failed} 本設定失敗，可再按一次重試`:"。"}`)}}
 return <main className="accounting-admin-page data-structure-admin-page"><header className="accounting-top"><a href="/data-structure" className="accounting-brand"><span>資</span><div><b>資料結構管理後台</b><small>CONTENT ADMIN</small></div></a><nav><a href="/data-structure">學生首頁</a></nav></header>
  <section className="accounting-admin-hero"><span>資料結構 · 獨立教材空間</span><h1>教材上傳與自動拆解</h1><p>固定歸入資料結構類科，不會混入中會、司律或醫檢師的教材與搜尋結果。</p></section>
  <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>批次上傳教材</h2><small>可一次選取多個檔案，或上傳 ZIP 自動解壓；每批最多 50 本。</small></div></div><div className="accounting-upload-form"><label>科目<input value="資料結構" readOnly/></label><label>用途<select value={type} onChange={e=>setType(e.target.value)}><option>核心教材</option><option>題庫與解析</option><option>考題與詳解</option><option>補充講義</option></select></label><label className="file">選擇教材／ZIP<input type="file" multiple accept=".pdf,.docx,.txt,.md,.json,.jsonl,.zip" onChange={e=>void choose(Array.from(e.target.files??[]))}/><span>{files.length?`已選取 ${files.length} 本教材`:"可多選檔案或選擇 ZIP"}</span></label><button disabled={busy||!files.length} onClick={()=>void upload()}>{busy?"批次處理中…":`上傳並自動處理${files.length?`（${files.length}）`:""}`}</button></div>{notice&&<p className="accounting-admin-notice">{notice}</p>}{batch.length>0&&<div className="data-batch-list">{batch.map(row=><article key={row.id} className={row.status}><div><b>{row.name}</b><small>{(row.size/1024/1024).toFixed(2)} MB</small></div><div className="data-batch-progress"><i style={{width:`${row.progress}%`}}/><span>{row.message}</span></div><strong>{row.status==="waiting"?"等待中":row.status==="uploading"?"上傳中":row.status==="processing"?"拆解中":row.status==="completed"?"已完成":row.status==="skipped"?"已略過":"失敗"}</strong></article>)}</div>}</section>
  <section className="accounting-admin-panel"><div className="accounting-admin-heading"><div><h2>資料結構教材清單</h2><small>拆解後可個別控制是否提供學生首頁檢索。</small></div><div><button className="search-all" disabled={bulkToggling||busy||processingId!==null||!docs.some(doc=>doc.vectorIndexed&&!doc.homepageSearchEnabled)} onClick={()=>void enableAllSearch()}>{bulkToggling?"正在開放…":"一鍵開放 Luna 搜尋"}</button><button onClick={()=>void load()}>重新整理</button></div></div><div className="accounting-document-list">{docs.map(doc=><article key={doc.id}><div><small>{doc.subject} · {doc.type}</small><h3>{doc.name}</h3><p>{(doc.sizeBytes/1024/1024).toFixed(2)} MB</p></div><div><b>{processingId===doc.id?"正在拆解…":doc.processingStage==="completed"?"處理完成":"處理中"}</b><p>{doc.error||doc.processingMessage}</p></div><div className="counts"><b>{doc.chapterCount}<small> 章／單元</small></b><b>{doc.questionCount}<small> 題／例題</small></b></div><div className="actions">{doc.processingStage!=="completed"?<button disabled={processingId!==null||busy} onClick={()=>void process(doc.id,doc.status==="failed")}>{processingId===doc.id?"處理中…":"繼續處理"}</button>:<button disabled={processingId!==null||busy} onClick={()=>void process(doc.id,false,true)}>重新建立索引</button>}<label><input type="checkbox" checked={doc.homepageSearchEnabled} onChange={()=>void toggle(doc)} disabled={!doc.vectorIndexed||processingId!==null||busy}/>允許 Luna 助教搜尋</label></div></article>)}{!docs.length&&<p>尚未上傳資料結構教材。</p>}</div></section>
 </main>
}
