import { and,eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { appSettings,documents,usageLogs } from "../../../../db/schema";
import { getOpenAIKey,openAIJson } from "../../../../lib/openai";
import { estimateCostUsdMicros } from "../../../../lib/usage";
import { requireAdmin } from "../../../../lib/member-auth";

type Turn={role:"student"|"mentor";text:string};
type Diagram={title:string;nodes:Array<{id:string;label:string;x:number;y:number;active?:boolean}>;edges:Array<{from:string;to:string;label?:string;directed?:boolean}>};
function outputText(payload:Record<string,unknown>){if(typeof payload.output_text==="string")return payload.output_text.trim();const output=Array.isArray(payload.output)?payload.output:[];return output.flatMap(item=>typeof item==="object"&&item&&Array.isArray((item as {content?:unknown[]}).content)?(item as {content:unknown[]}).content:[]).map(item=>typeof item==="object"&&item&&typeof(item as {text?:unknown}).text==="string"?(item as {text:string}).text:"").join("\n").trim()}
function fileResults(payload:Record<string,unknown>){const output=Array.isArray(payload.output)?payload.output:[];return output.flatMap(item=>{if(!item||typeof item!=="object"||(item as {type?:string}).type!=="file_search_call")return[];const rows=Array.isArray((item as {results?:unknown[]}).results)?(item as {results:unknown[]}).results:[];return rows.filter((row):row is Record<string,unknown>=>Boolean(row&&typeof row==="object"))})}
function cleanName(value:string){return value.replace(/\.(pdf|docx?|txt|md)$/iu,"").replace(/^\d{12,}_/u,"").trim()}
function parseReply(raw:string){const marker="\n【SVG_DATA】";const index=raw.indexOf(marker);if(index<0)return{reply:raw.trim()};const reply=raw.slice(0,index).trim(),json=raw.slice(index+marker.length).trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();try{const parsed=JSON.parse(json) as Diagram;if(!parsed.title||!Array.isArray(parsed.nodes)||!Array.isArray(parsed.edges)||parsed.nodes.length>24)return{reply};const ids=new Set(parsed.nodes.map(node=>String(node.id)));const nodes=parsed.nodes.map(node=>({id:String(node.id).slice(0,30),label:String(node.label).slice(0,20),x:Math.max(40,Math.min(760,Number(node.x)||400)),y:Math.max(40,Math.min(380,Number(node.y)||200)),active:Boolean(node.active)}));const edges=parsed.edges.filter(edge=>ids.has(String(edge.from))&&ids.has(String(edge.to))).map(edge=>({from:String(edge.from),to:String(edge.to),label:edge.label?String(edge.label).slice(0,16):undefined,directed:edge.directed!==false}));return{reply,diagram:{title:String(parsed.title).slice(0,80),nodes,edges}}}catch{return{reply}}}

export async function POST(request:Request){try{
 const body=await request.json() as {messages?:Turn[];simulateStudent?:boolean;imageDataUrls?:string[]};if(body.simulateStudent){const auth=await requireAdmin(request);if("error" in auth)return auth.error}
 const messages=(body.messages??[]).filter(item=>item&&["student","mentor"].includes(item.role)&&typeof item.text==="string").slice(-10),latest=[...messages].reverse().find(item=>item.role==="student")?.text.trim();if(!latest)return Response.json({error:"請先輸入資料結構問題。"},{status:400});if(!await getOpenAIKey())return Response.json({error:"Luna 助教模型尚未設定。"},{status:503});
 const db=await getDb(),[setting]=await db.select().from(appSettings).where(eq(appSettings.key,"openai_vector_store_id")).limit(1);const enabled=await db.select({fileName:documents.fileName,openaiFileId:documents.openaiFileId,subject:documents.subject,documentType:documents.documentType}).from(documents).where(and(eq(documents.examCategory,"data-structure"),eq(documents.homepageSearchEnabled,true),eq(documents.vectorIndexed,true)));
 if(setting?.value&&enabled.length)await Promise.all(enabled.map(doc=>doc.openaiFileId?openAIJson(`/vector_stores/${setting.value}/files/${doc.openaiFileId}`,{method:"POST",body:JSON.stringify({attributes:{exam_category:"data-structure",subject:doc.subject,document_type:doc.documentType,source_file:doc.fileName,homepage_enabled:true}})}).catch(()=>null):null));
 const conversation=messages.map(item=>`${item.role==="student"?"學生":"Luna 助教"}：${item.text.slice(0,2600)}`).join("\n\n"),images=(body.imageDataUrls??[]).filter(value=>/^data:image\/(?:jpeg|png|webp);base64,/.test(value)&&value.length<4_500_000).slice(0,2),allowSearch=Boolean(setting?.value&&enabled.length),model="gpt-5.6-luna",started=Date.now();
 const input=images.length&&!body.simulateStudent?[{role:"user",content:[{type:"input_text",text:`${conversation}\n\n請依圖片順序閱讀圖形、節點、箭頭與題目。`},...images.map(image_url=>({type:"input_image",image_url}))]}]:conversation;
 const diagramRule="若本題涉及樹、圖、鏈結串列、堆疊、佇列、雜湊或排序流程，而且畫圖確實能幫助理解，回答正文後另起一行輸出【SVG_DATA】，下一行只輸出合法 JSON：{title,nodes:[{id,label,x,y,active}],edges:[{from,to,label,directed}]}。畫布 800x420，座標須避免節點重疊，節點最多 24 個。若不需要圖，完全不要輸出標記。";
 const instructions=body.simulateStudent?"你是資料結構初學學生。閱讀助教最後回答，只提出一個有禮貌、自然、具體的接續問題，不要回答問題，也不要更換主題。":"你是資料結構課業答疑的 Luna 助教。以繁體中文回答，只處理資料結構、演算法、複雜度與程式流程，不得混入中會、法律或醫檢內容。先給簡短結論，再用必要步驟說明；若資料不足，指出缺少的節點、邊、操作順序或條件，不可補造。已開放教材時必須先搜尋並以更正版優先。圖形題要把節點、邊、方向與走訪順序說清楚。"+diagramRule;
 const payload=await openAIJson("/responses",{method:"POST",body:JSON.stringify({model,instructions,input,...(allowSearch?{tools:[{type:"file_search",vector_store_ids:[setting!.value],max_num_results:10,filters:{type:"and",filters:[{key:"exam_category",type:"eq",value:"data-structure"},{key:"homepage_enabled",type:"eq",value:true}]}}],tool_choice:"required",include:["file_search_call.results"]}:{}),max_output_tokens:3200})}) as Record<string,unknown>;
 const parsed=parseReply(outputText(payload));if(!parsed.reply)return Response.json({error:"Luna 助教暫時沒有完成回答。"},{status:502});const usage=(payload.usage??{}) as {input_tokens?:number;output_tokens?:number;input_tokens_details?:{cached_tokens?:number}},inputTokens=Number(usage.input_tokens||0),outputTokens=Number(usage.output_tokens||0),cachedTokens=Number(usage.input_tokens_details?.cached_tokens||0),cost=estimateCostUsdMicros(model,{inputTokens,outputTokens,cachedTokens}),results=fileResults(payload);await db.insert(usageLogs).values({model,source:"資料結構首頁 AI",inputTokens,outputTokens,cachedTokens,fileSearchCalls:results.length?1:0,estimatedCostUsdMicros:cost});const names=[...new Set(results.map(row=>cleanName(String(row.filename??""))).filter(Boolean))].slice(0,3);
 return Response.json({...parsed,source:results.length?`依據來源：${names.length?names.join("、"):"資料結構教材相關片段"}`:allowSearch?"本次已搜尋，但未命中已開放教材":"尚無已開放搜尋的資料結構教材，以下為 AI 一般知識說明",usage:{model:"Luna",inputTokens,outputTokens,cachedTokens,durationMs:Date.now()-started,estimatedCostUsd:cost/1_000_000}})
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Luna 助教回答失敗"},{status:500})}}
