import { and,eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { appSettings,documents,usageLogs } from "../../../../db/schema";
import { getOpenAIKey,openAIJson } from "../../../../lib/openai";
import { estimateCostUsdMicros } from "../../../../lib/usage";
import { requireAdmin } from "../../../../lib/member-auth";

type Turn={role:"student"|"mentor";text:string};
type Diagram={title:string;layout?:"free"|"growth-order";items?:Array<{id:string;label:string;formula:string;detail?:string}>;notes?:Array<{itemId:string;title:string;detail:string}>;nodes:Array<{id:string;label:string;detail?:string;x:number;y:number;active?:boolean;shape?:"circle"|"box"|"label"}>;edges:Array<{from:string;to:string;label?:string;directed?:boolean;dashed?:boolean}>};
function outputText(payload:Record<string,unknown>){if(typeof payload.output_text==="string")return payload.output_text.trim();const output=Array.isArray(payload.output)?payload.output:[];return output.flatMap(item=>typeof item==="object"&&item&&Array.isArray((item as {content?:unknown[]}).content)?(item as {content:unknown[]}).content:[]).map(item=>typeof item==="object"&&item&&typeof(item as {text?:unknown}).text==="string"?(item as {text:string}).text:"").join("\n").trim()}
function fileResults(payload:Record<string,unknown>){const output=Array.isArray(payload.output)?payload.output:[];return output.flatMap(item=>{if(!item||typeof item!=="object"||(item as {type?:string}).type!=="file_search_call")return[];const rows=Array.isArray((item as {results?:unknown[]}).results)?(item as {results:unknown[]}).results:[];return rows.filter((row):row is Record<string,unknown>=>Boolean(row&&typeof row==="object"))})}
function cleanName(value:string){return value.replace(/\.(pdf|docx?|txt|md)$/iu,"").replace(/^\d{12,}_/u,"").trim()}
function parseReply(raw:string){const marker="\n【SVG_DATA】";const index=raw.indexOf(marker);if(index<0)return{reply:raw.trim(),diagramTokens:0};const reply=raw.slice(0,index).trim(),json=raw.slice(index+marker.length).trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();try{const parsed=JSON.parse(json) as Diagram;if(!parsed.title||!Array.isArray(parsed.nodes)||!Array.isArray(parsed.edges)||parsed.nodes.length>24)return{reply,diagramTokens:0};const ids=new Set(parsed.nodes.map(node=>String(node.id)));const nodes=parsed.nodes.map(node=>({id:String(node.id).slice(0,30),label:String(node.label).slice(0,32),detail:node.detail?String(node.detail).slice(0,48):undefined,x:Math.max(40,Math.min(760,Number(node.x)||400)),y:Math.max(40,Math.min(380,Number(node.y)||200)),active:Boolean(node.active),shape:(["circle","box","label"].includes(String(node.shape))?node.shape:"circle") as "circle"|"box"|"label"}));const edges=parsed.edges.filter(edge=>ids.has(String(edge.from))&&ids.has(String(edge.to))).map(edge=>({from:String(edge.from),to:String(edge.to),label:edge.label?String(edge.label).slice(0,20):undefined,directed:edge.directed!==false,dashed:Boolean(edge.dashed)}));const items=(Array.isArray(parsed.items)?parsed.items:[]).slice(0,8).map(item=>({id:String(item.id).slice(0,20),label:String(item.label).slice(0,16),formula:String(item.formula).slice(0,28),detail:item.detail?String(item.detail).slice(0,30):undefined})),itemIds=new Set(items.map(item=>item.id)),notes=(Array.isArray(parsed.notes)?parsed.notes:[]).filter(note=>itemIds.has(String(note.itemId))).slice(0,3).map(note=>({itemId:String(note.itemId),title:String(note.title).slice(0,24),detail:String(note.detail).slice(0,42)})),layout=parsed.layout==="growth-order"&&items.length>1?"growth-order":"free";return{reply,diagram:{title:String(parsed.title).slice(0,80),layout,items,notes,nodes,edges},diagramTokens:Math.ceil(json.length/4)}}catch{return{reply,diagramTokens:0}}}

export async function POST(request:Request){try{
 const body=await request.json() as {messages?:Turn[];simulateStudent?:boolean;imageDataUrls?:string[]};if(body.simulateStudent){const auth=await requireAdmin(request);if("error" in auth)return auth.error}
 const messages=(body.messages??[]).filter(item=>item&&["student","mentor"].includes(item.role)&&typeof item.text==="string").slice(-10),latest=[...messages].reverse().find(item=>item.role==="student")?.text.trim();if(!latest)return Response.json({error:"請先輸入資料結構問題。"},{status:400});if(!await getOpenAIKey())return Response.json({error:"Luna 助教模型尚未設定。"},{status:503});
 const db=await getDb(),[setting]=await db.select().from(appSettings).where(eq(appSettings.key,"openai_vector_store_id")).limit(1);const enabled=await db.select({fileName:documents.fileName,openaiFileId:documents.openaiFileId,subject:documents.subject,documentType:documents.documentType}).from(documents).where(and(eq(documents.examCategory,"data-structure"),eq(documents.homepageSearchEnabled,true),eq(documents.vectorIndexed,true)));
 if(setting?.value&&enabled.length)await Promise.all(enabled.map(doc=>doc.openaiFileId?openAIJson(`/vector_stores/${setting.value}/files/${doc.openaiFileId}`,{method:"POST",body:JSON.stringify({attributes:{exam_category:"data-structure",subject:doc.subject,document_type:doc.documentType,source_file:doc.fileName,homepage_enabled:true}})}).catch(()=>null):null));
 const conversation=messages.map(item=>`${item.role==="student"?"學生":"Luna 助教"}：${item.text.slice(0,2600)}`).join("\n\n"),images=(body.imageDataUrls??[]).filter(value=>/^data:image\/(?:jpeg|png|webp);base64,/.test(value)&&value.length<4_500_000).slice(0,2),allowSearch=Boolean(setting?.value&&enabled.length),model="gpt-5.6-luna",started=Date.now();
 const input=images.length&&!body.simulateStudent?[{role:"user",content:[{type:"input_text",text:`${conversation}\n\n請依圖片順序閱讀圖形、節點、箭頭與題目。`},...images.map(image_url=>({type:"input_image",image_url}))]}]:conversation;
 const diagramRule="若教材解答含圖，或本題涉及樹、圖、鏈結串列、堆疊、佇列、雜湊、排序流程、成長率排序或公式關係，且圖解能幫助理解，必須依教材可確認內容重繪。正文後另起一行輸出【SVG_DATA】，下一行只輸出合法 JSON。成長率或函數排序一律使用固定版型：{title,layout:'growth-order',items:[{id,label,formula,detail}],notes:[{itemId,title,detail}],nodes:[],edges:[]}；items 必須依由慢到快排列，最多 8 項，座標完全不要輸出，系統會自動平均排版。其他樹與圖使用：{title,layout:'free',items:[],notes:[],nodes:[{id,label,detail,x,y,active,shape}],edges:[{from,to,label,directed,dashed}]}。不可把教材圖交給圖片生成模型，不可猜測看不清的公式。若不需要圖，完全不要輸出標記。";
 const instructions=body.simulateStudent?"你是資料結構初學學生。閱讀助教最後回答，只提出一個有禮貌、自然、具體的接續問題，不要回答問題，也不要更換主題。":"你是資料結構課業答疑的 Luna 助教。以繁體中文回答，只處理資料結構、演算法、複雜度與程式流程，不得混入中會、法律或醫檢內容。先給簡短結論，再用必要步驟說明；若資料不足，指出缺少的節點、邊、操作順序或條件，不可補造。已開放教材時必須先搜尋並以更正版優先。圖形題要把節點、邊、方向與走訪順序說清楚。正文禁止使用 Markdown 標題、星號、反引號、分隔線與 LaTeX 包圍符號；不要輸出 ##、###、**、```、\\[、\\]、\\(、\\)。標題直接寫中文，條列使用一、二、三或全形圓點，公式使用可直接閱讀的 Unicode 符號與純文字。"+diagramRule;
 const payload=await openAIJson("/responses",{method:"POST",body:JSON.stringify({model,instructions,input,...(allowSearch?{tools:[{type:"file_search",vector_store_ids:[setting!.value],max_num_results:10,filters:{type:"and",filters:[{key:"exam_category",type:"eq",value:"data-structure"},{key:"homepage_enabled",type:"eq",value:true}]}}],tool_choice:"required",include:["file_search_call.results"]}:{}),max_output_tokens:3200})}) as Record<string,unknown>;
 const parsed=parseReply(outputText(payload));if(!parsed.reply)return Response.json({error:"Luna 助教暫時沒有完成回答。"},{status:502});const usage=(payload.usage??{}) as {input_tokens?:number;output_tokens?:number;input_tokens_details?:{cached_tokens?:number}},inputTokens=Number(usage.input_tokens||0),outputTokens=Number(usage.output_tokens||0),cachedTokens=Number(usage.input_tokens_details?.cached_tokens||0),modelCost=estimateCostUsdMicros(model,{inputTokens,outputTokens,cachedTokens}),results=fileResults(payload),fileSearchCalls=results.length?1:0,toolCost=fileSearchCalls*2500,cost=modelCost+toolCost;await db.insert(usageLogs).values({model,source:"資料結構首頁 AI",inputTokens,outputTokens,cachedTokens,fileSearchCalls,estimatedCostUsdMicros:cost});const names=[...new Set(results.map(row=>cleanName(String(row.filename??""))).filter(Boolean))].slice(0,3);
 return Response.json({...parsed,source:results.length?`依據來源：${names.length?names.join("、"):"資料結構教材相關片段"}`:allowSearch?"本次已搜尋，但未命中已開放教材":"尚無已開放搜尋的資料結構教材，以下為 AI 一般知識說明",usage:{model:"Luna",inputTokens,outputTokens,cachedTokens,diagramTokens:parsed.diagramTokens,fileSearchCalls,modelCostUsd:modelCost/1_000_000,toolCostUsd:toolCost/1_000_000,durationMs:Date.now()-started,estimatedCostUsd:cost/1_000_000}})
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Luna 助教回答失敗"},{status:500})}}
